### ISSUE TITLE
how to create "lightweight" tag?

### ISSUE THREAD

**Issue by yalov** [PyGithub/PyGithub#1011]
There are "lightweight tag" and "annotated tag".

The tag `0.3.6` was created in the app as "lightweight". (Git Extensions app)
The tag `4.0.0`, I believe, is marked as annotated with `[...]` string. 

![](https://i.imgur.com/1wcjhJt.png)

The tag `4.0.0` was created as:
``` py
sha = repo.get_commits()[0].sha
t = repo.create_git_tag(tag="4.0.0", message="Test", object=sha, type="commit")
repo.create_git_ref('refs/tags/{}'.format(t.tag), t.sha)
```
How to create a "lightweight" tag?

------------
UPD.
Answer:
``` py
sha = repo.get_commits()[0].sha
repo.create_git_ref('refs/tags/{}'.format("4.0.0"), sha)
```

**Comment by sfdye** [comment]
> Note that creating a tag object does not create the reference that makes a tag in Git. If you want to create an annotated tag in Git, you have to do this call to create the tag object, and then create the refs/tags/[tag] reference. If you want to create a lightweight tag, you only have to create the tag reference - this call would be unnecessary.

https://developer.github.com/v3/git/tags/#create-a-tag-object

so i think you can just use `create_git_ref`
