### ISSUE TITLE
The number of contributors not correct using PyGithub

### ISSUE THREAD

**Issue by vivek14632** [PyGithub/PyGithub#1014]
I am using following code to get the number of contributors of a repository

```
from github import Github
g = Github("*****github Access token****")
repo = g.get_repo('mui-org/material-ui')
contributors_count = repo.get_contributors().totalCount
```
It is giving number of contributors as **443**, however, the correct number of contributors on the github website is **1077**.

Can some one tell why am I getting different values?

Also, is there any other function in PyGithub to get correct number of contributors?

**Comment by Hanaasagi** [comment]
In PyGithub 1.43.4, `get_contributors` method return a [`PaginatedList`](https://github.com/PyGithub/PyGithub/blob/v1.43.4/github/PaginatedList.py#L100) Object

When get `totalCount`,  it add querystring `per_page=1` in request to make sure the total page is the total count

Like this:

`https://api.github.com/repos/mui-org/material-ui/contributors?per_page=1`

And the response header has the link field the show next page url and last page url. More detail, please see [PaginatedList.py#L146](https://github.com/PyGithub/PyGithub/blob/v1.43.4/github/PaginatedList.py#L146)

```Python
    @property
    def totalCount(self):
        if not self.__totalCount:
            params = {} if self.__nextParams is None else self.__nextParams.copy()
            # set per_page = 1 so the totalCount is just the number of pages
            params.update({"per_page": 1})
            headers, data = self.__requester.requestJsonAndCheck(
                "GET",
                self.__firstUrl,
                parameters=params,
                headers=self.__headers
            )
            if 'link' not in headers:
                if data and "total_count" in data:
                    self.__totalCount = data["total_count"]
                elif data:
                    self.__totalCount = len(data)
                else:
                    self.__totalCount = 0
            else:
                links = self.__parseLinkHeader(headers)
                lastUrl = links.get("last")
                self.__totalCount = int(parse_qs(lastUrl)['page'][0])
        return self.__totalCount
```

In your code, it has the following `link` field

```
{
 'link': '<https://api.github.com/repositories/23083156/contributors?per_page=1&page=2>; '
         'rel="next", '
         '<https://api.github.com/repositories/23083156/contributors?per_page=1&page=443>; '
         'rel="last"'
}
```

The `totalCount` is 443. So where is the problem?

Github has the **anonymous contributors**.

> GitHub identifies contributors by author email address. This endpoint groups contribution counts by GitHub user, which includes all associated email addresses. To improve performance, only the first 500 author email addresses in the repository link to GitHub users. The rest will appear as anonymous contributors without associated GitHub user information.
-- [GitHub list-contributors API](https://developer.github.com/v3/repos/#list-contributors)

Also, there are some explanations in [GitHub Community](https://github.community/t5/GitHub-API-Development-and/API-Github-list-contributors/td-p/9631)
