### ISSUE TITLE
get_issues() since=date gets older issues

### ISSUE THREAD

**Issue by SalvoPizzimento** [PyGithub/PyGithub#1019]
Hi all, i tried to get closed issues of PyGithub since 1st January 2019 with this simple code
```
PyGit = client.get_repo("PyGithub/PyGithub")

date = datetime(2019, 1, 1, 0, 0)
issues = PyGit.get_issues(state="closed", since=date, sort="closed-desc")
for issue in issues:
	print(issue, issue.closed_at)
```
but what i get is this

> Issue(title="Github App unable to invite to org", number=1018) 2019-01-16 15:37:19
> Issue(title="dummy issue #911", number=1017) 2019-01-15 08:29:21
> Issue(title="GithubException: Repository access blocked", number=1015) 2019-01-15 19:50:33
> Issue(title="Add missing import to PullRequest", number=1007) 2019-01-04 14:28:54
> Issue(title="get_review_comments() method fails due to missing import", number=1004) 2019-01-04 14:28:54
> Issue(title="user.node_id missing", number=1001) 2019-01-10 12:49:53
> Issue(title="user.node_id missing ", number=999) 2019-01-10 12:50:52
> Issue(title="raise BadCredentialException when using Github enterprise", number=950) 2019-01-01 13:21:15
> Issue(title="BadCredentialsException not raised on GitHub enterprise", number=934) 2019-01-15 22:53:42
> Issue(title="create PullRequest between forked repo to original", number=792) 2018-05-18 02:52:21
> Issue(title="Implement `__len__` (and/or `__bool__`) on PaginatedList", number=579) 2019-01-15 22:53:41
> Issue(title="GitHub integrations support", number=449) 2017-01-27 16:34:41

how is this possible if I specified date with "since" option?

**Comment by Hanaasagi** [comment]
From GitHub API doc [List issues section](https://developer.github.com/v3/issues/#list-issues), we can know more info:
>since: Only issues **updated** at or after this time are returned. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.

For example, in your output:
```
Issue(title="create PullRequest between forked repo to original", number=792) 2018-05-18 02:52:21
```
[issues/792](https://github.com/PyGithub/PyGithub/issues/792) was closed on 18 May 2018, but  updated 12 days ago. So it will return.

**Comment by SalvoPizzimento** [comment]
@Hanaasagi thanks for you explanation :D. Yesterday I was so sleepy that I totally missread doc, my bad.
