### ISSUE TITLE
Allow indexing in PaginatedList _Slice objects

### ISSUE THREAD

**Issue by Powersource** [PyGithub/PyGithub#1046]
I just got an error `TypeError: '_Slice' object does not support indexing` when I tried to

```python3
tags = repo.get_tags()[:25]
tags[0]
```

**Comment by Powersource** [comment]
Still applies

**Comment by sfdye** [comment]
convert to list first?

**Comment by Powersource** [comment]
Due to some missing feature in `PyGithub||the github api` relating to tags, we switched to using the graphql api for this task. You can close this issue if you want.
