### ISSUE TITLE
[BUG] get_access_token uses hardcoded github URL

### ISSUE THREAD

**Issue by webknjaz** [PyGithub/PyGithub#1049]
It should use `base_url` supplied by the user. Otherwise, it's unusable with GitHub Enterprise.

**Comment by KVGarg** [comment]
I would like to work upon this issue. Need some information regarding solving this issue. Should an extra argument be passed to `get_access_token()` named - `base_url` with a default value of `DEFAULT_BASE_URL` ?

**Comment by s-t-e-v-e-n-k** [comment]
Which version are you looking at? The current master of GithubIntegration.get_access_token() uses self.base_url to construct the URL.
