### ISSUE TITLE
Missing "parent" field from Teams

### ISSUE THREAD

**Issue by TimGebhardt** [PyGithub/PyGithub#1054]
I would like to query the information about GitHub nested teams.  The "parent" field on a Team resource seems to be missing: 
https://developer.github.com/v3/teams/

**Comment by s-t-e-v-e-n-k** [comment]
Nested Teams is still in beta, we don't current use the custom media type of hellcat-preview anywhere, so our API responses won't include them.

**Comment by radykal-com** [comment]
I think nested teams went out of beta since this issue was created

**Comment by s-t-e-v-e-n-k** [comment]
This has also been fixed since in master.

**Comment by radykal-com** [comment]
Nice, so the next release will include it
