### ISSUE TITLE
Missing api for selecting a column in the Project board

### ISSUE THREAD

**Issue by shyam334** [PyGithub/PyGithub#1057]
Hello Guys,

I was using the library to automate a bit of the Project board feature, and noticed that there isn't a `get_column` method. I thought I'd report it as an issue/feature request.
The intent is to select a particular column in the Project board.

Corresponding GH api : `GET /projects/columns/:column_id`

https://developer.github.com/v3/projects/columns/#get-a-project-column
https://developer.github.com/enterprise/2.16/v3/projects/columns/#get-a-project-column

Thanks.

**Comment by viv2793** [comment]
@sfdye @shyam334 Can anyone assign this to me ?
