### ISSUE TITLE
Add support for the Checks API

### ISSUE THREAD

**Issue by nbraud** [PyGithub/PyGithub#1063]
The Github v3 API now supports a first-class notion of [check runs] and [check suites] that can be used to gate whether a pull-request should be merged or not.

Adding support for this part of the API to PyGithub would be useful for users who want to develop custom checks.  As I'm in that case, I might have a stab at this, but simply didn't make the time yet.

[check runs]: https://developer.github.com/v3/checks/runs/
[check suites]: https://developer.github.com/v3/checks/suites/

**Comment by wichtounet** [comment]
It would be really great to support this API indeed 👍 

We are currently using pygithub to add comments automatically to our PRs from our CI jobs. However, we would like to switch to the Checks API in order to keep the discussion cleaner.

**Comment by singh811** [comment]
@sfdye, I would like to work on this feature request.

**Comment by sfdye** [comment]
Go ahead 👍

**Comment by hawkins** [comment]
@singh811 Have you made any progress on this? I'd like to see this feature in too, so I'm happy to help if you have started, else I'll start and open a draft PR.

**Comment by szewczykmira** [comment]
Hi @singh811 how's the work going? It's the feature I'm dreaming about ;)

**Comment by aztlan2k** [comment]
@sfdye @singh811  @hawkins @nbraud 
Does anyone have any idea how difficult a task this would be?  is it a major task?

I'm wondering if there's any guidance on how to get it done?

**Comment by s-t-e-v-e-n-k** [comment]
Closing in favour of #1621
