### ISSUE TITLE
Feature request: fetch anonymous contributors

### ISSUE THREAD

**Issue by WofWca** [PyGithub/PyGithub#1065]
`get_contributors(self, anon=False):`
https://github.com/PyGithub/PyGithub/blob/118def30a3ee69e203113cc64dceea27ece12e13/github/Repository.py#L1802-L1812

**Comment by alexmusa** [comment]
I needed that feature 6 days ago. The modifications I ended up making are in the Pull Request #1075. Was the pull request made correctly ? I am not familiar with the mode of operation of Github and open source projects.

**Comment by sfdye** [comment]
Closed in #1075
