### ISSUE TITLE
Handle repos with missing licenses

### ISSUE THREAD

**Issue by Powersource** [PyGithub/PyGithub#1073]
Right now if you call `repo.get_license()` on a repo that doesn't even have a license file, you get an exception: `github.GithubException.UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/licenses/#get-the-contents-of-a-repositorys-license'}`.

Personally, I would prefer to just get a `None` returned instead. Idk what's most pythonic?

**Comment by cstayyab** [comment]
I would like to work on it if no one is working on this issue. Please assign it to me.

**Comment by Powersource** [comment]
The proper way [seems to be](https://github.com/spdx/spdx-spec/issues/50#issuecomment-456264240) to return 'NONE'.

**Comment by sfdye** [comment]
Understand your concern, but PyGithub is just wrapper for Github REST v3:
https://developer.github.com/v3/licenses/#get-the-contents-of-a-repositorys-license

> If a license is matched, the license key and name returned conforms to the SPDX specification.

When there is no license, Github indeed returns a 404. Guess you will have to catch this exception in your code.
