### ISSUE TITLE
I want to delete a directory. What should I do?

### ISSUE THREAD

**Issue by super1207** [PyGithub/PyGithub#1077]

**Comment by sfdye** [comment]
use `repo.delete_file(dir)`:
https://developer.github.com/v3/repos/contents/#delete-a-file

**Comment by WqyJh** [comment]
How to delete a directory recursively?

Thought I can delete all of the files one by one, it would create many commits. How can I delete all those files with one commit?

**Comment by s-t-e-v-e-n-k** [comment]
Don't use PyGithub for that, use git rm -r from the command line and then commit and push that.
