### ISSUE TITLE
Listing GitHub Enterprise Private Repo gets no repo at all

### ISSUE THREAD

**Issue by lovato** [PyGithub/PyGithub#1087]
Hi,

I am successfully listing all repos belonging to a person on GHEnterprise, when all of them are public. If all repositories are private, get_repos() lists nothing.

By looking at GitHub v3 documentation:
https://developer.github.com/v3/repos/#list-organization-repositories

I tried to find where is the method inside PyGithub for this APIcall, and was unable to find.
I think that this APIcall may work for me.

I am using my personal access token, which gives me full rights on the organization (I am also org owner).

Best,
Lovato

**Comment by lovato** [comment]
I ended adding a method on MainClass.py to fullfil my needs.

```
    def get_organization_repos(self, login):
        """
        :calls: `GET /orgs/:org/repos <https://developer.github.com/v3/repos/#list-organization-repositories>`_
        :param login: string
        :rtype: :class:`github.Organization.Organization`
        """
        assert isinstance(login, str), login
        headers, data = self.__requester.requestJsonAndCheck(
            "GET",
            "/orgs/" + login + "/repos"
        )
        return data
```
But it is just returning plain json, instead of a PyGithub object.
And I am not sure if this is the place to put this code.

I can create a PR, if I receive proper instructions.

Best

**Comment by sfdye** [comment]
How about this:
https://pygithub.readthedocs.io/en/latest/github_objects/Organization.html#github.Organization.Organization.get_repos

**Comment by lovato** [comment]
Thanks man. Worked perfectly. My bad.
