### ISSUE TITLE
search_commits, missing repository key

### ISSUE THREAD

**Issue by nowox** [PyGithub/PyGithub#1088]
I would like to get a GitHub Repository URL from a Commit HASH. This is feasible with the API:

```python
    import json
    import requests
    
    def search_commits(sha):
       headers = {'Accept': 'application/vnd.github.cloak-preview'}
       req = requests.get('http://api.github.com/search/commits',
           {'q': sha},
           headers=headers)
       return json.loads(req.text)
    
    commit = search_commits('e83c5163316f89bfbde7d9ab23ca2e25604af290')['items'][0]
    clone_url = commit['repository']['url']
```

Then I tried the same with `PyGitHub`:

```python
    from github import Github
    g = Github()
    
    commit = g.search_commits('e83c5163316f89bfbde7d9ab23ca2e25604af290')[0]
```

Unfortunately in this result (even in `commit.raw_data`) there is no key `repository`. 

It seems PyGitHub uses `search/commits` as described here: https://developer.github.com/v3/search/#search-commits

But instead of this object it returns a Commit object https://developer.github.com/v3/repos/commits/

How can I get the URL of the repository?

**Comment by sfdye** [comment]
Unfortunately since the Commit object does not have a `repository` attribute, I guess the work-around is just to use the `commit['url']` and some string manipulation.

**Comment by nowox** [comment]
Yeah, it is what I do with: 

```python
import re

repo = g.get_repo(
    re.search('repos/(.*?)/commits', c.raw_data['url']).group(1)
)
clone_url = repo.clone_url
```

But I am confused because [search-commits](https://developer.github.com/v3/search/#search-commits)  is not supposed to return a [commit](https://developer.github.com/v3/repos/commits/) object according the API specifications. The proof is that if I query the API directly I get what I need.

**Comment by DeerShark** [comment]
I also find this problem, this key is clearly in the public API documentation, but it has not been changed for so long...
