### ISSUE TITLE
Allow setting `name` for upload_asset

### ISSUE THREAD

**Issue by retorquere** [PyGithub/PyGithub#1095]
Currently, PyGithub uses `path.basename` for the `name` of the file assets -- could it be added that I can choose my own name? I can of course rename the file before upload, but it would be easier if I could just specify the name.

**Comment by sfdye** [comment]
Hi, can you provide a more detailed example?

**Comment by retorquere** [comment]
I have a local file called "build.xpi" that I want to upload as an asset named (not just labeled) "build-1234.xpi",bit I do not want to rename it locally before upload (other build stages rely on it being named build.xpi)
