### ISSUE TITLE
 PyGithub module does not work with Python 3.7.2

### ISSUE THREAD

**Issue by visantillan** [PyGithub/PyGithub#1097]
When try to running the simple demo after doing the installation throws the following:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from github import Github
ModuleNotFoundError: No module named 'github

OS: macOS Mojave 10.14.4
Python: 3.7.2

**Comment by MarcoFalke** [comment]
python3.7 is tested by travis, so that shouldn't be the issue: https://github.com/PyGithub/PyGithub/blob/f716df86bbe7dc276c6596699fa9712b61ef974c/.travis.yml#L8

How did you install it?
