### ISSUE TITLE
get_labels/get_label does not return description

### ISSUE THREAD

**Issue by phako** [PyGithub/PyGithub#1101]
It seems that it is missing the "Accept" : "application/vnd.github.symmetra-preview+json" header which is added for the edit call

Additionally, if you pass it and have "api_preview = True" it will be overwritten

**Comment by phako** [comment]
Yes, sorry, I'm still struggling with the tests.

**Comment by WilliamKluge** [comment]
Any known workarounds for this? I'm facing the same issue currently.

**Comment by phako** [comment]
@WilliamKluge I proposed a fix in https://github.com/PyGithub/PyGithub/pull/1102 but failed to get the tests working afterwards

**Comment by WilliamKluge** [comment]
I was able to get the test cases working with the added header for the label by modifying the replay data to also have the header. However, despite the test cases passing when I installed it into the project I found this issue in it did not resolve the problem.
