### ISSUE TITLE
totalCount shows wrong number of open issues

### ISSUE THREAD

**Issue by 242jainabhi** [PyGithub/PyGithub#1105]
```
from github import Github
g = Github('Access_Token')
repo = g.get_repo('pygithub/pygithub')
open_issues = repo.get_issues(state='open')
print(open_issues.totalCount)
```

This code prints 77, but github repo shows 60 open issues.

What is this extra count about?
![open_issues](https://user-images.githubusercontent.com/7472569/57015479-a3931200-6c32-11e9-82b9-1154567c083d.JPG)

**Comment by wangpeipei90** [comment]
My guess is that it counts open pull request as well. By default, pull requests are also regarded as issues.

**Comment by sfdye** [comment]
@wangpeipei90 Yes, exactly as explained by the official docs:
https://developer.github.com/v3/issues/#list-issues-for-a-repository

@242jainabhi 
Seem this is consistent with the API usage, I am gonna think this is not a bug.

You can identify PR by inspecting whether the response contains the `pull_request` key I guess.

**Comment by 242jainabhi** [comment]
@wangpeipei90 @sfdye 
Thanks for the clarification. It now makes sense to me.
