### ISSUE TITLE
PyGithub-1.36 and later cannot get files in a folder or file with a space in name

### ISSUE THREAD

**Issue by chanukov** [PyGithub/PyGithub#1114]
I have had a file that i checkout using pygithub
which was working great with 1.35
we tried moving to latest pygithub and the simple line
        self.github_api.git_repo.get_file_contents(urllib.quote('file with spaces.txt') , "master")
fails

        self.github_api.git_repo.get_file_contents(urllib.quote('/iOS/Supporting Files/Info.plist') , "master")  
also fails, yet works in 1.35 

This is blocking us from moving to later versions, as it breaks our release automation scripts.

**Comment by sfdye** [comment]
See #614 since 1.36 we did the quote for you. Just remove `urllib.quote` and it should work.
