### ISSUE TITLE
github.GithubException.RateLimitExceededException

### ISSUE THREAD

**Issue by 242jainabhi** [PyGithub/PyGithub#1115]
I am trying to fetch the number of open issues using the following code in my Flask application.
```
g = Github()

repo = g.get_repo(repo_name)

open_pulls = repo.get_pulls(state='open')
open_pull_titles = [pull.title for pull in open_pulls]

open_issues = repo.get_issues(state='open')
open_issues = [issue for issue in open_issues if issue.title not in open_pull_titles]
```
and I get the error `github.GithubException.RateLimitExceededException: `.

`repo.get_issues()` returns the count of open issues plus pull requests.

**Comment by shakeebr** [comment]
Interesting, I don't see this happening on my end.

**Comment by wangpeipei90** [comment]
If I understand correctly, the return type of get_issues and get_pulls is PaginatedList.   It uses `yield element` for iteration. So the request is not performed until `open_issues = [issue for issue in open_issues if issue.title not in open_pull_titles]`.  If your token limits are reached, it will throw the RateLimitExceedException.

**Comment by 242jainabhi** [comment]
Is there any workaround?

**Comment by sfdye** [comment]
`g = Github()`
Did you authenticate at this step? public api has less rate limits.

**Comment by wangpeipei90** [comment]
@242jainabhi 
The things I usually do when reaching the rate limit is just holding off the program for some time. 

Instead of using the list comprehension, I may use just a common loop with try-catch. Once a rate limit exception is caught, call the sleep function to wait for a while and check the rate limit with GitHub API again.  The code only proceeds if the rate limit comes back to 5000.

**Comment by 242jainabhi** [comment]
I am sorry for missing a part of the code. Below is the code in continuation to the code in first comment.
I am accessing `created_at` date for all the open issues. This will again access the API for all the issues and hence end up making calls more than the limit.
```
for issue in open_issues:
    created_at = issue.created_at.timestamp()
```

I could not find a solution to this problem. Even if I authenticate the requests, the limit will be exhausted if the issues are too many (let's say 2000).

**Comment by shamoons** [comment]
Something like this:
```
repositories = g.search_repositories(
    query='stars:>=10 fork:true language:python')
```
Also triggers the rate limit.  I assume, it's doing the pagination automatically and that's triggering the rate limit? Is there any way for me to do it manually so I can pause?

**Comment by wangpeipei90** [comment]
I now realize that this is a real issue. 
One possible workaround could be code snippet like the below. I have not tried it yet, let me know whether it works or not.

```python
iter_obj=iter(open_issues) ## PaginatedList is a generator
 while True:
    try:   
        issue=next(iter_obj) 
        ## do something
    except StopIteration:
        break  # loop end
    except github.GithubException.RateLimitExceededException:
        sleep(3600) # sleep 1 hour
        ## check token limits
        continue
```

**Comment by eelco** [comment]
@wangpeipei90 Does not work.

**Comment by 0xBenjamin** [comment]
For some reason this behavior is highly unpredictable and it's maddening.
My program can effectively cycle and preemptively call the ratelimit api to check if it adheres within the limits for one to two hours before randomly giving a 403.

Some native rate limit adherence would be a warm welcome here. Having to implement sleeps based on intuition when your application decides to spill the beans after two hours of running smoothly should not be expected behavior.

```
 File "word.py", line 126, in get_stargazers_inner
    for i in repo.get_stargazers_with_dates():
  File "/usr/local/lib/python3.6/dist-packages/github/PaginatedList.py", line 62, in __iter__
    newElements = self._grow()
  File "/usr/local/lib/python3.6/dist-packages/github/PaginatedList.py", line 74, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/lib/python3.6/dist-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers=self.__headers
  File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 276, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 287, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {'message': 'API rate limit exceeded for user ID xxxx.', 'documentation_url': 'https://developer.github.com/v3/#rate-limiting'}
```

**Comment by maxlovic** [comment]
See also #1233 for excessive requests.

**Comment by Xiaoven** [comment]
@wangpeipei90 

It works for me, but the `RateLimitExceededException` is not under `GithubException` in the version I used. Here is my code.

```python
issues = g.search_issues(query=keyword, **{'repo': repo, 'type': 'pr'})
            iter_obj = iter(issues)
            while True:
                try:
                    pr = next(iter_obj)
                    with open(pr_file, 'a+') as f:
                        f.write(pr.html_url + '\n')
                    count += 1
                    logger.info(count)
                except StopIteration:
                    break  # loop end
                except RateLimitExceededException:
                    search_rate_limit = g.get_rate_limit().search
                    logger.info('search remaining: {}'.format(search_rate_limit.remaining))
                    reset_timestamp = calendar.timegm(search_rate_limit.reset.timetuple())
                    # add 10 seconds to be sure the rate limit has been reset
                    sleep_time = reset_timestamp - calendar.timegm(time.gmtime()) + 10
                    time.sleep(sleep_time)
                    continue
```

Here is part of the log:

```
2020/01/08 23:42:09 PM - INFO - search remaining: 0
```

**Comment by unagaraju88** [comment]
Hi Xiaoven,

I tried your code snippet to search repositories:

result1 = g.search_repositories(query,'stars','desc')
while True:
                try:
                    ----SOMETHING----
                except RateLimitExceededException:
                    search_rate_limit = g.get_rate_limit().search
                    logger.info('search remaining: {}'.format(search_rate_limit.remaining))
                    reset_timestamp = calendar.timegm(search_rate_limit.reset.timetuple())
                    # add 10 seconds to be sure the rate limit has been reset
                    sleep_time = reset_timestamp - calendar.timegm(time.gmtime()) + 10
                    time.sleep(sleep_time)
                    continue
  
The problem i am encountering is , once the rate limit is resetted the continue will try to do all the steps mentioned in SOMETHING from the beginning and again I am not able to search more than 100+ repositories.

but i want to search the repositories from where it had stopped so i will get next 29 rate limit.
Please let me know how did it worked if you have to search for more than 100+ issues.

**Comment by sparkingdark** [comment]
Thanks, @Xiaoven I am finally able to solve this with your code.

**Comment by EnricoMi** [comment]
Ideally, PyGithub should throttle its requests transparently so that iterating over the paginated list (and accessing attributes that trigger more requests) does not fire off too quickly and get interrupted by GitHub's secondary rate limit (too frequent requests). Then no user code is required to wrap around these calls: #1989 #2145

The overall rate limit still needs to be monitored and obeyed by user code, better pro-actively and not reacting on exceptions.
