### ISSUE TITLE
Feature Request: Deployments API

### ISSUE THREAD

**Issue by jamiegs** [PyGithub/PyGithub#1117]
It appears that the Deployments API isn't currently in PyGithub. This API has been around for years. Is there any chance it could get added to PyGithub?

https://developer.github.com/v3/repos/deployments/

**Comment by s-t-e-v-e-n-k** [comment]
I'm going to work on this in my spare time, but I fear it's going to be as large as the branch protection rabbit hole I fell into -- see 171cc567ae4b4850a6270d3ed728a2f995a7462f

**Comment by eMerzh** [comment]
@s-t-e-v-e-n-k no pressure here, but did you manage to get this working?
i'm very interested in this for a personal project :)

**Comment by s-t-e-v-e-n-k** [comment]
I worked on this yesterday, and I think I have enough of it implemented, but I need to find some time to write tests before I propose a PR.

**Comment by s-t-e-v-e-n-k** [comment]
@eMerzh @jamiegs I've pushed up a branch linked above that implements it, but I'm not certain about a few sharp edges. Are you guys able to test it out in the real world and tell me what feels awkward/wrong?

**Comment by eMerzh** [comment]
awesome @s-t-e-v-e-n-k ❤️ ... i'll try to give it a go in the next week, but it seems to have everything i need :)

**Comment by s-t-e-v-e-n-k** [comment]
@eMerzh Have you had a chance to test this? Merging it soon would be awesome.

**Comment by eMerzh** [comment]
hey, sorry, bit late, but it seems to work as expected :)

thanks for this ...

**Comment by s-t-e-v-e-n-k** [comment]
@eMerzh Thanks for the confirmation, I'll push up a PR soon and we can get this in a proper release.
