### ISSUE TITLE
How to remove sent invitations

### ISSUE THREAD

**Issue by diegotejadav** [PyGithub/PyGithub#1120]
I used repo.add_to_collaborators to add massively some users to some repositories, but now I have to revert the action for those who haven't accepted the invitation yet, how can I list the invitations and cancel them?
Is there a way to use with PyGithub this API [example](https://developer.github.com/v3/repos/invitations/#delete-a-repository-invitation)?

**Comment by s-t-e-v-e-n-k** [comment]
The invitations API is only partially implemented, but I'll look at adding code to list and delete invitations for repositories today.

**Comment by diegotejadav** [comment]
Thank you so much @s-t-e-v-e-n-k !

**Comment by s-t-e-v-e-n-k** [comment]
https://github.com/PyGithub/PyGithub/pull/1156 is the first part of this work.

**Comment by diegotejadav** [comment]
Wow! this feature is going so fast!

**Comment by diegotejadav** [comment]
Thank you so much @s-t-e-v-e-n-k, finally I could test the new Repository methods and they work like a charm!
