### ISSUE TITLE
Is it possible to get back header data from a request?

### ISSUE THREAD

**Issue by shamoons** [PyGithub/PyGithub#1121]
Specifically, I'm doing

```
repo.get_contents(file_content.path)
```

And I want the returned header as well

**Comment by sfdye** [comment]
response.raw_headers

**Comment by shamoons** [comment]
Is response returned?

**Comment by shamoons** [comment]
If I do:
```
response = repo.get_contents(file_content.path)
print(response.raw_headers)
```

It doesn't work. What am I missing @sfdye ?

**Comment by wangpeipei90** [comment]
response.raw_headers works at least to me. Check the response object and make sure it is a valid result and not None
