### ISSUE TITLE
Delete tag in Github 

### ISSUE THREAD

**Issue by hemanthsavasere** [PyGithub/PyGithub#1124]
Hi, 
I just wanted to know if there is any way to delete a tag using pygithub as after deleting the release, the tag still remains. Searched in docs for git tag, had only methods of creation but not deletion.

Thanks

**Comment by sfdye** [comment]
https://developer.github.com/v3/git/tags/
https://developer.github.com/v3/repos/#list-tags

I just checked the Github API docs, it seems currently no way to delete a tag from API. One work-around is to do it in command line, i.e. delete the tag locally and push to remote, in Python you can use something like `GitPython`.

**Comment by hemanthsavasere** [comment]
Thanks, @sfdye.

**Comment by lukasmiciulis** [comment]
https://stackoverflow.com/questions/7247414/delete-a-tag-with-github-v3-api

**Comment by lokesh-wise** [comment]
This is the way to delete a tag in PyGithub

```
        ref = repo.get_git_ref('tags/{tag_name}')
        ref.delete()
```
