### ISSUE TITLE
[Feature Request] Ability to toggle repository features

### ISSUE THREAD

**Issue by glutanimate** [PyGithub/PyGithub#1128]
I think it could be quite helpful if we could toggle repository features like Wikis, Issues, and Sponsorships on and off via PyGithub. A possible use case would be setting up multiple new repositories with the same settings.

P.S.: Thanks for all your hard work on this project. It's been a great boon in my development flow.

**Comment by res0nance** [comment]
Wiki and issues can be toggled via https://github.com/PyGithub/PyGithub/blob/4a37860bc4a569a8c3bf6b0ea11fb416d2205c04/github/Repository.py#L1254

**Comment by glutanimate** [comment]
@res0nance Thanks for the pointer, completely missed that!

Though it seems like toggling sponsorship state at least is not possible at the moment.

@sfdye Perhaps we should change the scope of this issue to solely address sponsorships?

**Comment by res0nance** [comment]
@glutanimate Sponsorships are unfortunately not part of the API yet
