### ISSUE TITLE
PyGithub and proxy issues

### ISSUE THREAD

**Issue by harbya** [PyGithub/PyGithub#1131]
Hi team,
I need to ask a question.
I just following the PyGithub introduction documentation step by step but it looks like I could be facing proxy issues.
from github import Github
user="xxx" 
Pass="xxx"
g = Github(user,Pass)
or using an access token
#g = Github("access_token")
Github Enterprise with custom hostname
g = Github(base_url="https://github.mylabs.com.au/api/v3")
g.get_user() 
AuthenticatedUser(login=None)
for repo in g.get_user().get_repos(): 
print(repo.name) 
repo.edit(has_wiki=False) 
# to see all the available attributes and methods 
print(dir(repo))
 
then I get a timeout error: 

ConnectTimeout: HTTPSConnectionPool(host='github.mylabs.com.au', port=443): Max retries exceeded with url: /api/v3/user/repos (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000000000737AAC8>, 'Connection to github.mylabs.com.au timed out. (connect timeout=15)'))

My question is whether I can set the proxy used by PyGithub... 

The problem is that I've been looking everywhere and it looks like a lot of people seems to have hit the same problem but could not see anyone providing a fix. For example before I was testing with the REQUESTS package (as shown below) and there was a way to set the proxy:
import requests 
proxies = { 
'http':'http://proxy.mycompany.corp:8080', 
'https': 'https://proxy.mycompany.corp:8080', 
}
r = requests.get('https://github.mylabs.com.au/iagcl/iag-edh-data/pulls', proxies = proxies)

If you please advise me how to do similar thing with the PyGithub would be great... Thanks again ...

**Comment by yangyang-zhang** [comment]
I have the same problem. Have you solved it?

**Comment by harbya** [comment]
make  sure you set the below correctly:
g = Github('git-userid','password')

**Comment by yangyang-zhang** [comment]
Can I add a proxy?  Because Network barrier

**Comment by harbya** [comment]
I gave up trying with proxy but also using the base_url seems to work:
g = Github(base_url="https://github.company.com/api/v3")

Also maybe raise a tickect to github support. I found out they are quite good...

**Comment by yangyang-zhang** [comment]
Thank you for your advice.
