### ISSUE TITLE
Paginated list reversed only gives the first page of results backwards

### ISSUE THREAD

**Issue by micahsteinberg** [PyGithub/PyGithub#1136]
When I do
```
g = Github("xxx")
repo = g.get_repo("xxx")

for comm in repo.get_commits(since=datetime).reversed:
    ....
```
it only goes through the most recent 30 results in reverse order.

I was able to fix this with
```
def reverse_github_results(paginated_list):
    for i in range(paginated_list.totalCount//30, -1, -1):
        page = paginated_list.get_page(i)
        page.reverse()
        for item in page:
            yield item
```
but this possibly runs a bit slower and I thought I should let you guys know

**Comment by engn33r** [comment]
This was still an issue with v2.1.1 but the fix above worked for me :+1:

It would be great if this could be fixed in the library itself, with an example showing reversed usage in the docs.

**Comment by EnricoMi** [comment]
There does not seem to be a unit test for this, reopening, contribution welcome.

**Comment by etiennnr** [comment]
Can confirm this is still a problem for me, using version `1.59.1` though

**Comment by EnricoMi** [comment]
Can you confirm with latest release?

**Comment by engn33r** [comment]
For reference, I did not set `per_page` so I was using the default of 30 when I encountered this issue

**Comment by EnricoMi** [comment]
Confirmed, the `per_page` surfaced a bug: #2929
