### ISSUE TITLE
Replacing a specified string, Iterating over every file within every repo.

### ISSUE THREAD

**Issue by Dextroz** [PyGithub/PyGithub#1137]
Hello,

Sorry for the long title.

Essentially, I am attempting to write a script which will iterate over every repository I own. Then for a specific string and if found in any of the files within the repo; replace it.

Is this possible? I am aware I need to also use `update_file`. Could somebody point me in the right direction?

So far I have got:

```python
"""
A Python 3.7 script to remove a specific string from all file(s) and repos containing a specified string.
"""

ACCESS_TOKEN = "Sometoken"
STR_TO_REPLACE = "The string to find in a file and remove."

from github import Github

g = Github(ACCESS_TOKEN)
for repo in g.get_user().get_repos(type="owner"):
    print(repo.name)
    # Fetch all content from the repo.
    repo_contents = repo.get_contents("")
    # Show all repo contents.
    print(repo_contents)
    for file in repo_contents:
        print(file.name)
        try:
            # Search the file for the specified string and replace it with something else.
            # Not sure how to do this yet. This is where I need some help :-)
        except:
            # Some error which occurs if the string is not found. 
            # Tell user the string isn't in the file.
            print(f"The string {STR_TO_REPLACE} wasn't found in {file.name}")
```

Any help would be appreciated.

**Comment by sfdye** [comment]
`re`?

**Comment by Dextroz** [comment]
> `re`?

Thanks for replying @sfdye. I believe I need to use [` contents = repo.get_contents()`](https://pygithub.readthedocs.io/en/latest/examples/Repository.html#get-a-specific-content-file) for each file. Obtain the decoded base64 contents `contents = contents.decoded_content` and then use re to search it?

**Comment by sfdye** [comment]
Yes it should work.

**Comment by Dextroz** [comment]
@sfdye Could I not just use `if STR_TO_REMOVE in file_data` ?

**Comment by Dextroz** [comment]
@sfdye I just got the following error:
`github.GithubException.GithubException: 403 {'message': 'This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.', 'errors': [{'resource': 'Blob', 'field': 'data', 'code': 'too_large'}], 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents'}`

Can I catch this exception using:
```python
try:
    pass
except github.GithubException:
    pass
```

?

**Comment by Dextroz** [comment]
Sorted. Thanks for the help.
