### ISSUE TITLE
Get unauthenticated user's data

### ISSUE THREAD

**Issue by siddhant1999** [PyGithub/PyGithub#1138]
Since profile are public is there a way to use PyGithub to get the public data on users without needing their password, i.e. only having their username?

```
g = Github("user", "password")
g.get_user()
```
... fails if you do not provide a password

**Comment by rfverbruggen** [comment]
I would definitely like that.

Maybe something like this could be implemented:

```
# unauthenticated access
g = Github()

# get unauthenticated user info
g.get_user("username")

# get unauthenticated user repo info
g.get_user("username").get_repos():
```

**Comment by siddhant1999** [comment]
Thanks
