### ISSUE TITLE
topics attribute always return None, even when get_topics() return a list of topics

### ISSUE THREAD

**Issue by ronhab** [PyGithub/PyGithub#1143]
For example:
`g.get_repo('nteract/hydrogen').topics` return `None`

`g.get_repo('nteract/hydrogen').get_topics()` return `['atom', 'data-science', 'hydrogen', 'ipython', 'jupyter', 'jupyter-kernels', 'nteract', 'repl']`

If I add `headers={"Accept": Consts.mediaTypeTopicsPreview}` to the repo request, I can get the topics list in the attribute as well.

I can create a PR if needed.

**Comment by sfdye** [comment]
PR Please, I will review
