### ISSUE TITLE
What's the best way to get results in bulk?

### ISSUE THREAD

**Issue by choldgraf** [PyGithub/PyGithub#1145]
Is there a way for PyGitHub to return results as a bulk data dump?

## What I'd like

To be able to run a search query, and get a list of raw JSON, one for each item.

## What I've tried

I'll run a query with something like `search_issues(query)`, this returns a paginated list. I loop through the list, and on each "Issue" object I grab `raw_data` and turn it all into a DataFrame.

## Where I've run into challenges

I've found that returning a list of, e.g., issue objects and then looping through them individually takes a *lot* longer than if I just grab the JSON from the GitHub API directly. Is there some way to just get the whole dump of JSON objects at once rather than making an individual API request for each one?

**Comment by wangpeipei90** [comment]
You can probably try GitHub V4 graphql.
