### ISSUE TITLE
Expose `get_issue_events()` from `PullRequest`

### ISSUE THREAD

**Issue by mabrowning** [PyGithub/PyGithub#1149]
I'm attempting to script automatically closing old Pull Requests, but letting users re-open them if they are still working on them. I don't want to *keep* closing PRs, so I want to check that a PR hasn't been re-opened before closing it. One way of doing that is to look through the list of "issue events", but first I need to use `PullRequest.as_issue()`, which makes a needless API request. 

Only the issue number is needed for `GET /repos/:owner/:repo/issues/:issue_number/events`, so it should be possible to do directly from the `PullRequest` object. Any chance you could add that method? Similar to `PullRequest.get_issue_comments()` etc.

**Comment by 1sfoerster** [comment]
i am trying to find the pull request reviewers and pull request comment authors
can run pull.get_issue_events
I get 
Value is of type method!
method has property "__call__" of type "method-wrapper"
method has property "__class__" of type "type"
method has property "__delattr__" of type "method-wrapper"
method has property "__dir__" of type "builtin_function_or_method"
method has property "__doc__" of type "str"
  Here's the __doc__ value: 
  "\n        :calls: `GET /repos/:owner/:repo/issues/:issue_number/events <http://developer.github.com/v3/issues/events>`_\n        :rtype: :class:`github.PaginatedList.PaginatedList` of :class:`github.IssueEvent.IssueEvent`\n        "

method has property "__eq__" of type "method-wrapper"
method has property "__format__" of type "builtin_function_or_method"
method has property "__func__" of type "function"
method has property "__ge__" of type "method-wrapper"
method has property "__get__" of type "method-wrapper"
method has property "__getattribute__" of type "method-wrapper"
method has property "__gt__" of type "method-wrapper"
method has property "__hash__" of type "method-wrapper"
method has property "__init__" of type "method-wrapper"
method has property "__init_subclass__" of type "builtin_function_or_method"
method has property "__le__" of type "method-wrapper"
method has property "__lt__" of type "method-wrapper"
method has property "__ne__" of type "method-wrapper"
method has property "__new__" of type "builtin_function_or_method"
method has property "__reduce__" of type "builtin_function_or_method"
method has property "__reduce_ex__" of type "builtin_function_or_method"
method has property "__repr__" of type "method-wrapper"
method has property "__self__" of type "PullRequest"
method has property "__setattr__" of type "method-wrapper"
method has property "__sizeof__" of type "builtin_function_or_method"
method has property "__str__" of type "method-wrapper"
method has property "__subclasshook__" of type "builtin_function_or_method"

I know this pull request has four people involved ... author of the pull request (can get that) pull request merger, but can't find pull request reviewer or commenter
