### ISSUE TITLE
Is there a way to get the content of a file from a specific branch?

### ISSUE THREAD

**Issue by sudo-panda** [PyGithub/PyGithub#1157]

**Comment by sfdye** [comment]
Yes, there is:
https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html?highlight=get_content#github.Repository.Repository.get_contents

the `ref` is the branch name

**Comment by sudo-panda** [comment]
Ok thanks

**Comment by vaibhavi1321** [comment]
> Yes, there is:
> https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html?highlight=get_content#github.Repository.Repository.get_contents
> 
> the `ref` is the branch name

Thanks a lot, your suggestion helped me as well to figure out how to get content from a specific branch.

**Comment by rahul-005** [comment]
URL = "https://api.github.com/repos/{}/{}/contents/{}{}.csv?ref={}".format(REPO_OWNER, REPO_NAME, git_file_path, csv_file, BRANCH_NAME)
