### ISSUE TITLE
Organization.has_in_members uses incorrect URL if called from repository instance

### ISSUE THREAD

**Issue by dspechnikov** [PyGithub/PyGithub#1161]
This works correctly (returns `True`):
```python
github_client = Github('token')
organization = github_client.get_organization('org')
user = github_client.get_user('user')
organization.has_in_members(user)
```

The same call from repo instance returns `False`:
```python
github_client = Github('token')
organization = github_client.get_organization('org')
user = github_client.get_user('user')
repo = organization.get_repo('repo')
repo.organization.has_in_members(user)
```

The reason is that requested URL is  referring to `users` namespace instead of `orgs`:
`https://api.github.com/users/...`

**Comment by s-t-e-v-e-n-k** [comment]
I think this is a gotcha that we should document, because we're just going by what data Github returns.

```
>>> repo_raw_data = repo.organization.raw_data
>>> org_raw_data = org.raw_data
>>> diff = { k : repo_raw_data[k] for k in set(repo_raw_data) - set(org_raw_data) }
>>> diff
{u'bio': None, u'following_url': u'https://api.github.com/users/PyGithub/following{/other_user}', u'gists_url': u'https://api.github.com/users/PyGithub/gists{/gist_id}', u'name': None, u'organizations_url': u'https://api.github.com/users/PyGithub/orgs', u'company': None, u'site_admin': False, u'subscriptions_url': u'https://api.github.com/users/PyGithub/subscriptions', u'blog': u'', u'location': None, u'received_events_url': u'https://api.github.com/users/PyGithub/received_events', u'gravatar_id': u'', u'starred_url': u'https://api.github.com/users/PyGithub/starred{/owner}{/repo}', u'hireable': None, u'email': None, u'followers_url': u'https://api.github.com/users/PyGithub/followers'}
```

From comparing the raw_data, I see you're completely correct, but repo.organization is populated from the Repository object itself, from the JSON returned by GitHub, not by querying the name of org.

**Comment by dspechnikov** [comment]
Thanks for details on internals. 

Still, we basically have a method which returns an incorrect result. Shouldn't we at least raise an exception in this case to be explicit about that?

I spent quite a bit of time trying to figure that out. It would be great if nobody would repeat that in future versions.

**Comment by s-t-e-v-e-n-k** [comment]
In general if you want to perform an action on any item (be it an org, branch or user), you're much better off fetching it directly. I *think* that is brief enough to document, @sfdye what do you think?

**Comment by s-t-e-v-e-n-k** [comment]
The proper way to fix this would be to have a different Organization class that is used with no methods on it, but we use this pattern all over the code base, so I think you're entirely correct to raise an issue asking for help, but I don't think it's something we can fix.
