### ISSUE TITLE
General github api question: merge from another repo

### ISSUE THREAD

**Issue by MartykQ** [PyGithub/PyGithub#1164]
I'm currently working on bug detecting system.

I need to find a way to get all events for an issue, especially merges that come from the repository, that I'm currently in and from another repository.

Example: 
I have repoA, created an issue #1 there

In repoB, someone created a pull request that was merged and referenced to #1 via keyworld 'fixes'

What I would like to get is a way to get a reference to this pull request api link, working from /api/repos/repoA/issues/1

**Comment by s-t-e-v-e-n-k** [comment]
Having a play around with a closed issue, I can get at the commit itself from an event, but I can't see how to get at the PR itself. Perhaps IssueEvent is missing some information, but I can't the PR in the raw data returned from GitHub either.

**Comment by MartykQ** [comment]
@s-t-e-v-e-n-k I figured it out. However, as far as I'm concerned it's impossible to get with api v3. I used grahpQL query (api v4). 

```
query{
    repository(owner: "owner", name: "repo") {                
      issue(number: 1) {
      url
      state
      timeline(first: 100) { 
        nodes {
          __typename
          ... on CrossReferencedEvent {
            source {  
              ... on PullRequest {
                number
                title
                url
                changedFiles
                additions
                deletions
                author {
                  login
                }
                commits {
                  totalCount
                }
              }
            }
          }
        }
      }
    }
  }
}

```
