### ISSUE TITLE
Repository and team missing methods

### ISSUE THREAD

**Issue by lpiottiJC** [PyGithub/PyGithub#1170]
For Repository class couldn't find get_pending_invitations()
For Team class couldn't find get_team_by_slug()

**Comment by lpiottiJC** [comment]
My bad this is a Organization class method -> get_team_by_slug()

Actual exception:
AttributeError: 'Organization' object has no attribute 'get_team_by_slug'

**Comment by s-t-e-v-e-n-k** [comment]
Both of these have landed -- but you'll either need to wait for the next release, or run from HEAD.
