### ISSUE TITLE
NotSet is not None

### ISSUE THREAD

**Issue by 3nids** [PyGithub/PyGithub#1175]
why `github.GithubObject.NotSet is None` is returning `False`?

code would look much nicer and Pythonic if we could use something lilke 

    param or default_value

instead  of
 
    if param is not github.GithubObject.NotSet:
      return param
    else:
      return default_value

**Comment by s-t-e-v-e-n-k** [comment]
Because NotSet is a distinctly implemented object. It neatly shows what we aren't setting versus say explicitly setting things to None, but this decision was taken when the project began which is way before my involvement.
