### ISSUE TITLE
Specifying UnknownObjectExceptions

### ISSUE THREAD

**Issue by mwhite98** [PyGithub/PyGithub#1176]
Hello,

I'm writing a script to look for a directory of a certain name in a given repository, and if that directory doesn't exist, it throws an UnknownObjectException. I'd like to be able to specify the exception I'm catching as an UnknownObjectException, but I'm having trouble figuring out how to access that utility. Here's what I'm trying to do:
```
try:
    dir_test = repo.get_contents("test_directory")
except UnknownObjectException:
    print("This directory DNE")
```

And here's how I've tried to do it so far, and the resulting outputs:
```
except UnknownObjectException:
    # NameError: name 'UnknownObjectException' is not defined

except GithubException as ge:
    # NameError: name 'GithubException' is not defined

except Github(url, token).GithubException as ge:
    # AttributeError: 'Github' object has no attribute 'GithubException'

import github
except github.GithubException.UnknownObjectException: 
    # AttributeError: type object 'GithubException' has no attribute 'UnknownObjectException'
```

Any help as to how to go about specifying PyGithub exceptions would be greatly appreciated as I haven't found any examples online that have worked for me. Thanks!

**Comment by s-t-e-v-e-n-k** [comment]
```
import github
...
except github.UnknownObjectException as e:
```
