### ISSUE TITLE
MainGithub  get_organizations unexpected return type

### ISSUE THREAD

**Issue by DragosDumitrache** [PyGithub/PyGithub#1177]
Hello. I have started writting a Git interaction tool for my current workplace. We have our own instance of GHE and organise everything into orgs. I have started used PyGithub, currently using v1.43.7, which should be the latest one.

Apologies if this has been asked before, I did have a look and could find nothing of the sort.

The `get_organizations` pydoc on the `MainClass.Github` seems to suggest that the returned type for `get_organizations` is a `PaginatedList` of `Organizations`, as can be seen at the following URL: 
[get_organizations docs](https://pygithub.readthedocs.io/en/latest/github.html#github.MainClass.Github.get_organizations)

However, a successful call to `get_organizations` seems to return a `PaginatedList` of `NamedUser`, where each `NamedUser` is actually a git org (so it goes off and finds the right things on GHE, but returns the wrong type).

A quick fix to get the right type is to do something like this:

```py
named_users = git.get_organizations()
for named_user in named_users:
	actual_org = git.get_organization(named_user.login)
```

That is not in line with the documentation though, so I am wondering whether I am doing something wrong, or if this is the intended behaviour.

Kind regards,
Dragos

**Comment by s-t-e-v-e-n-k** [comment]
Nice catch! I've pushed up a fix.
