### ISSUE TITLE
Creating code review changes PR data.

### ISSUE THREAD

**Issue by Ferada** [PyGithub/PyGithub#1181]
I have some code that polls for pull requests, then, in some cases,
creates an automatic approval, like this:

    checked = set()
    ...
                # n is a Notification
                p = n.get_pull_request()
                if p.state == 'open':
                    print("Checking pull request {}.".format(p.id))
                    if p.id in checked:
                        continue
                    if ...
                        ...
                        p.create_review(event="APPROVE", body="")
                        n.mark_as_read()
                    checked.add(p.id)
    ...

This is actually not working like this, because `p.id` is being
modified!

There's this line in `PullRequest.py` in the `create_review` method:

```
        self._useAttributes(data)
```

That looks like it's taking the data from the pull request review and just applies it to itself ... that can't be right, can it? Before I create a PR then, what might have been the reason to have that call in there?

**Comment by s-t-e-v-e-n-k** [comment]
That pattern is actually used in way more places than just Pull Request, I need to dig into this more.
