### ISSUE TITLE
Missing functionality to get all issues associated with a repository project

### ISSUE THREAD

**Issue by meren** [PyGithub/PyGithub#1183]
Thanks for the very useful library. I am using the version `1.43.8` with Python version `3.6`.

I am wondering if there is a way to get all issues associate with a repository project.

I am unable to find a way to get all issues associated with a repository project (I have also not been able to find projects a given issue is associated with, which is very odd).

The raw data for an issue contains information for 'Assignees', 'Labels', and 'Milestone', but not 'Projects', which is shown right before 'Milestone' for every issue on the right-hand side of the GitHub interface, so there must be a straightforward way to get that information.

Any insights would be most welcome, and thank you very much for your time.

**Comment by s-t-e-v-e-n-k** [comment]
Getting all issues with a repository is via the Repository object:

```
>>> for i in list(g.get_repo('PyGithub/PyGithub').get_issues())[:5]:
...     print(i.number)
... 
1194
1193
1188
1187
1185
```

There is a repository method on Issue that returns the repository, like so:

```
>>> issue = g.get_repo('PyGithub/PyGithub').get_issue(1183)
>>> print(issue.repository.name)
PyGithub
```

**Comment by meren** [comment]
Thanks for the response, but this is not what I was asking. I am interested in getting all issues associated with, let's say `PROJECT #1`, some of the issues associated with in the following way:

![image](https://user-images.githubusercontent.com/197307/63217947-11494800-c115-11e9-9970-54e55826c258.png)

Best,
