### ISSUE TITLE
search_repositories() returns an incorrect number of results for queries.

### ISSUE THREAD

**Issue by FurkanToprak** [PyGithub/PyGithub#1185]
While direct use of the REST API v3 returns the complete enumeration of search results, `g.search_repositories()` returns an incomplete list of results.

For example, while `https://api.github.com/search/repositories?q=pony+language:python` shows that `total_count: 286`, `repositories.totalCount` is 111 for `repositories = g.search_repositories(query='pony+language:python')`. Indeed, after traversing through `repositories`, only 111 repositories are returned.

I hope there isn't something I missed in the documentation, but this is a rather serious issue. Thank you!

**Comment by FurkanToprak** [comment]
Here is my code for replication: 
```
from github import Github

g = Github("auth code")
repositories = g.search_repositories(query='pony+language:python')
print("There are at least", repositories.totalCount, "results under this query.")
i = 1
for repo in repositories:
    i += 1
    print(repo.created_at)
print(i)
```

**Comment by Hanaasagi** [comment]
@FurkanToprak A simple way to bypass it.
```Python
from github import Github

token = open('./.token').read().strip()

g = Github(token)
repositories = g.search_repositories(query='pony language:python')
print(repositories.totalCount)
```

After read the code, I think there are something wrong in url encoding.

https://github.com/PyGithub/PyGithub/blob/7bac694ae5378e51903d38bf7fdd10cbd39cedb9/github/PaginatedList.py#L151-L156

Finally, call this

https://github.com/PyGithub/PyGithub/blob/7bac694ae5378e51903d38bf7fdd10cbd39cedb9/github/Requester.py#L363-L376

Actually, it will request 

```Bash
curl "https://api.github.com/search/repositories?q=pony%2Blanguage%3Apython&per_page=1"
```

It will get `"total_count": 111`.

`+` should not be escape in above case.
