### ISSUE TITLE
On issue edit/create/query, labels parameter is inconsistently used

### ISSUE THREAD

**Issue by jpleger** [PyGithub/PyGithub#1187]
This is essentially the same behavior described in #222

When editing/creating/querying labels, some functions require labels to be passed as a Labels object and some require as a string. The preferred behavior would be to accept either a Label object or a string.

I'll submit a PR for this functionality.

**Comment by davidshepherd7** [comment]
This is particularly odd when doing cross-repository querying of issues by label. Since the github issue querying API only accepts label *names* we can't possibly query by label *identity*, which is what passing a Label object appears to be doing.

**Comment by pdxjohnny** [comment]
This is still an issue! Can we get this reopened? Create accepts Label objects, edit only works with label names.
