### ISSUE TITLE
ref parameter does not work on the get_contents() method

### ISSUE THREAD

**Issue by shjain0512** [PyGithub/PyGithub#1197]
If i try to include the ref parameter (branch name other than master), i get the below error :
UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents'}
It seems the ref parameter does not take the branch name other than master. 
Please verify

**Comment by Hanaasagi** [comment]
@shjain0512 For example, in PyGithub v0.1(https://github.com/PyGithub/PyGithub/tree/v0.1). There is a file named  `Design.md` in root dir. But in master branch, the file was removed.

```Python
import base64
from github import Github

token = open('./.token').read().strip()

g = Github(token)
repo = g.get_repo("PyGithub/PyGithub")
print(base64.b64decode(repo.get_contents('Design.md', ref='v0.1').content))
```

I can get the file content correctly. Please check the file in your branch.


**My Environment**
- PyGithub 1.43.8
- Python 3.7.3

**Comment by shjain0512** [comment]
> @shjain0512 For example, in PyGithub v0.1(https://github.com/PyGithub/PyGithub/tree/v0.1). There is a file named `Design.md` in root dir. But in master branch, the file was removed.
> 
> ```python
> import base64
> from github import Github
> 
> token = open('./.token').read().strip()
> 
> g = Github(token)
> repo = g.get_repo("PyGithub/PyGithub")
> print(base64.b64decode(repo.get_contents('Design.md', ref='v0.1').content))
> ```
> 
> I can get the file content correctly. Please check the file in your branch.
> 
> **My Environment**
> 
> * PyGithub 1.43.8
> * Python 3.7.3

Thanks for your reply. Yes, you are right it works in this case. It seems to work with the tag names but not the branch names.

**Comment by Hanaasagi** [comment]
@shjain0512 Branch name also works.

```Python
import base64
from github import Github

token = open('./.token').read().strip()

g = Github(token)
repo = g.get_repo("andymccurdy/redis-py")
print(base64.b64decode(repo.get_contents('run_tests', ref='logging').content))
```

Branch `logging` has a file named `run_tests`. And in `master`, it was deleted.

**Comment by s-t-e-v-e-n-k** [comment]
We don't actually mangle ref at all, we pass it as-is, so I would also ask for a test case where this doesn't work on a public repository.
