### ISSUE TITLE
API for checking the availablity of organization name

### ISSUE THREAD

**Issue by iamshreeram** [PyGithub/PyGithub#1199]
Is there any API, for checking the availability of organization name? 
Below are the details -
Method : `POST` 
URL : `https://api.github.com/organizations/check_name`
API : `check_name`

**Comment by Hanaasagi** [comment]
@iamshreeram Do you mean `get_organization` method? If the organization is not existed, it will throw a 404 exception.

Ref: https://pygithub.readthedocs.io/en/latest/examples/MainClass.html#get-organization-by-name

**Comment by Hanaasagi** [comment]
Sorry, I never heard that an organization could be privated. I know little about this.

**Comment by s-t-e-v-e-n-k** [comment]
That API doesn't exist, and if it did, it would represent an information leak about private organizations. I think @iamshreeram 's suggestion is the correct one, since you are constrained by what you yourself can view.
