### ISSUE TITLE
Preview Handling

### ISSUE THREAD

**Issue by astronouth7303** [PyGithub/PyGithub#1200]
Looking through https://developer.github.com/v3/previews/ it looks like each individual preview has its own MIME type to enable it, and there's no documented sequence to them (that is, it doesn't say that type U also covers types S and T, and there isn't a type Z that enables everything).

It looks like #1188 enables just one of these previews and touches 32 files in the process.

Maybe there's a better, more systemic way to handle this?

The current behavior is a single flag that enables the `moondragon` changes, which are from [2015](https://developer.github.com/changes/2015-01-07-prepare-for-organization-permissions-changes/) and were "merged" on June 24 of that year.

**Comment by astronouth7303** [comment]
Afaik, still an issue

**Comment by astronouth7303** [comment]
afaik, still and issue

**Comment by astronouth7303** [comment]
#1291 is a specific instance of this.

**Comment by astronouth7303** [comment]
Has this been fixed yet?

**Comment by sfdye** [comment]
Sorry about the stale bot, IIRC the use of custom header is supported (used internally), it's just not exposed for the user to use directly. Which header are looking at specifically?

**Comment by sfdye** [comment]
> it looks like each individual preview has its own MIME type to enable it, and there's no documented sequence to them (that is, it doesn't say that type U also covers types S and T, and there isn't a type Z that enables everything).

This is outside the scope of PyGithub, it should be a question for Github support
