### ISSUE TITLE
first time user of pygithub.  Set up incorrect?  I get error when I run the code 

### ISSUE THREAD

**Issue by GayleJames** [PyGithub/PyGithub#1203]
I am writing a python script to access the issues in a our team repository.  Here is what my code looks like:

from github import Github
g=Github("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
repo = g.get_repo("GJ")
open_issues = repo.get_issues(state='open')
closed_issues = repo.get_issues(state='closed')
for issue in open_issues:
    print(issue)

but I get the error below:
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}

do I need the url of the github repository in the code?  Where am i going wrong?

**Comment by s-t-e-v-e-n-k** [comment]
Bad credentials exception points to your token being incorrect. Double check your token, or switch to username and password if you do not have 2FA enabled.

**Comment by s-t-e-v-e-n-k** [comment]
base_url is for GitHub Enterprise, if you aren't using that, or don't know it is, then don't set it. You'll also need to pass password if you're giving a username.

**Comment by GayleJames** [comment]
resolved now, I did not have the api/v3 added to my enterprise url.  Thanks
