### ISSUE TITLE
Incomplete results, retries not working, random exceptions

### ISSUE THREAD

**Issue by x00x0x00x** [PyGithub/PyGithub#1204]
Configuration:
g = Github({api_key}, per_page=100, retry=1000)

**1** - Retries do not execute, the program ends with an error
**2** - For some reason Exception behavior is highly unpredictable and it's maddening.
My program can effectively cycle and preemptively call the ratelimit api to check if it adheres within the limits for one to two hours before randomly getting a 403/50x .

Some native rate limit adherence would be a warm welcome here. Having to implement sleeps based on intuition when your application decides to spill the beans after two hours of running smoothly should not be expected behavior.
``` File "word.py", line 126, in get_stargazers_inner
    for i in repo.get_stargazers_with_dates():
  File "/usr/local/lib/python3.6/dist-packages/github/PaginatedList.py", line 62, in __iter__
    newElements = self._grow()
  File "/usr/local/lib/python3.6/dist-packages/github/PaginatedList.py", line 74, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/lib/python3.6/dist-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers=self.__headers
  File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 276, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 287, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {'message': 'API rate limit exceeded for user ID xxxx.', 'documentation_url': 'https://developer.github.com/v3/#rate-limiting'}
```

Additionally, one could use the backoff library (function decorator with exponential backoff) -- however **it can not account for the current position in item iteration and will therefore start from scratch again**.
**3** - Incomplete results being returned
Example with keyword 'nyzo':
The api finds 28 results: https://api.github.com/search/repositories?q=nyzo
The library finds 15 results: https://i.imgur.com/XfjPI8i.png

**Comment by Hanaasagi** [comment]
For problem 1, I think you can use the `urllib3.util.Retry`, it provide more useful options to custom retry behavior.

Ref https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#urllib3.util.retry.Retry

----
For problem 3, I could not reproduce. Here my test code.

```Python
from github import Github

token = open('./.token').read().strip()

g = Github(token, per_page=100, retry=1000)
repos = g.search_repositories('nyzo')
count = 0
for repo in repos:
    print(repo.full_name)
    count += 1
print(f'\nTotal: {count}')
```

I got 28 results.
