### ISSUE TITLE
Getting a 404{data  error cant figure out

### ISSUE THREAD

**Issue by GayleJames** [PyGithub/PyGithub#1206]
I am trying to connect to our github url and I get what is below(this is just a portion:

**github.GithubException.GithubException: 404 {'data': '<!DOCTYPE html>\n<html>\n  <head>\n    <meta http-equiv="Content-type" content="text/html; charset=utf-8">\n    <meta http-equiv="Content-Security-Policy" content="default-src \'none\'; base-uri \'self\'; connect-src \'self\'; form-action \'self\'; img-src \'self\' data:; script-src \'self\'; style-src \'unsafe-inline\'">\n    <meta content="origin" name="referrer">\n    <title>Page not found &middot; GitHub</title>\n    <style type="text/css" media="screen">\n      body {\n        background-color: #f1f1f1;\n        margin: 0;\n      }\n      body,\n      input,\n      button {\n
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;\n      }\n      .container { margin: 30px auto 40px auto; width: 800px; text-align: center; }\n\n      a { color: #4183c4; text-decoration: none; font-weight: bold; }\n      a:hover { text-decoration: underline; }\n\n      h3 { color: #666; }\n      ul { list-style: none; padding: 25px 0; }\n      li {\n        display: inline;\n        margin: 10px 50px 10px 0px;\n      }\n      input[type=text],\n      input[type=password] {\n        font-size: 13px;\n        min-height: 32px;\n        margin: 0;\n        padding: 7px 8px;\n        outline: none;\n        color: #333;\n
      background-color: #fff;\n        background-repeat: no-repeat;\n** 

what could be wrong ?  what should be in the base_url?
I have the url of our github in there g=Github(base_url="https://www.oururl.com",login_or_token="xxxxx..............")

**Comment by peterkline** [comment]
This code has worked for me for the past few years.

```python
# gho is the login context after successful auth
token = "token"
github_url = "https://my_local_github.domain.com"
gho = github.Github(login_or_token=token, base_url=github_url)
```

**Comment by GayleJames** [comment]
thanks tried this way and i get: github.GithubException.GithubException: 404 {'data': 'Not Found'}
i am also using the enterprise domain name url

**Comment by peterkline** [comment]
So your URL looks like:
"https://www.oururl.com/api/v3"

with the api path?

Sorry my example was quickly typed out above.

**Comment by GayleJames** [comment]
no i use the url of our enterprise github site.  That is what i should be using for the base-url correct?

**Comment by peterkline** [comment]
I use GHE as well. You need the /api/v3 in your URL to create the connection

**Comment by GayleJames** [comment]
so you mean just add that on the end ? like so:?  www.compentrname.com/api/v3

**Comment by GayleJames** [comment]
so instead of this: github_url = "https://my_local_github.domain.com"
it should be: github_url = "https://my_local_github.domain.com/api/v3"?

**Comment by peterkline** [comment]
yes

**Comment by GayleJames** [comment]
now i get :     raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/enterprise/2.16/v3/repos/#get'} 
hmm any ideas?  i will look at the link there hmm

**Comment by peterkline** [comment]
Please post your code block if you can.  That will help the most

**Comment by GayleJames** [comment]
ok here it is:
**from github import Github
from pprint import pprint
token=("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
url="https://www.mycompany.com/api/v3"
g=Github(login_or_token=token,base_url=url)
print("MADE IT HERE")
print(url)
repo = g.get_repo("orgname/reponame.git")
open_issues = repo.get_issues(state='open')
for issue in open_issues:
    print(issue)**

**Comment by peterkline** [comment]
remove the .git from the repo name and give it a try

**Comment by GayleJames** [comment]
OMG i love you! that worked! thanks, I have been trying to get this figured out for days! 

**MADE IT HERE
https://www.xxxxx.com/api/v3
Issue(title="File Defects", number=8)**

**Comment by peterkline** [comment]
great!  Glad I could be of some help.

Please don't forget to close out the ticket.

**Comment by GayleJames** [comment]
ok
