### ISSUE TITLE
unable to get repo topics when using topics property

### ISSUE THREAD

**Issue by Hanaasagi** [PyGithub/PyGithub#1208]
### Problem

Recently, I found a problem on getting a repo's topics. If I use the `topics` property, it never work. But if I use the `get_topics` method, it will work.

```Python
from github import Github

token = open('./.token').read().strip()

g = Github(token)
repo = g.get_repo('PyGithub/PyGithub')
assert repo.topics is None
assert len(repo.get_topics()) == 4
```

### Environment

- PyGithub == 1.43.8
- Python == 3.7.4

The master branch (`a0f01cf`) has the same problem.

----
After check the source code of `get_topics`, I find that there should be have a specical header `"application/vnd.github.mercy-preview+json"`

https://github.com/PyGithub/PyGithub/blob/a0f01cf9cf5521fd034813242727de72eb52df42/github/Repository.py#L2529-L2539

Thanks, I wanna submit a patch for this.

**Comment by sfdye** [comment]
Feel free to send us a PR

**Comment by ipfans** [comment]
Same problems here.
@sfdye can we merge this PR and release new version?
