### ISSUE TITLE
Endpoint / method to retrieve all the files on a range of PRs

### ISSUE THREAD

**Issue by michaelvincerra** [PyGithub/PyGithub#1220]
I'd really like to see all the files included on a Pull Request (PR) for several PRs, using PyGitHub. 
Incidentally, I created a hack to get this information, using the GitHub API v3, but it's not very graceful. And given the anonymous management of queries with PyGithub, it'd be so cool to have this feature in PyGithub vs. the GitHub API.  

I noticed this unit test only verifies that files on one pr can be retrieved.  
https://github.com/PyGithub/PyGithub/blob/master/github/PullRequest.py

Does that speak to the intended use case? I'd like to know. Especially because the return value of this method provide a "Paginated list" object. 

Problem scenario: This method yields only one document on one PR. 
"""
g = Github("username", "password")
user = g.get_user("distro")
repo = user.get_repo("documentation")
pulls = repo.get_pulls(state='all', sort='created', base='master', direction="desc")
for pull in pulls: 
   files = pull.get_files()
   print(files) 
"""

This methods seems to be imagined as if a developer only seeks files on 1 PR, and not all the files on a range of PRs.   If I'm missing some method in your docs that already exists, please let me know. 

Here's where I've looked: 
https://pygithub.readthedocs.io/en/latest/github_objects/File.html
https://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html

**Comment by s-t-e-v-e-n-k** [comment]
PaginatedList is an iteratable, since that is what the v3 API gives us to play with for many many return types.  You can either call list() on pull.get_files() or just iterate over it. Other than that, your code should get all files in the range of PRs.

**Comment by michaelvincerra** [comment]
Thanks for the response. If I call `list()', I receive: 
"""
AttributeError                            Traceback (most recent call last)
<ipython-input-35-14e486d3b05d> in <module>()
     59     file = pull.get_files()
     60     for f in file:
---> 61         f = file.list()
     62     print(f)
     63 

AttributeError: 'PaginatedList' object has no attribute 'list'
"""

**Comment by s-t-e-v-e-n-k** [comment]
I'm sorry, I'll be more clear.

You can either do:

```
files = list(pull.get_files())
print(files)
```

or

```
for f in pull.get_files():
    print(f)
```

**Comment by michaelvincerra** [comment]
Thank you for the clarification. I'd love to see more examples like this in your docs.
