### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith' when trying to access UserKey attributes

### ISSUE THREAD

**Issue by pirate** [PyGithub/PyGithub#1224]
**Description:**

I'm trying to iterate through Github users and get their public keys.  Unfortunately I'm getting an `AttributeError` when trying to access some of the returned `UserKey` object's attributes. 

This happens whether the attributes are accessed directly or via `.raw_data`.

It looks like it's an issue with some of the attributes only being available on `AuthenticatedUser`'s keys vs a `NamedUser`'s keys.

**Steps to reproduce:**
```python
from github import Github

g = Github('access_token')

for user in g.get_users():
    keys = '\n'.join(
        f'key: {key.url}'
        for key in user.get_keys()
    )
    print(f'{user.id} {user.login}\n{keys}')
```

```python
  File "./all_github_users.py", line 27, in <genexpr>
    for key in user.get_keys()
  File "/usr/local/lib/python3.7/site-packages/github/UserKey.py", line 82, in verified
    self._completeIfNotSet(self._verified)
  File "/usr/local/lib/python3.7/site-packages/github/GithubObject.py", line 265, in _completeIfNotSet
    self._completeIfNeeded()
  File "/usr/local/lib/python3.7/site-packages/github/GithubObject.py", line 269, in _completeIfNeeded
    self.__complete()
  File "/usr/local/lib/python3.7/site-packages/github/GithubObject.py", line 274, in __complete
    self._url.value
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 276, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 292, in __customConnection
    if not url.startswith("/"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Line causing the error:**

https://github.com/PyGithub/PyGithub/blob/a0f01cf9cf5521fd034813242727de72eb52df42/github/Requester.py#L284

**Expected behavior:**

The attributes not available on a `NamedUser`'s keys should be `None` or not present on `UserKey`.

**Comment by s-t-e-v-e-n-k** [comment]
UserKey performs double duty being returned from get_keys(), as well as used for AuthenticatedUser.create_key(), which means we need to handle both cases. I'm reticent to create a special type just for get_keys().

What is happening here is the raw data returned by GitHub gives you the id and the key text only. Since all of the attributes attempt to complete an incomplete object, it attempts to GET self.url, which is None, because GitHub didn't return one.

Thinking on it, we could add an IncompletableObject exception, rather than this traceback.

**Comment by pirate** [comment]
It doesn't need to be a special type, just put None in those values so it doesn't error out, `.raw_data` should still be usable even if the object doesn't have all the values imo, otherwise the UX is frustrating because you can't dump the object without manually iterating over the keys and knowing beforehand which ones will error and which ones wont.

**Comment by s-t-e-v-e-n-k** [comment]
.raw_data calls complete() just in case we don't have the complete object, which will lead to the exact traceback you're seeing. You can look under the covers using ._rawData, but everything is terrible when GitHub doesn't return a URL of the object. :-(
