### ISSUE TITLE
Can I Create Tokens with PyGithub? I can't find any examples and would love some guidance  

### ISSUE THREAD

**Issue by lwasser** [PyGithub/PyGithub#1230]
Hi There 👋 !
I'm new to pygithub and the github api so please let me know if this isn't the right place to ask this question. i've been pouring through the docs and do some some reference to the [authorization](https://pygithub.readthedocs.io/en/latest/github_objects/Authorization.html) object but i'm not exactly sure how to use it. Has anyone implemented authorization as follows:

user authenticates with github username and password
Token is created in their account via pygithub
Token string is accessed via pygithub

Most of the examples start with the user providing the login credentials or the token string. but i'd like to create the string via the api and then access it.

Thank you for any guidance!

**Comment by kcranston** [comment]
Trying to switch from github3 to pygithub, and looking for replacement instructions for gh3's  [authenticating with 2FA](https://github3py.readthedocs.io/en/master/examples/two_factor_auth.html) and [using tokens](https://github3py.readthedocs.io/en/master/examples/oauth.html). I can see how to use pygithub  login with username + password, or how to login with a token, but would like to authenticate with username + password + 2fa_code and then use that authentication to get a token (which I can then save to a local config).

**Comment by lwasser** [comment]
we need a sad face github emoji for this!

**Comment by Zethson** [comment]
Could this issue be reopened?
