### ISSUE TITLE
since arguement of get_repos

### ISSUE THREAD

**Issue by megretson** [PyGithub/PyGithub#1232]
Hi all! 

I am trying to use pygithub to get a list of publicly available repos on github. Rather than getting all repos available on github, I'm trying to limit it to a subset of these repos. My code is as follows:

```
from github import Github
import sys
import datetime as dt

g = Github(sys.argv[1]) // token passed as command line argument
since = dt.datetime.now() - dt.timedelta(minutes=1) // get all repos in the past minute

for repo in g.get_repos(visibility='public', since=since):
    print(repo.name)
```

This consistently throws the following error:
```
    assert since is github.GithubObject.NotSet or isinstance(since, int), since
AssertionError: 2019-09-30 10:22:20.979714
```

In the documentation it's clear the since argument is expecting an integer (see here: https://pygithub.readthedocs.io/en/latest/github.html ) but I cannot see how an integer could be used in this context. Can someone please explain the usage of this argument?

**Comment by Chun-Fil-A** [comment]
I think the doc may be wrong, this is the method header I'm seeing in master 

```    def get_repos(self, type=github.GithubObject.NotSet, sort=github.GithubObject.NotSet, direction=github.GithubObject.NotSet):
        """
        :calls: `GET /orgs/:org/repos <http://developer.github.com/v3/repos>`_
        :param type: string ('all', 'public', 'private', 'forks', 'sources', 'member')
        :param sort: string ('created', 'updated', 'pushed', 'full_name')
        :param direction: string ('asc', desc')
        :rtype: :class:`github.PaginatedList.PaginatedList` of :class:`github.Repository.Repository`
        """```

**Comment by Chun-Fil-A** [comment]
The method in the MainClass.py referes to the github api v3. 
It is looking for the id of the last repository you have seen.
This link goes into further detail.  
https://developer.github.com/v3/repos/#list-all-public-repositories
