### ISSUE TITLE
Do not allow to perform requests

### ISSUE THREAD

**Issue by maxlovic** [PyGithub/PyGithub#1233]
Hi everyone.
I am using the library for my pet project. I really like its architecture,
However, I ran into an issue or a feature of the library.
I need to retrieve information about all the issues (including pull requests) in a repository. I was surprised by the low performance of the following script.

```python
import pandas as pd
from github import Github

def load(reponame, login, password):
    # Log in to GitHub (see below)
    gh = Github(login, password, per_page=100)
    # Define the repository: reponame="user/repo"
    repo = gh.get_repo(reponame)

    # Create a pandas dataframe
    column_names = ["Created", "IsPR"]
    df_issues = pd.DataFrame(columns = column_names)

    issues = repo.get_issues(state="all")

    for issue in issues:
        df_issues.loc[issue.number] = [issue.created_at,
                    issue.pull_request != None, issue.labels, issue.milestone]
    
    return df_issues
```

The script should load up to 100 issues in one request and process them in a loop.
I have noticed that while in `for issue in issues:`, the script still utilizes network.

Digging into this weird behavior, it turned out, that PyGithub can send a request to GitHub if a property value is not set:

```python
@property
def pull_request(self):
    """
    :type: :class:`github.IssuePullRequest.IssuePullRequest`
    """
    
    self._completeIfNotSet(self._pull_request)
    if self._pull_request is NotSet:
        return None
    return self._pull_request.value
```

So when the script fetches 100 issues, `N` of them are pull requests. For those `100-N` issues the `pull_request` property value is not set. On each such issue a network request to GitHub is performed.

For my use case these http requests are useless, significantly decrease performance and sometimes make gthub to reject the request due to rate limiting.
I already have this data. required. If `self._pull_request is NotSet`, then I can safely say it is not a PR, but an issue.

I have not found a way to turn off this behavior in PyGithub's API.

I think there should be a way to tell, that I dont want further hidden request when acessing an item (`GithubObject`)
I think there should be an option to tell if hidden requests on an object are allowed.
At the moment the `_fetchNextPage` function of `PaginatedList` sets all items as not completed:
```
self.__contentClass(self.__requester, headers, element, completed=False)
```

A workaround might be to use `get_pulls` to retrieve all pull requests, but then the data is retrieved again, although it is already present when retreiving issues.

**Comment by maxlovic** [comment]
Up

**Comment by s-t-e-v-e-n-k** [comment]
These "hidden" requests are a feature. We want to make access to the GitHub API easy, sadly, this does mean that if the GitHub API hasn't returned enough information, we need to make another request.

I think the easiest way is via monkey patching by making your request and then overriding g._requester.__structuredFromJson to always return None.

**Comment by maxlovic** [comment]
The thing is that repo.get_issues() already has PR flag if it is a PR. Because the whole info about the issue is retrieved.
So I would suggest adding conditional hidden requests. Certain fields do not need hidden requests.

**Comment by s-t-e-v-e-n-k** [comment]
The PaginatedList that is behind get_issues() is generic and we have absolutely no idea if GitHub has returned everything in a list format because we're at the mercy of whatever they send us. So for safety we assume every item in the list is incomplete.
