### ISSUE TITLE
edit_branch_protection returns 404 object not found error 

### ISSUE THREAD

**Issue by prasathkumarramachandran** [PyGithub/PyGithub#1239]
I am trying to edit the branch protection for the master branch using edit_branch_protection..
This returns object not found 404 error.. I am using github enterprise server..

---> 69     branch.edit_protection(strict=True,require_code_owner_reviews= True, required_approving_review_count=2)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\github\Branch.py in edit_protection(self, strict, contexts, enforce_admins, dismissal_users, dismissal_teams, dismiss_stale_reviews, require_code_owner_reviews, required_approving_review_count, user_push_restrictions, team_push_restrictions)
    178             self.protection_url,
    179             headers={'Accept': Consts.mediaTypeRequireMultipleApprovingReviews},
--> 180             input=post_parameters
    181         )
    182 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\github\Requester.py in requestJsonAndCheck(self, verb, url, parameters, headers, input)
    274 
    275     def requestJsonAndCheck(self, verb, url, parameters=None, headers=None, input=None):
--> 276         return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
    277 
    278     def requestMultipartAndCheck(self, verb, url, parameters=None, headers=None, input=None):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\github\Requester.py in __check(self, status, responseHeaders, output)
    285         output = self.__structuredFromJson(output)
    286         if status >= 400:
--> 287             raise self.__createException(status, responseHeaders, output)
    288         return responseHeaders, output
    289 

UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/enterprise/2.17/v3/repos/branches/#update-branch-protection'}

**Comment by s-t-e-v-e-n-k** [comment]
Did you fetch the branches using get_branches()? That does not return enough information to call the protection methods, you must use get_branch() to get the complete information.
