### ISSUE TITLE
get_labels() on a Pull Request 

### ISSUE THREAD

**Issue by michaelvincerra** [PyGithub/PyGithub#1244]
Similar to GH-1220. 

Can you please advise on how to retrieve the *labels* on 1 pull request?
  
Your revised documentation, April 2018,  makes change to conform to GitHub API v3 in this PR: https://github.com/PyGithub/PyGithub/pull/754/commits/8ff93f5f576dc8d4c5d6afce85c9273e5b97c73f

What's not clear to me is how I could replace `issues` with `pulls` in the above PR.

I would like an example of how to query the labels in 1 pull request (my example returns a select few).  To do so, the example could be similar to getting specific labels in open issues, like so:

```
gH      = Github("user", "password")
user    = gH.get_user('<gh-user>')
repo    = user.get_repo("<repo-name>")
pulls   = repo.get_pulls(state='all', sort='created', base='master', direction="desc")[:5]
issues   =  repo.get_issues(state="open")  

for issue in issues:
    labels = issue.labels
    label = [l.name for l in labels if l.name=='P1' or l.name=='P2' or l.name=='P3']
    print(label)
```
Alternate: In example below, I'd like to replace `issues` with `pulls`, but it doesn't work.

``` 
           for issue in issues:
                labels = issue.get_labels()
                label = [l.name for l in labels if l.name=='P1' or l.name=='P2' or l.name=='P3']
                print(label)
```

Also, in PyGitHub's docs, `labels` is an attribute of the github.PullRequest.PullRequest class. 
It's not clear whether one can pull labels on a single PR, per docs here:
https://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html#pullrequest

**Comment by michaelvincerra** [comment]
@s-t-e-v-e-n-k requested, please.

**Comment by s-t-e-v-e-n-k** [comment]
Your replacement of issues with pulls still says issues. However, hopefully the below helps you:

```
>>> repo = g.get_repo('PyGithub/PyGithub')
>>> pr = repo.get_pull(1231)
>>> pr.labels
[Label(name="high priority"), Label(name="improvement")]
>>> for label in pr.get_labels():
...     print label.name
... 
high priority
improvement
```

**Comment by michaelvincerra** [comment]
Thanks for your quick response.  I don't quite understand  the leap in logic that you propose. 
Can you explain in more detail?
> Your replacement of issues with pulls still says issues. 

Goal:  Systematically expose the `labels` on several PRs (if labels are P1, P2, or P3).
If I can show the labels on one Pull Request (PR), then I can expose labels on several PRs. 
I realize in your example, you use the REPL, whereas I'm writing a function. 

When I follow your example, I use PR 844 in my repo, which has been merged.
```
pr = repo.get_pull(844)
labels = pr.get_labels()
print(type(labels)) # I use `type` to understand how to introspect the object/or iterate  over it.
```
Output: 
```
<class 'github.PaginatedList.PaginatedList'>
```
The problem is: 1) I don't understand how to iterate over the PaginatedList; and 2) if I use the next modified example, it produces an empty list: `[ ]`
```
pr = repo.get_pull(844)
labels = pr.get_labels()
x = [l.name for l in labels]
print(x)
```
Output: 
```
[ ]
```
Any advice or pointers would be extremely helpful. 


>However, hopefully the below helps you:
> ```
> >>> repo = g.get_repo('PyGithub/PyGithub')
> >>> pr = repo.get_pull(1231)
> >>> pr.labels
> [Label(name="high priority"), Label(name="improvement")]
> >>> for label in pr.get_labels():
> ...     print label.name
> ... 
> high priority
> improvement
> ```

**Comment by s-t-e-v-e-n-k** [comment]
A PaginatedList is just an iterable, you can iterate over it directly in a for loop or a list comprehension, or you can coerce it to a list by calling list() on it -- ```list(labels)``` in your code above. PR 844 has no labels, which is why it's an empty list. Which is why I picked PR 1231, because it has two set.

**Comment by mvincerx** [comment]
Thank you @s-t-e-v-e-n-k.  Nothing like scientific proof to humble a man...  I didn't realize that most recent PRs didn't have labels; therefore, an empty list is the expected response. I've since changed that so most recent PRs do have labels. Now the `get_labels()` call returns labels on a PR. I'd like to applaud your team in making that invocation of the Pull Request object available to developers.

**Comment by s-t-e-v-e-n-k** [comment]
You're welcome!
