### ISSUE TITLE
403 {'message': 'Maximum number of login attempts exceeded. Please try again later.

### ISSUE THREAD

**Issue by dontejiggetts** [PyGithub/PyGithub#1248]
Hello,

I am trying to incorporate this API in my code. I am trying to simply authenticate a Github object using the code from the tutorial. I have a class that looks like this:

from github import Github

token = "some token"

# Github Enterprise with custom hostname
g = Github("url", token)

# Then play with your Github objects:
for repo in g.get_user().get_repos():
    print(repo.name)

When I run this script I get the following:
github.GithubException.GithubException: 403 {'message': 'Maximum number of login attempts exceeded. Please try again later.', 'documentation_url': 'https://developer.github.com/v3'}

Is there any way to fix this? I got this exception today and I have not tried to run this since yesterday evening. I have tried making new tokens and still get the same problem. Any help would be useful. Thank you

**Comment by s-t-e-v-e-n-k** [comment]
The first parameter for Github() is your token, not the URL, so I think that error is coming from Github itself trying to authenticate with a username of your Enterprise install and a password of your token.

You should be using:
```
g = Github(token, base_url="url")
```
