### ISSUE TITLE
How to deal with token expiration?

### ISSUE THREAD

**Issue by tino** [PyGithub/PyGithub#1264]
This is both a question and a report of what I think is a design flaw. I'm trying to use PyGithub in a webapp that handles Github webhooks. I've set up a Github App for it, and am able to authenticate and perform the actions I want. However, now it is time to deal with token expiration, as Github tokens only live for an hour.

The first hurdle is that the `expires_at` property of an `InstallationAuthorization()` returns a naive datetime. Trying to assert the token is still valid is therefor problematic:
```python
>>> import os
... import codecs
... from github import Github, GithubIntegration
... decoder = codecs.getdecoder("unicode_escape")
... PRIVATE_KEY = decoder(os.environ["GITHUB_APP_PRIVATE_KEY"].encode())[0]
... APP_ID = 44107
... INSTALLATION_ID = 3289834
... integration = GithubIntegration(APP_ID, PRIVATE_KEY)
... integration_accessor = integration.get_access_token(INSTALLATION_ID)

>>> integration_accessor
InstallationAuthorization(expires_at=2019-10-20 09:36:48)

>>> import datetime
... now = datetime.datetime.now().astimezone()

>>> integration_accessor.expires_at > now
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't compare offset-naive and offset-aware datetimes
```

If I *naively* try to do this, the token is "expired" the moment I get it:
```python
>>> import time
... integration_accessor = integration.get_access_token(INSTALLATION_ID)
... now = datetime.datetime.now()
... print('valid?', now < integration_accessor.expires_at)
... print(now)
... print(integration_accessor.expires_at)
valid? False
2019-10-20 09:56:53.049639
2019-10-20 09:56:53

>>> now.astimezone().tzinfo
datetime.timezone(datetime.timedelta(0, 3600), 'WEST')
```
That is of course because I'm in UTC+1, but would be the case for everyone in later-than-UTC timezones. So I really think `expires_at` should be a timezone-aware datetime object.

But in general, how do people handle this? Any wrapper code to check a token for being still valid out there? Or a re-auth & retry loop?

**Comment by LeoQuote** [comment]
You can store it in redis and give it an expire time slightly smaller than 3600s.

**Comment by huwcbjones** [comment]
Token expiry is in UTC (hence no timezone)
Therefore use `datetime.utcnow()` and you won't have any issues
