### ISSUE TITLE
After v 1.44, TypeError: encoding or errors without a string argument

### ISSUE THREAD

**Issue by hopkinsnji** [PyGithub/PyGithub#1266]
I have a job that runs regularly... it threw this error today- `TypeError: encoding or errors without a string argument`. So I pinned the version to v1.43.8 and it works fine. 
![Screen Shot 2019-10-21 at 12 46 30 PM](https://user-images.githubusercontent.com/45208412/67234786-5c305600-f40b-11e9-89d9-40cd9da0751e.png)
I wonder if anyone else has experienced the same issue.

**Comment by s-t-e-v-e-n-k** [comment]
I changed that code explicitly during one of my remove Python 2 only code crusades. I'll investigate.

**Comment by hopkinsnji** [comment]
Thanks a lot s-t-e-v-e-n-k
