### ISSUE TITLE
get_organization_membership is using the wrong api

### ISSUE THREAD

**Issue by moustafab** [PyGithub/PyGithub#1276]
I'm trying to get the membership of a list of users in an org, and the methods for NamedUser and Authenticated user is using the [get-your-organization-membership](https://developer.github.com/v3/orgs/members/#get-your-organization-membership) api but NamedUser should be using the [get-organization-membership](https://developer.github.com/v3/orgs/members/#get-organization-membership) api

**Comment by s-t-e-v-e-n-k** [comment]
Good catch, thanks! However, there should be methods on Organization to get the list of members too.
