### ISSUE TITLE
Exception in get_dir_contents

### ISSUE THREAD

**Issue by roptat** [PyGithub/PyGithub#1283]
In the latest release of PyGithub, I found the following exception thrown by get_dir_contents:

```
Traceback (most recent call last):
  File "/data/tyreunom/projects/offlate/offlate/systems/github.py", line 63, in send
    sha = project.get_dir_contents(mfile, 'translation').sha
  File "/gnu/store/jgz8y4a97rys726clj8n67kiqpwwy1bf-profile/lib/python3.7/site-packages/github/Repository.py", line 1806, in get_dir_contents
    for attributes in data
  File "/gnu/store/jgz8y4a97rys726clj8n67kiqpwwy1bf-profile/lib/python3.7/site-packages/github/Repository.py", line 1806, in <listcomp>
    for attributes in data
TypeError: string indices must be integers
```

I think the issue is that it expects to be looking for a directory, not a single file. Line 1806 has:

```python
return [
  github.ContentFile.ContentFile(..., completed=(attributes["type"] != "file"))
  for attributes in data
]
```

but data is a dictionary when looking for a single file, so attributes is a key (a string), leading to the above exception. I can work around that issue by looking for the parent directory and looping over the results.

**Comment by s-t-e-v-e-n-k** [comment]
I can reproduce that traceback when fetching a file, but not a directory. There is a more suitable method to fetch files: Repository.get_contents().

**Comment by s-t-e-v-e-n-k** [comment]
I'm tempted to "fix" this by throwing an exception if data is a dictionary.

**Comment by roptat** [comment]
oh I didn't see the get_contents, thanks. I guess it's fine to throw an exception, then. Would be nice to document that though, since they both use the same API call :)
