### ISSUE TITLE
Feature request : Access to Security alerts settings

### ISSUE THREAD

**Issue by rodo** [PyGithub/PyGithub#1288]
I would like to read the settings of security alerts on repositories, adding a function to get these informations on a repo will be helpful.

Thanks for all your work, your lib is really useful

**Comment by miketheman** [comment]
This appears to have been implemented in #1195 and released in version 1.44 (latest is 1.45) - have you tried to use this version and functionality?

**Comment by rodo** [comment]
Thanks it's now possible to know and change the status of this parameter.
