### ISSUE TITLE
Select custom media type for diff and patch formats

### ISSUE THREAD

**Issue by gioboske** [PyGithub/PyGithub#1291]
How to select a custom media type in header to get a response in diff or patch format (for commits, commit comparison, and pull requests as specified in [GitHub API](https://developer.github.com/v3/media/#commits-commit-comparison-and-pull-requests).

More in general: how custom media type in request header are supported in PyGithub?
I've read PyGithub API, but I didn't find any solution only found some similar issues (such as #1188).

Thank you!

**Comment by astronouth7303** [comment]
I observe that this is a problem generally in #1200.

Simply, afaik,m PyGithub does not have a solution for previews right now.

**Comment by gioboske** [comment]
Thank you for the clarification.
