### ISSUE TITLE
A better way to read the get_comment comment.body

### ISSUE THREAD

**Issue by imvieira** [PyGithub/PyGithub#1292]
```
from github import Github

gh = Github(base_url="https://github.XYZ.com/api/v3", login_or_token="XXXX")
repo = gh.get_repo("ORG/REPO")

for issue in repo.get_issues(state='all'):
    for comment in issue.get_comments():
        print(comment.body.encode("utf-8"))

```
I ran the sample above to get all the comments from each issue. However, the output is almost unreadable because left the words like "\n\r" all over the text without a spacing or paraphrasing. 

Please, do you know a better way to get the comments and its format with the sample code above? Thank you!

**Comment by s-t-e-v-e-n-k** [comment]
You're now printing bytestrings, since you're encoding the output to UTF-8. The easiest way is to fix your terminal to work with UTF-8 and not encode the body.
