### ISSUE TITLE
Support for "Autolink References" (aka key_links)

### ISSUE THREAD

**Issue by tomislacker** [PyGithub/PyGithub#1293]
## Story
As a user of this fine library, I'd like to be able to conduct CRUD operations on the new _Autolink References_ feature, [introduced 2019-10-14](https://github.blog/2019-10-14-introducing-autolink-references/). This would allow for creating automation, such as a [probot](https://github.com/probot) app for managing them.

Unfortunately though, there is no real API target yet and only works through `github.com` -- there is not even a [preview](https://developer.github.com/v3/previews/) for it. Perhaps given that, this feature request should be considered void until they do.

## Details
Using browser dev tools, we can see what the requests look like. Below are the observations I made.

### Check (POST) `/:owner/:repo/settings/key_links/check`
Multipart Form Fields:
- `key_link[key_prefix]`: `JIRAPROJECTA-`
- `key_link[url_template]`: `https://jira.pygithub.com/browse/JIRAPROJECTA-<num>`

### Create (POST) `/:owner/:repo/settings/key_links/new`
Form fields:
- `utf8`: `✓` _No idea what this is about..._
- `authenticity_token`: _REDACTED (string, base64 encoded binary string)_
- `timestamp`: _REDACTED (long, unix epoch of request with millis)_
- `timestamp_secret`: _REDACTED (string, 64 character hexadecimal)_
- `key_link[key_prefix]`: `JIRAPROJECTA-`
- `key_link[url_template]`: `https://jira.pygithub.com/browse/JIRAPROJECTA-<num>`

### Delete (POST) `/:owner/:repo/settings/key_links/<key_link_id>`
Form fields:
- `_method`: `delete`
- `authenticity_token`: _REDACTED (string, base64 encoded binary string)_

### List
This one doesn't seem to have a REST-y endpoint yet and reloads the page with
a (GET) `/:owner/:repo/settings/key_links`.

**Comment by s-t-e-v-e-n-k** [comment]
I don't think this is even a REST API, this appears to be set up using github.com directly, and does not appear in the API docs.

**Comment by Parakoopa** [comment]
This should be re-opened now:
https://github.blog/changelog/2021-08-02-apis-for-autolinks/

**Comment by wyardley** [comment]
Hi all - could this and / or #2016 get reopened?
