### ISSUE TITLE
closed event doesn't populate commit_id

### ISSUE THREAD

**Issue by dleach02** [PyGithub/PyGithub#1295]
The documentation on events notes that the close event will populate the commit_id field if the issue was closed by a PR using the "closes / fixes #NN" syntax. I have not seen this to be true and am now wondering what the linkage is from an issue that allows the GitHub UI to display "Fixed by #NN" on the closed status line?

https://developer.github.com/v3/issues/events/

**Comment by s-t-e-v-e-n-k** [comment]
We are entirely at the mercy of what GitHub returns here, I can see there is a "reference" Event that includes the commit ID after the "closed" event.

**Comment by dleach02** [comment]
@s-t-e-v-e-n-k , this isn't always the case about the reference event. I understand this package is at the mercy of GitHub so is there a forum to post questions to GitHub API to ask  how this is actually done?

**Comment by s-t-e-v-e-n-k** [comment]
There is https://github.community/t5/GitHub-API-Development-and/bd-p/api .
