### ISSUE TITLE
SEARCH_COMMITS() not working for multiple attribute

### ISSUE THREAD

**Issue by nitishvu** [PyGithub/PyGithub#1308]
Hi
function call 1 and 2 are working fine but 3 failing.
can you please help

1)github_auth.search_commits("author:nvulli")
2)github_auth.search_commits("author-date:<2019-08-26")
3)github_auth.search_commits("author:nvulli+author-date:<2019-08-26")

**Comment by Xiaoven** [comment]
I have the same problem, too
