### ISSUE TITLE
Need repo.get_project(id)

### ISSUE THREAD

**Issue by rayjlinden** [PyGithub/PyGithub#1311]
Looks like the only way to get a project is to get all the projects from a repo and then find the right one from that.  If I know the id before - it would be nice to get the project from the repo by id.

**Comment by s-t-e-v-e-n-k** [comment]
There is -- it just isn't under Repository. It's a top level call, 
 documented here: https://pygithub.readthedocs.io/en/latest/github.html#github.MainClass.Github.get_project
