### ISSUE TITLE
Referencing github.Issue.Issue pull_request forces extra API call to GitHub 

### ISSUE THREAD

**Issue by dleach02** [PyGithub/PyGithub#1316]
When using the search_issues API a PaginatedList of Issues is returned. When you iterate through the list and try to check whether the issue is a pull request or not you test the Issue.pull_request field for Null test. 

Problem is that if the Issue item is not a PR, this field has not been "completed" so the library makes an API call to GitHub to grab the individual issue being processed causing an unnecessary API call (and using up your rate limits). We already have all the issue data from the search. But this time when the object is updated with the issue data, object is considered "completed".

If the issue object actually is a PR this field will have already been "completed" so no extra API call is performed.

All the fields in the Issue object should have been considered "completed" when building the PaginatedList from the search_issues.

**Comment by dleach02** [comment]
As a test, I modified the calls to self.__contentClass() to pass in 'completed=True' when building the list of objects.  This stops the extra API call but not sure what this might expose.

**Comment by s-t-e-v-e-n-k** [comment]
We can't do that generically, because we can not be certain that GitHub has returned a complete object. I can think of two cases off the top of my head where they aren't complete. You can use _pull_request if that is all you need to check.

**Comment by dleach02** [comment]
@s-t-e-v-e-n-k, I dug into the code and was using the _pull_request as another work around. For my benefit and future google searchers, could you elaborate on the two cases where complete results are not returned? It seems like doing it the way it is done pretty much defeats the purpose of using the search API to load on Github?

**Comment by s-t-e-v-e-n-k** [comment]
We are at the mercy of what GitHub returns. There isn't a field GitHub populates saying "Okay, you have all the data we know about", so we need to be naive and marked the object as incomplete. Repository.get_branches() and NamedUser.get_repos() are the two off the top of my head that do not return complete objects.
