### ISSUE TITLE
how to handle the rate limit error? 

### ISSUE THREAD

**Issue by niinpatel** [PyGithub/PyGithub#1319]
We are getting this error a lot: 

```
GithubException: 403 {u'documentation_url': u'https://developer.github.com/v3/#rate-limiting', u'message': u'API rate limit exceeded for user.'}
```

According to their documentation on https://developer.github.com/v3/#rate-limiting, they send the `X-RateLimit-Reset` header in the response from which we can figure out when to make the api call again. Is it possible to get the value of that header in PyGithub? If not, how much is the minimum time we should wait before making the api call again?

**Comment by gjabouley-invn** [comment]
Hello

to get the values: `core_rate_limit = <github_object>.get_rate_limit().core`

we are seeing since this week-end some strange behavior of the Github API /rate_limit endpoint, which always return "5000" for the core counter remaining calls...
Anybody having the same problem?

**Comment by 11510746** [comment]
> Hello
> 
> to get the value you need to wait for rate limit reset (in case you get close to the limit):
> 
> ```
> core_rate_limit = <github_object>.get_rate_limit().core
> reset_timestamp = calendar.timegm(core_rate_limit.reset.timetuple())
> sleep_time = reset_timestamp - calendar.timegm(time.gmtime())
>                     + 5  # add 5 seconds to be sure the rate limit has been reset
> time.sleep(sleep_time)
> ```
> 
> we are seeing since this week-end some strange behavior of the Github API /rate_limit endpoint, which always return "5000" for the core counter remaining calls...
> Anybody having the same problem?

I think it is because we consume the search remain rather than the core remain.

[The definition of `core` is here](https://developer.github.com/v3/rate_limit/)

> For these reasons, the Rate Limit API response categorizes your rate limit. Under resources, you'll see four objects:
> The core object provides your rate limit status for all **non-search-related** resources in the REST API.
> The search object provides your rate limit status for the Search API.


I obtained the value of `g.get_rate_limit().search.remaining` and found it would decrease.

```python
for pr in g.search_issues(query=keyword, **{'repo': repo, 'type': 'pr'}):
    rl = g.get_rate_limit()
    rl_core = rl.core
    rl_search = rl.search
    # print the info here
```

The output is 

```sh
core | Limit: 5000, Remaining: 5000, Reset: 2020-01-08 14:09:16.
search | Limit: 30, Remaining: 29, Reset: 2020-01-08 13:10:16.
core | Limit: 5000, Remaining: 5000, Reset: 2020-01-08 14:09:16.
search | Limit: 30, Remaining: 29, Reset: 2020-01-08 13:10:16.
...
core | Limit: 5000, Remaining: 5000, Reset: 2020-01-08 14:09:16.
search | Limit: 30, Remaining: 28, Reset: 2020-01-08 13:10:16.
core | Limit: 5000, Remaining: 5000, Reset: 2020-01-08 14:09:16.
search | Limit: 30, Remaining: 28, Reset: 2020-01-08 13:10:16.
...
core | Limit: 5000, Remaining: 5000, Reset: 2020-01-08 14:09:16.
search | Limit: 30, Remaining: 27, Reset: 2020-01-08 13:10:16.
core | Limit: 5000, Remaining: 5000, Reset: 2020-01-08 14:09:16.
search | Limit: 30, Remaining: 27, Reset: 2020-01-08 13:10:16.
```

While iterating, it will send new requests to get next pages. The code is in `PaginatedListBase.__iter__(self)`.

```python
    def __iter__(self):
        for element in self.__elements:
            yield element
        while self._couldGrow():
            newElements = self._grow()  # the _grow function will send new request
            for element in newElements:
                yield element
```

**Comment by gjabouley-invn** [comment]
Hello
yes you should indeed adapt my proposal to the right rate limit counter (core, search, graphql). For search counter, we usually stop when remaining calls are 5 (but we don't use a lot /search api)
For timeouts, i would suggest to enable Retry() mechanism (if not already done), see #1103 , maybe it  can help
