### ISSUE TITLE
Unable to create issue using oAuth token 

### ISSUE THREAD

**Issue by kodeshpa** [PyGithub/PyGithub#132]
Hi,

I am trying to create an issue using library. But always get GithubException: 404 {u'message': u'Not Found'} error message . Please help

my code looks as fellow. let me know if i am doing something wrong

repo_service = Github('Token')
repo_service.get_repo('Repo Name').create_issue('test', 'TestSam', assignee=None, milestone=None, labels = None)

**Comment by jpmens** [comment]
For anybody finding this in future: I was attempting the same, also with a Github Personal Token, but the token didn't have sufficient priviledges, and the Github API returns `404` then.

Adding `public_repo` rights to the token solved the problem, and I was then able to create new issues programatically.

![airjp818](https://user-images.githubusercontent.com/60706/54865188-f3440b00-4d61-11e9-86b5-07643bf9ad6c.png)
