### ISSUE TITLE
Publish sdist and bdist wheel

### ISSUE THREAD

**Issue by groodt** [PyGithub/PyGithub#1321]
The benefits of wheels are well documented. See: https://pythonwheels.com/
This package is pure Python and publishing it as both source and as a wheel is simple.

It looks like there is config for Travis to upload wheels, but it doesn't appear to be happening for some reason. Is this something that we can fix or you'd like assistance in fixing?

**Comment by s-t-e-v-e-n-k** [comment]
Our travis configuration https://github.com/PyGithub/PyGithub/blob/master/.travis.yml#L31 has bdist_wheel, so huh, I'm going to dig into that.

**Comment by s-t-e-v-e-n-k** [comment]
Nice catch, by the way! Planning a release in the next few days.

**Comment by groodt** [comment]
Thanks so much @s-t-e-v-e-n-k

**Comment by s-t-e-v-e-n-k** [comment]
The v1.45 release did not upload a wheel. :-(
