### ISSUE TITLE
Get list of repositories 

### ISSUE THREAD

**Issue by jakethedogg** [PyGithub/PyGithub#1326]
I need to get a list of all repositories that a specific user has access to through an access token. And then pull ssh and https URLs from each repository for cloning.
But I can't understand how i can do that with PyGithub. Will be happy for any help!

**Comment by s-t-e-v-e-n-k** [comment]
https://pygithub.readthedocs.io/en/latest/github_objects/AuthenticatedUser.html#github.AuthenticatedUser.AuthenticatedUser.get_repos
