### ISSUE TITLE
Some questions regarding retrieving gists.

### ISSUE THREAD

**Issue by plutocow** [PyGithub/PyGithub#1331]
Hi, just discovered this library, I was wondering is there some sort of delays in the way gists appear in the API?
I'm trying to obtain the gists from the past hour, the API documentation states for the param **since**: Only gists updated at or after this time are returned.

My code looks like this:
```
now = datetime.datetime.now()
# target is the past hour
target = datetime.datetime(now.year, now.month, now.day, now.hour, 0, 0) - datetime.timedelta(hours=8)

g = Github(GITHUB_TOKEN)
gists = g.get_gists(since=target)

rate_limit_remaining = g.get_rate_limit()
print('Rate: {}'.format(rate_limit_remaining))
print("Total Gists: {}".format(str(gists.totalCount)))
```

The output looks like this: 
```
Now   : 2019-12-29 18:13:45.444242
Target: 2019-12-29 12:00:00
Rate: RateLimit(core=Rate(remaining=4969, limit=5000))
Total Gists: 0
```

**Comment by s-t-e-v-e-n-k** [comment]
MainClass.get_gists() (which is what you're calling) only returns public gists. Since your parameters look fine, are you sure they're public?

**Comment by plutocow** [comment]
> MainClass.get_gists() (which is what you're calling) only returns public gists. Since your parameters look fine, are you sure they're public?

When I modify the time from 8 hours to 12 I get valid results:

```
target = datetime.datetime(now.year, now.month, now.day, now.hour, 0, 0) - datetime.timedelta(hours=12)

Rate: RateLimit(core=Rate(remaining=4995, limit=5000))
Total Gists: 522
Discovered a gist: 81274dc5cc4c2cf123bccfb41112f0cd
Rate: RateLimit(core=Rate(remaining=4993, limit=5000))
Uploaded: 2019-12-29 07:58:25
URL: https://gist.github.com/81274dc5cc4c2cf123bccfb41112f0cd
```

**Comment by s-t-e-v-e-n-k** [comment]
> That is why I was wondering if there is some sort of caching mechanism that prevents me from getting the most recent public gists.

It certainly does sound like caching -- but I suspect it's on GitHub's end. :-(

**Comment by plutocow** [comment]
Yea thats unfortunate...
I'll leave this open until I can do more testing with postman to see if it is indeed a Github problem.

Also one additional question, how do I actually obtain the raw contents of a gist? 
Looking at the docs, when I call **get_gists** and single out a Gist, I can get a dict of strings to the **GistFile** but not the object itself for the content.

**Comment by s-t-e-v-e-n-k** [comment]
I can't reproduce that, can you show me what code you're using? If I pull out a single Gist, I get a Gist object, I have to call .files on it to get the GistFile.

**Comment by plutocow** [comment]
> I can't reproduce that, can you show me what code you're using? If I pull out a single Gist, I get a Gist object, I have to call .files on it to get the GistFile.

Here's the code:

```
from github import Github, GithubException

g = Github()
gist_id = "60a5750403a6c6dc10e3964bc6b76345"

gist = g.get_gist(gist_id)
print(type(gist))

files = gist.files
print(type(files))

for gist_file in files:
    print(type(gist_file))

```
Output: 

```
<class 'github.Gist.Gist'>
<class 'dict'>
<class 'str'>
Traceback (most recent call last):
  File "github_scraper.py", line 26, in <module>
    print(gist_file.filename)
AttributeError: 'str' object has no attribute 'filename'
```

From what I can see from the [documentation](https://pygithub.readthedocs.io/en/stable/github.html#github.MainClass.Github.get_gist), calling that function gives me a Gist object and calling files only returns a "dict of string to github.GistFile.GistFile" so I'm slightly confused on how to actually get the GistFile.
