### ISSUE TITLE
Repository compare function didn't work if one branch is orphan

### ISSUE THREAD

**Issue by zhangnianlin** [PyGithub/PyGithub#1334]
Hello, I'm using github to extract some information from my github.
one of my repo have a branch which is orphan. i'm trying to compare master to this branch, to get status, but it seems will cause problems.  

### Errors
```
Traceback (most recent call last):
  File "my_script.py", line 102, in main
    compared = repo.compare("master",branch.name)
  File "/usr/local/lib/python3.6/dist-packages/github/Repository.py", line 851, in compare
    self.url + "/compare/" + base + "..." + head
  File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 268, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 279, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 404 {"message": "No common ancestor between master and orphan.", "documentation_url": "https://developer.github.com/enterprise/2.18/v3/repos/commits/#co
mpare-two-commits"}
```
### What I did 
I tried serveral ways to fix this problem in my program.
1. Capture it with UnknownObjectException( which is 404 error.) which will not work. (I capture it with GithubException, it works.) 
2. Try to make a new empty Comparison object , but it seems really hard to do it. 

### Questions
Is there another way to do compare orphan branch with master?
or a better way to handle this error? 
cause I need Comparison object for other usage.

**Comment by s-t-e-v-e-n-k** [comment]
I mean, that is the crux of the problem, there is no way to compare them since they don't share a common ancestor -- IE, they have no history in common.

You can make an empty Comparison object by cheating a little:
```
>>> c = github.Comparison.Comparison(None, {}, {}, True)
>>> c
<github.Comparison.Comparison object at 0x7f79c8b4fa58>
>>> c._rawData
{}
```

**Comment by zhangnianlin** [comment]
alright , got it . thanks a lot.
