### ISSUE TITLE
Dismissal Restrictions Enabled When no Users/Teams Provided

### ISSUE THREAD

**Issue by AetherDeity** [PyGithub/PyGithub#1335]
Branch protection for organization repos allow for the inclusion of dismissal restrictions for who should be able to dismiss reviews. To disable this feature, you must pass an empty object when editing branch protection. The current function `edit_protection` in `Branch.py` excludes the field if no users or teams are provided, which is the same as setting both to an empty list. This has the effect of limiting who can dismiss a review to admin users.

Unfortunately, the fix is not as simple as including the field with an empty dict when neither users nor teams are provided, as this causes a validation error when used to edit branch protection for user owned repos.

```
422 {'message': 'Validation Failed', 'errors': ['Only organization repositories can have users and team restrictions'], 'documentation_url': 'https://developer.github.com/v3/repos/branches/#update-branch-protection'} 
```

I am happy to PR a fix, but am unsure what direction the maintainers would like to go.

1. Add org context to the Branch object when calling `get_branch` from a Repository object. This has the benefit of not introducing an API breaking change or additional arguments to `edit_protection`.

2. Add an option to the `edit_protection` function that allows the user to specify whether it is a branch or an org repo. This will require a default that will either need to be defaulted to true or false. Default of user repo would maintain current behavior and leave org repos misconfigured. Default to org repo would cause validation errors for user repos, thus introducing an API breaking change.

3. Something else.

**Comment by s-t-e-v-e-n-k** [comment]
I'm still unhappy with parts of the branch protection API, but mostly at how brittle it is exported by GitHub.

Could we look at the Branch object and if it has users and teams dismissal restrictions set, then pass those if NotSet, otherwise ignore them, would that work?

**Comment by AetherDeity** [comment]
The Branch object itself wouldn't have any branch protection attributes to check; that data is retrieved by the `get_protection` call, which returns a BranchProtection object. Given just the Branch object, there is currently no way that I know of to determine whether the call should or should not include the dismissal restrictions.

**Comment by s-t-e-v-e-n-k** [comment]
Some of the attributes are populated when calling get_branch():

```
>>> repo = g.get_repo('PyGithub/PyGithub')
>>> b = repo.get_branch('master')
>>> b._rawData['protection']
{'enabled': True, 'required_status_checks': {'enforcement_level': 'off', 'contexts': []}}
```

**Comment by AetherDeity** [comment]
It looks like the only protection data provided when getting branch info is whether protection is enabled and what status checks are required. The rest of the data is only provided when queried from the protection API.

**Comment by s-t-e-v-e-n-k** [comment]
Drat, GitHub ruining my good plans. I think an is_organization attribute on Branch (or a better name, suggestions welcome) would work. Do you want to get started on a PR for that?

**Comment by AetherDeity** [comment]
Yep, I can do that. And you are comfortable with that being an extra argument passed in to the Branch init?
