### ISSUE TITLE
Can't verify authorizations of token-authorized user

### ISSUE THREAD

**Issue by bilderbuchi** [PyGithub/PyGithub#134]
Hi!
I think I've found a bug. I successfully created an API authorization with some scopes. In the program I want to use this autorization in, I'm trying to verify the correct scopes before proceeding, but this does not work as expected. From iPython:

``` python
from github import Github
user = Github(some_token).get_user()
auths=user.get_authorizations()
auths
Out[5]: <github.PaginatedList.PaginatedList instance at 0xad31bac>
for a in auths:
    print a.note
---------------------------------------------------------------------------
GithubException                           Traceback (most recent call last)
<ipython-input-6-b49dc83bedec> in <module>()
----> 1 for a in auths:
      2     print a.note

/usr/local/lib/python2.7/dist-packages/github/PaginatedList.pyc in __iter__(self)
     33             yield element
     34         while self._couldGrow():
---> 35             newElements = self.__grow()
     36             for element in newElements:
     37                 yield element

/usr/local/lib/python2.7/dist-packages/github/PaginatedList.pyc in __grow(self)
     45 
     46     def __grow(self):
---> 47         newElements = self._fetchNextPage()
     48         self.__elements += newElements
     49         return newElements

/usr/local/lib/python2.7/dist-packages/github/PaginatedList.pyc in _fetchNextPage(self)
     83 
     84     def _fetchNextPage(self):
---> 85         headers, data = self.__requester.requestAndCheck("GET", self.__nextUrl, self.__nextParams, None)
     86 
     87         links = self.__parseLinkHeader(headers)

/usr/local/lib/python2.7/dist-packages/github/Requester.pyc in requestAndCheck(self, verb, url, parameters, input)
     78         output = self.__structuredFromJson(output)
     79         if status >= 400:
---> 80             raise GithubException.GithubException(status, output)
     81         return headers, output
     82 

GithubException: 404 {u'message': u'Not Found'}
```

is this a bug or am I doing something wrong/impossible. 

btw, when creating a github instance with an authorization token, this does not error out when the token is invalid, i.e. I can say `Github("mySillyString")` without error message - is this by design?

**Comment by ericsoco** [comment]
It's been a long time since either of you cared about this thread, but -- a note for posterity and possible increased googleability:

Since the [GitHub Authorizations API](https://developer.github.com/v3/oauth_authorizations/#oauth-authorizations-api) requires Basic Authentication, and does not support using OAuth, I was stumped on how to check the granted scopes for an authorized user.

The `X-OAuth-Scopes` response header on all GitHub API requests lists those scopes. Easy-peasy. Once you know where to look...

Thanks for calling that out here!
