### ISSUE TITLE
Enterprise github authentication is not working from latest releases

### ISSUE THREAD

**Issue by sandeephello** [PyGithub/PyGithub#1340]
Hi, Enterprise github authentication is not working since PyGithub==1.40. I am able to do authentication from PyGithub==1.39. 

# How to re-produce
Install latest PyGithub
```
pip install PyGithub
```

## Python code 
from github import Github
g = Github(base_url="https://{hostname}/api/v3", login_or_token="access_token")
g.get_organization('xxxxxx'))

and error is 
```
github.GithubException.BadCredentialsException: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/enterprise/2.18/v3'}
```

**Comment by s-t-e-v-e-n-k** [comment]
How to reproduce requires an Enterprise install, which I do not have access too. Are you able to inspect the headers that code uses and see what response curl gets back?

**Comment by sandeephello** [comment]
Please close this case. I checked this  this issue more and found that issue was coming only in my machine, not in any other machine.
