### ISSUE TITLE
Github class documentation (Docs » Reference » Main class: Github) on readthedocs is empty

### ISSUE THREAD

**Issue by jnareb** [PyGithub/PyGithub#1341]
When trying to go back to the main class reference documentation (automatically generated, I guess) on [Read the Docs][1], I found it **empty**. 

I remember having it documentation of methods, like for example `save` and `load` - which now cannot be found anywhere except in Changelog.

[Docs » Reference » Main class: Github][2]

[1]: https://pygithub.readthedocs.io/
[2]: https://pygithub.readthedocs.io/en/latest/github.html

**Comment by chanukov** [comment]
It seems like all reference logs at https://pygithub.readthedocs.io/en/latest/ no longer show anything.
I used to use 
https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html
for figuring out the methods available/ all reference things is now empty and has nothing there.

**Comment by AaricChen** [comment]
Same issue. please fix this ASAP thanks

**Comment by chanukov** [comment]
@s-t-e-v-e-n-k I believe your change to drop python2 in docs broke this somehow as this was working just last week, any ideas?

**Comment by s-t-e-v-e-n-k** [comment]
Drat! That is a large change to go through. I'll try and find some time over the weekend to dig into what Sphinx is (and more importantly, isn't) doing.
