### ISSUE TITLE
How do I download a file?

### ISSUE THREAD

**Issue by vikas027** [PyGithub/PyGithub#1343]
I am trying to download a file and so far have reached here, also looked at https://github.com/PyGithub/PyGithub/issues/661

I have reached here so far.

```python
    repo = client.get_repo(GIT_REPO)
    contents = repo.get_contents(file_path, ref=GIT_BRANCH)
    print (contents)    # <-- ContentFile(path="clusters/poc2/test.txt")
    file_content = repo.get_contents(urllib.parse.quote(contents.path), ref=GIT_BRANCH)
    print (file_content)   # <-- ContentFile(path="clusters/poc2/test.txt")
```

I can use GitAPI to download a file, but just trying out my hands with this package :)

**Comment by s-t-e-v-e-n-k** [comment]
There are two methods, -- first, just use ``file_content.content`` which is the contents, which you can write to a file. Secondly, there's ``file_content.download_url`` to grab it.

**Comment by Trymzet** [comment]
So you can do it like this:
```python
from github import Github
import urllib
import base64

def github_file_to_bytes(repo, path, git_token, branch="main"):
    g = Github(git_token)
    repo = g.get_repo(repo)
    content_encoded = repo.get_contents(urllib.parse.quote(path), ref=GIT_BRANCH).content
    content = base64.b64decode(content_encoded)
    return content
```

**Comment by topherbuckley** [comment]
Can someone here explain why we have to import base64 and decode a file ourselves? Why is this not built into the `get_contents` function? How can we know what the proper decoding is for a given file?

**Comment by trymzet** [comment]
@topherbuckley I see they now have a `content_decoded` property, so you can do
```python
content = repo.get_contents(urllib.parse.quote(path), ref=branch).content_decoded
```

**Comment by topherbuckley** [comment]
> @topherbuckley I see they now have a `content_decoded` property, so you can do
> 
> ```python
> content = repo.get_contents(urllib.parse.quote(path), ref=branch).content_decoded
> ```

I see `decoded_content` but not `content_decoded`.

**Comment by topherbuckley** [comment]
Linking to my comment [here](https://github.com/PyGithub/PyGithub/issues/2345#issuecomment-2560716863) as it is a more generally applicable answer given the strange piecewise handling of files <1MB, <100MB, other. (I was getting empty files with the methods in this thread without any error/warning pointing to why).
