### ISSUE TITLE
Support for update and delete repository labels

### ISSUE THREAD

**Issue by docktermj** [PyGithub/PyGithub#1349]
Currently there is support for **creating** a label for use in a repository.  https://github.com/PyGithub/PyGithub/blob/fc7109eab750b52ce3c96ad447c3e9011419c952/github/Repository.py#L1194-L1219

However, there is no support for **updating** nor **deleting** a label from a repository.  This issue requests an enhancement for updating and deleting repository labels.

References:

### Updating

```
PATCH /repos/:owner/:repo/labels/:name
```
https://developer.github.com/v3/issues/labels/#update-a-label

### Deleting

```
DELETE /repos/:owner/:repo/labels/:name
```
https://developer.github.com/v3/issues/labels/#delete-a-label

**Comment by docktermj** [comment]
I did a "monkey-patch" in my code to add the missing methods.  It can serve as an example of what is being requested.

https://github.com/docktermj/python-github-tasks/blob/7fd9f3735583df724bc4c51266fcd13a63160e3d/github-tasks.py#L742-L790

**Comment by s-t-e-v-e-n-k** [comment]
Actually, both of those operations are supported! They act on the ``Label`` object, not ``Repository``.

https://pygithub.readthedocs.io/en/latest/github_objects/Label.html

But I do note that Label.edit needs to be fixed...

**Comment by docktermj** [comment]
May I suggest that from a symmetry perspective, the Create, Update, and Delete be from the same level of abstraction?   

When Label.delete() occurs,  one could assume equally that the label is deleted from the repository default or that the label is deleted from an issue.  ...or could be deleted from an unknown set, such as the account "default" labels used to instantiated default labels on repository creation.   Net: the behavior of Label.delete() is ambiguous.

By having Repository.create_label(),  Repository.update_label(), Repository.delete_label() there is no ambiguity from which "set" the label is being deleted.

**Comment by s-t-e-v-e-n-k** [comment]
Labels as a first-class object are on the Repository. If you want to remove them from an Issue or a PR, there are a bunch of functions to add/remove/replace labels.

I'm tempted to write a Labels mix-in to homogenise it across Repo/Issue/PR, but in any case the functions you are asking about are implemented.

**Comment by s-t-e-v-e-n-k** [comment]
However, I think Label.edit() is the correct way to do that, since you're modify the label itself, not which labels are on a PR/issue.

**Comment by docktermj** [comment]
One way of determining if an object is a "first class object" is to determine that it is independent of other objects.  The current architecture has Label as an object dependent on a Repository object.  

A Label as a first-class object could be added to an Account, Repository, or Issue equally.  Once that is understood, you may want to reconsider your design.

The asymmetry of CREATE and DELETE seems very odd to me.

**Repository.py** has create.
```
POST /repos/:owner/:repo/labels
```

But **Label.py** has delete.
```
DELETE /repos/:owner/:repo/labels/:name
```

Yet **Issue.py** has both create and delete labels.
```
POST /repos/:owner/:repo/issues/:number/labels
DELETE /repos/:owner/:repo/issues/:number/labels/:name
```

Based on the URIs, it appears that it's an architectural choice in PyGithub, rather than the GitHub architecture. 

All I'm asking is that as a Software architect, you make a good choice.

**Comment by s-t-e-v-e-n-k** [comment]
This is a separate issue. This API pre-dates my involvement in the project, but we can talk about deprecation and how to address it there. Further, it's unclear if DELETE /repos/:owner/:repo/issues/:number/labels/:name actually deletes the label or deletes the link from the issue to the label ...
