### ISSUE TITLE
readthedocs: Edit on github link is broken

### ISSUE THREAD

**Issue by schneiderl** [PyGithub/PyGithub#1351]
While looking at a page on the documentation ([this one for instance](https://pygithub.readthedocs.io/en/latest/github_objects/BranchProtection.html)) I've seen that the "Edit on github" link is broken. It redirects to a 404. 

Should it be like this? 

Thank you.

**Comment by s-t-e-v-e-n-k** [comment]
It isn't ideal, but the link provides value for everything that isn't a reference -- everything under github_objects is generated by the docs toolchain and is a reference and automatically generated.

It appears that link can only be turned off globally, and I think it provides more benefit.

**Comment by schneiderl** [comment]
Oh, understood.
Well, guess that's it then haha. 
Guess I'm closing the issue for now as it seems to be already known by the maintainers.

Thank you for your answer @s-t-e-v-e-n-k .
