### ISSUE TITLE
search_topics returns different number of repositories compared to searching in browser.

### ISSUE THREAD

**Issue by davidlee321** [PyGithub/PyGithub#1352]
```python
repos = g.search_topics('recipes')
print(len(list(repos)))
for repo in repos:
    print(repo.name)
```

prints

```
80
recipes
franz-recipes
chef-recipes
cooking-recipes
deployer-recipes
...
```

API gets 80 repos. However my browser (https://github.com/topics/recipes) returns 449 public repositories. Any help wld be aprpeciated.

**Comment by s-t-e-v-e-n-k** [comment]
I continue to remain convinced that the website is not using the REST API. We're sadly at the mercy of what GitHub returns.
