### ISSUE TITLE
Create Blob returning 404 Not Found

### ISSUE THREAD

**Issue by youssefarizk** [PyGithub/PyGithub#1353]
Hi, I'm trying to create a Blob using the `create_git_blob` function, but it is returning a 404 not found. Below is the code and I'm using it on an Enterprise Github instance. This used to work a month ago but stopped working now. I have had no other troubles with other functions, so the problem can't be the `base_url` or `gh_access_token` configuration. Has anything changed?

`g = Github(base_url=base_url,
               login_or_token=gh_access_token)

    repo = g.get_repo(repository)

    # -- Prepare content of the blob

    updated_file_content = .....
    
    # Create a blob
    file_blob = repo.create_git_blob(content=updated_file_content, encoding="utf-8")`

**Comment by s-t-e-v-e-n-k** [comment]
I can't reproduce this, on GitHub itself:

```
>>> b = repo.create_git_blob(content, encoding="utf-8")
>>> b
GitBlob(sha="a8a940627d132695a9769df883f85992f0ff4a43")
```

**Comment by youssefarizk** [comment]
Apologies, this was entirely my bad. I didn't permission the access token to `repo` 🤦‍♂ 

Thanks for looking into this!
