### ISSUE TITLE
how to use retry parameter github.Github(GITHUB_AUTH_TOKEN,retry=3)

### ISSUE THREAD

**Issue by gs-nvulli** [PyGithub/PyGithub#1354]
Hi I found below parameter in documentation
    retry – int or urllib3.util.retry.Retry object
so this int(retry) is the number of times to retry ??
can you please let me know how to use and what is the timeout ??
I can see the default read timeout=15.

github.Github(GITHUB_AUTH_TOKEN,retry=3)

**Comment by s-t-e-v-e-n-k** [comment]
They are two disparate concepts:

* Timeout is how long we wait for a reply before giving up. The default is 15 seconds.

* Retry is how many times we will re-send the request if we get a temporary error or the request times out. The default is to not retry.

Your example that you've included at the bottom is the correct way to use retry.

**Comment by gs-nvulli** [comment]
Thanks for the INFO.
