### ISSUE TITLE
retrieving since value is not documented

### ISSUE THREAD

**Issue by ssbarnea** [PyGithub/PyGithub#1358]
I am trying to use `get_organizations()` to make a tool that dumps them but which can restart if interrupted. 

The issue is that the function only returns an interator so I have no clue which was the last value of `since`, one that I would have to save on error, in order to be able to restart from zero next time.

**Comment by s-t-e-v-e-n-k** [comment]
You have two choices -- you can coerce the ``PaginatedList`` to a list by calling ``list(<result>)`` or, keep track of the ``created_at`` of each org as you process it.

**Comment by ssbarnea** [comment]
@s-t-e-v-e-n-k  That does not make sense because the expectation is that the iteration will auto-load new pages when it reaches end of current page. Coercing it to a list forces it to attempt to pre-load all values which would hog the server and trigger the rate-limiting for sure, mainly returning an error after a number of pages.

Are you sure that results are always returned sorted by `created_at`, meaning that I can use it as a valid counter? If that is true, the solution is to store it and use it, no problem.
