### ISSUE TITLE
Timeout creating Git Blob of large content

### ISSUE THREAD

**Issue by shashankrnr32** [PyGithub/PyGithub#1376]
I guess `repo.create_git_blob(..)` enforces a 15s timeout for creating Git Blobs. But, with a raw request it is possible to create a blob with request time of about 35 seconds. Is there a reason why timeout is kept 15 seconds?

**Comment by s-t-e-v-e-n-k** [comment]
The default timeout is 15 seconds, which is what we'd reasonably expect 99% of requests to complete by. In this case, you should override it when you create the ``Github()`` object, by setting the ``timeout`` keyword argument,

**Comment by shashankrnr32** [comment]
Great. Thanks
