### ISSUE TITLE
Trying to get the user name who has commented last in an issue using pygithub

### ISSUE THREAD

**Issue by srihari15** [PyGithub/PyGithub#1378]
I am delving into this wonderful library. I am trying to find information in the docs where **I can get the user name who commented last in an issue** but I have not been able to find any as of yet. I would really appreciate if there is any help :) Thanks

**Comment by srihari15** [comment]
Right now, I am using this:

`for issue in issues.get_comments():
            print(issue.user.name)`

This returns me all the names of the people who have commented. I do not want to use closed_by as issues may be open as well.
I know there are workarounds but is there something like issue.last_updated_by which returns the name as a str?

**Comment by huwcbjones** [comment]
A quick mwe using the latest version (1.45)
```python
from github import Github

gh = Github("YOUR_TOKEN")
repo = gh.get_repo("REPO")
issue = r.get_issue(issue_number)
comments = [e for e  in i.get_timeline() if e.event =="commented"]
if comments:
    last_commented_user = comments[-1].actor
```

This uses the github timeline events, filters for comment events, then get's the `NamedUser` for the last comment

**Comment by srihari15** [comment]
Thanks for this. I was using the following
`
from github import Github
gh = Github("YOUR_TOKEN")
repo = gh.get_repo("REPO")
issue = r.get_issue(issue_number)
user = [comment.user.name for comment in issue.get_comments()][-1]
`
