### ISSUE TITLE
Remove AccessToken from URLs

### ISSUE THREAD

**Issue by rafaelcapucho** [PyGithub/PyGithub#1392]
Hi guys, I received this email from GitHub

```
Hi @rafaelcapucho,

On February 9th, 2020 at 22:37 (UTC) your application (OauthGitHubStudentDeveloperPack) used an access token (with the User-Agent python-requests/2.22.0) as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/user

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated and will be removed July 1st, 2020.

Depending on your API usage, we'll be sending you this email reminder once every 3 days.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team
```

We're using your library, does it require any changes on your side? 
Thank you.

**Comment by s-t-e-v-e-n-k** [comment]
What version are you using? I can't see in the code where we pass access_token as a query parameter.

**Comment by rafaelcapucho** [comment]
It seems that the problem happens in the [social_core](https://github.com/python-social-auth/social-core/pull/428), if we don't have this problem happening here too I'm going to close this.. Thank you!

**Comment by jhyelton** [comment]
@s-t-e-v-e-n-k I know this issue is closed, but we're getting the same notices from Github about this.  We're using pygithub==1.43.2.
