### ISSUE TITLE
how to add proxy host in github api

### ISSUE THREAD

**Issue by yourlovemyall** [PyGithub/PyGithub#1394]

**Comment by yourlovemyall** [comment]
i want use the tool in no outer internet privilege, so I want to add proxy host instead of "api.github.com" host

**Comment by yourlovemyall** [comment]
i try using base_url instead of proxy host, but when I get the function "get_apge",  it will cause an error when i try to get one url code content;

**Comment by s-t-e-v-e-n-k** [comment]
There is no such function in our codebase that I can see. However, proxies are configured the "usual" way, by exporting a value to the environment:

``export http_proxy=http://yourproxy:8080/``

**Comment by yourlovemyall** [comment]
if I only want this requirement which use proxy，not all http request。

**Comment by yourlovemyall** [comment]
i think the extension need this，if we need run our service in our inner network，which no outer network， wo should need add proxy host to transfer our request.
