### ISSUE TITLE
Repository.get_contents does not return directory information

### ISSUE THREAD

**Issue by ksookocheff-va** [PyGithub/PyGithub#140]
The GitHub API returns a list of all files in a directory when you use Get Contents on a directory.

example:
https://api.github.com/repos/twitter/bootstrap/contents/js/?ref=d28343dc3ad53a411ae3685e7d6a7866c8c22d6b

Currently PyGithub only returns None when using this API to query a directory.

**Comment by vipulgupta2048** [comment]
Hi, how would one go about find directories? I just need to find if the directory exist in the repo or not
