### ISSUE TITLE
Linked pull requests

### ISSUE THREAD

**Issue by IlyaFaer** [PyGithub/PyGithub#1401]
I'm using PyGitHub to implement [issue tracker](https://github.com/IlyaFaer/GitHub-Scraper). The very overall idea is to show active issues and related pull requests of several repositories.

For now I'm [walking through list of PRs and checking for GitHub keywords within their bodies](https://github.com/IlyaFaer/GitHub-Scraper/blob/50119a5f7dd1766685c8543e805b6cf73e558625/scraper/pr_index.py#L47-L59) to find relations between issues and PRs. It takes time and causes me to keep not very beautiful code.

Some days ago my eye came across the new widget "Linked pull requests" in issue card. It would be great to implement method to return list of these PRs (or to return them while reading issues itself) in PyGitHub.

Thanks in advance!

![Безымянный](https://user-images.githubusercontent.com/26030071/74608253-9c20f480-50f0-11ea-9649-6df66b49596f.png)

**Comment by s-t-e-v-e-n-k** [comment]
I can't see an API endpoint for this feature, sorry! GitHub can of course do internal things for the website, but we are at the mercy of what public API calls are available.

**Comment by dkaszews** [comment]
According to https://github.com/orgs/community/discussions/179613 and https://stackoverflow.com/questions/60717142/getting-linked-issues-and-projects-associated-with-a-pull-request-form-github-ap this is now possible with the use of either GraphQL, or searching for link/unlink events
