### ISSUE TITLE
PaginatedList length/count issue

### ISSUE THREAD

**Issue by ChaiBapchya** [PyGithub/PyGithub#1403]
commit.get_statuses() returns a PaginatedList
I am trying to find the length of PaginatedList using

https://github.com/PyGithub/PyGithub/blob/2991e9f1782e068d753f52009b1db2ad528fd6a1/github/PaginatedList.py#L106

### totalcount()
`commit.get_statuses().totalcount`
```
AttributeError: 'PaginatedList' object has no attribute 'totalcount'
```

### len()
`len(commit.get_statuses()`
```
Error: TypeError: object of type 'PaginatedList' has no len()
```

**Comment by s-t-e-v-e-n-k** [comment]
Capitalisation matters! PaginatedList.totalCount (note the capital C) is the correct attribute.
