### ISSUE TITLE
[Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by ArjunSarihyan** [PyGithub/PyGithub#1404]
from github import Github
# using username and password
g = Github("user", "password")
# or using an access token
g = Github("access_token")
# Github Enterprise with custom hostname
g = Github(base_url="https://{hostname}/api/v3", login_or_token="access_token")
for repo in g.get_user().get_repos():
    print(repo.name)
    repo.edit(has_wiki=False)
    # to see all the available attributes and methods
    print(dir(repo))

**********************************************************************************************************
Error->

gaierror                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\urllib3\connection.py in _new_conn(self)
    158             conn = connection.create_connection(
--> 159                 (self._dns_host, self.port), self.timeout, **extra_kw)
    160 

~\Anaconda3\lib\site-packages\urllib3\util\connection.py in create_connection(address, timeout, source_address, socket_options)
     56 
---> 57     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
     58         af, socktype, proto, canonname, sa = res

~\Anaconda3\lib\socket.py in getaddrinfo(host, port, family, type, proto, flags)
    747     addrlist = []
--> 748     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    749         af, socktype, proto, canonname, sa = res

gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
~\Anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    599                                                   body=body, headers=headers,
--> 600                                                   chunked=chunked)
    601 

~\Anaconda3\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    342         try:
--> 343             self._validate_conn(conn)
    344         except (SocketTimeout, BaseSSLError) as e:

~\Anaconda3\lib\site-packages\urllib3\connectionpool.py in _validate_conn(self, conn)
    838         if not getattr(conn, 'sock', None):  # AppEngine might not have  `.sock`
--> 839             conn.connect()
    840 

~\Anaconda3\lib\site-packages\urllib3\connection.py in connect(self)
    300         # Add certificate verification
--> 301         conn = self._new_conn()
    302         hostname = self.host

~\Anaconda3\lib\site-packages\urllib3\connection.py in _new_conn(self)
    167             raise NewConnectionError(
--> 168                 self, "Failed to establish a new connection: %s" % e)
    169 

NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001C42D189488>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
~\Anaconda3\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    448                     retries=self.max_retries,
--> 449                     timeout=timeout
    450                 )

~\Anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    637             retries = retries.increment(method, url, error=e, _pool=self,
--> 638                                         _stacktrace=sys.exc_info()[2])
    639             retries.sleep()

~\Anaconda3\lib\site-packages\urllib3\util\retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    398         if new_retry.is_exhausted():
--> 399             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    400 

MaxRetryError: HTTPSConnectionPool(host='%7bhostname%7d', port=443): Max retries exceeded with url: /api/v3/user/repos (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001C42D189488>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-62-89973ad029a2> in <module>
----> 1 for repo in g.get_user().get_repos():
      2     print(repo.name)
      3     repo.edit(has_wiki=False)
      4     # to see all the available attributes and methods
      5     print(dir(repo))

~\Anaconda3\lib\site-packages\github\PaginatedList.py in __iter__(self)
     57             yield element
     58         while self._couldGrow():
---> 59             newElements = self._grow()
     60             for element in newElements:
     61                 yield element

~\Anaconda3\lib\site-packages\github\PaginatedList.py in _grow(self)
     69 
     70     def _grow(self):
---> 71         newElements = self._fetchNextPage()
     72         self.__elements += newElements
     73         return newElements

~\Anaconda3\lib\site-packages\github\PaginatedList.py in _fetchNextPage(self)
    200     def _fetchNextPage(self):
    201         headers, data = self.__requester.requestJsonAndCheck(
--> 202             "GET", self.__nextUrl, parameters=self.__nextParams, headers=self.__headers
    203         )
    204         data = data if data else []

~\Anaconda3\lib\site-packages\github\Requester.py in requestJsonAndCheck(self, verb, url, parameters, headers, input)
    317         return self.__check(
    318             *self.requestJson(
--> 319                 verb, url, parameters, headers, input, self.__customConnection(url)
    320             )
    321         )

~\Anaconda3\lib\site-packages\github\Requester.py in requestJson(self, verb, url, parameters, headers, input, cnx)
    408             return "application/json", json.dumps(input)
    409 
--> 410         return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
    411 
    412     def requestMultipart(

~\Anaconda3\lib\site-packages\github\Requester.py in __requestEncode(self, cnx, verb, url, parameters, requestHeaders, input, encode)
    470 
    471         status, responseHeaders, output = self.__requestRaw(
--> 472             cnx, verb, url, requestHeaders, encoded_input
    473         )
    474 

~\Anaconda3\lib\site-packages\github\Requester.py in __requestRaw(self, cnx, verb, url, requestHeaders, input)
    496             cnx = self.__createConnection()
    497         cnx.request(verb, url, input, requestHeaders)
--> 498         response = cnx.getresponse()
    499 
    500         status = response.status

~\Anaconda3\lib\site-packages\github\Requester.py in getresponse(self)
    114             timeout=self.timeout,
    115             verify=self.verify,
--> 116             allow_redirects=False,
    117         )
    118         return RequestsResponse(r)

~\Anaconda3\lib\site-packages\requests\sessions.py in get(self, url, **kwargs)
    544 
    545         kwargs.setdefault('allow_redirects', True)
--> 546         return self.request('GET', url, **kwargs)
    547 
    548     def options(self, url, **kwargs):

~\Anaconda3\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    531         }
    532         send_kwargs.update(settings)
--> 533         resp = self.send(prep, **send_kwargs)
    534 
    535         return resp

~\Anaconda3\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    644 
    645         # Send the request
--> 646         r = adapter.send(request, **kwargs)
    647 
    648         # Total elapsed time of the request (approximately)

~\Anaconda3\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPSConnectionPool(host='%7bhostname%7d', port=443): Max retries exceeded with url: /api/v3/user/repos (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001C42D189488>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by s-t-e-v-e-n-k** [comment]
From some checking, I think this error is from a proxy setting without a protocol set, but I'm confident it isn't a PyGithub issue.

**Comment by ArjunSarihyan** [comment]
Any solution for that?
