### ISSUE TITLE
Fetch status of most recent commit of all PRs of a certain repo

### ISSUE THREAD

**Issue by ChaiBapchya** [PyGithub/PyGithub#1405]
Currently, I use `get_commits()` to get all commits on the repo & check `commit.get_combined_status()`to get the latest status of those commits

```
for commit in repo.get_commits():
    combined_status = commit.get_combined_status()
    ...

```

However, if a particular commit in a PR has been force-pushed (overwritten) then I don't want to check for the "stale" commit anymore. How to filter that out?

Basically, I just want to get the "latest" status of the most recent commit of all PRs of a certain repo.

Is there any way to do that?

**Comment by sfdye** [comment]
Sorry for the stale bot, I believe you can get the latest commit from the pull request's head commit sha (or similar) and inspect the commit status from there.

**Comment by sfdye** [comment]
Let me know this does not work for you.
