### ISSUE TITLE
add_to_assignees() breaks create_review_request()

### ISSUE THREAD

**Issue by fpoli** [PyGithub/PyGithub#1406]
Given a PullRequest object `pull`, the following sequence of operations leads to a 404 error:

1. `pull.add_to_assignees("fpoli")`
2. `pull.create_review_request(reviewers=["some-user"])`

However, the following works fine:

1. `deepclone(pull).add_to_assignees("fpoli")`
2. `pull.create_review_request(reviewers=["some-user"])`

Possible reason: internally, `add_to_assignees` calls the `_useAttributes` defined in the `Issue` class, which replaces the `self._url` of the pull request with the url of an _issue_. Then, the `create_review_request` call fails because it sends a POST request to a non-existing endpoint like <https://api.github.com/repos/viperproject/viperserver/issues/10/requested_reviewers>, which should be <https://api.github.com/repos/viperproject/viperserver/pulls/10/requested_reviewers>.

**Comment by s-t-e-v-e-n-k** [comment]
I've failed to reproduce this. Are you able to give me a short example that fails reproducibly?

**Comment by fpoli** [comment]
Version: `PyGithub==1.46`

Code:
```
github = Github(os.environ["GITHUB_ACCESS_TOKEN"])
repo = github.get_repo("fpoli/test")
pull = repo.create_pull(
    title="PR title",
    body="PR body",
    base="master",
    head="new-feature",
)

print("Before:", pull._url.value)
pull.add_to_assignees("fpoli")
print("After:", pull._url.value)

pull.create_review_request(reviewers=["fpoli"])
```

Output:
```
Before: https://api.github.com/repos/fpoli/test/pulls/3
After: https://api.github.com/repos/fpoli/test/issues/3
Traceback (most recent call last):
  File "./main.py", line 18, in <module>
    pull.create_review_request(reviewers=["fpoli"])
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/PullRequest.py", line 485, in create_review_request
    "POST", self.url + "/requested_reviewers", input=post_parameters
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/home/fpoli/.local/lib/python3.5/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://developer.github.com/v3"}
```
