### ISSUE TITLE
AssertionError when passing valid(?) parameter

### ISSUE THREAD

**Issue by akmadian** [PyGithub/PyGithub#1407]
When using PullRequest.set_labels() or PullRequest.add_to_assignees(), and passing a list of strings as a parameter to either of them, I get 
```
Traceback (most recent call last):  File ".\standardize.py", line 133, in <module>    st = Standardize('fae925c6fa18ed6f026931019c644712ac2af0fa', 'config.example.json')  File ".\standardize.py", line 25, in __init__
    self.standardize()  File ".\standardize.py", line 44, in standardize
    PRCONFIG=self.config.config['PR']  File "C:\src\gh-standardize\gh-standardize\repository.py", line 80, in createChangesPR    self.assignChangesPR(PR, PRCONFIG)
  File "C:\src\gh-standardize\gh-standardize\repository.py", line 98, in assignChangesPR
    PR.add_to_assignees(PRCONFIG['AUTOASSIGN'])  File "C:\Users\Ari\.virtualenvs\gh-standardize-TV0O1TPc\lib\site-packages\github\PullRequest.py", line 836, in add_to_assignees        
    ), assigneesAssertionError: (['akmadian'],)
```
where ['akmadian'] is the list of assignees, or for labels, it could be ['bug', 'help wanted'], etc. AFAIK, this is valid syntax because the documentation for both [add_to_assignees()](https://pygithub.readthedocs.io/en/latest/github_object/PullRequest.html#github.PullRequest.PullRequest.add_to_assignees), and [set_labels()](https://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html#github.PullRequest.PullRequest.set_labels) both say that a list of strings is a valid parameter. I am loading the lists of strings from a JSON file via json.loads(), but I don't think that should make a difference since the JSON array is converted to a python list anyways. When I take the first index of the list and pass a single string, it works alright. This may also happen with other similar methods, but these are the only two I've tested.

Is this a bug, or am I missing something syntax-wise here? Thanks :)

**Comment by s-t-e-v-e-n-k** [comment]
The docstring could be a little clearer, but you just pass as many parameters as you want, and that is the list. If you want to pass a constructed array, use *.  IE:

``PR.add_to_assignees(*PRCONFIG['AUTOASSIGN'])

**Comment by akmadian** [comment]
Ah I see, so it was a small syntax thing :) Will give it a try tomorrow. Thanks!

**Comment by truthdoug** [comment]
This caught me as well on `PullRequest.set_labels()`. It feels more pythonic to accept a python list as the arguments.

A backward-compatible way to address this would be to check if the first element is a list and, if so, expand that.
