### ISSUE TITLE
PullRequest.update_branch(): allow expected_head_sha to be empty and use head ref

### ISSUE THREAD

**Issue by ahauan4** [PyGithub/PyGithub#1411]
The function `PullRequest.update_branch()` currently requires parameter `expected_head_sha`.
But this parameter is not mandatory according to
https://developer.github.com/v3/pulls/#update-a-pull-request-branch
> Default: SHA of the pull request's current HEAD ref.

Currently I'm unable to use this default, because the function does not allow the parameter to be empty.

**Comment by ahauan4** [comment]
I created pull request https://github.com/PyGithub/PyGithub/pull/1412

**Comment by ahauan4** [comment]
Pull request merged. Issue can be closed

**Comment by s-t-e-v-e-n-k** [comment]
Good point! In future, you can put "Fixes #<issue number>" in the commit message to do so automatically.
