### ISSUE TITLE
Add `delete()` Method to `ProjectCard`

### ISSUE THREAD

**Issue by KermMartian** [PyGithub/PyGithub#1413]
Basically what it says on the tin. The Github API [allows you to delete a card from a project](https://developer.github.com/v3/projects/cards/#delete-a-project-card) by card ID, but this functionality isn't exposed in PyGithub. Based on looking briefly at the documentation, the implementation might be something like:

```
    def delete(self):
        """
        :calls: `DELETE /projects/columns/cards/:card_id <https://developer.github.com/v3/projects/cards>`_
        :rtype: bool
        """
        status, _, _ = self._requester.requestJson(
            "DELETE",
            self.url,
            headers={"Accept": Consts.mediaTypeProjectsPreview},
        )
        return status == 204
```

**Comment by s-t-e-v-e-n-k** [comment]
That looks pretty close for a PR -- are you comfortable also writing a test, or would I prefer I do the heavy lifting?

**Comment by KermMartian** [comment]
I'm happy writing a test and submitting a PR, thanks! Will do.

**Comment by KermMartian** [comment]
@s-t-e-v-e-n-k I'm afraid I bit off a bit more than I can chew with the testing; if I could hand it off to you, I'd be grateful. TIA.

**Comment by s-t-e-v-e-n-k** [comment]
Fixed in https://github.com/PyGithub/PyGithub/pull/1417 since I missed up the commit message.
