### ISSUE TITLE
List pull requests based on commit

### ISSUE THREAD

**Issue by mawkee** [PyGithub/PyGithub#1414]
There's a functionality on the Github API that is apparently not supported on PyGithub -- https://developer.github.com/v3/repos/commits/#list-pull-requests-associated-with-commit

## Motivation

I'm doing an auto-versioning type of thing on my repo, and I need to walk through all the pull requests searching for labels. I can get all the commits since the last release using `<repo>.get_commits(since=date_from_last_release)`. It would be incredibly useful if those commits came with their associated pull requests - that way I could simply check for each label on those.

I couldn't find this functionality on the documentation or reading the code, and I couldn't find another decent way to do this on the current PyGithub implementation.

## Caveats

This feature seems to be in preview period and the API might change, so it's probably not worth doing this right now (if ever).

**Comment by mawkee** [comment]
I can probably try to submit a pull request for this if there's interest. On my project I prefer not to rely on a preview API with a reasonable chance of having to re-do this.

**Comment by s-t-e-v-e-n-k** [comment]
I think it's probably fine, we currently support a fair amount of preview endpoints anyway. I look forward to reviewing your PR.
