### ISSUE TITLE
Team missing "get_repo_permissions"

### ISSUE THREAD

**Issue by tl-adrian-bridgett** [PyGithub/PyGithub#1415]
There is a "set_repo_permissions" call (great!) however there's no way to read the permissions.  GitHub does support this:

https://developer.github.com/v3/teams/#check-if-a-team-manages-a-repository

I'm especially interested in the full permissions that it describes just after that link (so that you can see admin/push/pull).

I had a quick look to see if I could send a PR (the call is easy, but lost my way figuring out how to convert that into a Repository!)

**Comment by s-t-e-v-e-n-k** [comment]
What do you mean convert it into a Repository? I can see arguments both ways for having it on Repository or on Team. Where are you getting stuck?

**Comment by tl-adrian-bridgett** [comment]
Hi, thanks for such a speedy response! :-)

The JSON returned from the "GET /orgs/:org/teams/:team_slug/repos/:owner/:repo" call looks like a repository (but I guess it's a slightly different view than that you'd receive from "GET /repos/:owner/:repo" as the permissions will reflect the team, I'm not sure what the other fields will be).

I was getting stuck figuring out how to return a Repository.  With a bit more time today I've figured out what to copy&paste so there's now a PR:
https://github.com/PyGithub/PyGithub/pull/1416
