### ISSUE TITLE
API Rate Limit example

### ISSUE THREAD

**Issue by brymon68** [PyGithub/PyGithub#1419]
Hello, 

I seem to be hitting Github search rate limits. I have written a utility to keep track of API calls but still seem to be hitting the search_code rate limit with basic authentication (30 per minute). 

Currently what I am doing is searching my entire Github organization's projects for a particular set of keywords. There are about 40-50 repos within the organization so I would expect I could make all necessary searches within 2 minutes. Is my logic correct? 

Here is some example code where I am using pypi package 'ratelimit' to limit my API requests to 29 per minute: 

```
@sleep_and_retry
@limits(calls=29, period=60)
def search_code(githubClient, query_string):
    search_results = []
    search = githubClient.search_code(query=query_string)
    for item in search:
        search_results.append(item)
    return search_results
```

Are there any examples that anyone has written where you are successfully able to avoid rate limits for searching? 

Thanks in advance.

**Comment by s-t-e-v-e-n-k** [comment]
The search API has a different limit, as shown in https://github.com/PyGithub/PyGithub/blob/425280cee77b5542d0cdfaa6fea488fe9d61894a/github/RateLimit.py#L71 , have you tried to inspect the object to see what your limits are as you step through the repos?

**Comment by brymon68** [comment]
Eh I just severely dropped it down to like 20 requests per minute keeping track of count. Not ideal but whatever. Thanks for response @s-t-e-v-e-n-k
