### ISSUE TITLE
Support new "Delete Reactions" endpoints

### ISSUE THREAD

**Issue by wesleimp** [PyGithub/PyGithub#1421]
GitHub Developer API announcement:
https://developer.github.com/changes/2020-02-26-new-delete-reactions-endpoints/

These new endpoints need to be supported:

- [ ] Delete a commit comment reaction
  - `DELETE /repos/:owner/:repo/comments/:comment_id/reactions/:reaction_id`
  - Docs: https://developer.github.com/v3/reactions/#delete-a-commit-comment-reaction

- [ ] Delete an issue reaction
   - `DELETE /repos/:owner/:repo/issues/:issue_number/reactions/:reaction_id`
   - Docs: https://developer.github.com/v3/reactions/#delete-an-issue-reaction

- [ ] Delete a reaction to a commit comment
  - `DELETE /repos/:owner/:repo/issues/comments/:comment_id/reactions/:reaction_id`
  - Docs: https://developer.github.com/v3/reactions/#delete-an-issue-comment-reaction

- [ ] Delete a pull request comment reaction
  - `DELETE /repos/:owner/:repo/pulls/comments/:comment_id/reactions/:reaction_id`
  - Docs: https://developer.github.com/v3/reactions/#delete-a-pull-request-comment-reaction

- [ ] Delete team discussion reaction
  - `DELETE /orgs/:org/teams/:team_slug/discussions/:discussion_number/reactions/:reaction_id`
  - Docs: https://developer.github.com/v3/reactions/#delete-team-discussion-reaction

- [ ] Delete team discussion comment reaction
  - `DELETE /orgs/:org/teams/:team_slug/discussions/:discussion_number/comments/:comment_number/reactions/:reaction_id`
  - Docs: https://developer.github.com/v3/reactions/#delete-team-discussion-comment-reaction

**Comment by gjcairo** [comment]
Hey, I will work on this.

**Comment by s-t-e-v-e-n-k** [comment]
Closed via merging #1708
