### ISSUE TITLE
Organization.get_teams does not call the right github API URL 

### ISSUE THREAD

**Issue by stephenyocum** [PyGithub/PyGithub#1430]
When calling get_teams() from an organization object, it results in an error.
This is due to the organization's url attribute being in the format 
https://api.github.com/users/:org
This results in a call to GitHub at https://api.github.com/users/:org/teams when calling get_teams() 
 
The GitHub API specifies that call should be made to https://api.github.com/orgs/:org/teams for this operation.  https://developer.github.com/v3/teams/#list-teams

If it makes any difference the program will first fetch a repository from it's full name then the organization object is found from repo's attribute and from there we are trying to fetch the teams via get_teams() resulting in this error

Unfortunately as I am using this functionality in a job related capacity I cannot provide any code or logs but I hope that this information helps.

**Comment by s-t-e-v-e-n-k** [comment]
What version are you using?

I can see we call /user/orgs in AuthenicatedUser.get_orgs(), and every Organization object I've looked at has the URL in the correct form:

```
>>> org = g.get_organization("PyGithub")
>>> org.url
'https://api.github.com/orgs/PyGithub'
```

 Are you able to give us redacted output of what you're seeing?
