### ISSUE TITLE
Org.invite_user("email") returns github.GithubException.UnknownObjectException: 404 

### ISSUE THREAD

**Issue by cmy4322** [PyGithub/PyGithub#1432]
I am trying to invite via email to an organization. 

G = github.Github(base_url=GIT_URL, login_or_token=GIT_ACCESS_TOKEN)
org = G.get_organization("org")
org.invite_user(email='foo@company.com')

However I am getting this error

`github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://developer.github.com/enterprise/2.18/v3/orgs/members/#create-organization-invitation"}`

 Anyone know why this is failing?

**Comment by s-t-e-v-e-n-k** [comment]
Because GitHub Enterprise 2.18 does not support that API endpoint. Compare https://developer.github.com/enterprise/2.18/v3/orgs/members/#create-organization-invitation to https://developer.github.com/v3/orgs/members/#create-organization-invitation .
