### ISSUE TITLE
Auth problem 🤔

### ISSUE THREAD

**Issue by andyhuber** [PyGithub/PyGithub#1439]
Hi guys. 

I wanted to use your amazing library to fetch some GitHub stats. and everything works great if I run my local python scripts. If I deploy the exact same script and try to invoke it on a Google Cloud Function I get the following error.  Has someone experienced similar problems?

> ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/XXX/XXX-app (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7edc316c9a50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by s-t-e-v-e-n-k** [comment]
[Errno -3] Temporary failure in name resolution

Would appear to be the root cause, the container (I'm guessing?) can't resolve api.github.com

**Comment by andyhuber** [comment]
What a stupid issue. Sorry, my bad. I realized that billing was not enabled for the new GCP project. and Cloud functions block outbound traffic if there is no billing account. Would have loved to get a better message from GCP than me spending hours to solve this :)
