### ISSUE TITLE
unable to set global username and email on git

### ISSUE THREAD

**Issue by byteshiva** [PyGithub/PyGithub#1445]
unable to set global username and email
```
g = Github(repoToken)
    repo = g.get_repo(repoName)
    repo.config_writer().set_value("user", "name", userName).release()
    repo.config_writer().set_value("user", "email", emailStr).release()
```

error
```
AttributeError: 'Repository' object has no attribute 'config_writer'

```

**Comment by s-t-e-v-e-n-k** [comment]
I can't see config_writer anywhere in the code base. What are you basing it's use on?

**Comment by byteshiva** [comment]
> I can't see config_writer anywhere in the code base. What are you basing it's use on?

I trying to do the following? How do I accomplish this using pygithub 

```

git config --global user.name "FIRST_NAME LAST_NAME"


git config --global user.email "OUR_NAME@example.com


```

**Comment by s-t-e-v-e-n-k** [comment]
You can't accomplish that by using PyGithub. Git configuration and GitHub configuration are completely separate. You run those commands in a terminal or a command prompt.
