### ISSUE TITLE
Support new 'visibility' field of Repository

### ISSUE THREAD

**Issue by adiagil** [PyGithub/PyGithub#1446]
Unable to create internal type of repo

**Comment by s-t-e-v-e-n-k** [comment]
What do you mean? Are you able to give more information, along with what code you're using, and what error you're getting?

**Comment by adiagil** [comment]
According https://developer.github.com/v3/repos/#create-a-repository-for-the-authenticated-user
I can see when I am creating new repo I can use string parameter **visibility**. It doesn't available

Can be public or private. If your organization is associated with an enterprise account using GitHub Enterprise Cloud or GitHub Enterprise Server 2.20+, visibility can also be internal. For more information, see "Creating an internal repository" in the GitHub Help documentation.
The visibility parameter overrides the private parameter when you use both parameters with the nebula-preview preview header.

**Comment by s-t-e-v-e-n-k** [comment]
Ah ha, this is an API extension that was published in December. https://developer.github.com/changes/2019-12-03-internal-visibility-changes/

**Comment by adiagil** [comment]
Ok thank you very much. Do you have ETA when it could be implemented?

**Comment by ruairitobrien** [comment]
@s-t-e-v-e-n-k I was thinking I could take a stab at this if that's OK?

**Comment by s-t-e-v-e-n-k** [comment]
@ruairitobrien Absolutely, I look forward to reviewing your PR.

**Comment by ruairitobrien** [comment]
@s-t-e-v-e-n-k sorry to have to trouble you with this :)

I added the visibility prop to `Organization.create_repo`

This required a header to be set `application/vnd.github.nebula-preview+json`

I updated the test to pass in the visibility flag and have tested it works in a real project but I am hitting an error in the unit tests that I am not sure about. Initially the test failed and I realised in needed to update the recording but when I tried to update it like so:

```
pytest -k Organization.testCreateRepoWithAllArguments --record
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.6.10, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /usr/app, inifile: pytest.ini
plugins: cov-2.8.1
collected 640 items / 640 deselected                                                                                                                                                                               

============================================================================================= 640 deselected in 10.70s =============================================================================================
```

No changes were made to the recording file. 

I did a workaround by manually updating the record and the test passed but I guess that's not ideal. I'm a bit new to a lot of the technologies in this project so just wanted to check if you had any pointers on how to make sure I am doing a real recording for the test. Thanks!

**Comment by ruairitobrien** [comment]
Also I realise I probably need to add this flag to a few other places but am hoping to get feedback on what I have so far to make sure I am on the right track.

**Comment by s-t-e-v-e-n-k** [comment]
pytest is actually pretty great at telling you what it will run -- play around with -k and --collect-only which will tell you exactly what it will execute without doing so.

**Comment by kunalnanda** [comment]
Any updates on this feature?

**Comment by kayhannay** [comment]
I have tried to add the visibility parameter today. I hit an issue while updating the recordings for the tests. The organization "BeaverSoftware" does not exist any more. So currently the only way I see to implement this is by editing the record data manually. Once this is done, all tests pass.

@ruarfff The reason that nothing was recorded in your case is that no tests were executed: `collected 640 items / 640 deselected`. Try to run the test using `pytest -k testCreateRepoWithAllArguments --record`.

**Comment by ruarfff** [comment]
> I have tried to add the visibility parameter today. I hit an issue while updating the recordings for the tests. The organization "BeaverSoftware" does not exist any more. So currently the only way I see to implement this is by editing the record data manually. Once this is done, all tests pass.
> 
> @ruarfff The reason that nothing was recorded in your case is that no tests were executed: `collected 640 items / 640 deselected`. Try to run the test using `pytest -k testCreateRepoWithAllArguments --record`.

Thanks! In my PR I had eventually gotten to the point where I hit the same issue as you. The PR has gotten to a point of being able to create repos with the parameter but got a bit more complicated to get tests passing when adding the parameter in the various GETs.

I need to get back to that soon. It just appears getting the tests to pass is fairly significant effort unless I am missing something.

**Comment by MarkWilsonODS** [comment]
Where would I find this feature?  I have 1.54.1. Thanks.

**Comment by adiagil** [comment]
Just to be sure if this feature included already included in any releases.
