### ISSUE TITLE
Listing all private repos through PyGithub

### ISSUE THREAD

**Issue by testchrishahahn** [PyGithub/PyGithub#1452]
Hey, I'm trying to list all the private repos from another user. I'm kind of new to this, but would like some help. I have python installed along with sublime. I'm stuck with how to run the script and what the script should contain. Here's what I have so far in my sublime text. 

> 
> def get_repos(type=private, sort=full_name):
>         """
>         :calls: `GET /orgs/:org/repos <https://developer.github.com/v3/repos/#list-organization-repositories>`_
>         :param login: string
>         :rtype: :class:`github.Organization.Organization`
>         """
>         assert isinstance(login, str), login
>         headers, data = self.__requester.requestJsonAndCheck(
>             "GET",
>             "/orgs/" + name_of_org + "/repos"
>         )
>         return data
> 

I'm lost after this. Do I need a header? How do I run it in SSH? Any help please? Sorry, fairly new to API and python >_>.

**Comment by s-t-e-v-e-n-k** [comment]
Generally, you want to save the script to a text file, and then run it with &lt;path to python or python.exe&gt; &lt;script name&gt;, in this case, you're conflating code you should write versus what you should call.

This module does require a modicum of understanding of Python (but not APIs, we handle all that for you). I'd suggest a resource like https://learnpythonthehardway.org/python3/ to help with your Python knowledge.

But to answer your original question, https://pygithub.readthedocs.io/en/latest/github_objects/NamedUser.html#github.NamedUser.NamedUser.get_repos is the method you should look at. Currently we don't support searching by visibility, but there is another issue open for that.
