### ISSUE TITLE
Requesting non-existent branch raises `GithubException` instead of `UnknownObjectException`

### ISSUE THREAD

**Issue by twelvelabs** [PyGithub/PyGithub#1455]
Looks like you're checking the error message string for "Not Found", but the API is returning "Branch not found":

https://github.com/PyGithub/PyGithub/blob/393bd21bd168769d8ecf4b23f4b32e9a4de5f17a/github/Requester.py#L387

Are there other reasons that the API would return a 404? Seems like just using the status code would be sufficient here. If not, then perhaps something like `"not found" in output.get("message").lower()`. Happy to submit a PR.

**Comment by s-t-e-v-e-n-k** [comment]
Yes, the API returns 404 for things like membership of organizations and one or two other things that escape me. I'm not against the change, but if you do put up a PR, then please include a test.
