### ISSUE TITLE
How to check whether a specific file exists avoiding any exceptions?

### ISSUE THREAD

**Issue by Kharacternyk** [PyGithub/PyGithub#1458]
I'm working on some kind of a crawler that needs to fetch the file `a` or, if doesn't exist, the file `b` and so on. This is performed on large number of repos. My current code utilizes `repo.get_contents("a")` but the exceptions that occur when `a` doesn't exist are very costly.

I believe this a common problem, but I haven't found anything on it neither in this repo nor in the docs.

Any help is appreciated.

**Comment by s-t-e-v-e-n-k** [comment]
As a suggestion call ``get_contents()`` with the directory, not the full path. / (as in the root of the repository) can be specified as empty string. For example:

```
>>> repo = g.get_repo("PyGithub/PyGithub")
>>> files = repo.get_contents('')
>>> 'setup.py' in [f.name for f in files]
True
```

**Comment by Kharacternyk** [comment]
This solution works fine, at least in my use case. Thanks!
