### ISSUE TITLE
The documentation implies that PaginatedList has __len__, but it doesn't.

### ISSUE THREAD

**Issue by Kharacternyk** [PyGithub/PyGithub#1462]
https://github.com/PyGithub/PyGithub/blob/393bd21bd168769d8ecf4b23f4b32e9a4de5f17a/github/PaginatedList.py#L107

In REPL:

```python
>>> print(len(g.search_code(query="filename:vimrc")))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'PaginatedList' has no len()
```

8ae2bcb implemented `__len__` and mentioned it in the `__doc__`. 8a589c9 removed `__len__` implementation but left `__doc__` as is. Related #579.

**Comment by sfdye** [comment]
Can we re-open this or create a new issue to track this bug?

**Comment by s-t-e-v-e-n-k** [comment]
@sfdye I've opened https://github.com/PyGithub/PyGithub/issues/1476
