### ISSUE TITLE
get_organization_membership is passed org, which should str but asserts if not int

### ISSUE THREAD

**Issue by brianlangdon** [PyGithub/PyGithub#1472]
The function get_organization_membership in file AuthenticatedUser.py expects (self, org) then asserts if org is not an int

line 1310 - assert isinstance(org, int)

however API expects a string - organisation login value

"GET", "/user/memberships/orgs/" + str(org)

changing assert to the following works as expected

line 1310 - assert isinstance(org, str)

(sorry, i'm not following all the rules this is my first ever GitHub issue)

**Comment by s-t-e-v-e-n-k** [comment]
As it is written we coerce it to a str so we can construct the URL from an integer. The idea being that you give it the ID of the organization, and it returns the membership. However, I can see that calling it with the ID of an organization that I am a member of, it raises a 404, and giving it the org name works fine. I'll push up a PR soon.
