### ISSUE TITLE
Provide a less wasteful way to retrieve some resources

### ISSUE THREAD

**Issue by edigaryev** [PyGithub/PyGithub#1474]
Let's say you wanted to retrieve the reactions for this issue. You'd code something like this:

```python
github = Github()

for reaction in github.get_repo("PyGithub/PyGithub").get_issue(1474).get_reactions():
    print(reaction)
```

The problem is that this makes at least 3 requests:

* http://developer.github.com/v3/repos — `GitHub.get_repo()`
* http://developer.github.com/v3/issues — `Repository.get_issue()`
* https://developer.github.com/v3/reactions/#list-reactions-for-an-issue — `Issue.get_reactions()`

Where only the last one will be sufficient to get the job done:

```
GET /repos/:owner/:repo/issues/:issue_number/reactions
```

It would be nice if one could do this instead:

```python
github = Github()

for reaction in github.get_reactions("PyGithub/PyGithub", 1474):
    print(reaction)
```

See Octokit example: https://octokit.github.io/octokit.rb/Octokit/Client/Reactions.html#issue_reactions-instance_method

**Comment by sfdye** [comment]
You want GraphQL :trollface:

**Comment by sfdye** [comment]
We could make a new shortcut method `github.get_reactions`, but it is simply impossible to make it for all the APIs we have, due to how the API is designed.

**Comment by edigaryev** [comment]
>You want GraphQL

Thought about this too, but GraphQL is somewhat more burdensome to use, compared to this library.

>but it is simply impossible to make it for all the APIs we have, due to how the API is designed

Can you provide a more concrete example of a method for which making such a shortcut would be inconvenient?

**Comment by s-t-e-v-e-n-k** [comment]
> Can you provide a more concrete example of a method for which making such a shortcut would be inconvenient?

Our main class is already 854 lines. Adding a ``get_reactions`` endpoint is easily at least 15 lines, it just does not scale, both in terms of code size and in terms of testing.

**Comment by edigaryev** [comment]
>Our main class is already 854 lines. Adding a `get_reactions` endpoint is easily at least 15 lines, it just does not scale, both in terms of code size and in terms of testing.

What if the library would provide a way to instantiate `Issue` like this:

```python
issue = Issue("PyGithub/PyGithub", 1474)
```

...and then one could just call `issue.get_reactions()` to retrieve reactions.

Quickly looking [at the code](https://github.com/PyGithub/PyGithub/blob/a9f174bd1d6da6cf4053e09349e7e22b0d8fee09/github/Issue.py#L64) it seems that `self._completeIfNotSet(...)` guards should account for the missing internal state, but I haven't tested this yet.

**Comment by edigaryev** [comment]
>but I haven't tested this yet

This seems to work, however it's very hacky:

```
>>> requester = Github()._Github__requester
>>> Issue.Issue(requester, None, {"url": "https://api.github.com/repos/PyGithub/PyGithub/issues/1474"}, False).title
'Provide a less wasteful way to retrieve some resources'
```

To make it more clean, we can:

* move defaults pased to `Requester` from `Github.__init__()` to `Requester.__init__()` to facilitate easier re-use of this class
* implement `Issue.from_number()` class method that instantiates an issue object by calling `super.__init__()` (which is `CompletableGithubObject`) with the right parameters

So the example above could be reproduced by doing:

```
>>> Issue.from_number(PyGithub/PyGithub", 1474).title
'Provide a less wasteful way to retrieve some resources'
```
