### ISSUE TITLE
repo.create_file() is slow

### ISSUE THREAD

**Issue by AnthonyGiorgio** [PyGithub/PyGithub#1478]
I'm experimenting with PyGithub to perform a mass import of files into a repo for archival purposes.  I've had a lot of success so far, but one thing I've noticed is that the performance of `repo.create_file()` is quite slow.  It takes multiple seconds to create and commit a new file to the repo, whereas doing a single commit using the git CLI only takes a few seconds for the entire set of files.

Is there a way to batch a number of files together into a single commit?

**Comment by sfdye** [comment]
I would imagine using a series of low-level API like `create_git_blob` followed by `create_git_commit`.
