### ISSUE TITLE
PaginatedList totalCount is wrong when iterating the issues

### ISSUE THREAD

**Issue by shacharor-Vayyar** [PyGithub/PyGithub#1479]
This code works fine:

```
g = Github(username, password)
repo = g.get_repo(repo)
issues = repo.get_issues(state='closed', sort='updated', direction='asc')
print(issues.totalCount)
for idx, issue in enumerate(issues):
    print(issues.totalCount)
    break
```

The output will be: 
```
195
195
```

195 is indeed the number of closed issues.

If I comment one of the lines:

```
g = Github(username, password)
repo = g.get_repo(repo)
issues = repo.get_issues(state='closed', sort='updated', direction='asc')
# print(issues.totalCount)
for idx, issue in enumerate(issues):
    print(issues.totalCount)
    break
```

The output becomes:
```
42
```

42 is the number of **opened** issues I have on that repo. This is obviously wrong.

The for-loop iterates on 195 in both cases, so no problem there.

**Comment by steveoh** [comment]
`totalCount` is wrong when using labels also.

I misunderstood labels and queried for two mutually exclusive labels. This resulted in `0`issues being returned but `totalCount` displayed `11`. 

Possibly related to https://github.com/PyGithub/PyGithub/issues/960

**Comment by steveoh** [comment]
not stale; still waiting for a contributor to triage.

**Comment by steveoh** [comment]
> not stale; still waiting for a contributor to triage.
