### ISSUE TITLE
Switch to CalVer for release?

### ISSUE THREAD

**Issue by sfdye** [PyGithub/PyGithub#1482]
https://calver.org/

For some historical reasons, the current SemVer has conflicting version number with a stale (v2) branch. 

The Github API is calendar sensative (aware), should we switch to Calver for new releases? 

e.g. `YY.MM.MICRO` or `YY.MINOR.MICRO`

**Comment by sfdye** [comment]
@s-t-e-v-e-n-k what do you think?

**Comment by s-t-e-v-e-n-k** [comment]
I am pretty neutral on this. I mean, if you want, I have no objections, but I will also mention we've been pretty bad at following semver guidelines. :-)

**Comment by sfdye** [comment]
I think we can stick to the current sem var.
