### ISSUE TITLE
Type stubs are not packaged

### ISSUE THREAD

**Issue by christopher-dG** [PyGithub/PyGithub#1490]
I just installed 1.50 hoping to have mypy pick up the new type information, but it still doesn't find anything. I looked at the `github` installation in my virtualenv, and no `.pyi` files were in there with the `.py` ones.
It looks like we need to create a `github/py.typed` file and include it in your package data? [source](https://www.python.org/dev/peps/pep-0561/#packaging-type-information)

**Comment by christopher-dG** [comment]
Oops... should have checked open PRs too. This is closed by #1489 which seems to correctly install the stub files.

**Comment by sfdye** [comment]
Type stubs are now published in `1.51`:
https://pypi.org/project/PyGithub/1.51/
