### ISSUE TITLE
Feature: allow to add teams to repository collaborators

### ISSUE THREAD

**Issue by schlitzered** [PyGithub/PyGithub#1491]
there seems to be no way to add a team to a to a repository right now.

i guess the add_to_collaborators method would need to be extended for this

**Comment by s-t-e-v-e-n-k** [comment]
The endpoint that ``Repository.add_to_collaboraters`` calls only mentions usernames. Given the function accepts a string, what response do you get back if you pass in the slug of a team? If you need to XXX out private information, please feel free.

**Comment by andygrunwald** [comment]
The call to add a team to a repository is `team.set_repo_permission`. See https://pygithub.readthedocs.io/en/stable/github_objects/Team.html#github.Team.Team.set_repo_permission

However, this endpoint uses a deprecated endpoint right now. See [Teams: Add or update team repository (Legacy)](https://developer.github.com/v3/teams/#add-or-update-team-repository-legacy)

The new GitHub API endpoint is [Teams: Add or update team repository](https://developer.github.com/v3/teams/#add-or-update-team-repository)

**Comment by andygrunwald** [comment]
Related: https://github.com/PyGithub/PyGithub/issues/1507

**Comment by s-t-e-v-e-n-k** [comment]
@schlitzered As a workaround, ``Team.set_repo_permission()``, but the API is deprecated.

**Comment by schlitzered** [comment]
i will take a look at this, thanks

**Comment by arjenpdevries** [comment]
This should not have been closed; as detailed, the API `set_repo_permission` is deprecated so a solution needs to be provided.
