### ISSUE TITLE
`github.ProjectCard.ProjectCard.move` doesn't seem to be working

### ISSUE THREAD

**Issue by ian-howell** [PyGithub/PyGithub#1495]
The [`move`](https://github.com/PyGithub/PyGithub/blob/v1.50/github/ProjectCard.py#L140) function appears to function (the response is a 201), but the `ProjectCard` doesn't actually change columns on the Project board.

I created a simple project and repo, as well as an issue under the repo. I can move the issue around in the Github UI, but PyGithub seems unwilling to do so.

**Comment by s-t-e-v-e-n-k** [comment]
That should have been corrected in https://github.com/PyGithub/PyGithub/pull/1451, are you using 1.50?

**Comment by ian-howell** [comment]
nope, I was on 1.46. Upgrading has solved the issue. Thanks!

**Comment by lisaattrillium** [comment]
I can't get this to work either. What are some acceptable options for "position" params?

**Comment by lisaattrillium** [comment]
can you move cards from one project to another?
