### ISSUE TITLE
Use of team_reviewers results in: "Could not resolve to a node with the global id of..." error 

### ISSUE THREAD

**Issue by digi-talo** [PyGithub/PyGithub#1499]
When creating a review request for a PR and a team is added as such:

`pr.create_review_request(team_reviewers=["team_name"])`

it results in an exception:
```
self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": ["Could not resolve to a node with the global id of 'MDQ6VGVhbTQxMDAz'."], "documentation_url": "https://developer.github.com/v3/pulls/review_requests/#create-a-review-request"}
```
I can add individual reviewers without issue, the exception only occurs when using a valid team name.

**Comment by s-t-e-v-e-n-k** [comment]
I would suggest dropping the org/, the documentation mentions team slug, which would be the bare team name.

**Comment by digi-talo** [comment]
Sorry I missed, that's actually what I did. I corrected my post.
