### ISSUE TITLE
Cannot fetch the list of merged PRs with date range

### ISSUE THREAD

**Issue by marouni** [PyGithub/PyGithub#1508]
Hello :wave: 

I'm unable to fetch the list of merged PRs using the issues endpoint with PyGithub : 
```
from github import Github

g = Github()

print(g.search_issues(query="repo:apache/beam+is:pr+is:merged+merged:2020-04-22..2020-05-06+sort:updated").totalCount)
```

Returns :
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    print(g.search_issues(query="repo:apache/beam+is:pr+is:merged+merged:2020-04-22..2020-05-06+sort:updated").totalCount)
  File "/home/abbass/.virtualenvs/github-stats/lib/python3.6/site-packages/github/PaginatedList.py", line 154, in totalCount
    "GET", self.__firstUrl, parameters=params, headers=self.__headers
  File "/home/abbass/.virtualenvs/github-stats/lib/python3.6/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/home/abbass/.virtualenvs/github-stats/lib/python3.6/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"message": "The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource": "Search", "field": "q", "code": "invalid"}], "documentation_url": "https://developer.github.com/v3/search/"}
```

The same query works in a browser : 
https://api.github.com/search/issues?q=repo:apache/beam+is:pr+is:merged+merged:2020-04-22..2020-05-06+sort:updated&sort=created&order=asc

**Comment by s-t-e-v-e-n-k** [comment]
If you're actually using ``Github()`` then you're making the query anonymously, which is likely why you're getting back an exception. Generate a token pass it in as the first argument.

**Comment by marouni** [comment]
@s-t-e-v-e-n-k 

The repository that I'm using is a public one apache/beam, even with the token (a personal one for this github account) I keep getting the same error.

Isn't supposed to return the same result as this call :
https://api.github.com/search/issues?q=repo:apache/beam+is:pr+is:merged+merged:2020-04-22..2020-05-06+sort:updated&sort=created&order=asc

**Comment by paulgessinger** [comment]
Have a similar issue I think. Looks to me like `search_issues` escapes `+` to `%2B`, which triggers the error. If curl the exact URL that the verbose logging says it's trying, I get the same error. If I replace `%2B` with `+` it works fine.

**Comment by s-t-e-v-e-n-k** [comment]
Ahhh, that's a wonderful hint. I've been scratching my head over this, but that gives me a direction to dig when I get some time.

**Comment by paulgessinger** [comment]
I think it's because its basically double encoding the +. @marouni I think in your example, you might be able to get it to work by just removeing the + signs. Spaces get urlencoded to +, and then it should make it to the API endpoint in the correct form.

**Comment by marouni** [comment]
@paulgessinger Thanks for the hint, I'll give it a try !

**Comment by s-t-e-v-e-n-k** [comment]
@marouni Did the hint help? If so, I think we can solve this by replacing the +'s with spaces.

**Comment by marouni** [comment]
@s-t-e-v-e-n-k 
yup : 
```
from github import Github

g = Github()

print(g.search_issues(query="repo:apache/beam is:pr is:merged merged:2020-04-22..2020-05-06 sort:updated").totalCount)
```
```
112
```

**Comment by s-t-e-v-e-n-k** [comment]
Excellent! I will put together a PR that replaces +'s with a test that will close this issue.

**Comment by marcosfede** [comment]
I spent several hours debugging today and was finally able to pinpoint that it was an encoding error. replacing `+` with spaces worked out, but it would be great if this could be fixed to avoid further confusion.
