### ISSUE TITLE
Check of outdated PR comments

### ISSUE THREAD

**Issue by ilya-palachev** [PyGithub/PyGithub#1515]
Hello,

The current API for PR comments contains a lot of fields that can be checked. But sometimes I need to check whether the comment is outdated or not. How can it be done using `PyGithub`?

If there is any way to do that, then this is a question. If not, this is a feature request :smile:

Thanks in advance!

**Comment by s-t-e-v-e-n-k** [comment]
I'm sorry for missing this issue being filed. Can you define what makes a comment outdated? If it's been edited?

**Comment by ilya-palachev** [comment]
> I'm sorry for missing this issue being filed. Can you define what makes a comment outdated? If it's been edited?

Thanks for response!

I meant the "Outdated" mark that appears when the code being commented was edited and the comment is not applicable to it anymore:
![outdated-and-resolved-comments](https://user-images.githubusercontent.com/8101418/82791265-65edd080-9ea8-11ea-8fb6-20bda4734c8e.png)
The "Resolved" mark (which is made by developers manually) is also interesting.

This feature could help to distinguish comments that were addressed and that were not.

**Comment by s-t-e-v-e-n-k** [comment]
I'm not certain about the resolved mark, I think that is a UI behaviour only, however, from some quick testing, I think you can check for the outdatedness of a comment by comparing the ``original_position`` to the ``position`` property, like so:

```
>>> g = Github(TOKEN)
>>> repo = g.get_repo("PyGithub/PyGithub")
>>> pr = repo.get_pull(1395)
>>> for c in pr.get_comments():
...     line = str(c.id)
...     if c.original_position != c.position:
...         line += " is outdated"
...     else:
...         line += " is not outdated"
...     print(line)
... 
378599711 is outdated
378600370 is outdated
378600453 is outdated
378600571 is outdated
378600862 is not outdated
378601708 is outdated
378601899 is not outdated
378603197 is outdated
378824865 is not outdated
```

**Comment by ilya-palachev** [comment]
> I'm not certain about the resolved mark, I think that is a UI behaviour only, however, from some quick testing, I think you can check for the outdatedness of a comment by comparing the `original_position` to the `position` property, like so:
> 
> ```
> >>> g = Github(TOKEN)
> >>> repo = g.get_repo("PyGithub/PyGithub")
> >>> pr = repo.get_pull(1395)
> >>> for c in pr.get_comments():
> ...     line = str(c.id)
> ...     if c.original_position != c.position:
> ...         line += " is outdated"
> ...     else:
> ...         line += " is not outdated"
> ...     print(line)
> ... 
> 378599711 is outdated
> 378600370 is outdated
> 378600453 is outdated
> 378600571 is outdated
> 378600862 is not outdated
> 378601708 is outdated
> 378601899 is not outdated
> 378603197 is outdated
> 378824865 is not outdated
> ```

Thanks! It looks working like intended. However, sometimes `position` is `None`. How should I interpret such case?

Moreover, this method is not very evident (without your comment I would not even get this). To make it more useful, it would be great to add some comments about what `position` and `original_position` are. The current comments don't contain this information:
https://github.com/PyGithub/PyGithub/blob/master/github/PullRequestComment.py#L107-L113
and
https://github.com/PyGithub/PyGithub/blob/master/github/PullRequestComment.py#L123-129

Maybe it would be good to provide the method for outdated comments:
```python
@property
def is_outdated(self):
    return self.position != self.original_position
```

**Comment by s-t-e-v-e-n-k** [comment]
position is the code position, so position as None is I think are comments on PR itself, not made on any part of the diff. WRT adding the property, we sadly don't export anything that GitHub does not.

Given the API docs we're working from on developer.github.com, the fields aren't documented at all, so all of this is just guesswork in the dark anyway. :-)

**Comment by ilya-palachev** [comment]
OK, thanks! Then I think it's enough and we can close this issue.
