### ISSUE TITLE
How to work with the GithubException object

### ISSUE THREAD

**Issue by pconrad** [PyGithub/PyGithub#152]
I have a question about how to work with the GithubException object

Sample Code:
     try:
        team = org.create_team(teamName,
                         [],
                         "push");
     except GithubException as e:
         print (e)

When I print (e) I get:

```
 422 {u'message': u'Validation Failed', u'errors': [{u'field': u'name', u'code': u'already_exists', u'resource': u'Team'}]}
```

What I'd like to be able to do is see the list of attributes and member functions of  the GithubException object so that I can pull out various stuff to check for particular events... but I can'f find this in the documentation for the PyGithub API.    Maybe I just need to understand better the relationship between the PyGithub API and the underlying github RESTful API.

From the source, it appears that there are two properties of the GithubException object:

https://github.com/jacquev6/PyGithub/blob/master/github/GithubException.py

```
status
data
```

and putting that together with the output, it appears the 422 is the status (perhaps returned by the API?), and the data is a dictionary object (perhaps an encoding of the JSON that got returned?)  but these are only guesses.    

It appears that the only place GithubException occurs in the source is in Requester.py---and this tends to confirm my guesses.

Is there somewhere in the documentation for the github API itself where one can find the keys that one would expect to find in the JSON object, i.e. in this case "message", "errors", and then within "errors", "field", "code", "and "resource"?   

From trial and error guesswork, I settled on code like this, but this feels "hacky---I'd be more comfortable if I knew whether I was doing this right...

```
team = False   # Sentinel to see if it succeeded or failed
try:
   team = org.create_team(teamName,
                     [],
                     "push");
   print(" team {0} created...".format(teamName),end='')
except GithubException as e:
   if (e.data['errors'][0]['code']=='already_exists'):
      print(" team {0} already exists...".format(teamName),end='') 
   else:
      print (e)

if (team != False):
   # do something with team...
```

Am I on the right track?

**Comment by NicoHood** [comment]
Hi,
I try to catch an exception:

```python
github.GithubException.BadCredentialsException: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}
```

Now I i try to access it directly I get the following error:
```
AttributeError: type object 'GithubException' has no attribute 'BadCredentialsException'
```

How can I catch this specific exception and not only a general githubexception?

**Comment by izgzhen** [comment]
> Hi,
> I try to catch an exception:
> 
> ```python
> github.GithubException.BadCredentialsException: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}
> ```
> 
> Now I i try to access it directly I get the following error:
> 
> ```
> AttributeError: type object 'GithubException' has no attribute 'BadCredentialsException'
> ```
> 
> How can I catch this specific exception and not only a general githubexception?

use `github.BadCredentialsException` -- which is more clear from source code.

**Comment by s-t-e-v-e-n-k** [comment]
GithubException is a class as well as a module, the full module path to the class is github.GithubException.GithubException, which you can't import BadCredentialsException from. All of the exceptions are exported via github, so ``from github import BadCredentialsException`` will work fine.
