### ISSUE TITLE
Attempting to get the reaction of the latest comment

### ISSUE THREAD

**Issue by srihari15** [PyGithub/PyGithub#1531]
Hi folks, I am trying to get the reaction for the latest comment made and the user who made the reaction/emoji, in the issue if there is any. I have followed the docs and couldn't follow it clearly. If someone could guide me, it would be really helpful. TIA!

**Comment by srihari15** [comment]
Tried the following:
reaction = [comment.get_reactions for comment in issues.get_comments()]

getting an o/p:
<bound method IssueComment.get_reactions of xxxxxx

expected O/p
user name of the one who reacted

**Comment by s-t-e-v-e-n-k** [comment]
It's a method, like ``get_coments``: ``comment.get_reactions()``

If you want a list of usernames who reacted, you need to iterate over the returned list of reactions as well.

```
[r.user.name for r in c.get_reactions() for c in issues.get_comments()]
```

**Comment by s-t-e-v-e-n-k** [comment]
@srihari15 Did my comment help?

**Comment by srihari15** [comment]
Yes it did help. Thanks. I will close this issue.
