### ISSUE TITLE
HWO TO CREATE NEW REPO

### ISSUE THREAD

**Issue by pyanishjain** [PyGithub/PyGithub#1534]
IS IT IS POSSIBLE TO CREATE A NEW REPOSITORY WITH THIS PYTHON MODULE OR NOT

**Comment by s-t-e-v-e-n-k** [comment]
Yes, https://pygithub.readthedocs.io/en/latest/github_objects/AuthenticatedUser.html#github.AuthenticatedUser.AuthenticatedUser.create_repo is the documentation for the method.
