### ISSUE TITLE
Connect with ssh

### ISSUE THREAD

**Issue by silverhairs** [PyGithub/PyGithub#1537]
Is it possible to connect using a local ssh instead of username/pass?

**Comment by pyanishjain** [comment]
yes  it is possible
how to upload a folder into my github using this

**Comment by silverhairs** [comment]
Can you tell me how.
and I don't really understand what you mean? do you want to push?

**Comment by silverhairs** [comment]
> yes it is possible
> how to upload a folder into my github using this

Can you tell me how.
and I don't really understand what you mean? do you want to push?

**Comment by s-t-e-v-e-n-k** [comment]
It is not possible to connect to the GitHub API using ssh credentials.
