### ISSUE TITLE
Add ability to download binary content of release asset

### ISSUE THREAD

**Issue by jesseli2002** [PyGithub/PyGithub#1541]
I know #525 introduced release asset capabilities, but unless I've missed the right doc page I don't think it's possible to download the binary content of a release asset - just the information about an asset.  See https://developer.github.com/v3/repos/releases/#get-a-single-release-asset and the note about downloading the asset's binary content.

**Comment by s-t-e-v-e-n-k** [comment]
Ah ha, that is diabolical. I think the best way to handle this is to add a method to GitReleaseAsset that calls GET self.url with the Accept header set. What do you think?

**Comment by jesseli2002** [comment]
Sounds fair to me, although I can't say I'm too familiar with the code.

**Comment by JacekPliszka** [comment]
I can prepare something - I need the same thing + I need it in Actions artifacts.

**Comment by dzarda** [comment]
This is sortof important IMHO

**Comment by neel-m** [comment]
Is there still some interest in this capability?
I need to download ReleaseAssets and was able to add requestFile() to Requester.py and download_asset() to GitReleaseAsset.py and get it to work.  I am sure there is more that will be needed.  Is there anybody who can help?
