### ISSUE TITLE
More precise typing on `Github.get_user()`

### ISSUE THREAD

**Issue by nymous** [PyGithub/PyGithub#1550]
In `MainClass.pyi` the `get_user` method is typed as such:
```py
    def get_user(
        self, login: Union[str, _NotSetType] = ...
    ) -> Union[AuthenticatedUser, NamedUser]: ...
```

But I took a look at the implementation and I think the returned type can be better by using [function overloading](https://mypy.readthedocs.io/en/stable/more_types.html#function-overloading):
```py
from typing import overload
...

    @overload
    def get_user(self, login: str
    ) -> NamedUser: ...
    @overload
    def get_user(
        self, login: _NotSetType = ...
    ) -> AuthenticatedUser: ...
    def get_user(
        self, login: Union[str, _NotSetType] = ...
    ) -> Union[AuthenticatedUser, NamedUser]: ...
```

That way if you call it with a `login` mypy knows it returns a `NamedUser`, and if you call without the `login` argument it returns an `AuthenticatedUser`.

Note: this is my current use case but I didn't check to see if other methods could be improved like this.
Should I create a PR with this already and see about the rest later on?

**Comment by nymous** [comment]
Also just found out that the `:rclass:` docstring doesn't specify `AuthenticatedUser` as a possible return value

**Comment by s-t-e-v-e-n-k** [comment]
Based on my reading of the docs of function overloading we only need the first two, but this looks amazing! Are you happy with pushing up a PR for this?
