### ISSUE TITLE
required_linear_history not supported in branch protection

### ISSUE THREAD

**Issue by rthill91** [PyGithub/PyGithub#1551]
I don't see `required_linear_history` as an available option in `edit_protection` or elsewhere. Is there a specific reason for its absence or any timeline on when it might make it in?

[The update protection GH docs for reference](https://developer.github.com/enterprise/2.20/v3/repos/branches/#update-branch-protection)

**Comment by s-t-e-v-e-n-k** [comment]
Huh. I will note that parameter was not available when I wrote the branch protection code, which is why it's missing. I'll investigate adding it.

**Comment by gohelh-adsk** [comment]
This parameter was introduced in GitHub 2.20 ([release notes](https://enterprise.github.com/releases/2.20.0/notes)) along with two other options as well, `allow_force_pushes` and `allow_deletions`. Support for all three would be great.
