### ISSUE TITLE
Moving towards the v4 API

### ISSUE THREAD

**Issue by fclairamb** [PyGithub/PyGithub#1553]
I've been using this library to help us automate some processes flawlessly. But lately, I faced the issue described in #1461 which seems to require the v4 API.

So, what is your view on migrating to the v4 API? Do you think...
1. It should be somewhere else? Because you think this library should be limited to REST?
1. It should be a new major version and new branch rewriting everything in GraphQL 
1. It should be done progressively by starting to implement the features that are only in the v4 API (like #1461) and progressively switch everything else to v4 (or not)?

I prefer this third approach but I'm opened to anything and will be happy to contribute to it.

**Comment by s-t-e-v-e-n-k** [comment]
Sadly, It should be somewhere else, this library is 100% limited to REST. (So the first option)

**Comment by sfdye** [comment]
Yup, PyGithub will remain as a V3 REST library, if you need V4 I am pretty sure there are great libraries for GraphQL.

**Comment by fclairamb** [comment]
It seems somebody changed their mind about that with [v2.2.0](https://github.com/PyGithub/PyGithub/releases/v2.2.0) and switched towards the third option. 

And that's great !
