### ISSUE TITLE
Not all issue reactions are supported by PyGitHub

### ISSUE THREAD

**Issue by vlerenc** [PyGithub/PyGithub#1554]
Please see https://github.com/PyGithub/PyGithub/blob/master/github/Issue.py#L577-L584. It lists the supported reactions, but some are missing, if you follow your own error message leading to https://developer.github.com/v3/reactions/#reaction-types, e.g. `eyes`.

**Comment by s-t-e-v-e-n-k** [comment]
I'm tempted to remove that check and just assert content is a string, and let GitHub throw an error if an unsupported emoji is passed in -- what do you think?

**Comment by vlerenc** [comment]
Yes @s-t-e-v-e-n-k, my thought as well. Otherwise, you always run the risk of becoming outdated. Thanks!
