### ISSUE TITLE
renaming files in a gist

### ISSUE THREAD

**Issue by jasonwiener** [PyGithub/PyGithub#156]
looking at the InputFileContent class, it doesn't appear to support renaming a file in a gist. am i mistaken?

**Comment by owy1** [comment]
I'm sorry but how do you rename a gist file on "editing gist" mode?

**Comment by kpsychas** [comment]
There is a box above the source code where you can edit the name. Just a note for anyone that considers this obvious: the filename that appears on top of the page is not editable and that is what probably creates confusion.

**Comment by owy1** [comment]
Thx so much!
Ophelia
