### ISSUE TITLE
from github import Github make mistake 

### ISSUE THREAD

**Issue by UNSWHARDEN** [PyGithub/PyGithub#1560]
raceback (most recent call last):
  File "D:/github api/github/src/mainClass.py", line 1, in <module>
    from github import Github
ImportError: cannot import name 'Github' from 'github' (unknown location)

**Comment by s-t-e-v-e-n-k** [comment]
Is your module called github too? Since that won't work without some rather interesting hacks to ``sys.modules``.

**Comment by UNSWHARDEN** [comment]
> 您的模块也称为github吗？由于没有一些相当有趣的破解手段才能奏效`sys.modules`。

I pulled the code directly from github. The name of the folder that was put was changed. .

**Comment by s-t-e-v-e-n-k** [comment]
Did that solve the issue?

**Comment by UNSWHARDEN** [comment]
> 这样解决了吗？

no

**Comment by UNSWHARDEN** [comment]
I have solved the problem, I changed the pycharm version to the professional version, set up the python environment, and then import the pygithub package again.
