### ISSUE TITLE
Feature: Merge pull request

### ISSUE THREAD

**Issue by staticdev** [PyGithub/PyGithub#1561]
Is this on the roadmap? Since I fetched a pull request using the query function, I would like to merge it.

**Comment by s-t-e-v-e-n-k** [comment]
It's already implmented: https://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html#github.PullRequest.PullRequest.merge

**Comment by staticdev** [comment]
@s-t-e-v-e-n-k perfect!! I just thought it was going to be here.. https://pygithub.readthedocs.io/en/latest/examples/PullRequest.html

Now I see they are examples, not everything implemented. Thanks!!

**Comment by s-t-e-v-e-n-k** [comment]
You're welcome!

**Comment by staticdev** [comment]
@s-t-e-v-e-n-k is it possible to delete_branch_on_merge? or delete it separately afterwards?
