### ISSUE TITLE
Bug on Repository.get_pulls

### ISSUE THREAD

**Issue by staticdev** [PyGithub/PyGithub#1566]
I tried making a find pull requests on with the parameters:

`pulls = repo.get_pulls(state="open", base="master", head="nox-mypy")`

repo: https://github.com/staticdev/toml-validator

It is returning 2 PRs, but there is only one!

Same happens with same parameters on repo https://github.com/staticdev/pdf-split-tool.

**Comment by sfdye** [comment]
Could you attach the log?

**Comment by staticdev** [comment]
@sfdye see there is no error! It is just finding more PRs than it should. What do you need exactly?

**Comment by sfdye** [comment]
I mean the output

**Comment by staticdev** [comment]
@sfdye 
>> print(pulls)
<github.PaginatedList.PaginatedList object at 0x7feed0ae5580>
>> print(pulls.totalCount)
2

Need anything else?

**Comment by s-t-e-v-e-n-k** [comment]
Your ``head`` parameter isn't formatted correctly, so GitHub is ignoring it. From the GItHub API docs: "Filter pulls by head user or head organization and branch name in the format of user:ref-name or organization:ref-name. For example: github:new-script-format or octocat:test-branch"

**Comment by s-t-e-v-e-n-k** [comment]
```
>>> repo = g.get_repo('staticdev/toml-validator')
>>> pulls = repo.get_pulls(state="open", base="master", head="staticdev:nox-mypy")
>>> list(pulls)
[PullRequest(title="Fix mypy for nox", number=98)]
```

**Comment by staticdev** [comment]
Strange.. why do I need to pass the username in the heads this way? I
created the PR using the head with just "nox-mypy".

**Comment by s-t-e-v-e-n-k** [comment]
I have no idea about the strange ideas that GitHub has, I'm just telling you why your code doesn't work. :-)

**Comment by staticdev** [comment]
@s-t-e-v-e-n-k So it may be a bug on Github API. I looked up in unit tests from PyGithub and also repositories using it and couldn't find an implementation for this filter.

**Comment by s-t-e-v-e-n-k** [comment]
@staticdev The first example is creating a pull request, those examples don't mention fetching by head. I can't see any unit test that calls `Repository.get_pulls()` with `head`.

Why should it work the way you're using it? It's completely up to GitHub what data they return, we are at their mercy. The docs at https://developer.github.com/v3/pulls/#list-pull-requests clearly mention the format required. If you want to open an issue against GitHub, feel free, but as I see it, this isn't an PyGithub issue.

**Comment by staticdev** [comment]
I see.. But, it is not coherent with the other argument which is "base". And I also agree it is not a PyGithub issue. Thanks for the headsup @s-t-e-v-e-n-k.
