### ISSUE TITLE
How to delete branch?

### ISSUE THREAD

**Issue by staticdev** [PyGithub/PyGithub#1570]
Is it possible to delete a branch by it's name? I did not see that on the docs: https://pygithub.readthedocs.io/en/latest/github_objects/Branch.html

I also did not find a way to delete it while merging a PR and there is an [open issue from 2017](https://github.com/PyGithub/PyGithub/issues/580).

**Comment by CircleOnCircles** [comment]
I also need this feature.

**Comment by staticdev** [comment]
@CircleOnCircles it is already implemented. You can have an example usage in the tool I am building to manage multiple projects here: https://github.com/staticdev/git-portfolio

**Comment by CircleOnCircles** [comment]
here is the example sniptlet if you want to do it using pygithub
```python
g = Github("[ACCESS TOKEN]")
repo = g.get_repo('COVID19-TCDG/datasets')
for b in repo.get_branches():
    if b.name.startswith('create-pull-request/patch'):
        repo.get_git_ref(f"heads/{b.name}").delete()
```
