### ISSUE TITLE
pygithub api：How to get all comments about a problem？

### ISSUE THREAD

**Issue by UNSWHARDEN** [PyGithub/PyGithub#1571]

**Comment by UNSWHARDEN** [comment]
why？
repo = g.get_repo("PyGithub/PyGithub")
#open_issues = repo.get_issues(state='open')

file = open("D:/readme.txt", "a")

for issue in repo.get_issues():
    for com in issue.get_comments():
        print(com);

result
:IssueComment(user=NamedUser(login="s-t-e-v-e-n-k"), id=646923543)
IssueComment(user=NamedUser(login="s-t-e-v-e-n-k"), id=646923716)
IssueComment(user=NamedUser(login="s-t-e-v-e-n-k"), id=646924325)
IssueComment(user=NamedUser(login="codecov-commenter"), id=645830376)
IssueComment(user=NamedUser(login="s-t-e-v-e-n-k"), id=645944479)
IssueComment(user=NamedUser(login="sfdye"), id=645947369)
IssueComment(user=NamedUser(login="s-t-e-v-e-n-k"), id=645954480)
IssueComment(user=NamedUser(login="sfdye"), id=645955740)
IssueComment(user=NamedUser(login="s-t-e-v-e-n-k"), id=646391557)


I need comments not users

**Comment by s-t-e-v-e-n-k** [comment]
You're so close! https://pygithub.readthedocs.io/en/latest/github_objects/IssueComment.html#github.IssueComment.IssueComment is the documentation for the class being returned, and the first attribute is ``body``.

**Comment by UNSWHARDEN** [comment]
Sorry, how do I get these reviews? I don't understand its API very well, can you give me an example

**Comment by UNSWHARDEN** [comment]
> 你好亲密！[https://pygithub.readthedocs.io/zh_CN/latest/github_objects/IssueComment.html#github.IssueComment.IssueComment](https://pygithub.readthedocs.io/en/latest/github_objects/IssueComment.html#github.IssueComment.IssueComment)是要返回的类的文档，第一个属性是`body`。

Sorry, how do I get these reviews? I don't understand its API very well, can you give me an example

**Comment by s-t-e-v-e-n-k** [comment]
Change ``print(com)`` to ``print(com.body)`` and that should give you the text of the issue.

**Comment by UNSWHARDEN** [comment]
> 更改`print(com)`为`print(com.body)`，它应该为您提供问题的文字。

thanks
