### ISSUE TITLE
Hexadecimal usernames fail

### ISSUE THREAD

**Issue by henrykironde** [PyGithub/PyGithub#1573]
Use  Formatted String Literals when parsing the username

**Comment by s-t-e-v-e-n-k** [comment]
Can you paste a traceback?

**Comment by henrykironde** [comment]
```python
✦ ❯ python                         
Python 3.7.6 (default, Dec 30 2019, 19:38:28) 
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import github
>>> gh = github.Github()

>>> maintainer = '0x00b1'
>>> gh.get_user(maintainer)
NamedUser(login="0x00b1")

>>> maintainer = 0x00b1
>>> gh.get_user(maintainer)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/henrykironde/Documents/GitHub/Environments/py37/lib/python3.7/site-packages/github/MainClass.py", line 256, in get_user
    assert login is github.GithubObject.NotSet or isinstance(login, str), login
AssertionError: 177
```

**Comment by s-t-e-v-e-n-k** [comment]
So this isn't a bug, this is how we do type checking -- that assertion is saying if login is passed in, it must be a string, and 0x00b1 isn't.

**Comment by henrykironde** [comment]
And that is true @s-t-e-v-e-n-k. but there are some projects using this tool and the data is in form of json or yaml, like Travis files.  where you could find something like 
```j
users:
    - henrykironde
    - 0x00000
```
These are both allowed user names on Github. 
But it will work only if we quote the usernames.
0x00000 can be a string and a hex rep. We could change the way the send requests to the api but also if you could handle it at a lower lever, that could be great so that we don't have to tell these edge case users to quote their names.

```md
users:
    - henrykironde
    - '0x00000'
```
If we open our application, the user name will not point to the GitHub user by default.

**Comment by s-t-e-v-e-n-k** [comment]
```
if not isintance(user, str):
    user = str(user)
```

in your application? I don't feel its our job to avoid an assertion error we added to make sure the type of the data is correct.
