### ISSUE TITLE
mypy stub files not always kept up to date

### ISSUE THREAD

**Issue by alex-torok** [PyGithub/PyGithub#1578]
The [PullRequest.pyi](https://github.com/PyGithub/PyGithub/blob/master/github/PullRequest.pyi) file is missing a few attributes that are present in the source. I noticed that `draft` and `maintainer_can_modify` are both missing, but there are likely more in PullRequest or other classes.

I created #1577 to fix the above problem, but wanted to file this issue to bring up the issue that there may be more, and that some sort of CI solution is likely needed to fix existing omissions and prevent future regression.

**Comment by s-t-e-v-e-n-k** [comment]
We try and keep them up to date, but sometimes things in the code change without updating the stubs. The plan I'm working towards is running mypy in strict mode, so any errors such as this are caught during CI, but we aren't there yet.

**Comment by sfdye** [comment]
we can enforce mypy strict mode in pre-commit

**Comment by s-t-e-v-e-n-k** [comment]
That is my plan -- but turning it on results in a bunch of failures, which I'm working through as I get time.
