### ISSUE TITLE
More support for Deployments

### ISSUE THREAD

**Issue by colbygallup** [PyGithub/PyGithub#1586]
I am trying to create a server that uses [GitHub Deployments](https://developer.github.com/v3/repos/deployments/) for a continuous deployment (similar to [Heroku's automatic GitHub deploys](https://devcenter.heroku.com/articles/github-integration)). PyGithub allows me to get and create deployments, but doesn't seem to support deletion or deployment statuses. Without these functions, it will be more difficult to display feedback about deployments within a repository.

Are there any existing plans to add this functionality? If not, I am willing to work on this.

**Comment by sfdye** [comment]
No plans yet, PR welcome
