### ISSUE TITLE
More than 1000 results search_repositories()

### ISSUE THREAD

**Issue by augustoolucas** [PyGithub/PyGithub#1589]
Is there a way to get more than 1000 results when searching for repositories? How could I iterate over all the existing results and not only through the first 1000?

**Comment by s-t-e-v-e-n-k** [comment]
There is not -- from the GitHub documentation for the API we're using -- "To satisfy that need, the GitHub Search API provides up to 1,000 results for each search."

**Comment by Ravineesh** [comment]
Hi @augustoolucas , did you get a workaround for this?
