### ISSUE TITLE
Since parameter not working in get_users?

### ISSUE THREAD

**Issue by DanielGorlo** [PyGithub/PyGithub#1590]
I'm trying to fetch users with pagination, and am facing issues. GitHub returns 0 results.

Here's my snippet:
`users = g.search_users('', location="Israel", since=44345425)`

When searching from the UI I see there are many results after user with id 44345425, but through PyGithub I'm just unable to fetch these.

Help please?

**Comment by s-t-e-v-e-n-k** [comment]
I can't find the documentation to hand, but if I'm remembering correctly, the ``since`` parameter is a timestamp, not an id. Searching for users named empty string is probably your issue there, but I'm not very familiar with the Search API.
