### ISSUE TITLE
Github deprecating `access_token` query parameter

### ISSUE THREAD

**Issue by xino** [PyGithub/PyGithub#1591]
<img width="1099" alt="Screenshot 2020-06-30 at 22 01 57" src="https://user-images.githubusercontent.com/65710507/86221824-4e77c680-bb7d-11ea-867b-41d28ab57aea.png">

**Comment by s-t-e-v-e-n-k** [comment]
That has to be another application causing that -- for two reasons, firstly, our User-Agent is sent as PyGithub, and second, the only authorisation we send via query string is client_id and client_secret, which we have also firmly deprecated.
