### ISSUE TITLE
[Feature Request] Display progress bar when uploading large assets

### ISSUE THREAD

**Issue by MapleCCC** [PyGithub/PyGithub#1594]
When using PyGithub to upload release assets, the script just waits for the upload to complete, and there is nothing in console that tells the progress. This could baffle some users. It would be much better to display a progress bar to indicate that something is going on.

Some existing library like [tqdm](https://github.com/tqdm/tqdm) and [progressbar2](https://github.com/WoLpH/python-progressbar) are good tools to utilize.

**Comment by jesseli2002** [comment]
Just a question - I wasn't aware that PyGithub provided the functionality to download a release asset - see #1541 and so I had to call the API myself; how are you doing it?

**Comment by MapleCCC** [comment]
@jesseli2002 Sorry, I made a mistake. It should be about uploading release assets. You are right that there is currently no release-asset download functionality provided by PyGithub.

**Comment by jd-0001** [comment]
@MapleCCC zip file example will be great 😉

**Comment by MapleCCC** [comment]
@jd-0001 The API of PyGithub is designed in a neat OOP style. So it should be easy if you try to follow the OOP mindset in a natural way. Follow is an example that creates a new release for a repository and upload an asset for this new release:

```python
from github import Github

g = Github(xxxxx)
repo = g.get_repo(xxxxx)
release = repo.create_git_release(xxxxx)
release.upload_asset(xxxxx)
```

**Comment by jd-0001** [comment]
Thanks @MapleCCC :)

**Comment by MapleCCC** [comment]
@jd-0001 I switched from distributing software through Github releases, to distributing software through PyPI. So I didn't pursue the path of programmatically managing releases and assets any further. That being said, this progress bar feature should not be too hard to implement. [tqdm](https://github.com/tqdm/tqdm) is a good tool to use for this.
