### ISSUE TITLE
module 'jwt' has no attribute 'encode'

### ISSUE THREAD

**Issue by jomach** [PyGithub/PyGithub#1595]
Hi, 

when running on python 3.8.2 with PyGithub 1.51 when I try this: 
`token = GithubIntegration(71447,'/Users/jorge/Downloads/bot.2020-07-04.private-key.pem').create_jwt() `
I get: 
`  File "/Users/jorge/.venv/dmesh-bot/lib/python3.8/site-packages/github/MainClass.py", line 802, in create_jwt
    encrypted = jwt.encode(payload, key=self.private_key, algorithm="RS256")
AttributeError: module 'jwt' has no attribute 'encode'`

Does someone have the same issue ?

**Comment by s-t-e-v-e-n-k** [comment]
Seems like jwt has changed their API -- if you ``pip install jwt==0.5.4`` in that venv does that help?

**Comment by jomach** [comment]
no. Same result as before

**Comment by jomach** [comment]
ok, I found a working solution. 
my dependencies: 
aiohttp==3.6.2
botbuilder-adapters-slack==4.9.1
botbuilder-core==4.9.1
botbuilder-dialogs==4.9.1
botbuilder-integration-aiohttp==4.9.1
botbuilder-schema==4.9.1
botframework-connector==4.9.1
certifi==2020.4.5.2
cffi==1.14.0
chardet==3.0.4
common==0.1.2
cryptography==2.8
jwt==0.5.4
PyGithub==1.51
PyJWT==1.7.1
pyparsing==2.4.7
pytest==5.4.3
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
requests==2.22.0
requests-oauthlib==1.3.0
six==1.15.0
sortedcontainers==2.2.2
urllib3==1.25.9

then I use this :
``` 
   from github import Github, GithubIntegration, InstallationAuthorization, GithubException, Consts
    private_key = None
    with open('/Users/jorge/Downloads/blabla-bot.2020-07-04.private-key.pem', 'rb') as fh:
        private_key = fh.read()
    git_integration = GithubIntegration(71447, private_key)
    app_token = git_integration.get_access_token(10267567)
```

**Comment by s-t-e-v-e-n-k** [comment]
I'm not clear on JWT at all, but I'll try and dig into this, see when JWT dropped the function we use.

**Comment by sfdye** [comment]
the package is [pyjwt](https://github.com/PyGithub/PyGithub/blob/0ca534ee1c0d6c6ddcf5f238ffe1838d75a8e082/setup.py#L102), which hasn't been updated on [PyPI](https://pypi.org/project/PyJWT/#history) for a while
