### ISSUE TITLE
get_stats_contributors gets stuck on specific repo

### ISSUE THREAD

**Issue by basnijholt** [PyGithub/PyGithub#1599]
The following call (for that repo specifically) gets stuck in an infinite loop:
```
g = Github(TOKEN)
repo = g.get_repo("basnijholt/cf-graph-countyfair").get_stats_contributors()
```

I am using Python 3.8.2 and PyGithub 1.51.

This is probably related to the "Contributors" tab not showing up at https://github.com/basnijholt/cf-graph-countyfair.
<img width="1255" alt="Screenshot 2020-07-12 at 13 05 47 1" src="https://user-images.githubusercontent.com/6897215/87244818-7817d400-c440-11ea-8665-a48ef19d4814.png">

I am not sure how to check this, but `get_stats_contributors` should raise an error whenever this is not possible.

**Comment by s-t-e-v-e-n-k** [comment]
I've dug into this, and I'm not convinced it's an infinite loop -- we send the request to GitHub, and they reply back with 202 Accepted, IE -- "We're working on it". PyGithub then sleeps for 2 seconds and makes the request again, which results in another 202.

I'm tempted to add an exception WaitTimeExceeded or such that fires after a number of 202 responses -- what do you think?

**Comment by basnijholt** [comment]
Adding an exception seems to be the correct way to handle this! 👍
