### ISSUE TITLE
Add copyright and license notice

### ISSUE THREAD

**Issue by jacquev6** [PyGithub/PyGithub#16]

**Comment by NicoHood** [comment]
Is this software GPL or LGPL now?

**Comment by spectejb** [comment]
@jacquev6 - I wanted to follow up on @NicoHood 's question.  It appears this software is dual-licensed under both GPL and LGPL where we could choose either.  Can you confirm that is true?  Thanks, in advance, for your help!

**Comment by jacquev6** [comment]
@spectejb @NicoHood I have found no indication of double licensing in the source repo. Can you please be more explicit about the confusion? I think opening a new issue would also be more visible for the current maintainers if you want more follow-up.

Just in case you're confused by the COPYING and COPYING.LESSER files, they are here because https://choosealicense.com/licenses/lgpl-3.0/ says so (paragraph "How to apply").

So my *intention* was LGPL.

**Comment by spectejb** [comment]
Thanks for adding the LGPL 3.0 license, jacquev6!  It may be helpful to delete the GPL 3.0 text as well.  

Appreciate the clarification!
