### ISSUE TITLE
github.__version__ is missing

### ISSUE THREAD

**Issue by basnijholt** [PyGithub/PyGithub#1600]
This is very standard, see https://www.python.org/dev/peps/pep-0396/

**Comment by s-t-e-v-e-n-k** [comment]
Sort of. It is very much optional, based on even the content of that PEP.

**Comment by basnijholt** [comment]
Everything is optional, however, right now there is no option to check the version inside of your code, which is kind of suboptimal.

**Comment by s-t-e-v-e-n-k** [comment]
I'm still trying to understand your use case. Are you checking for API support by attempting checking the version in your code, or for example not using something like ``hasattr()``?

**Comment by basnijholt** [comment]
After importing the code, it is often useful to print the version.

`pip list` might not point to the correct version.

I ran into this when reporting on https://github.com/PyGithub/PyGithub/issues/1599 and having trouble finding out which version I was using.

**Comment by pllim** [comment]
I also wish to print out the version that is used and came across this issue. With `setuptools_scm` available now, should be easier to implement?
