### ISSUE TITLE
Help accessing issue event body

### ISSUE THREAD

**Issue by MarinaWyss** [PyGithub/PyGithub#1604]
Hi there, I am a bit stuck and would love some help if possible.

I am trying to access the date that an issue was opened/closed. I believe I should do this through the issue events, but so far I have only been able to see a list of issue events with ids (like `IssueEvent(id=2633664990)`). I saw that in some cases calling `.body` works to access the content itself, but that doesn't seem to be the solution here. 

Any ideas? Here is basically what I am doing:

```
repo = Github.get_repo("some_repo")
issues = repo.get_issues()

for issue in issues:
    for event in issue.get_events():
        print(event)
```

Thank you :)

**Comment by jesseli2002** [comment]
[Issues](https://pygithub.readthedocs.io/en/latest/github_objects/Issue.html#github.Issue.Issue) have the `created_at`, `updated_at`, and `closed_at` properties - does that work?

**Comment by MarinaWyss** [comment]
Yes, this is all I needed! Thanks so much for your quick help :)
