### ISSUE TITLE
get_user does not support retrieving user information by ID

### ISSUE THREAD

**Issue by natanlao** [PyGithub/PyGithub#1615]
I'm writing a script that interfaces with both ZenHub and GitHub (using PyGithub). ZenHub only identifies users by their user id (databaseId), so if I want to find the name of the user associated with an id, I have to query GitHub's API. There's an 
[undocumented endpoint](https://stackoverflow.com/questions/11976393/get-github-username-by-id) for this (`/user/:id`). 

A quick example. (My user id is 23219746.) I'm on `PyGithub==1.43.5` but I can see this is still the case on v1.51.

```pycon
>>> import github
>>> g = github.Github("...")
>>> g.get_user(g.get_user().id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/natan/DataBiosphere/azul/.venv/lib/python3.8/site-packages/github/MainClass.py", line 226, in get_user
    assert login is github.GithubObject.NotSet or isinstance(login, str), login
AssertionError: 23219746
```

Does PyGithub support undocumented endpoints? If so, it seems trivial to add support for this:

```diff
diff --git a/github/MainClass.py b/github/MainClass.py
index cadd1ff5..b450492a 100644
--- a/github/MainClass.py
+++ b/github/MainClass.py
@@ -261,18 +261,25 @@ class Github(object):
         :param login: string
         :rtype: :class:`github.NamedUser.NamedUser` or :class:`github.AuthenticatedUser.AuthenticatedUser`
         """
-        assert login is github.GithubObject.NotSet or isinstance(login, str), login
+        assert login is github.GithubObject.NotSet or isinstance(login, str) or isinstance(login, int), login
         if login is github.GithubObject.NotSet:
             return AuthenticatedUser.AuthenticatedUser(
                 self.__requester, {}, {"url": "/user"}, completed=False
             )
-        else:
+        elif isinstance(login, str):
             headers, data = self.__requester.requestJsonAndCheck(
                 "GET", "/users/" + login
             )
             return github.NamedUser.NamedUser(
                 self.__requester, headers, data, completed=True
             )
+        else:
+            headers, data = self.__requester.requestJsonAndCheck(
+                "GET", "/user/" + login
+            )
+            return github.NamedUser.NamedUser(
+                self.__requester, headers, data, completed=True
+            )
 
     def get_users(self, since=github.GithubObject.NotSet):
         """
```

**Comment by s-t-e-v-e-n-k** [comment]
If we were to do this, it would be via another method, MainClass.get_user_by_id() or such -- are you certain the endpoint is undocumented?

**Comment by natanlao** [comment]
> are you certain the endpoint is undocumented?

If there is documentation, I have not been able to find it. The closest is [`GET /users/{username}`](https://docs.github.com/en/rest/reference/users#get-a-user). There are endpoints of the form `GET /user/...` but none as described in this issue.

**Comment by wrecker** [comment]
@natanlao Github now allows numerical usernames, so the `/user/:id` will return unpredictable results if there exists a username that is the same as the `:id` you are querying for. For e.g I just went ahead and created a github account with username `23219746`. 
`curl https://api.github.com/users/23219746`

**Comment by natanlao** [comment]
@wrecker The endpoint seems to work as expected. The `GET /users/{username}` endpoint queries by username and the `GET /user/{userid}` endpoint (note the dropped `s`) queries by user id.

```console
$ http get https://api.github.com/user/23219746 | jq .login
"natanlao"
$ http get https://api.github.com/users/23219746 | jq .login
"23219746"
$ http get https://api.github.com/users/natanlao | jq .login
"natanlao"
$ http get https://api.github.com/users/23219746 | jq .login
"23219746"
```

**Comment by wrecker** [comment]
@natanlao Good point. I completely missed the 's' in the API endpoints!
