### ISSUE TITLE
get_assets not returning assets

### ISSUE THREAD

**Issue by ikawaljeet** [PyGithub/PyGithub#1618]
I am trying to download assets from my private repo. I am able to get the latest relast but i am not getting list of assets. 

code snippet is given below:

    github = Github(token)
    organization = github.get_organization(org)
    repository = organization.get_repo(repo)
    print("repo: {}".format(repository))
    releases = repository.get_releases()
    print("releases: {}".format(list(releases)))
    latestrelease = repository.get_latest_release()
    print("latest release: {}".format(latestrelease))
    assets = latestrelease.get_assets()
    print("assets: {}".format(list(assets)))
   
Output
repo: Repository(full_name="skywalkerInc/SharpenTheAxe")
releases: [GitRelease(title="FirstRelease")]
latest release: GitRelease(title="FirstRelease")
assets: []

Please help.

**Comment by hippocritical** [comment]
got the same issue, tried for hours until searching if this was a bug...
Fix pls? :(
