### ISSUE TITLE
Get status of checks on a Pull Request

### ISSUE THREAD

**Issue by ChaiBapchya** [PyGithub/PyGithub#1621]
Currently, PyGithub API doesn't allow to check for status of the checks run on a PR.

For e.g. in case of a PR https://github.com/apache/incubator-mxnet/pull/18785
There are 12 status checks.
There should be an API that exposes the status of each of those 12 checks or overall status of that PR.

**Comment by ChaiBapchya** [comment]
Related issue https://github.com/PyGithub/PyGithub/issues/1063

**Comment by wrecker** [comment]
@s-t-e-v-e-n-k @sfdye I have made significant progress on implementing the Github Checks API. For now I have most of the READ actions implemented based on this: https://docs.github.com/en/rest/reference/checks

- [x] CheckSuite
- [x] CheckRun
- [ ] CheckRunOutput
- [ ] CheckRunAnnotation
- [ ] GithubApp

Whats your preferred way of sending PRs? One big monolith PR (with individual commits) or split PRs?

**Comment by sfdye** [comment]
Of course individual PR is easier to review, but both are welcome

**Comment by wrecker** [comment]
@sfdye The first of the PRs is in.

**Comment by cristianmtr** [comment]
Is this available? I can't find it

**Comment by ChaiBapchya** [comment]
Don't think its supported yet. There was some PR opened on aug 2 but got closed. so ya.. we're all waiting :)

**Comment by Croydon** [comment]
Please re-ope this then :)

**Comment by Seluj78** [comment]
Hey ! If you upgrade to `1.54`, check suite and runs are supported !

If you want an example, I use it here: https://github.com/AFPy/PyDocTeur/pull/47

**Comment by ChaiBapchya** [comment]
While I can see check-suites works with 1.54
I can see that the number returned is incorrect
For example:
For this commit: https://github.com/apache/incubator-mxnet/pull/18785/commits/232538f4f4f704fd5d01b97b66655bab5393942b
There were 14 checks made.
But the result returned by the api for this specific commit is: 
```
>>> commit
Commit(sha="232538f4f4f704fd5d01b97b66655bab5393942b")
>>> for a in cs:
...      print(a)
...
CheckSuite(url="https://api.github.com/repos/apache/incubator-mxnet/check-suites/1063117829", id=1063117829)
CheckSuite(url="https://api.github.com/repos/apache/incubator-mxnet/check-suites/1064967098", id=1064967098)
```

**Comment by s-t-e-v-e-n-k** [comment]
That is a Check Suite (That is, a suite of checks), which contains a number of Check Runs, and you'll probably find each CheckSuite has 7 CheckRuns.

**Comment by ChaiBapchya** [comment]
Closing since the issue is resolved! Thanks everyone involved in this issue & corresponding PRs!
