### ISSUE TITLE
Paginatoin for the get_contents function?

### ISSUE THREAD

**Issue by guitaristtom** [PyGithub/PyGithub#1626]
Hi, I'm trying to list the contents of a directory in a Github project, the only issue I'm running in to is that it is maxing out at 1000 entries. I know that the Github API has pagination support, but I tried adding `page=2` to the `get_contents()` function, but it just errors out. 

How would I go about adding pagination or loading the next set of values from the get_contents function?
```
        repo = self.github.get_repo("<repo>")
        contents = repo.get_contents("<folder>")
        for file in contents:
            print(file.path)
```

**Comment by s-t-e-v-e-n-k** [comment]
From the GitHub API documentation: "This API has an upper limit of 1,000 files for a directory. If you need to retrieve more files, use the Git Trees API." That API is using the Repository.get_git_tree() endpoint.

**Comment by guitaristtom** [comment]
Hmm, interesting. 

I guess I haven't used the API since v2 and they changed that. Thank you.
