### ISSUE TITLE
[Example] Full example of commit multiple file

### ISSUE THREAD

**Issue by xpdable** [PyGithub/PyGithub#1628]
I am moving from gitlab to github.
We use https://github.com/python-gitlab/python-gitlab as the library
To make a commit for multiple files we use exactly this example: https://python-gitlab.readthedocs.io/en/stable/gl_objects/commits.html

I find create_git_commit would do the same thing in github but lack of docs.
Could someone help to provide an example of creating those Tree etc.. staffs ?

Thanks very much.

**Comment by xpdable** [comment]
well, finally I end up with the full process... hopefully will share later...

**Comment by xpdable** [comment]
Here is a full example abstracted from my real usage:
I get a lot hints from this https://github.com/PyGithub/PyGithub/issues/863#issuecomment-517927446

To commit to master branch
```python
import github
g = github.Github(base_url="https://git.mycompany.com/api/v3",login_or_token="mytoken")
repo = g.get_repo('myorg/myrepo')
# you can read file content into blob, here just use str for example
blob1 = repo.create_git_blob("file-content", "utf-8")
element1 = github.InputGitTreeElement(path="path-in-repo.ext", mode='100644', type='blob', sha=blob1.sha)
blob2 = repo.create_git_blob("file-content2", "utf-8")
element2 = github.InputGitTreeElement(path="folder/path-in-repo.ext", mode='100644', type='blob', sha=blob2.sha)
head_sha = repo.get_branch('master').commit.sha
base_tree = repo.get_git_tree(sha=head_sha)
tree = repo.create_git_tree([element1, element2], base_tree)
parent = repo.get_git_commit(sha=head_sha)
commit = repo.create_git_commit("commit_message", tree, [parent])
master_refs = self.github_repo.get_git_refs().get_page(0)
master_ref = None
# I guess here is a bug/issue I will address it in another new issue
for ref in master_refs:
    if ref.ref == "refs/heads/{}".format("master"):
        master_ref = ref
master_ref.edit(sha=commit.sha)
```

**Comment by raphodn** [comment]
I wanted to do something similar (i.e. commit multiple files at once), but this time in a branch. Below is working code (let me know if it can be optimised though)

```
import github
g = github.Github("mytoken")
repo = g.get_repo('myorg/myrepo')

blob1 = repo.create_git_blob("file-content", "utf-8")
element1 = github.InputGitTreeElement(path="path-in-repo.ext", mode='100644', type='blob', sha=blob1.sha)
blob2 = repo.create_git_blob("file-content2", "utf-8")
element2 = github.InputGitTreeElement(path="folder/path-in-repo.ext", mode='100644', type='blob', sha=blob2.sha)

head_sha = repo.get_branch('master').commit.sha

# everything above is identical to @xpdable 
# but here I create the branch
branch = repo.create_git_ref(ref=f"refs/heads/branch-name", sha=head_sha)
branch_sha = repo.get_branch("branch-name").commit.sha

# similar to @xpdable but replacing head_sha with branch_sha
base_tree = repo.get_git_tree(sha=branch_sha)
tree = repo.create_git_tree([configuration_element, stats_element], base_tree)
parent = repo.get_git_commit(sha=branch_sha)
commit = repo.create_git_commit("commit_message", tree, [parent])
branch_refs = repo.get_git_ref("heads/branch-name")
branch_refs.edit(sha=commit.sha)

# optional : open a PR with the new branch
repo.create_pull(title="PR title", body="PR body", base="master", head="branch-name")
```

**Comment by abulka** [comment]
Any advice on how to delete files as part of such multiple file commits? 

Some posts talk about creating new trees with references to paths with null sha's, or modifying existing trees incl. ideas about looping and finding all references to the deleted blobs?
- https://stackoverflow.com/questions/23637961/how-do-i-mark-a-file-as-deleted-in-a-tree-using-the-github-api
- https://stackoverflow.com/questions/55786299/delete-multiple-files-from-github-api
- https://gist.github.com/gjtorikian/5208350

**Comment by josecelano** [comment]
> I wanted to do something similar (i.e. commit multiple files at once), but this time in a branch. Below is working code (let me know if it can be optimised though)
> 
> ```
> import github
> g = github.Github("mytoken")
> repo = g.get_repo('myorg/myrepo')
> 
> blob1 = repo.create_git_blob("file-content", "utf-8")
> element1 = github.InputGitTreeElement(path="path-in-repo.ext", mode='100644', type='blob', sha=blob1.sha)
> blob2 = repo.create_git_blob("file-content2", "utf-8")
> element2 = github.InputGitTreeElement(path="folder/path-in-repo.ext", mode='100644', type='blob', sha=blob2.sha)
> 
> head_sha = repo.get_branch('master').commit.sha
> 
> # everything above is identical to @xpdable 
> # but here I create the branch
> branch = repo.create_git_ref(ref=f"refs/heads/branch-name", sha=head_sha)
> branch_sha = repo.get_branch("branch-name").commit.sha
> 
> # similar to @xpdable but replacing head_sha with branch_sha
> base_tree = repo.get_git_tree(sha=branch_sha)
> tree = repo.create_git_tree([element1, element2], base_tree)
> parent = repo.get_git_commit(sha=branch_sha)
> commit = repo.create_git_commit("commit_message", tree, [parent])
> branch_refs = repo.get_git_ref("heads/branch-name")
> branch_refs.edit(sha=commit.sha)
> 
> # optional : open a PR with the new branch
> repo.create_pull(title="PR title", body="PR body", base="master", head="branch-name")
> ```


I think the line:
```
tree = repo.create_git_tree([configuration_element, stats_element], base_tree)
```
should be replaced by:
```
tree = repo.create_git_tree([element1, element2], base_tree)
```

I have created a full example here: https://github.com/josecelano/pygithub/blob/main/src/04_sign_commit_with_multiple_files_using_github_api.py

**Comment by raphodn** [comment]
Thanks for the heads up @josecelano , i fixed my example :ok_hand:

**Comment by bauergeorg** [comment]
Hi, do sombody know how it works with git-lfs?

**Comment by felipinbombin** [comment]
Hi! I had the same question as @abulka (how to delete a file in a commit with multiple changes), and I found the solution. To delete a file you have to create an `InputGitTreeElement` with `sha` param with value `None`.

Here is an example of deleting a file:
```python
from github import Github, InputGitTreeElement

github_repository_name='org/repo-name'
branch_name='branch-name'
commit_message='delete file'

g = Github('GITHUB_ACCESS_TOKEN')

repo_obj = g.get_repo(github_repository_name)

head_sha = repo_obj.get_branch(branch_name).commit.sha
base_tree = repo_obj.get_git_tree(sha=head_sha)
changes = []

element = InputGitTreeElement(path='path/to/file/in/repo', mode='100644', type='blob', sha=None) # here is the magic
changes.append(element)

new_tree = repo_obj.create_git_tree(changes, base_tree)
parent = repo_obj.get_git_commit(sha=head_sha)

commit = repo_obj.create_git_commit(commit_message, new_tree, [parent])
branch_refs = repo_obj.get_git_ref('heads/{0}'.format(branch_name))
branch_refs.edit(sha=commit.sha)
```

I hope this can be useful!
