### ISSUE TITLE
GithubException type-checking problem

### ISSUE THREAD

**Issue by staticdev** [PyGithub/PyGithub#1630]
I am having a hard time to get a good solution for type-checking when I have GithubException given this interface:

https://github.com/PyGithub/PyGithub/blob/6eba4506d4d44892c5e224054b809003fc3326f6/github/GithubException.pyi

Let me use give a practical use example to reproduce:

```
import github # PyGithub
g = github.Github("access_token")
github_repo = "staticdev/git-portfolio"
repo = g.get_repo(github_repo)
try:
    created_pr = repo.create_pull(
        title="title", body="body", head="head", base="base", draft=False,
    )
except github.GithubException as github_exception:
    extra = ""
    for error in github_exception.data["errors"]:
        if "message" in error:
            extra += f"{error['message']} "
        else:
            extra += f"Invalid field {error['field']}. "
```

When I check this code with mypy for example I get the errors:

```
src/git_portfolio/mypy.py:13:31: error: Invalid index type "str" for "Union[str, Dict[str, str]]"; expected type "Union[int, slice]"  [index]
                extra += f"{error['message']} "
                                  ^
src/git_portfolio/mypy.py:15:45: error: Invalid index type "str" for "Union[str, Dict[str, str]]"; expected type "Union[int, slice]"  [index]
                extra += f"Invalid field {error['field']}. "
```

Proposed solution: after opening an [issue on Mypy](https://github.com/python/mypy/issues/9221), @Akuli suggested using [TypedDict](https://www.python.org/dev/peps/pep-0589/) which I found great.

**Comment by s-t-e-v-e-n-k** [comment]
This seems to include ``error`` is still a list inside the loop based on my reading? Are you able to perform a little more debugging on what variables are what types?

**Comment by staticdev** [comment]
@s-t-e-v-e-n-k the problem is that github.GithubException.data is defined as a Dict of Union[str, List[str]] but the "errors" field in data is always going to be a List never a string. That is why you can use TypedDict to define data and say that specifically "errors" is a List.

Since you support Python 3.5 and 3.6 you the [backport](need https://pypi.org/project/typing-extensions/) to make use of TypedDict.

**Comment by s-t-e-v-e-n-k** [comment]
From my reading of the code, ``data`` is defined as ``Dict[str, Union[str, List[str], List[Dict[str, str]]]]`` which to my reading is a dictionary with str keys, and the value being either a str, a list of str or a list of dictionaries of str, str ... I'm going to dig into this more.

**Comment by s-t-e-v-e-n-k** [comment]
I think the type checking is correct -- errors is a list, and message is not contained underneath it. For example: https://github.com/PyGithub/PyGithub/blob/master/tests/Branch.py#L87

**Comment by staticdev** [comment]
@s-t-e-v-e-n-k errors IS a list, the problem is that from your interface "errors" is not a list, but a Union[str, List[str]]. It can't assume it is a list because Mypy give errors.

**Comment by s-t-e-v-e-n-k** [comment]
@staticdev That was exactly my point. It is a list, but your code is treating it like a dictionary, so of course type validation fails.errors is either a string, or a list of strings, it doesn't contain members like your code has.

**Comment by staticdev** [comment]
@s-t-e-v-e-n-k how am I treating `errors` like a dictionary? I am just iterating over it as a list:

```for error in github_exception.data["errors"]:```

Can you give me an example where github_exception.data["errors"] is a string? I double checked it and didn't find a case.

**Comment by s-t-e-v-e-n-k** [comment]
``extra += f"{error['message']} "`` which is in fact the line that type checking is erroring on.
