### ISSUE TITLE
[Question] commit_id of a specific file inside the repo

### ISSUE THREAD

**Issue by Dreadnut93** [PyGithub/PyGithub#1632]
Is it possible to obtain the latest commit_id of a specific file in my repo?  From the ContentFile object I am able to extract the sha which is different from the commit_id the given file has.

**Comment by s-t-e-v-e-n-k** [comment]
A commit points to a tree, which contains a list of files, so files themselves don't have a commit sha1. What is the actual problem you're trying to solve?

**Comment by Dreadnut93** [comment]
@s-t-e-v-e-n-k  I am working on the traceability and reproducibility of machine learning experiments.  I specifies which files + commit_ids i  would like to use to run the ML job and save this info in a database so that I can always know which files I used to train my model. It is implemented in a way that if the user does not specify a commit id it I would like to find the latest commit and save it in the database. Currently, I am taking the commit id of the master repo but it is not tha optimal.

**Comment by s-t-e-v-e-n-k** [comment]
Just as an idea, perhaps the sha links to the tree?

**Comment by Dreadnut93** [comment]
@s-t-e-v-e-n-k  Is it possible to accees the tree from the ContentFile sha?
