### ISSUE TITLE
Typing error on Github.search_issues

### ISSUE THREAD

**Issue by silasary** [PyGithub/PyGithub#1633]
7b20b13d0b853e813b201edf1daf159ca8bc983f set the type of all kwargs to `Dict[str, Any]`. This is incorrect, as `repo` is `str`.

My assumption is that the author of #1517 didn't understand the the way typed **kwargs work, and meant to simply assign it to `Any`.

Mypy error message: `error: Argument "repo" to "search_issues" of "Github" has incompatible type "str"; expected "Dict[str, Any]"  [arg-type]`

**Comment by s-t-e-v-e-n-k** [comment]
That was me, and I thought it was how kwargs typing worked. :-( I was expecting typing to parse the remaining args as a dictionary -- shall I set it to Any, or something else?

**Comment by silasary** [comment]
Yeah, **kwargs are always `Dict[str, T]`, so you only give it the `T`.

Probably Any, as qualifiers vary in what they accept.
