### ISSUE TITLE
Repository.create_pull typing regression

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [PyGithub/PyGithub#1634]
From PR #1581:

error: No overload variant of "create_pull" of
"Repository" matches argument types "str", "str", "str", "str"  [call-overload]
            pr = gh.get_repo(REPO).create_pull(
                 ^
note: Possible overload variants:
note:     def create_pull(self, title: str, body: str, base: str, head: str, maintainer_can_modify: Union[bool, _NotSetType], draft: bool, issue: _NotSetType) -> PullRequest
note:     def create_pull(self, title: _NotSetType, body: _NotSetType, base: str, head: str, maintainer_can_modify: _NotSetType, draft: bool, issue: Issue) -> PullRequest

It was fine with PyGithub v1.51 but failed in PyGithub v1.52.

My code is the following...

pr = gh.get_repo(REPO).create_pull(
    title,
    "This PR has been automatically created by insights-services.",
    "master",
    branch_name,
)

**Comment by s-t-e-v-e-n-k** [comment]
@dashmug I've pulled your comment into a new issue so we can discuss it here.

**Comment by dashmug** [comment]
@s-t-e-v-e-n-k Thanks.

**Comment by s-t-e-v-e-n-k** [comment]
branch_name is a string in this case, I'm guessing?

**Comment by s-t-e-v-e-n-k** [comment]
That should match the first one, I suspect the draft bool should also be a Union of bool, _NotSetType.

**Comment by dashmug** [comment]
@s-t-e-v-e-n-k  I've tested the changes in #1635 and it has fixed my specific issue. Thank you.
