### ISSUE TITLE
Implement __len__ for PaginatedListBase

### ISSUE THREAD

**Issue by wdawson** [PyGithub/PyGithub#164]
Not sure if I'm missing something, but it might be nice to get the length of a Paginated List. Sorry if I'm not seeing how this is already implemented.

**Comment by MichaelPereira** [comment]
@jacquev6 Is it still the recommended way of getting the size of list if not provided by another object? Or can it be replaced by the `total_count` property introduced in 9a51a61e3fe6eebf68307305991ea89039d956e1 as part of #224?
