### ISSUE TITLE
1.52 started giving no overload invariant to Repository.create_pull

### ISSUE THREAD

**Issue by staticdev** [PyGithub/PyGithub#1640]
This issue is related to: #1634

After this one was fixed, I started getting the same error on a code that didn't have it:

https://github.com/staticdev/git-portfolio/pull/53/checks?check_run_id=943684564

The call is being made by passing: 

```
repo.create_pull(
                title="title", body="body" head=pr.head, base=pr.base, draft=True,
            )
```

I think the problem I given by the removal of `draft: bool` on line 186:

https://github.com/PyGithub/PyGithub/commit/5ad091d0182a7abd0dd7da51fc6dc727fc4bb82d

**Comment by s-t-e-v-e-n-k** [comment]
Does that still not validate against master? Based on your code and assuming ``pr.head`` and ``pr.base`` are strings, and some quick checking, it should befine.

**Comment by staticdev** [comment]
Yes, both strings @s-t-e-v-e-n-k. The code was already working and checking on 1.51.

**Comment by s-t-e-v-e-n-k** [comment]
@staticdev You didn't answer my question though -- have you checked against master, since I get this:

```
% cat /tmp/tmp.xjC9uVmD5q 
from github import Github

g = Github("token")
repo = g.get_repo("reponame")
repo.create_pull(title="title", body="body", head="head", base="base", draft=True)
% mypy /tmp/tmp.xjC9uVmD5q
Success: no issues found in 1 source file
```

**Comment by staticdev** [comment]
@s-t-e-v-e-n-k it seems to be fixed on master.

**Comment by s-t-e-v-e-n-k** [comment]
Excellent! I'm going to close this, and I'll be making a release tomorrow or Satuday. Thanks for checking!
