### ISSUE TITLE
[Bug- Known issue still not fixed] wrong 'last-modified' #629

### ISSUE THREAD

**Issue by Dreadnut93** [PyGithub/PyGithub#1642]
Creating a new issue since the old one was closed without solving the problem. The solution was proposed in Fixed File.last_modified attribute #1032 but never merged to master.

**Comment by s-t-e-v-e-n-k** [comment]
I wasn't involved then, but that PR is fixing it the wrong way. Since ContentFile is a subclass of GithubObject, that method can just be overridden in ContentFile -- it should also check to see those attributes are unset, and requires a test. Would you like a shot at tackling this?

**Comment by wrecker** [comment]
@s-t-e-v-e-n-k I took a crack at this fix. in PR #1652

**Comment by jounathaen** [comment]
Hi, I think the bug still persists but all of the  fixes are marked stale. Therefore I'd suggest to re-open this.
