### ISSUE TITLE
No exception while inti Github with invalid base url and given wrong output on its methods

### ISSUE THREAD

**Issue by xpdable** [PyGithub/PyGithub#1644]
I happened to use `https://git.mycompany.com/` to init github.Github other than `https://git.mycompany.com/api/v3/`.
However, seems not validation is invoked and an object is well returned `<github.MainClass.Github object at 0x7fd61c9c0d68>`
Then its method will perform strangely. for example any `get_repo('whateverrepo')` will return `Repository(full_name=None)` other than an exception `github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://developer.github.com/enterprise/2.21/v3/repos/#get"}`

**Comment by s-t-e-v-e-n-k** [comment]
Yes, we don't attempt any URL validation when creating the Github() instance, but only on the first fetch, such as your get_repo() call. Are you able to try again with debugging on? I'm curious what response get_repo() is getting.

**Comment by xpdable** [comment]
> Yes, we don't attempt any URL validation when creating the Github() instance, but only on the first fetch, such as your get_repo() call. Are you able to try again with debugging on? I'm curious what response get_repo() is getting.

Ok below is the debugging script:
```python
class Issue1644(unittest.TestCase):

    def testInvalidateInitURLThenGetRepo(self):
        g = Github(base_url="https://git.mygheurlwithoutapiv3suffix.com/", login_or_token="whateverrightorwrong")
        repo = g.get_repo("myorg/myrepo")  # Debug goes into steps here
        print(repo.full_name)
        assert repo.full_name == 'myorg/myrepo'
```
Then the raw request finally goes to [`Requester.py Line 513` ]() while the response is as below:
![image](https://user-images.githubusercontent.com/2903719/89769814-68b7a380-db30-11ea-9f7d-8b36618181d7.png)
So obviously the url is not correct but no so wrong which leads to `302`
Next into the return phase: The data of 302 content response is passing to `Repository` initialzation.
![image](https://user-images.githubusercontent.com/2903719/89770457-61dd6080-db31-11ea-9e99-19047048a285.png)
Then the Repository with all `None` is generated
![image](https://user-images.githubusercontent.com/2903719/89770308-2a6eb400-db31-11ea-8783-d3c49aea853e.png)

**Comment by xpdable** [comment]
So after some other test, if your `base_url` is responing something you will get an all `None` repo after your then invoke `get_repo('xxxx')`.
if your `base_url` is totally wrong and not reachable, you will get connection exception.

**Comment by s-t-e-v-e-n-k** [comment]
Thank you for the debugging -- so I think there's something else running at the root of that website, since it redirects with a 302 to a login page. Due to some other fun and games with GitHub's responses, we can't assume everything is JSON, so we try our best to deal with odd responses, and that is what is causing this odd behaviour. If it gave a 404 or something other 4xx error code, then you would get an exception, but only first method call, not initialisation, since we don't make any requests at that point.

**Comment by xpdable** [comment]
> Thank you for the debugging -- so I think there's something else running at the root of that website, since it redirects with a 302 to a login page. Due to some other fun and games with GitHub's responses, we can't assume everything is JSON, so we try our best to deal with odd responses, and that is what is causing this odd behaviour. If it gave a 404 or something other 4xx error code, then you would get an exception, but only first method call, not initialisation, since we don't make any requests at that point.

That is very resaonable. Just quick mind if add a parameter in the initilaztion to flag whether do validation, e.g. `Github(base_url='xxx', login_or_token='ttt', validate=True)` and maybe default to False. And to validate, just check if a `g.get_user()` returning non None object.
