### ISSUE TITLE
pullrequest missing `rebaseable` property

### ISSUE THREAD

**Issue by neo-liang-sap** [PyGithub/PyGithub#1651]
Hello, 
Currently in pullrequest.py there's no `rebaseable` property, from github api spec https://docs.github.com/en/rest/reference/pulls#mergability you can see `rebaseable` exist, is there any plan to add this property in future?

BTW one question related to this, if i want to check whether a pullrequest needs rebase, the only thing i can check is
```
pullrequest.mergeable_state == 'dirty' && pullrequest.mergeable == False
```
am i right?

Thanks!

**Comment by s-t-e-v-e-n-k** [comment]
Closed via merging #1690
