### ISSUE TITLE
Is there any user suggestions endpoint? 

### ISSUE THREAD

**Issue by nk521** [PyGithub/PyGithub#1653]
To get a list of suggested mentionable users in a comment box (look at attached image) github web uses `https://github.com/suggestions` url. But is there any method available for this?

![image](https://user-images.githubusercontent.com/30789322/90096954-6d5ba200-dd52-11ea-90fc-897b2830d5da.png)

**Comment by s-t-e-v-e-n-k** [comment]
That isn't an RESTful endpoint, and I can't find anything like what you want in the API documentation either. Sorry.
