### ISSUE TITLE
pullrequest.get_review_requests() not returning people who joined as reviewer

### ISSUE THREAD

**Issue by neo-liang-sap** [PyGithub/PyGithub#1654]
Hi, 
say we have a PR which owner request review from 'A', and then 'B' joined as reviewer.
Then when i create an api request like:
```
userlist,teamlist=pullrequest.get_review_requests()
```
only `A` in `userlist`, `B` is not there

`B` should also be exist in `userlist`

**Comment by s-t-e-v-e-n-k** [comment]
This is up to the data that GitHub returns -- review requests are asking people for reviews, if B joined themselves, there wouldn't be a review request generated.

**Comment by neo-liang-sap** [comment]
Hi @s-t-e-v-e-n-k , thanks for the explanation, i totally understand it.
Is there any api i can use to get full list of reviewers in a PR? contains both who joined as reviewer and asked for review
