### ISSUE TITLE
create_pull fails when trying to associate issue

### ISSUE THREAD

**Issue by BigTheta** [PyGithub/PyGithub#1659]
I am trying to create a pull request with an associated issue such that closing the pull request will close the issue. 

I am using:

```
issue = (gh.create_issue(title="Merge branch "+args.branch,body=output.decode("utf-8")))
pr = gh.create_pull("Merge branch "+args.branch,body="Closes 
"+str(issue.number),issue=issue,base="main",head=args.bran
```

when running the above i get:

`TypeError: __create_pull_1() got an unexpected keyword argument 'issue'`

I am working off the create_pull documentation in: https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html

**Comment by s-t-e-v-e-n-k** [comment]
The ``issue`` argument for ``Repository.create_pull()`` is about using the issue for the body of the PR, not linking it. Sorry, the docs could be clearer here. Don't include the ``issue`` argument, everything else is fine.

**Comment by BigTheta** [comment]
I see. 

I was able to accomplish what we wanted by putting "Closes #<issue>" in the body argument. I did not realize that the base needed to default branch for the linked issue functionality to work. 

Thank you for responding.
