### ISSUE TITLE
ModuleNotFoundError error seen using github

### ISSUE THREAD

**Issue by allegit** [PyGithub/PyGithub#1664]
When I run my python program that does the following import:

`from github.MainClass import Github`

I get the the below error:

ModuleNotFoundError: No module named 'github'

It does not matter if use `from github import Github`, I get the same error. I've the PyGithub module installed locally as well as globally, but this does not seem to alter the problem. My syspath is:

`$ python3 -m site
sys.path = [
    '/Users/vasanth/repos',
    '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python37.zip',
    '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7',
    '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/lib-dynload',
    '/Users/vasanth/Library/Python/3.7/lib/python/site-packages',
    '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages',
    '/Library/Python/3.7/site-packages',
]
USER_BASE: '/Users/vasanth/Library/Python/3.7' (exists)
USER_SITE: '/Users/vasanth/Library/Python/3.7/lib/python/site-packages' (exists)
ENABLE_USER_SITE: True`

There are three reasons for a ModuleNotFoundError:

1. The name of the module is incorrect.
2. The path of the module is incorrect.
3. The Library Module not installed

When I go to the Python interpreter prompt and try this, I get the below:

```
>>> import github.MainClass
>>> github.MainClass.__file__
'/Users/vasanth/Library/Python/3.7/lib/python/site-packages/github/MainClass.py'
```

It is very bizarre that it can't find from my program.

**Comment by s-t-e-v-e-n-k** [comment]
Is your script called 'github' by any chance? If so, that would cause this issue.

**Comment by allegit** [comment]
No, it is not called by that name.

**Comment by s-t-e-v-e-n-k** [comment]
Have you tried debugging from the script itself, by checking sys.path and so on inside the script? Your Python environment looks correct at least.

**Comment by s-t-e-v-e-n-k** [comment]
As a further thing to check, compare your shebang for the script versus ``which python3``, the Python setup on OS X is a little odd.
