### ISSUE TITLE
NEW Project using PyGitHub: GSIL

### ISSUE THREAD

**Issue by FeeiCN** [PyGithub/PyGithub#1665]
GitHub HomePage: https://github.com/FeeiCN/GSIL
GSIL is Monitor Github sensitive information leaks in near real time and send alert notifications.

**Comment by s-t-e-v-e-n-k** [comment]
Thanks for letting us know!

**Comment by FeeiCN** [comment]
@s-t-e-v-e-n-k I mean hope you add to https://pygithub.readthedocs.io/en/latest/introduction.html#projects-using-pygithub , thanks!
