### ISSUE TITLE
How to close a pull request?

### ISSUE THREAD

**Issue by dilipvinu** [PyGithub/PyGithub#1672]
Hi, can someone tell me how an open pull request can be closed and associated branch be deleted? Thanks.

**Comment by s-t-e-v-e-n-k** [comment]
It depends what you mean by close -- if you mean merge, there's a method for that, actually closing like the button on the Web UI I daresay is done by by fetching the PR as an issue and closing it, but I've not tested it.

**Comment by s-t-e-v-e-n-k** [comment]
Deleting the branch requires fetching the branch name and calling ``delete_git_ref()`` on the repo.

**Comment by dilipvinu** [comment]
Thanks @s-t-e-v-e-n-k !
