### ISSUE TITLE
Include failed requests in debug log

### ISSUE THREAD

**Issue by salomvary** [PyGithub/PyGithub#1673]
It would be nice if Requester's debug logger logged requests that failed "below" HTTP level, eg. TCP connection failed.

If the request fails there is currently nothing logged (except a stack trace which does not tell what the attempted request was): https://github.com/PyGithub/PyGithub/blob/master/github/Requester.py#L508-L536

Something like this should do the job:

```python
        status = -1
        responseHeaders = None
        output = None

        try:
            response = cnx.getresponse()

            status = response.status
            responseHeaders = dict((k.lower(), v) for k, v in response.getheaders())
            output = response.read()

            cnx.close()
            if input:
                if isinstance(input, IOBase):
                    input.close()
        finally:
            self.__log(verb, url, requestHeaders, input, status, responseHeaders, output)
```

**Comment by s-t-e-v-e-n-k** [comment]
We should probably just turn on urllib3's http.client debug logging rather than doing those gymnastics.
