### ISSUE TITLE
[BUG] No latest release can be retrieved

### ISSUE THREAD

**Issue by paolarozo** [PyGithub/PyGithub#1675]
When calling the function https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html?highlight=latest#github.Repository.Repository.get_latest_release

This exception is thrown 
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-the-latest-release"}

**Comment by s-t-e-v-e-n-k** [comment]
```
>>> repo = g.get_repo("PyGithub/PyGithub")
>>> repo.get_latest_release()
GitRelease(title="")
```

Does the repo in question have any releases?
