### ISSUE TITLE
Unexpectedly more pull requests are returned.

### ISSUE THREAD

**Issue by YuriSilenok** [PyGithub/PyGithub#1678]
For a repository in an organization, I'm trying to get pull requests using the branch name as a filter.

```
org = GITHUB.get_organization('Students-of-the-city-of-Kostroma')
repo = org.get_repo('Student-timetable')
for pr in repo.get_pulls(head='task-1340'):
    print(pr)
```
I expect to get one pull request in the response.
![image](https://user-images.githubusercontent.com/14871471/91720568-04708880-eba0-11ea-8f93-548710248a19.png)
Actual result: I get all open pull requests.
![image](https://user-images.githubusercontent.com/14871471/91720687-341f9080-eba0-11ea-923c-c91164243332.png)
![image](https://user-images.githubusercontent.com/14871471/91720725-47326080-eba0-11ea-8116-8444802adf75.png)

**Comment by schen2315** [comment]
for anyone else encountering this issue, i used filter `head="ORG_NAME:BRANCH_NAME"`
