### ISSUE TITLE
Adding a team with permission to a repository is failing

### ISSUE THREAD

**Issue by RaghunathLingutla** [PyGithub/PyGithub#1686]
Hi,
I have developed below code to add a team with admin permission, which was working fine, till two to three weeks ago. Suddenly same code is failing with error.

```
from github import Github

g = Github(personal_token)
org = g.get_organization(organization_name)
repo_obj = org.get_repo('test-repo-add-team')

team = org.get_team(team_id)
team.set_repo_permission(repo_obj, 'Admin')
print(f'Added data team to test-repo-add-team')
```

Below is the error message,
Traceback (most recent call last):
  File "/Test/github/adding_team_to_repo.py", line 7, in <module>
    team.set_repo_permission(repo_obj, 'Admin')
  File /Test/venv/lib/site-packages/github/Team.py", line 249, in set_repo_permission
    "PUT", self.url + "/repos/" + repo._identity, input=put_parameters
  File "/Test/venv/lib/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/Test/venv/lib/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "documentation_url": "https://docs.github.com/rest/reference/teams#add-or-update-team-repository-permissions"}

**Comment by Aricg** [comment]
Same.
github.GithubException.GithubException: 422 {"message": "Validation Failed", "documentation_url": "https://docs.github.com/rest/reference/teams#add-or-update-team-repository-permissions"}

**Comment by Aricg** [comment]
Looking into this it appears that the api method is deprecated.

https://docs.github.com/en/free-pro-team@latest/rest/reference/teams#add-or-update-team-project-permissions-legacy
Deprecation Notice: This endpoint route is deprecated and will be removed from the Teams API. We recommend migrating your existing code to use the new Add or update team project permissions endpoint.

The new method is 
https://developer.github.com/v3/teams/#add-or-update-team-project-permissions
Which is in "Preview"

Why they would deprecate the old method while the new one is still in preview is anyone's guess..

**Comment by s-t-e-v-e-n-k** [comment]
master now has merged a commit which adds Team.update_team_repository() which uses the new endpoint. You can try and use that and see if that works.

**Comment by dregad** [comment]
@s-t-e-v-e-n-k I was facing the same issue. My code was throwing:

```
DeprecationWarning: Call to deprecated method set_repo_permission. (
        Team.set_repo_permission() is deprecated, use Team.update_team_repository() instead.
        )
```

A drop-in replacement of `set_repo_permission` by `update_team_repository` fixed the issue.

Tested with PyGithub 1.55.

Thanks !
