### ISSUE TITLE
Python PyGithub how to list projectCard?

### ISSUE THREAD

**Issue by jf-marquis-Adeo** [PyGithub/PyGithub#1689]
I'm trying to access project card from github api with PyGithub but I'm unable to find how to call the projectcard method (https://developer.github.com/v3/projects/cards/) It seems to be ready to use (https://pygithub.readthedocs.io/en/latest/github_objects/ProjectCard.html) 
My code working for projects :
```
from github import Github

# github access token
g = Github("XXXXX")

repo = g.get_repo("Myrepo")
projects = repo.get_projects(state='open')
for project in projects:
    print('do something with project')
```
thanks a lot for your help

**Comment by KenwoodFox** [comment]
Did you ever figure this out? I cant tell if i have a code issue or if the library does not support projectsv2 yet.
