### ISSUE TITLE
[Question] creating an instance from a webhook .json file

### ISSUE THREAD

**Issue by carlescufi** [PyGithub/PyGithub#1693]
When running a GitHub Action, the path `/github/workflow/event.json` typically points to the webhook event payload. Is it possible to load that JSON file and create an instance of PyGithub object (eg. `PullRequest`) from it?

**Comment by s-t-e-v-e-n-k** [comment]
So, yes, it's possible, you could do it with a Flask app, or even some AWS Lambda instance to parse the JSON, get the Repository object and then call create_pull_request.
