### ISSUE TITLE
403 error for otherwise functional token

### ISSUE THREAD

**Issue by seanbreckenridge** [PyGithub/PyGithub#1700]
The following fails on my machine:

```python
import json
from github import Github

with open("./token.json", "r") as f:
    auth_token = json.load(f)["token"]

g = Github(auth_token)

repo = next(iter(g.get_user().get_repos()))
# this fails with a 403
print(repo.get_views_traffic())
```

```
{'message': 'Must have push access to repository', 'documentation_url': 'https://docs.github.com/rest/reference/repos#get-repository-clones'}
Traceback (most recent call last):
  File "./requests_fails.py", line 13, in <module>
    r.raise_for_status()
  File "/home/sean/.local/share/virtualenvs/pygithub_requests_error-nXm25YLC-/home/sean/.local/share/pyenv/shims/python/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/seanbreckenridge/albums/traffic/clones
```

The token has the `repo` scope, and if I request the same using `curl`, it works fine.

![](https://camo.githubusercontent.com/7eff8b96b08c3576dd21f49fbb215c57f719f80b/68747470733a2f2f692e696d6775722e636f6d2f4f4d46724e6e4b2e706e67)

This was working fine at one point, and then just stopped. I originally found this while using <https://github.com/karlicoss/ghexport/issues/4>, you can see the process of debugging it in that issue.

I've debugged this quite a bit in the above issue, created <https://github.com/seanbreckenridge/pygithub_requests_error> which has code that runs in a virtualenv which causes the error *on my machine*. Strangely, @karlicoss, who I debugged this with doesn't have the same error.

See the [log file with errrors](https://github.com/seanbreckenridge/pygithub_requests_error/blob/master/log.txt), for [this script](https://github.com/seanbreckenridge/pygithub_requests_error/blob/master/run), which runs:

- a basic `curl` with the token, which succeeds ([link](https://github.com/seanbreckenridge/pygithub_requests_error/blob/master/curl_test.sh))
-  `PyGithub` which fails ([link](https://github.com/seanbreckenridge/pygithub_requests_error/blob/master/pygithub_requests_fails.py))
- `requests` which fails ([link](https://github.com/seanbreckenridge/pygithub_requests_error/blob/master/requests_fails.py))
- subclassed `PyGithub` with `httpx` [which succeeds](https://github.com/seanbreckenridge/pygithub_requests_error/blob/a9df0bcbf91b321e068ca591e5e6b91b804fca16/log.txt#L283-L296). ([link](https://github.com/seanbreckenridge/pygithub_requests_error/blob/master/httpx_subclass_succeeds.py))

This seems to be a `requests` error, since even just requesting something basic to github with the python `requests` module (without `PyGithub` at all) fails (see [`./requests_fails.py`](https://github.com/seanbreckenridge/pygithub_requests_error/blob/master/requests_fails.py)), when the analogous `curl` command works fine.

So I'm not sure if this should be classified as a `PyGithub` error, or a `requests` error.

See <https://github.com/karlicoss/ghexport/issues/4#issuecomment-693694338>; in which I use `pdb` to step into right before the request is made (in `PyGithub.Requester`). If I make the request with the `requests` module, it fails. If I make it with `httpx`, it succeeds.

Similarly, I can subclass the `PyGithub.Requester` `HTTPSRequestsConnectionClass` to use [`httpx`](https://github.com/encode/httpx), and then `PyGithub` works fine. (See [`httpx_subclass_succeeds.py`](https://github.com/seanbreckenridge/pygithub_requests_error/blob/master/httpx_subclass_succeeds.py) and the output [here](https://github.com/seanbreckenridge/pygithub_requests_error/blob/a9df0bcbf91b321e068ca591e5e6b91b804fca16/log.txt#L283-L296)).

I suspect this is an issue with `requests`, though I'm not sure how no one else has had this issue. Apologies if this should have been posted to the `requests` module instead, but I'm not sure how to debug this any further.

**Comment by s-t-e-v-e-n-k** [comment]
I would also file an issue with requests, since we are dependant on them.

**Comment by seanbreckenridge** [comment]
Will do so

**Comment by seanbreckenridge** [comment]
Sorry for the delay, submitted a minimal example to [psf/requests](https://github.com/psf/requests/issues/5801)

**Comment by seanbreckenridge** [comment]
This has been resolved; the cause was a `.netrc` file interfering with [`trust_env`](https://docs.python-requests.org/en/latest/api/#requests.Session.trust_env); closing
