### ISSUE TITLE
GET /repositories endpoint on Github iterate over paginated list is slow

### ISSUE THREAD

**Issue by dave4422** [PyGithub/PyGithub#1701]
Hi!

I am trying to receive all repository names for an enterprise github server. 
Something like this:
`[repo.name for repo in gh.get_repos()]
`
Unfortunately, this is incredibly slow. The server has some 1000s of repos and it takes a couple of minutes.

I already set per_page in Github to =100.

Do you have any other suggestions how to speed this up? Is pygithub doing a single get request for every repo?
I also tested all_repositories from github3 library and this is much much faster (so the bottle neck is not my connection...) but I don't want to use an additional library...

**Comment by s-t-e-v-e-n-k** [comment]
As a suggestion, turn on debug logging for both libraries and see what requests are being made.

**Comment by deepanshu11madan** [comment]
yeah running into a similar problem, on logging, looks like pygithub is doing a single get request for every repo

**Comment by s-t-e-v-e-n-k** [comment]
Items returned from PaginatedLists are not "complete" because we no idea what information GitHub hasn't sent, so querying any properties tends to result in fetching the object again, if you're after only the name, or something similar, use the _ properties.
