### ISSUE TITLE
search_issues does not expose draft status

### ISSUE THREAD

**Issue by ssbarnea** [PyGithub/PyGithub#1706]
While it is possible to include or exclude drafts when performing a search_issues query, it seems that the returned result does not include any information regarding if the returned PR is a draft one or not.

How can we gather this information?

**Comment by s-t-e-v-e-n-k** [comment]
The query can include "draft:true" or "draft:false" according to https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/searching-issues-and-pull-requests . Further more, the returned PullRequest object should have a draft attribute, for example:

```
>>> repo = g.get_repo("PyGithub/PyGithub")
>>> pr = repo.get_pull(1727)
>>> pr.draft
False
```

**Comment by dhruvmanila** [comment]
This is not true as GitHub API v3 considers every pull request as issue but not every issue is a pull request. 

This means that whenever you search using the `/search/issues` endpoint what you get is the issue object. If you searched for PR using `is:pr` or `type:pr` you will still get the issue object but there will be a `pull_request` attribute which will contain only the URL information which you can use to get the pull request object and then check for draft status.

```
...
"closed_at": null,
      "pull_request": {
        "url": "https://api/github.com/repos/octocat/Hello-World/pull/1347",
        "html_url": "https://github.com/octocat/Hello-World/pull/1347",
        "diff_url": "https://github.com/octocat/Hello-World/pull/1347.diff",
        "patch_url": "https://api.github.com/repos/octocat/Hello-World/pulls/1347"
      },
      "body": "...",
      "score": 1,
...
```

**Comment by dhruvmanila** [comment]
@s-t-e-v-e-n-k I think you can close this one.

For reference, the code returns an Issue obejct: https://github.com/PyGithub/PyGithub/blob/master/github/MainClass.py#L550

**Comment by s-t-e-v-e-n-k** [comment]
@dhruvmanila Thank you for your brilliant explanation, doing so.

**Comment by ssbarnea** [comment]
Yeah, that is what I was doing for a good number of months but is damn slow as for each returned result I need to make another query in order to figure it out if is draft or not. I guess there is no way to bulk get this information yet, which is bit weird because in the web interface they display the draft status and I doubt they make an extra request for each listed PR.
