### ISSUE TITLE
get_issues unsuported operand

### ISSUE THREAD

**Issue by rvernica** [PyGithub/PyGithub#1709]
I'm using this library against an GitHub EE instance:
```
In [18]: gh = github.Github(base_url = base_url, login_or_token = token)

In [20]: repo = gh.get_repo('...')

In [21]: repo.get_issues()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-912cf87b50b9> in <module>
----> 1 repo.get_issues()

~/.local/lib/python3.6/site-packages/github/Repository.py in get_issues(self, milestone, state, assignee, mentioned, labels, sort, direction, since, creator)
   2468                 url_parameters["creator"] = creator._identity
   2469         return github.PaginatedList.PaginatedList(
-> 2470             github.Issue.Issue, self._requester, self.url + "/issues", url_parameters
   2471         )
   2472

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Python: 3.6
PyGithub: 1.52

BTW, normally modules define `__version__`:
```
In [22]: github.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-043504657421> in <module>
----> 1 github.__version__

AttributeError: module 'github' has no attribute '__version__'

In [25]: import requests

In [26]: requests.__version__
Out[26]: '2.24.0'
```

**Comment by s-t-e-v-e-n-k** [comment]
I wonder if the repo isn't being returned, or you don't have permission, so self.url is None.

**Comment by rvernica** [comment]
I think permissions are fine as I tried cURL and another library and they both worked.

**Comment by s-t-e-v-e-n-k** [comment]
Can you see what `repo.url` is before calling get_issues?

**Comment by rvernica** [comment]
It is `None`:
```
In [14]: repo = gh.get_repo('...')

In [15]: repo.url

In [16]: type(repo.url)
Out[16]: NoneType
```

**Comment by s-t-e-v-e-n-k** [comment]
What does `repo.raw_data` return? Please feel free to redact anything you feel needs to be hidden.

**Comment by rvernica** [comment]
```
In [9]: repo.raw_data
Out[9]: {'data': '<html><body>You are being <a href="https://.../login?return_to=...">redirected</a>.</body></html>'}
```
It looks like it is either *not* using the API endpoint (but the UI endpoint) or it is *not* using the token to authenticate.

**Comment by s-t-e-v-e-n-k** [comment]
Sorry, my free time evaporated for a few weeks. This seems like your base_url is incorrect, since you're getting redirected. Or turn on debug logging and see the full data sent and returned.

**Comment by rvernica** [comment]
No worries. I think the `base_url` is fine. It is somehow not using the token to authenticate. This is why it is getting redirected to the login page. I tried another library and it works fine with the same `base_url`

**Comment by s-t-e-v-e-n-k** [comment]
Can you turn on console debugging, and see if the token is getting sent in your requests?

**Comment by rvernica** [comment]
How do it turn it on and how should the output look like? What should I look for?

**Comment by s-t-e-v-e-n-k** [comment]
```
import github
github.enable_console_debug_logging()
```

I've not used it for a while, but it should output what it sends and receives from the remote end.
