### ISSUE TITLE
github.BranchProtection.BranchProtection missing 3 attributes

### ISSUE THREAD

**Issue by grenstong** [PyGithub/PyGithub#1716]
GitHub api provides to do the following:
-  required_linear_history: true,
-  allow_force_pushes: true,
-  allow_deletions: true

https://developer.github.com/v3/repos/branches/#update-branch-protection

The functions related to this 3 branch protection rules are not added in the class mentioned in the title.

**Comment by jacobisaliveandwell** [comment]
Is there any way to get this some immediate attention?

**Comment by s-t-e-v-e-n-k** [comment]
There is a PR open for this, but it requires more work before it can be merged.

**Comment by jacobisaliveandwell** [comment]
@s-t-e-v-e-n-k awesome. got a pr #?

**Comment by Grenston** [comment]
> There is a PR open for this, but it requires more work before it can be merged.

Thanku I am waiting a lot for this to be merged.

**Comment by grenstong** [comment]
Hi @s-t-e-v-e-n-k  any update on this fuctionality?

**Comment by s-t-e-v-e-n-k** [comment]
Huh, I completely missed the author closing the PR.

**Comment by jacobisaliveandwell** [comment]
@Grenston like the PR author, I've worked around this and don't have time to figure out the broken tests. Maybe in a month or two...

**Comment by Baitanik** [comment]
Is there any update on this feature.. 
it will really helpful if we can get this

**Comment by rkleinman-hpe** [comment]
Can we get the PR re-opened to keep working on it?
