### ISSUE TITLE
How can I use ‘Client ID’ and ‘Client Secret’ of OAuth Apps to login 

### ISSUE THREAD

**Issue by a523** [PyGithub/PyGithub#1719]
I‘m trying "[GitHub Enterprise Cloud](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/setting-up-a-trial-of-github-enterprise-cloud)", because it will improve my github api rate limit.
And the organization only provides `OAuth Apps` not `Personal access tokens` , How can I use ‘Client ID’ and ‘Client Secret’ of OAuth Apps to request github api  with PyGithub.

I user curl like this ，It works.
```shell
curl -u my_client_id:my_client_secret 'https://api.github.com/rate_limit'
```
output
```shell
{
  "resources": {
    "core": {
      "limit": 15000,
      "used": 0,
      "remaining": 15000,
      "reset": 1602336141
    },
    "search": {
      "limit": 30,
      "used": 0,
      "remaining": 30,
      "reset": 1602332601
    },
    "graphql": {
      "limit": 5000,
      "used": 0,
      "remaining": 5000,
      "reset": 1602336141
    },
    "integration_manifest": {
      "limit": 5000,
      "used": 0,
      "remaining": 5000,
      "reset": 1602336141
    },
    "source_import": {
      "limit": 100,
      "used": 0,
      "remaining": 100,
      "reset": 1602332601
    },
    "code_scanning_upload": {
      "limit": 500,
      "used": 0,
      "remaining": 500,
      "reset": 1602336141
    }
  },
  "rate": {
    "limit": 15000,
    "used": 0,
    "remaining": 15000,
    "reset": 1602336141
  }
}
```
The rate limit is 15000, to show that my login is valid.

But I don't Know How to user PyGithub to get the same effect.

I tried this, but it didn't work.
```pyhton 
>>> from github import Github
>>> g = Github(client_id='my_client_id', client_secret='my_client_secret')
1: FutureWarning: client_id and client_secret are deprecated and will be removed in a future release, switch to token authentication
>>> g.get_rate_limit()
RateLimit(core=Rate(reset=2020-10-10 12:39:24, remaining=42, limit=60))
# limit is 60 not 15000
```

**Comment by nokome** [comment]
@a523 To avoid the `FutureWarning` (which is to avoid sending `client_id` and `client_secret` in query strings which is deprecated) pass them as the first and second arguments. This will send them in the `Authorization` header as curl does (which is NOT deprecated):

```python
g = Github('my_client_id', 'my_client_secret')
```

However, I think that you may be getting a lower rate limit for another reason. Are you are using a "GitHub App" not an "Oauth App"? I found that I get a rate limit of 60 when I use the credentials for our org's Github App, but get a rate limit of 5000 when I use our Oauth App (on github.com)

**Comment by Chelsea-Z** [comment]
@a523 Hi, I'm having the same issue. Did you figured it out?

**Comment by nokome** [comment]
The approach I described above (i.e. not using the `client_id` and `client_secret` kwargs) seems to work fine for us. See https://github.com/stencila/hub/blob/master/worker/util/github_api.py for reference.

**Comment by a523** [comment]
> Did you figure it out

Yes,  that two methods can work for me.

Method 1：
```python
from github import Github
g = Github('my_client_id', 'my_client_secret')

# It works
``` 
Not like this !!!
```python 
g = Github(client_id='my_client_id', client_secret='my_client_secret')

# This code doesn't work
```
Method 2：
You can generate a token by emulating the client
1. Access the url https://github.com/login/oauth/authorize?client_id=your_client_id in your browser
2. The may ask you to login to github， and then the browser will go to another domain that you have specified, like this: 
`http://jiebaby.com/?code=a2f205a1f9643f2fe5c8`
This code `a2f205a1f9643f2fe5c8`  is what you need for the next step
3. Use a tool like 'postman' request url with POST method.
```shell
url: https://github.com/login/oauth/access_token
method: POST
args: client_id  client_secret  code
```
The can return access_token
![post_github](https://user-images.githubusercontent.com/21216466/102756905-7ec15480-43ab-11eb-8e73-243ed44d2b8c.jpg)

4. Now, you can use this access_token like this
```python
g = Github(access_token,  retry=9)
```
There is the  oauth docs：https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps
