### ISSUE TITLE
[Question] Getting a PR/issue comment's edit history details 

### ISSUE THREAD

**Issue by dhananjay19** [PyGithub/PyGithub#1726]
Is there a method to get a PR/issue comment's edit history details ?
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment

I could not find from the APIs references : https://pygithub.readthedocs.io/en/latest/apis.html

**Comment by s-t-e-v-e-n-k** [comment]
That isn't an API method, and indeed, I can't see any API method for fetching it. If you do find something like please open another issue.
