### ISSUE TITLE
Organization missing get_installations method

### ISSUE THREAD

**Issue by thoward27** [PyGithub/PyGithub#1730]
While trying to use PyGithub in my project, I've run into a bit of a dilemma. It appears that the `get_installations()` method is not present on the `Organization` object as described here: https://pygithub.readthedocs.io/en/latest/github_objects/Organization.html#github.Organization.Organization.get_installations

Perhaps there's a better way to achieve what I'm trying to do, so let me try to add a bit of context.

I've created a Github application and installed it into a Github Org that I own. Now, I'm trying to use PyGithub to clone a repo from that org using a JWT as described here: https://docs.github.com/en/free-pro-team@latest/developers/apps/authenticating-with-github-apps#generating-a-private-key

The trouble is, I seem to be in need of an `installation_id`, which I cannot figure out how to get programmatically using PyGithub.

Besides trying to use `Organization().get_installations()`, I have also explored the `GithubApplication` interface, yet that doesn't seem to include any method for calling https://docs.github.com/en/free-pro-team@latest/rest/reference/apps#list-installations-for-the-authenticated-app

Please advise!

**Comment by s-t-e-v-e-n-k** [comment]
Sadly, it is because the docs on readthedocs are generated from master, and not the latest release, so you've found a method that was recently added. I'll be making a release over the next week or so.

**Comment by thoward27** [comment]
@s-t-e-v-e-n-k, thanks for the quick reply! Do you have any other recommendations for me, I'm having a particularly hard time trying to figure out how to access this endpoint: https://docs.github.com/en/free-pro-team@latest/rest/reference/apps#list-repositories-accessible-to-the-app-installation using PyGithub, is that something that should be currently possible?

**Comment by s-t-e-v-e-n-k** [comment]
Our documentation should always contain the URL that is called, allowing you to search for which method calls a certain endpoint. `Installation.get_repos()` calls that endpoint.

**Comment by thoward27** [comment]
@s-t-e-v-e-n-k, I did happen to notice that, what I can't seem to put my finger on is how to properly get the installations using PyGithub. Do you happen to know of any examples?

**Comment by s-t-e-v-e-n-k** [comment]
There seems to be a method conflict in MainClass around fetching an Installation.

**Comment by s-t-e-v-e-n-k** [comment]
https://github.com/PyGithub/PyGithub/pull/1738 may help here -- @thoward27 are you able to test with that branch if `Github.get_installation(repo, owner)` works for you?

**Comment by dhruvmanila** [comment]
I used this in `GithubCredentials.py` to test `CheckRun` feature using an app I created:
```python
def __get_access_token():
    with open("path/to/private_key.pem") as file:
        private_key = file.read()
    app_id = APP_ID
    github_integration = github.GithubIntegration(app_id, private_key)
    installation = github_integration.get_installation(OWNER, REPO)
    access_token = github_integration.get_access_token(installation.id)
    return access_token.token
```
Also, I don't think you can clone a repository from the API.

**Comment by s-t-e-v-e-n-k** [comment]
I will note that is calling GithubIntegration.get_installation() not MainClass.get_installation().

However, does the posted example help @thoward27 ?

**Comment by dhruvmanila** [comment]
Yes, this is using `github.GithubIntegration.get_installation()` to access the installed app in the repository but the ***app needs to be installed in the repository*** and not in an organization to access this endpoint. 

> The trouble is, I seem to be in need of an installation_id, which I cannot figure out how to get programmatically using PyGithub.

To access information regarding an organization installation `Organization.get_installations()` needs to be released first, `installation_id` will be present in this endpoint for an organization. Also, it seems that the `installation` object is missing a lot of attributes according to [this](https://docs.github.com/en/free-pro-team@latest/rest/reference/orgs#list-app-installations-for-an-organization).

The `app_id` and `private_key` information will be in the application settings. This information will not change so it can be stored as an environment variable wherever your app is being hosted.

**Comment by s-t-e-v-e-n-k** [comment]
@thoward27 I'm going to close this issue since I'll be making a release that exports that method.

@dhruvmanila I would welcome any PR/issue at improving any part of this library, of course.

**Comment by dato** [comment]
Is the [endpoint](https://docs.github.com/en/free-pro-team@latest/rest/reference/apps#get-an-organization-installation-for-the-authenticated-app) `GET /orgs/{org}/installation` available through the library? I _think_ it's what I need so that an application installed in an organization can create repositories that still don't exit... but I cannot find a way to do this (this == either the endpoint I mentioned, or being able to create repositories as an app, without that endpoint).
