### ISSUE TITLE
Incorrect annotation for `PullRequest.create_review_request`

### ISSUE THREAD

**Issue by dubois** [PyGithub/PyGithub#1731]
The method is documented as taking `List[str]` (and asserts the same) [(see code)](https://github.com/PyGithub/PyGithub/blob/ee4c7a7e9e23224ab97696e55cb2983562357da7/github/PullRequest.py#L514)

But the annotation says it takes `str` [(see code)](https://github.com/PyGithub/PyGithub/blob/ee4c7a7e9e23224ab97696e55cb2983562357da7/github/PullRequest.pyi#L64)

**Comment by s-t-e-v-e-n-k** [comment]
That is a nice catch indeed! Do you feel comfortable pushing a pull request for that change -- change str to List[str] for both reviewers and team_reviewers. If not, that's totally fine, I can do so.
