### ISSUE TITLE
Sporadically Git tree creation failure due to `base_tree is not a valid tree oid`

### ISSUE THREAD

**Issue by XuegeGeGe** [PyGithub/PyGithub#1732]
Hello,

We use PyGithub to create PR, and sometimes get error with "base_tree is not a valid tree oid", and once this happens, the call will be constantly failing for a period of time (minutes to hours), however, the call could get back to work sometime later.
Stack trace:
```
Traceback (most recent call last):
  File "gitpr3.py", line 138, in <module>
    update_pvc_name("amp-app-processing", "us-west-1a", "new_pvc", "new_ast_versions", "new_sdkdb_versions")
  File "gitpr3.py", line 54, in update_pvc_name
    tree = repo.create_git_tree(elements, base_tree=upstream.get_git_tree(upstream_master.object.sha))
  File "/Users/xuegecao/Workplace/Python/.virtualenvs/operator-with-latest/lib/python3.7/site-packages/github/Repository.py", line 1113, in create_git_tree
    "POST", self.url + "/git/trees", input=post_parameters
  File "/Users/xuegecao/Workplace/Python/.virtualenvs/operator-with-latest/lib/python3.7/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/Users/xuegecao/Workplace/Python/.virtualenvs/operator-with-latest/lib/python3.7/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "base_tree is not a valid tree oid", "documentation_url": "https://developer.github.com/enterprise/2.19/v3/git/trees/#create-a-tree"}
```

Our code snippet, the code always fails on the last line `repo.create_git_tree`:
```
    github = Github(base_url=GITHUB_PIE, login_or_token=GAT)

    # Get upstream/master
    upstream = github.get_repo(REPO_NAME)
    upstream_master = upstream.get_git_ref("heads/master")

    repo = github.get_repo(USER_REPO)

    # We need to deal with trees and tree elements because the
    # Github repo update_file API creates one commit per-file
    # and that clutters up our Git history. This approach lets
    # us batch all the changes into a single commit.
    # We want to get files from the upstream repo, so that's what we pass in.
    elements: List[InputGitTreeElement] = get_updated_elements(
        upstream, namespace, cluster, new_pvc, ast_versions, sdkdb_versions, tapi_analyze_sdkdb_versions)

    # Construct the tree of all our changes so far, based off upstream/master
    tree = repo.create_git_tree(elements, base_tree=upstream.get_git_tree(upstream_master.object.sha))
```

Since the same script would get different results (success/failure) at different time, it looks like something wrong/inconsistent on the server side, any pointer would be appreciated, thanks!

**Comment by s-t-e-v-e-n-k** [comment]
You are absolutely correct it's on GitHub's side. So, I wonder what get_git_tree is returning when it fails, or if the server is running a re-index job or something similar. Does it happen after pushes, or after some other event?

**Comment by XuegeGeGe** [comment]
* `get_git_tree` will still return the tree with correct SHA
* the repo we're handling is big and contributed by multiple teams, so I really don't know what could be the trigger of it
  * what we've observed was -  the issue will last for a while (minutes to hours) and the PR could come after several hours (despite the API showed failure)

Could you suggest us an alternative way for PR creation? Thank!

**Comment by XuegeGeGe** [comment]
For the fresh example today, we've been getting `base_tree is not a valid tree oid` from GitHub API calls, however, a PR came in after couple of hours!
