### ISSUE TITLE
Guest auth

### ISSUE THREAD

**Issue by rez0n** [PyGithub/PyGithub#1741]
Hi, thank you for the cool library. 
I working on a script for the CI and have a question, any way to interact with GitHub without an authorization? As a guest.

**Comment by s-t-e-v-e-n-k** [comment]
Yes, by passing no arguments to the `Github` constructor.

```
>>> g = Github()
>>> repo = g.get_repo("PyGithub/PyGithub")
>>> repo.full_name
'PyGithub/PyGithub'
```
