### ISSUE TITLE
Search repositories duplicates 

### ISSUE THREAD

**Issue by Revyen** [PyGithub/PyGithub#1748]
I'm trying to search for specific repositories and store information in a database.

for some search queries I'm getting a high amount of duplicates repositories while iterating the response (up to around 50% per response page)

`repos = github_client.search_repositoies(query=f"{query_name} created:{from_date}..{to_date}")
for repo in repos_per_page:
  store_repo()`

I'm a bit puzzled why the search query from the github api returns not duplicates at all but the paginated list I'm getting from pygithub

**Comment by s-t-e-v-e-n-k** [comment]
Do you mean the search query run via curl or the search function on the website? Because they are very different.

**Comment by Revyen** [comment]
I've tried search via curl and compared the result with the paginated list. Some queries returned little to none duplicates but other returned many duplicates while iterating the paginated list.

**Comment by ascholerChemeketa** [comment]
I'm seeing the same issue using `search_repositoies`. I run the same search twice in a row and I git a different set of results. Sometimes I get the expected result set. Other times, I get a result where one item is missing and another exists twice.

**Comment by ascholerChemeketa** [comment]
Setting `sort='updated'` in the serach_repositories call appears to help.

Maybe the default search order produces undeterministic paging. So as the PagianatedList retrieves the individual page results, things slide back and forth between pages and are missed or duplicated.
