### ISSUE TITLE
Search for Issues also brings PRs

### ISSUE THREAD

**Issue by hvithval** [PyGithub/PyGithub#1751]
Good morning, I'm working on a python script to check repos and migrating them and I found myself needing to query open issues on Github and I notice that when doing:
```
g = Github(args.gitHubToken)
repo = g.get_repo("<orgname>/<reponame>)
open_issues = repo.get_issues(state='open')
```
This is returning both the **open issues** and **open PRs**... is this the correct behavior? is my query wrong?/ is the response incorrect?

I'll appreciate your comments.

Regards
Hvithval

**Comment by s-t-e-v-e-n-k** [comment]
From https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#list-repository-issues :

Note: GitHub's REST API v3 considers every pull request an issue, but not every issue is a pull request. For this reason, "Issues" endpoints may return both issues and pull requests in the response. You can identify pull requests by the pull_request key. Be aware that the id of a pull request returned from "Issues" endpoints will be an issue id. To find out the pull request id, use the "List pull requests" endpoint.

I wouldn't call it correct behaviour, but it the existing GitHub behaviour.
