### ISSUE TITLE
Does this library expose the token i

### ISSUE THREAD

**Issue by cristianmtr** [PyGithub/PyGithub#1754]
According to this https://github.blog/2012-09-21-easier-builds-and-deployments-using-git-over-https-and-oauth/,
 tokens are exposed:

> Note: Tokens should be treated as passwords. Putting the token in the clone URL will result in Git writing it to the .git/config file in plain text. Unfortunately, this happens for HTTP passwords, too. We decided to use the token as the HTTP username to avoid colliding with credential helpers available for OS X, Windows, and Linux.

Does this library also expose tokens if used to authenticate?

Like:

```python
g = Github(os.environ["DEV_BOT_TOKEN"])
```

We use this lib in our GH actions setup and don't want to leak tokens.

**Comment by dhruvmanila** [comment]
No, encapsulation prevents anyone to access the token or any other authorization details from outside the object. Also, even if you enable logging for debugging purposes, the tokens and other authorization details are removed before it gets logged.

Here is where the authorization details are stored: https://github.com/PyGithub/PyGithub/blob/master/github/Requester.py#L279 and here is the function which logs on debug: https://github.com/PyGithub/PyGithub/blob/master/github/Requester.py#L588

**Comment by s-t-e-v-e-n-k** [comment]
Correct, we don't log tokens, or write them to disk, they are in memory only.
