### ISSUE TITLE
Repository stats incorrect

### ISSUE THREAD

**Issue by alexforencich** [PyGithub/PyGithub#1756]
I'm running 1.53, and the `stargazers_count`, `watchers_count`, `forks_count`, and `network_count` seem to be mixed up.  Running against a repo with 3 watchers, 20 stars, and 94 forks, `stargazers_count` returns 20, `watchers_count` returns 20, `forks_count` returns 3, and `network_count` returns 94.  Seems like `watchers_count` is returning the number of stargazers, `forks_count` is returning the number of watchers, and `networks_count` is returning the number of forks.  I'm also not sure what `networks_count` is supposed to return.

**Comment by alexforencich** [comment]
I just checked on another repo that has 59 watchers, 500 stars and 94 forks (previous one was a fork of this repo) and pygithub `stargazers_count` returns 500, `watchers_count` returns 500, `forks_count` returns 94, and `networks_count` returns 94.  Seems inconsistent, whatever is going on.

**Comment by s-t-e-v-e-n-k** [comment]
We are at the mercy of whatever data GitHub returns here, sadly -- we have no transparency into how GitHub calculates those numbers.

**Comment by alexforencich** [comment]
I see.  So the problem is the data from github being incorrect.  Is there an alternative way to get that information?  Perhaps `get_stargazers().totalCount` would be more reliable?

**Comment by alexforencich** [comment]
Ah, maybe I am misunderstanding what some of the fields mean.  `forks_count` seems to be forks of the repo directly, while `network_count` is the total number of forks across from the original repo.  So those numbers actually make sense, and the stargazers count is correct.  However, `watchers_count` still appears to be wrong, and `get_watchers` appears to return the same thing as `get_stargazers`.

**Comment by alexforencich** [comment]
Ah, it seems I need the subscriber count (why does the terminology need to be so different between the user interface and the API???)
