### ISSUE TITLE
No examples or documentation around working with pull request reviews

### ISSUE THREAD

**Issue by ssbarnea** [PyGithub/PyGithub#1758]
While there are some examples on how to work with [Pull Requests](https://github.com/PyGithub/PyGithub/tree/master/doc/examples) there is effectually nothing documented around how to obtain information about the **review status** from a PR object.

As I have a specific PR, I do want to findout the CI check report on it and the current review status: if anyone approved it or requested changes, so I would figure out how far is from being ready to merge.

So far all I got was the `pull_request.url` property but how do I endup instantiating a PullRequestReview out of it? I was not able to see any example, doc or even tests doing it. After half and hour of googling and being unable to find any example, I decided that maybe we need a simple example.

**Comment by dhruvmanila** [comment]
> I do want to findout the CI check report on it 

This can be found out using the Checks API on the latest commit pushed to the PR. The API is quite new and the CheckRun object and endpoints were [added](https://github.com/PyGithub/PyGithub/pull/1727) just a few days back. Once that is published in the next version, you will be able to use it. Note that some CI uses the Status API to send the status of the tests.

> but how do I endup instantiating a PullRequestReview out of it?

All objects contain either a `create_` or `get_` methods which are used to either do something or get something. In your case, as you want to create a review, look for `create_` prefixed methods in the PullRequest object: `create_comment(), create_review_comment(), create_review, ...`

For reference always look at the GitHub provided documentation: https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls
