### ISSUE TITLE
Feature Request - Ability to create a GitRef

### ISSUE THREAD

**Issue by chrisjohnson00** [PyGithub/PyGithub#1759]
https://docs.github.com/en/free-pro-team@latest/rest/reference/git#create-a-reference
The API supports creating a ref, but this library doesn't (yet) support it.
Edit/delete are supported in this library, so create should be simple.  I'll attempt to tackle it if/when I have the time.

**Comment by dhruvmanila** [comment]
This library supports it as well: https://github.com/PyGithub/PyGithub/blob/master/github/Repository.py#L955

**Comment by chrisjohnson00** [comment]
So it does, thanks... I was looking in `GitRef.py` and only saw delete/edit and no create.
