### ISSUE TITLE
example for creating and updating GitHub check run

### ISSUE THREAD

**Issue by saheerb** [PyGithub/PyGithub#1766]
I would like my CI server to create and update GitHub check run as it does the CI builds. I plan to use PyGitHub, but I couldn't find any example on this. After hours of digging, I can to some what like the snippet below but I get a "bad credentials error". Thank you for the awesome GitHub SDK but it will be a great help, if there is an example code for this particular workflow. 

```
import jwt
import time
from github import Github

pem_file = "ci-results.2020-11-27.private-key.pem"
installation_id = 111
app_id = 111

time_since_epoch_in_seconds = int(time.time())
payload = {
    # issued at time
    'iat': time_since_epoch_in_seconds,
    # JWT expiration time (10 minute maximum)
    'exp': time_since_epoch_in_seconds + (5 * 60),
    # GitHub App's identifier
    'iss': app_id
}

this_jwt = jwt.encode(payload, open(pem_file, 'r').read().strip().encode(), 'RS256').decode()

gh = Github(jwt=this_jwt)

gh.get_app("ci-results")
```

github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest

**Comment by dhruvmanila** [comment]
You need an installation access token to act as an app and do things with an app. Also, you do not need to create the JWT manually, we provide methods for that.

```python
# Fill the required information
APP_ID = 
PRIVATE_TOKEN =  
INSTALLATION_ID = 

github_integration = github.GithubIntegration(APP_ID, PRIVATE_TOKEN)
# Note that installation access tokens last only for 1 hour, you will need to regenerate them after they expire.
access_token = github_integration.get_access_token(INSTALLATION_ID)

login = github.Github(access_token)
# Pass in the parameters as necessary
repo = login.get_repo()                # get the repository
check_run = repo.create_check_run()    # create the check run
check_run.edit()                       # update the check run

**Comment by saheerb** [comment]
Thanks, I will try this. But I am curious to know how you found this. Is this documented?

**Comment by dhruvmanila** [comment]
I created a bot for the repo I am currently maintaining, so I did some research into it and that's how I know all this.

Installation access token: https://docs.github.com/en/free-pro-team@latest/rest/reference/apps#create-an-installation-access-token-for-an-app
Permissions required for an app: https://docs.github.com/en/free-pro-team@latest/rest/reference/permissions-required-for-github-apps
Building GitHub apps: https://docs.github.com/en/free-pro-team@latest/developers/apps/building-github-apps

Hope this helps! You can explore more through the documentation.

**Comment by saheerb** [comment]
Thanks @dhruvmanila  I did dig in the guthub docs before posting the question here. But  was not able to find the documentation on how to use check_run with "PyGithub". I eventually used "github3.py"

My question was, how did you get the instructions for pygithub? Was it digging in the code or some examples/documentation I missed?

**Comment by dhruvmanila** [comment]
Ah, yes I contributed the Checks API (CheckRun and CheckSuite) for this library so I did take a look at the codebase. 

Also, I might be wrong but it seems that the class `GithubIntegration` is not documented at all.

**Comment by saheerb** [comment]
Thanks Dhruv!
