### ISSUE TITLE
Return MainClass.Github.get_installation(id)

### ISSUE THREAD

**Issue by atodorov** [PyGithub/PyGithub#1776]
Removed in https://github.com/PyGithub/PyGithub/pull/1738/ but we've got an application which uses it and inheriting the base class and adding this method results it lots of boilerplate code due to using `self.__requester` attribute which isn't available in the inherited class.

**Comment by s-t-e-v-e-n-k** [comment]
Are you able to switch the application to using the other get_installation() method?

**Comment by atodorov** [comment]
> Are you able to switch the application to using the other get_installation() method?

IDK really. At the top of my head I think no. The use case is that we have the application ID and using that and the removed method we get an `Installation` object and then iterate on `inst.get_repos()` to find all of the authorized repositories for this installation.

**Comment by dhruvmanila** [comment]
I have taken a look at the installation object and the `GithubIntegration` class and I propose the following changes:

`GithubIntegration` should only be used to generate the JWT or installation access token for the app/installation. No endpoints should be provided in that class. Once the user has generated the appropriate credentials, they should be passed to the main `Github` class and make all the API calls through the instance. The current `GithubIntegration.get_installation()` function [should actually be in the `Repository` class.](https://docs.github.com/en/free-pro-team@latest/rest/reference/apps#get-a-repository-installation-for-the-authenticated-app)

The function `Github.get_installation()` is indeed a [valid endpoint](https://docs.github.com/en/free-pro-team@latest/rest/reference/apps#get-an-installation-for-the-authenticated-app) which should be provided with the `installation_id` parameter and the `Github` object should be initialized with the installation access token. As I mentioned before, the `installation` object is missing a lot of attributes.

@s-t-e-v-e-n-k I can implement this change but I need a go/no-go.

**Comment by s-t-e-v-e-n-k** [comment]
@dhruvmanila Absolutely, please go for it. If you do re-add get_installation() it needs a docstring and tests, of which it had neither before.

**Comment by dhruvmanila** [comment]
@s-t-e-v-e-n-k I want to discuss something: As per [my comment here](https://github.com/PyGithub/PyGithub/issues/1730#issuecomment-723556956), I have been using the class to programmatically get the installation ID for a specific installation in the repository (`GithubIntegration.get_installation(owner, repo)`) and using that I generate the installation access token and then make all the API calls as an installation. Now, with the proposed change of moving the method to `Repository` object, the process will become like so:
1. Instantiate a `GithubIntegration` object and get the JWT.
2. Use the JWT to instantiate the `Github` object.
3. Get the specific repository using `get_repo()`.
4. Get the specific installation from the repository object using `get_installation()`
5. Get the ID of the installation.
6. Generate the installation access token using that ID.
7. Use the installation access token to instantiate the `Github` object and now we will be able to act as an installation.

This seems cumbersome but this is the way the library has been set up to access different objects from the main `Github` object. The [same function from the comment](https://github.com/PyGithub/PyGithub/issues/1730#issuecomment-723556956) will become something like this:

```python
def _get_access_token():
    private_key = pathlib.Path(PRIVATE_KEY_FILEPATH).read_text(encoding="utf-8")
    github_integration = github.GithubIntegration(APP_ID, private_key)
    jwt = github_integration.create_jwt()
    github_api = github.Github(jwt=jwt)
    repo = github_api.get_repo(OWNER, REPO)
    installation = repo.get_installation()  # this installation is specific to this repository
    access_token = github_integration.get_access_token(installation.id)
    return access_token.token

token = _get_access_token()
github_api = github.Github(login_or_token=token)

# make all the API calls as an installation ...
```
This will need to be documented properly in the examples section which will be done in a separate PR.

**Comment by s-t-e-v-e-n-k** [comment]
If you want to also create convenience functions to make this less cumbersome, I'm all ears.

**Comment by dhruvmanila** [comment]
JWT and installation access token cannot be provided together and also they have an expiration time so a user will need to generate another one. It seems cumbersome as this is being done only for testing purposes. If the user is accessing the API as an installation, the app will most likely be working with webhooks in which they receive the installation ID in each payload.
