### ISSUE TITLE
How to get all user's details(login, name, location etc)

### ISSUE THREAD

**Issue by rakeshcusat** [PyGithub/PyGithub#178]
Thanks for providing your library, I really appreciate your good work.
Currently I am using your library to fetch user's details. code snippet is as follow.
    `gh = Github(login_or_token="rakeshcusat", password=pswd, per_page=100)
    user_pages = gh.get_users().get_page(0)
    print_page(user_pages)   #This method prints all user details.`
This works. it prints 135 user details. But I want to print all user details. I am facing two problems. 
1. I don't know how to get the total number of pages, so I can iteratively pass the page number in get_page() method.
2. As we know there is rate limit on the API call, I want to know the current remaining limit for API call. API call returns "X-RateLimit-Remaining" value in header but I don't know how to access this value. Is there any interface available to access this value?

**Comment by goutham9032** [comment]
dic={}
for i in g.get_user().get_orgs()
     dic=i

i need all the data with out mentioning the keys,like i.name or i.created_at,it needs to store all information with out explicitily naming them
expected o/p
{
    "login":"name"
     "created_at":"date"
     "updated_at":"date"
     and so on
}
