### ISSUE TITLE
Way to get all the installed GitHub apps in the org

### ISSUE THREAD

**Issue by prathameshnyt** [PyGithub/PyGithub#1781]
Can you please let me know how I can all the properties for a list of all the installed GitHub apps in the organizattion. 

[Organization.get_installations](https://pygithub.readthedocs.io/en/latest/github_objects/Organization.html#github.Organization.Organization.get_installations ) is not returning all the fields from mentioned in [list-app-installations-for-an-organization](https://developer.github.com/v3/orgs/#list-app-installations-for-an-organization) I can get some information using `get_app` but that requires slug. Let me know if I am missing something here.

**Comment by dhruvmanila** [comment]
It's because the `Installation` object is incomplete. I am working on the fix in #1791
