### ISSUE TITLE
Getting a lot of 409 Conflict errors in response and the error message is unclear

### ISSUE THREAD

**Issue by lumichael24** [PyGithub/PyGithub#1787]
contents = repo.get_contents(path, ref="master")
repo.update_file(contents.path, "commit msg", "contents", contents.sha, branch="master")

Exception thrown from update_file:
409 {"message": "is at 0929670cc804228df5f0b3e8f7a741dfb735ba62 but expected c45b5444e7ae45df5356ca2b8dbf49db646826d4", "documentation_url": "https://developer.github.com/enterprise/2.20/v3/repos/contents/#create-or-update-a-file"}

This happens when we're sending many requests for many different files at the same time but with different Github instance objects. Is there a maximum number of connections that we have with the Github api? Or what does this error mean?

**Comment by YSArch** [comment]
Same error with my app

**Comment by YSArch** [comment]
when update_file() updates next file, it marks its previous file's sha as expected - cache issue????

**Comment by YSArch** [comment]
We got the same error when multiple Github instances updated (or added or deleted) multiple files even those Github instances worked on different files at same repository.

**Comment by YSArch** [comment]
Have not figured out its cause by PyGithub implementation or Github API

**Comment by YSArch** [comment]
https://github.com/philschatz/octokit.js/issues/63

**Comment by YSArch** [comment]
Timing issue: sleep(10) before repo.update_file() could reduce such 409 errors, but when more Github instances and files are involved, more sleeps are required, so it's not a scale solution.

**Comment by YSArch** [comment]
Fix the issue by git tree approach to update bulk files at once.
