### ISSUE TITLE
Getting new commits sha after merging of pull request 

### ISSUE THREAD

**Issue by mpushki** [PyGithub/PyGithub#1792]
My merged pull request contains 3 commits from fork repo. Merged commits(from origin master) have different commit_sha than commits from PR (from fork repo)

I've read about merge_commit_sha (new sha for the last commit from pull request) - but it is not what I want. Also events way - the same problem. Merged event contains only 1 new commit sha(latest).

In other hand: If I check all new commits and call search_issues to find PR, sorting and etc, it will take a lot of time.

I need to find new sha for each merged commits using only pr number and repo.
 Could you please clarify - is it possible to find this info via pygithub?

**Comment by s-t-e-v-e-n-k** [comment]
So the `merge_commit_sha` may be the commit of the PR, or it may be the merge commit that git created. I would suggest you look into the `parents` property of the linked sha from the PR, which should allow you to transverse the graph of commits. If this isn't helpful, then I will require more information, and ideally an example.
