### ISSUE TITLE
Release a version that supports Python 3.5 and requires pyjwt<2.0.0

### ISSUE THREAD

**Issue by xupefei** [PyGithub/PyGithub#1801]
PyGithub 1.54 is the last version that supports Python 3.5, however the broken pyjwt dependency makes it unusable in Python 3.5.
We unfortunately are not able to upgrade Python in the production system, could you kindly release a 1.54 hotfix (sth like 1.54_2) that pins pyjwt to < 2.0.0 without dropping Python 3.5 support?

Thank you!

By the way, version 1.54.1 is confusing in terms of pyjwt because it's pyjwt 2.0.0 works for Python >=3.6 (you may be noticed https://github.com/PyGithub/PyGithub/issues/1796 is using py3.5). If PyGithub decides to drop py3.5, pinning pyjwt to <2.0.0 does not bring benefit.

**Comment by s-t-e-v-e-n-k** [comment]
So this is actually difficult due to 1.54.1 being out. The only option I can see is releasing a 1.54.2 that does not include the changes from 1.54.1 and then releasing those as 1.55, but that makes me sad. @sfdye What are your thoughts here?

**Comment by sfdye** [comment]
> PyGithub 1.54 is the last version that supports Python 3.5, however the broken pyjwt dependency makes it unusable in Python 3.5.

We could fix the `pyjwt` dependency issue and backport the fix to say `1.53.1`. PR welcome

**Comment by s-t-e-v-e-n-k** [comment]
I have created a new release tag and branch -- v1.54.0 since that sorts between v1.54 and 1.54.1 (although somewhat awkwardly)

However our publish pipeline failed, so you can currently install it via git tags, but not pypi.

**Comment by s-t-e-v-e-n-k** [comment]
Publish pipeline issue filed as https://github.com/pypa/warehouse/issues/9361

**Comment by s-t-e-v-e-n-k** [comment]
v1.54.0.1 has been released -- https://pypi.org/project/PyGithub/1.54.0.1/
