### ISSUE TITLE
Allow to create multi comment reviews

### ISSUE THREAD

**Issue by Seluj78** [PyGithub/PyGithub#1805]
Currently, the method `https://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html#github.PullRequest.PullRequest.create_review` only accepts a list of string (If i'm not mistaken) and cannot accept a list of comment with for example requested changes.

Like @dhruvmanila said in his comment (https://github.com/PyGithub/PyGithub/issues/1803#issuecomment-751656549):

> Yes, through this endpoint you create a review and in the comments field you list all the comments you want to post on the specific lines.

Which would require not using the method `create_review_comments` but only using the raw API. Is it something that can be added ?

**Comment by dhruvmanila** [comment]
[That method](https://github.com/PyGithub/PyGithub/blob/master/github/PullRequest.py#L463) accepts a list, the documentation does not clearly state what type of elements should it contain but according to GitHub, it should be a list of dictionary objects for Python. Each dictionary represents a comment with the necessary information.

https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#create-a-review-for-a-pull-request
Fill in the required fields as mentioned. Also, you won't be able to use the `line` field as that is only available with the comfort-fade preview headers. You will have to use the `position` field which is different than the `line` field.

**Comment by Seluj78** [comment]
You mean something like

```python
comments = [
   {
       "path": "folder/file.ext",
       "position": 42,
       "body": "My body for the review",
   }
]
```

That should be all I need since I don't need multi line comments right ? (for the `comments` part at least, then I should fill in the rest of the parameters).

I'll try and let you know

**Comment by Seluj78** [comment]
As you can see here it works perfectly ! It's not the most intuitive way but it works !

<img width="974" alt="Screenshot 2020-12-28 at 21 12 39" src="https://user-images.githubusercontent.com/4641317/103240736-70e27500-4951-11eb-9349-2503d5a6e5db.png">

[`47adf83` (Afpy/PyDocTeur #59)](https://github.com/AFPy/PyDocTeur/pull/59/commits/47adf8350c77cbf7ab28f67346de4dcc2596d56d)
