### ISSUE TITLE
Handling hitting abuse detection limits and using Retry-After

### ISSUE THREAD

**Issue by cristianmtr** [PyGithub/PyGithub#1814]
Hey

Thanks a lot for the library. It really helped us with our CI setup.

However recently we have started hitting the abuse detection limits imposed by GH https://docs.github.com/en/free-pro-team@latest/rest/guides/best-practices-for-integrators#dealing-with-abuse-rate-limits

When this happens the library seems to just throw an exception. How can I get the Retry-After header? It is part of the exception?

**Comment by s-t-e-v-e-n-k** [comment]
We sadly do not currently preserve the headers when creating an exception. However, this is an amazing idea, and I'm going to reflect on how to implement this.

**Comment by cristianmtr** [comment]
The headers could be added to the `GithubException` as another field.
