### ISSUE TITLE
409 Error when updating a repo's file

### ISSUE THREAD

**Issue by IThinkImOKAY** [PyGithub/PyGithub#1815]
I'm trying to update a file in one of my repositories. My code works for a while, but then `PyGithub` gives the following traceback:

    Traceback (most recent call last):
      File "main.py", line 30, in <module>
        repo.update_file("example.txt", "Updated".format(author), update(), file.sha)
      File "/home/dio/.local/lib/python3.7/site-packages/github/Repository.py", line 2124, in update_file
        input=put_parameters,
     File "/home/dio/.local/lib/python3.7/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
        verb, url, parameters, headers, input, self.__customConnection(url)
      File "/home/dio/.local/lib/python3.7/site-packages/github/Requester.py", line 340, in __check
        raise self.__createException(status, responseHeaders, output)
    github.GithubException.GithubException: 409 {"message": "example.txt does not match <string of very long numbers>", "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    
 The token that I'm using has full `repo` scope permissions, so why is this happening? How do I prevent it?

**Comment by YSArch** [comment]
I got the same error when running my app concurrently, but each run updates their different files at same github branch.

**Comment by s-t-e-v-e-n-k** [comment]
409 is Conflict, I'm guessing GitHub is hashing the file in question (hence <string of very long numbers>), and get back something different from it expects. My theory here is GitHub hasn't updated the storage from your last update before you send another one, leading to this explosion. My suggestions are to not update so fast using the API, or switch to a library that works on a git repository directly, such as GitPython.

**Comment by jason-jjxy** [comment]
Is there a way to find out the wait time required when updating using the API? Currently experiencing the same issue in the following code and getting the same error.

```
contents_json["plugins"][0][plugin_name] = plugin_version
print(contents_json)
print(wordpress_sha.sha)
repo.update_file("wordpress.json", "Second test of the update", str(contents_json), wordpress_sha.sha, branch=open_pr.get("branch_name"))
```
