### ISSUE TITLE
Repository' object has no attribute 'create_deployment'

### ISSUE THREAD

**Issue by getamu** [PyGithub/PyGithub#1823]
Hello, when I try to run
```
# Github Enterprise with custom hostname
g = Github(base_url="https://{hostname}/api/v3", login_or_token="sometoken")
# get the repository
repo = g.get_repo("org/repo")
# HTTP POST to /repos/:owner/:repo/deployments
deployment = repo.create_deployment(ref = 'jenkins', environment = 'DEV', description= 'Deploying to the environment')
```
I get `Repository' object has no attribute 'create_deployment'`
Why is this happening?

**Comment by s-t-e-v-e-n-k** [comment]
What version are you using? Repository.create_deployment was first added in v1.47

**Comment by getamu** [comment]
I did `pip install PyGithub` so mostly latest one (what is the command to check that). When I am doing dir(github.Deployment.Deployment) it is not showing anything as well

**Comment by s-t-e-v-e-n-k** [comment]
pip freeze would show you. What version of Python are you using?

**Comment by getamu** [comment]
yes, it is `PyGithub==1.45`.
I did the following,
`pip3 install PyGithub==1.54.1`
and to run the script I am using `python3 scriptname.py`
Now, I get 
```
status = deployment.get_status(deployment.id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/github/Deployment.py", line 178, in get_status
    headers, data = self._requester.requestJsonAndCheck(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/enterprise/2.22/rest/reference/repos#get-a-deployment-status"}
```

**Comment by s-t-e-v-e-n-k** [comment]
https://pygithub.readthedocs.io/en/latest/github_objects/Deployment.html#github.Deployment.Deployment.get_status

It is the status of the deployment id, if you're unclear, use https://pygithub.readthedocs.io/en/latest/github_objects/Deployment.html#github.Deployment.Deployment.get_status

In either case, the original issue has been solved, so I'm going to close this. Thanks!
