### ISSUE TITLE
Why does Repository.contents_url append a {+path} to the end?

### ISSUE THREAD

**Issue by Xevion** [PyGithub/PyGithub#1824]
```python
>>> repo.contents_url
'https://api.github.com/repos/PyGithub/PyGithub/contents/{+path}'
>>> repo.contents_url.format_map({'+path' : 'test'})
'https://api.github.com/repos/PyGithub/PyGithub/contents/test'
```

Simply a question about the PyGitHub API; Why does the Repository.contents_url attribute return a valid contents URL with `{+path}` appended to the end? I would almost understand `{path}`, but `{+path}` seems odd to me, and I can't find anything about this online.

It is not special python formatting to use a plus sign here (and only with `str.format_map` can you easily format it). Nothing online talks about a GitHub API URL containing `{+path}` in it's API responses (unless that's exactly what's going on here and my googling failed).

Sorry for the stupid question, but this is very odd to me, and with a lack of source code for `contents_url` attribute (i.e. I can't find it, or it's returned from the API), I'm unable to answer why there is a plus sign in the formatting field.

**Comment by s-t-e-v-e-n-k** [comment]
`Repository.contents_url` is populated directly from what the GitHub API returns, so that's what we return.
