### ISSUE TITLE
Hashable classes

### ISSUE THREAD

**Issue by xtuchyna** [PyGithub/PyGithub#1826]
Hello people!

I wonder if entities like Repository, Issue, PullRequest and etc. could be hashable in future, i.e. using them in structures like dictionary or sets would be possible?

**Comment by s-t-e-v-e-n-k** [comment]
Not currently planned, but an interesting idea.

**Comment by makusu2** [comment]
Looks like there was already a PR for this, it's just been ignored for years: https://github.com/PyGithub/PyGithub/pull/531
