### ISSUE TITLE
Cannot get private repos of user

### ISSUE THREAD

**Issue by Divkix** [PyGithub/PyGithub#1827]
I'm trying to fetch all the repositories of a user but this seems to give an error:

```
>>> print([i.name for i in g.get_user(login='Divkix').get_repos(visibility='all')])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_repos() got an unexpected keyword argument 'visibility'
```

Version: 1.54.1

**Comment by s-t-e-v-e-n-k** [comment]
Sadly, that is not supported by GitHub. The endpoint we're using for that method is https://docs.github.com/en/rest/reference/repos#list-repositories-for-a-user , and it has no support for visibility.

**Comment by Shegox** [comment]
I did run into this today as well and found a way to archive this.
When `get_user()` is invoked without parameters it returns an `AuthenticatedUser` object and `get_repos()` on that uses the `user/repos` endpoint allowing for listing of private repos as well. When `get_user("Shegox")` is invoked with a login a `NamedUser` is returned and invoking `get_repos()` on a NamedUser uses the `user/:login/repos` endpoint, returning only public repos.

Following works to list all repositories for the authenticated user (and you can only see the repos for the authenticated user):
```py
>>> print(*g.get_user().get_repos(affiliation="owner", visibility="all"), sep="\n")
Repository(full_name="Shegox/go-private-test")
Repository(full_name="Shegox/shegox.github.io")
...
```
