### ISSUE TITLE
Support for per_page in get_users method

### ISSUE THREAD

**Issue by Theremsoe** [PyGithub/PyGithub#1828]
Looking in Github API Documentation, I see that endpoint [users](https://docs.github.com/en/rest/reference/users#list-users) has support for ```per_page``` but if I compare it with ```get_users``` method the support for this query string parameter is not implemented yet. How can limit the number of items to get from this endpoint?

Thanks

**Comment by s-t-e-v-e-n-k** [comment]
It does actually support it! `MainClass.get_users` returns a `PaginatedList` which has a `get_page` method.
