### ISSUE TITLE
Question: Is PyGitHub Thread Safe?

### ISSUE THREAD

**Issue by ptwobrussell** [PyGithub/PyGithub#183]
Is PyGitHub thread safe? For example, if I were to use a thread pool to repeatedly make calls a function like get_followers() which is calling http://developer.github.com/v3/users/followers/ under the hood, is there any danger that you know of within 1) PyGitHub itself and 2) with the way that GitHub's API would respond?

**Comment by dzieciou** [comment]
An alternative would be two create multiple instances of `GitHub` class. I guess instances would be isolated enough from each other.
