### ISSUE TITLE
404 Response for repo.create_git_tree()

### ISSUE THREAD

**Issue by ohurtubise** [PyGithub/PyGithub#1830]
Hello!

I have a script running on a daily schedule which pushes a JSON data file to a repo where a separate service is able to retrieve and use it. The purpose of pushing daily is to make sure the data file is the most up to date version. Was able to get this working, but never got around to implementing it until recently. Worked first time I ran it, but now I get a 404 response every time. Here is the error message: 

"github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/enterprise/2.22/rest/reference/git#create-a-tree"}"

My code:
`
from github import Github
from github import InputGitTreeElement
import datetime

token = "<my token>"
g = Github(login_or_token=token)
repo = g.get_repo('ohurtubise/PyGit') 
fileName = "Processed-Taxonomy_master.json"
commitMessage = "Updated Taxonomy {}".format(datetime.date.today())
branch_ref = repo.get_git_ref('heads/master')
branch_sha = branch_ref.object.sha
base_tree = repo.get_git_tree(branch_sha)
element_list = list()
data = open('taxonomy.json').read()
element_list.append(InputGitTreeElement(fileName,'100644','blob',data))
tree = repo.create_git_tree(element_list)
parent = repo.get_git_commit(branch_sha)
commit = repo.create_git_commit(commitMessage, tree, [parent])
branch_ref.edit(commit.sha)
`
taxonomy.json is the file being pushed.
I get the 404 error after trying "tree = repo.create_git_tree(element_list)"
I also tried "tree = repo.create_git_tree(element_list, base_tree)", but still same error. Anything else I can provide to help troubleshoot please let me know. Not the most familiar with the intricacies of Github like commit sha and such so excuse my noob-ness if I sound like one haha

**Comment by jantman** [comment]
How did you solve this?
