### ISSUE TITLE
contents.decoded_content python types error

### ISSUE THREAD

**Issue by WixoLeo** [PyGithub/PyGithub#1833]
Fantastic day everyone!

There is a little typing issue with the library, specifically with the `contents.decoded_content` attribute.
While it works fine, our type linter (mypy) screams that there is no such attribute.

Is that an issue with `MyPy` or with `pygithub` library? Or am I don't something wrong?

Here is a minimal working example:
```py
from github import Github
github_client = Github(token)
repo = github_client.get_repo(repo_name)
contents = repo.get_contents(file_path, ref="master")
print(json.loads(contents.decoded_content))
# MyPy Error:
# Item "List[ContentFile]" of "Union[List[ContentFile], ContentFile]" has no attribute "decoded_content"
```

**Comment by s-t-e-v-e-n-k** [comment]
Sorry, I missed this bug! This is your issue, you're calling decoded_content on a list, not on a ContentFile object directly -- if GitHub returns a list, we do as well, so you need to check for that and iterate over it if required.

**Comment by WixoLeo** [comment]
> Sorry, I missed this bug! This is your issue, you're calling decoded_content on a list, not on a ContentFile object directly -- if GitHub returns a list, we do as well, so you need to check for that and iterate over it if required.

Ahh I see, thank you!

**Comment by zepptron** [comment]
hey @s-t-e-v-e-n-k !
I'm a little lost here unfortunately. I'm facing the same "issue" currently but I dont know how this could be implemented properly. could you provide an example please?

thats what I have: 
```python
conts = repo_client.get_contents(
  path="",
  ref=f"refs/heads/{branch}")

files = {
  "name": conts.path,
  "sha": conts.sha
}
```

it works, but mypy complains about "path" and "sha" not being attributes. If I iterate over it mypy complains that this class doesnt have `__iter__` :-/ 

Would be nice if you could push me in the right direction
