### ISSUE TITLE
#1783 made pygithub incompatible with Python 3.5 (py35)

### ISSUE THREAD

**Issue by rs2** [PyGithub/PyGithub#1836]
#1783 introduced f-strings, which are py36+: https://github.com/PyGithub/PyGithub/blame/34d097ce473601624722b90fc5d0396011dd3acb/github/MainClass.py#L340

Xref: #1801, #1783

CC: @s-t-e-v-e-n-k , @sfdye

**Comment by pascal-hofmann** [comment]
Python 3.5 reached EOL 4 months and 3 weeks ago (13 Sep 2020).

See https://endoflife.date/python

**Comment by sfdye** [comment]
Like what @pascal-hofmann said, as we are moving to support the newer and stable versions of Python, if you want to stay on Python 3.5 you can alway use an older version, e.g `PyGithub<1.54.1`
