### ISSUE TITLE
Request for a new release

### ISSUE THREAD

**Issue by maorfr** [PyGithub/PyGithub#1847]
Hello!

Thank you all for this great tool! We are using it extensively. We have made a small contribution in https://github.com/PyGithub/PyGithub/commit/6900f187b53711d7e9e43fcadede2e44d7d12f7d and were wondering when are you planning to cut a new release?

Thanks in advance!

cc @apahim

**Comment by maorfr** [comment]
hey @s-t-e-v-e-n-k! any chance you are planning to cut a new release soon?

thanks a lot!

**Comment by tbrrt11** [comment]
Hi guys! Does anybody know when is next release coming?

**Comment by phlax** [comment]
+1 it would be good to fix pyjwt incompatibilities

**Comment by jharris-tc** [comment]
+1 this would be very helpful for me

**Comment by Apreche** [comment]
+1 I am using the secrets functionality that is not yet released, and it's a little bothersome to install from the git repo instead of pypi.

**Comment by s-t-e-v-e-n-k** [comment]
https://pypi.org/project/PyGithub/1.55/ has been released

**Comment by maorfr** [comment]
thanks a lot!

**Comment by jharris-tc** [comment]
thank you very much!
