### ISSUE TITLE
Error logging in with username and password.

### ISSUE THREAD

**Issue by MikeMNelhams** [PyGithub/PyGithub#1851]
I am writing a project that should be able to allow specific users to automatically perform some actions on some file contents after logging in. I tried to alter some of the code and I'm getting some strange behaviour.

I have scoured the internet and I am literally using the exact documented code as copy and pasted, yet it always returns: github.GithubException.GithubException: 401 {"message": "Requires authentication", "documentation_url": "https://docs.github.com/rest/reference/users#get-the-authenticated-user"}. 

My username and password are correct before you ask. I have run my code with PATkey tokens to ensure the rest of it works, but I obviously cannot distribute those publicly. The passwordbox function will return the string password put into this, so this isn't the issue either. From what I gather, this code should run perfectly fine, but it doesn't for me: 
https://pygithub.readthedocs.io/en/latest/introduction.html
https://stackoverflow.com/questions/46524697/login-problems-using-pygithub

I can't find _any_ working examples of logging in with username and password, only tokens. Is it possible my code is not the issue?

Here is my code which causes the error: 
```python
from github import Github
from easygui import passwordbox  # This works similarly to getpass, but works for pycharm without going to terminal. 

def login():
    # Ask for login details
    username = input("Username? ")
    _password = passwordbox("Please enter your password for user: {} ".format(username))

    # Login
    g = Github(username, _password)
    del _password 
    user = g.get_user()
    
    login = user.login
    print("Login Successful!")

login()
```
I hope that I'm an idiot and that the solution is simple. I understand that the initial github instance is unauthorised, but that error message tells that I am required to login before I login?! Surely

**Comment by MikeMNelhams** [comment]
Nevermind, you NEED to update your main page documentation. Github deprecated the use of username/password login for anything besides direct website login https://hackaday.com/2020/09/15/githubs-move-away-from-passwords-a-sign-of-things-to-come/. Update this: https://pygithub.readthedocs.io/en/latest/introduction.html, please. The code above would have worked half a year ago.

**Comment by erinn** [comment]
For the record it unfortunately isn't exactly as simple as this. For github.com username/password is no longer possible with the API as noted. However, for GitHub Enterprise Server (the self hosted on premise server) username and password is still an option: https://docs.github.com/en/enterprise-server@3.1/rest/overview/other-authentication-methods for 99% of users they won't ever care and as such the docs being as they are are fine. But I just wanted to note this here for the other 1%.
