### ISSUE TITLE
AuthenticatedUser.get_emails() returned data changed to list of dicts

### ISSUE THREAD

**Issue by cbrianhill** [PyGithub/PyGithub#1852]
According to the [provided type information](https://github.com/PyGithub/PyGithub/blob/master/github/AuthenticatedUser.pyi#L111) for `AuthenticatedUser`, the `get_emails` function returns a list of string.  However, in my experience with version 1.54.1 of this module, it appears to return a list of dictionaries that looks like the following:

```
[
  {
    "email": "xxx@yyy.com",
    "primary": false,
    "verified": true,
    "visibility": null
  },
  ...
]
```

**Comment by s-t-e-v-e-n-k** [comment]
It used too, and in fact our test suite still works based on that assumption. https://github.com/PyGithub/PyGithub/blob/master/tests/AuthenticatedUser.py#L101

So it looks like GitHub has changed the API out from under us.
