### ISSUE TITLE
Include GitHub App usage in doc/examples

### ISSUE THREAD

**Issue by swinton** [PyGithub/PyGithub#1855]
It would be great to have an example showing how to use PyGithub with [GitHub Apps](https://docs.github.com/en/developers/apps/creating-a-github-app).

GitHub Apps are a "first class vehicle" for integrating with GitHub, and [offer several benefits over OAuth / Personal Access Tokens](https://docs.github.com/en/developers/apps/migrating-oauth-apps-to-github-apps#reasons-for-switching-to-github-apps).

I have [some demo code](https://github.com/swinton/pygithub-playground/blob/main/demo.py) that works, and I'd be happy to submit a PR for this example, if that would be a welcome addition.

**Comment by goldstar611** [comment]
I second this. Having some good reference scripts, even if they're 10 lines each, would be very helpful. I'm actually in the process of migrating from your `github-app-demo.py` repo to this repo :)

**Comment by s-t-e-v-e-n-k** [comment]
Please do submit a PR!
