### ISSUE TITLE
GitHub Class Doesn't Clean-up Connections After Use

### ISSUE THREAD

**Issue by Philip-Mais** [PyGithub/PyGithub#1859]
The following code in unit test throws ResourceWarning for open connections and I cannot see a method to use to close these down. Am I missing something, or is this a possible memory/connection leak oversight?

```
repository = "someuser\somerepository"
connection = Github (self.token)
connection.get_repo (repository).get_latest_release ().get_assets () [0]
del connection
```

**Comment by jobveldhuis** [comment]
I haven't been able to dive in the code right now. I think it might have something to do with the design decision to keep connections open so they can be reused. Is there a specific reason for you to delete the connection object?

**Comment by Philip-Mais** [comment]
Hi @jobveldhuis, that sounds a reasonable conclusion and therefore sounds like the connection leak warning may be a "by design" thing in this library.
The reason I'm deleting the connection object in my unit test is because each unit test is instantiating a new connection as some settings potentially change between unit tests as a result of me unit testing input validation into my app. It's highly unlikely this will cause me an issue in the real-world use of the code as in real-world use I would only ever open and use the 1 connection to GitHub and therefore the "leaked connection" would close with the app. It's more me trying to ensure my ResourceWarning in unit testing isn't surfacing my incorrect use of the library.
Thanks

**Comment by jobveldhuis** [comment]
You're welcome. What library are you using for unit testing? Because I think you could pull these tests off without the ResourceWarning by using some sort of 'setup' function that is ran before every individual test.

**Comment by Philip-Mais** [comment]
I'm using unittest natively in Python. I can suppress with a warnings.simplefilter ("ignore", ResourceWarning) call immediately before the call that orphans a connection. I am only using this where I call the method that orphans the connection though, so I can catch any other programming issues I may have elsewhere in my code.

**Comment by s-t-e-v-e-n-k** [comment]
Yes, it's a design decision to persist connections -- HTTPS is a heavy weight protocol, given it requires client and server to exchange keys and agree on SSL ciphers to use, so anything we can do to cut down on that negotiation is a big win. There is an internal variable inside the Requester class that you can reach in and set to False if you really want to experiment (called `__persist`).

**Comment by hemslo** [comment]
We are using `PyGithub` in a dynamic way, create different `Github` object on demand, we found there are multiple session connection pools exist at the same time, those connections are not closed until GC. After digging into `PyGithub` code, I found several issues:

1. misleading class attribute `__connection` in [Requester.py](https://github.com/PyGithub/PyGithub/blob/bcca758d13ef466a7ae13f4d9d99689ba0043640/github/Requester.py#L233C1-L233C1), all [usages](https://github.com/PyGithub/PyGithub/blob/bcca758d13ef466a7ae13f4d9d99689ba0043640/github/Requester.py#L809C10-L809C10) are supposed to be instance attribute.
2. `Requester` is not thread safe, when there are multiple usages from different threads, `__connection` can be overwritten.
3. there is no easy way to close session in [HTTPSRequestsConnectionClass](https://github.com/PyGithub/PyGithub/blob/bcca758d13ef466a7ae13f4d9d99689ba0043640/github/Requester.py#L101) or [HTTPRequestsConnectionClass](https://github.com/PyGithub/PyGithub/blob/bcca758d13ef466a7ae13f4d9d99689ba0043640/github/Requester.py#L168).
4. connections created by [__customConnection](https://github.com/PyGithub/PyGithub/blob/bcca758d13ef466a7ae13f4d9d99689ba0043640/github/Requester.py#L468) are not collected, there is no way to close them afterwards.

Proposals:
1. change class attribute `__connection` to instance attribute explicitly.
2. guard `__connection` with a lock when write to it.
3. add a `close` method to `Requester` and used in MainClass like:
    ```python
       with Github(auth=auth) as g:
         # do something
    ```
    and can call it explicitly
    ```python
        g = Github(auth=auth)
        # do something
        g.close()
    ```
4. collect all connections created by `__customConnection` and close them in `close`

If above proposals sound good, I can prepare a PR for it.
