### ISSUE TITLE
Update token used by requester

### ISSUE THREAD

**Issue by stephenmuss** [PyGithub/PyGithub#1860]
I'm using PyGithub in a Github app and use some logic to manage tokens and to refresh when necessary.

It would be helpful if there was a mechanism in `Github` objects to update the token used by the requester and to reset its `__authorizationHeader`.

This looks like it would be straight-forward enough and I'd be happy to contribute, but I'd want to make sure I consider any other use cases and how they ought to be included.

For example, is it enough to include something along the following lines?

```py
# Requester.py
class Requester:
    def update_login_or_token(self, login_or_token):
        self.__authorizationHeader = "token " + login_or_token


# MainClass.py
class Github:
    def update_login_or_token(self, login_or_token):
        self.__requester.update_login_or_token(login_or_token)
```

**Comment by s-t-e-v-e-n-k** [comment]
Okay, I will admit I can foresee at least one use case here, where you want to a super-powered token for only some requests, like deleting assets. Personally, as long as the code is documented, and tested sounds fine to include to me if you want to put up a PR. `Requester.update_login_or_token` probably won't be quite that simple, but it looks like a good start.

**Comment by alirezaimn** [comment]
Updating the token can be super helpful. I'm having trouble using PyGithub to fetch dozens of commits from many repositories. If a feature to rotate between a list of API tokens is added, once a RateLimitException is raised, the requested object can switch to the next available token.
