### ISSUE TITLE
Can I create an organization in GHE?

### ISSUE THREAD

**Issue by mda590** [PyGithub/PyGithub#1863]
Hello!

I am trying to create a new organization in GitHub Enterprise, but I can't seem to find a way to do it. Is this not implemented or am I missing something completely obvious?

Thanks!
Matt

**Comment by jobveldhuis** [comment]
Hey there, this is currently not implemented in the Github API. You can see the documentation [here](https://docs.github.com/en/enterprise-server@2.21/rest/overview/endpoints-available-for-github-apps#orgs).

**Comment by mda590** [comment]
Thanks for that @jobveldhuis! I should have updated this. I found that GHE server has an extra admin API which allows for a bunch of other actions to be taken, including creating an organization. Docs are [here](https://docs.github.com/en/enterprise-server@3.0/rest/reference/enterprise-admin#create-an-organization). I've forked this project to add those additional endpoints for internal use - will try to contribute it back here once complete.
