### ISSUE TITLE
top-level directory in tarball is different when using `get_latest_release()` than on the tags page

### ISSUE THREAD

**Issue by sandrotosi** [PyGithub/PyGithub#1871]
Hello,
i'm not even sure it's a _bug_ in PyGithub or somewhere else, but here's what i have:

if i go [here](https://github.com/pydata/pydata-sphinx-theme/tags) and download v0.4.3 tar.gz (fullurl: https://github.com/pydata/pydata-sphinx-theme/archive/v0.4.3.tar.gz) i end up with a tarball that has as top-level directory `pydata-sphinx-theme-0.4.3`

but if i try to do a similar operation with PyGithub:

```
In [82] g = Github()

In [83]: repo = g.get_repo("pydata/pydata-sphinx-theme")

In [84]: repo.get_latest_release().tarball_url
Out[84]: 'https://api.github.com/repos/pydata/pydata-sphinx-theme/tarball/v0.4.3'
```

and then download that URL, the resulting tarball has a top-level directory name `pydata-pydata-sphinx-theme-0528853`; the content is exactly the same, just the top-level dir is different

now, i can clearly see the URLs are different, but why they top-level directory is too? it's not repo-dependent.

is there a better way to download the same tarball i'd get from the GH tags page via PyGithub? i hope that's not something like `"https://github.com/USER/REPO/archive/"{}'.tar.gz'` cause that'd suck :)

thanks!

**Comment by s-t-e-v-e-n-k** [comment]
This is likely an artifact of GitHub, not our code, we have no visibility into how GitHub constructs tarballs that are linked from the API. I'm guessing that tarball is generated from the commit, hence the directory name.

I'd suggest looking at something like this:

```
>>> repo = g.get_repo("PyGithub/PyGithub")
>>> tags = repo.get_tags()
>>> tags[4]
Tag(name="v1.54.1", commit=Commit(sha="34d097ce473601624722b90fc5d0396011dd3acb"))
>>> tags[4].tarball_url
'https://api.github.com/repos/PyGithub/PyGithub/tarball/refs/tags/v1.54.1'
```
