### ISSUE TITLE
Documentation - Features for unreleased versions

### ISSUE THREAD

**Issue by calebstewart** [PyGithub/PyGithub#1873]
I'm currently in the early stages of a project which will use this module, and based on the docs found [here](https://pygithub.readthedocs.io/en/latest), the project currently supports creation of repository secrets, which is a feature that I require. However, upon further inspection, this appears to be a v2.0.0 feature which is not released on PyPi yet. 

Is it possible to either make the `latest` version on `ReadTheDocs` refer to the latest release version, or alternatively at least mark features that do not exist in the latest version as such in the documentation? This isn't an "end of the world" thing, but it confused me for a bit, and took some searching to understand why the feature I was reading about in the documentation was not available on an up-to-date installation.

Thanks for all you do! This project is super useful, and well documented. :)

**Comment by s-t-e-v-e-n-k** [comment]
Not a v2.0.0 feature, it's merged in master and will be in our next release. You've done a good job at enumerating our two choices -- marking features as 'unreleased' is probably impractical without teaching Sphinx how to do so. When I have some time, I will see if we can shift readthedocs to using the latest tag, not HEAD of master.

**Comment by Phuurl** [comment]
@s-t-e-v-e-n-k Sorry to ask, but are there any estimates for when the next release including Secrets support will be? 

I'm also currently looking to use it in a project, and although I can just use it by installing straight from `master`, it'd definitely be nicer to be able to install a versioned release for it!

No worries if not though 😀

**Comment by Phuurl** [comment]
Ah nice, looks like it was included in yesterday's 1.55 release - cheers 🚀
