### ISSUE TITLE
get_issues method returns the open issues and pull requests

### ISSUE THREAD

**Issue by tareq97** [PyGithub/PyGithub#1874]
As shown in the screenshot it queries 104 issues i.e Issues(77) + PullRequest(27) = 104. According to the tool documents it should only get the open issues but it is also fetching the pull request. Is this expected behavior? 

![image](https://user-images.githubusercontent.com/10094302/111087386-9ed36080-8521-11eb-88b4-85ecae727922.png)

Note: If there is option to query only issues please let me know.

**Comment by s-t-e-v-e-n-k** [comment]
From GitHub's API docs:

```
Note: GitHub's REST API v3 considers every pull request an issue, but not every issue is a pull request. For this reason, "Issues" endpoints may return both issues and pull requests in the response. You can identify pull requests by the pull_request key.
```
