### ISSUE TITLE
How to know if a File in commit.files has been deleted or not?

### ISSUE THREAD

**Issue by rajobasu** [PyGithub/PyGithub#1875]
When I see the files in commit.files, for some commit, how to know whether that is actually a file deletion, since then trying to get it’s contents throws a 404. The variables associated with files or commit doesn’t really show this, or maybe I am reading the documentation wrong.

**Comment by s-t-e-v-e-n-k** [comment]
`File` has a `status` that gives that information, like in the following example:

```
>>> repo = g.get_repo("PyGithub/PyGithub")
>>> c = repo.get_commit("69bfc3251148ef4ac119f0ab2a11a734ddf63ee0")
>>> for file_ in c.files:
...     file_.filename
...     file_.status
... 
'tests/NamedUser.py'
'modified'
'tests/ReplayData/NamedUser.testGetReposWithAllArgs.txt'
'added'
'tests/ReplayData/NamedUser.testGetReposWithType.txt'
'removed'
```
