### ISSUE TITLE
Performance Issue: Check if github.IssueEvent.IssueEvent has an Assignee takes long

### ISSUE THREAD

**Issue by MaximilianKarl** [PyGithub/PyGithub#1885]
Case:

I want to read out the information from the IssueEvent.
Not all IssueEvents have an Assignee/Assigner.

Minimum Code:
```{python}
import cProfile

def test(event):
    if event.assignee is not None:
        return
issues = repo.get_issues(state='all')
for issue in issues:
    for event in issue.get_events():
        cProfile.run("test(event)")
        cProfile.run("test(event)")
```

Results

1.  **event.assignee is None:**
      First Run:
      6182 function calls (6158 primitive calls) in 0.236 seconds
      Second Run:
      7 function calls in 0.000 seconds
2. **event.assignee is not None:**
      First Run:
      7 function calls in 0.000 seconds
      Second Run:
      7 function calls in 0.000 seconds

Is there a faster way to check if IssueEvent has an Assignee?

I have the same problem with Labels and Assigner too.

**Comment by s-t-e-v-e-n-k** [comment]
So the issue as I can see it is you're only interested in a subclass of IssueEvents, and you need to enumerate all of them, is this correct? Sadly, we are the mercy of whatever the GitHub API provides, and I can't see a way to request a subset of events.

**Comment by MaximilianKarl** [comment]
Well i need some other informations of the Issue and IssueEvent too. I have to check if there is an assignee or not. Otherwise i will get an exception when there is no assignee. When there is now assignee it takes around 0.2 seconds and when i itterate all issues and Events then it takes al long time to gather the informations about the repository.

I guess the problem is when there is no Assignee the it needs to initiallize first a None NamedUser with the 6000 function calls.

**Comment by MaximilianKarl** [comment]
The problem is the completeIfNotSet call. So there is no way to check if the value is set without calling the completeIfNotSet Method

```(python)
@property
    def assignee(self):
        """
        :type: :class:`github.NamedUser.NamedUser`
        """
        self._completeIfNotSet(self._assignee)
        return self._assignee.value
```

**Comment by s-t-e-v-e-n-k** [comment]
Then short-circuit it if you wish by getting the value, but you get to keep both pieces if it breaks.

**Comment by s-t-e-v-e-n-k** [comment]
We have absolutely no way of knowing if what GitHub returned populated all fields, so we need to check.

**Comment by MaximilianKarl** [comment]
How should short-circuit help me here?

**Comment by MaximilianKarl** [comment]
Found a solution:

changed:
```(python)
if event.assignee is not None:
```
to:

```(python)
if event._assignee == github.GithubObject.NotSet:
```

then i get around the _completeIfNotSet. 

Maybe you want to document this in readsthedocs.

**Comment by s-t-e-v-e-n-k** [comment]
Lovely! I'm going to close this issue, but I would welcome a PR adding an example.
