### ISSUE TITLE
Is it possible to generate analytics for a certain branch using PyGitHub??

### ISSUE THREAD

**Issue by HemanthVenki910** [PyGithub/PyGithub#1895]
We want to explore the possibility of generating analytics for a certain in Github, Some Analytics would be number of commits into the certain branches, top contributors for the said branch and similar metrics, If yes, How?

**Comment by s-t-e-v-e-n-k** [comment]
Yes, it is possible -- I'd start by investigating the https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.get_commits method.

**Comment by HemanthVenki910** [comment]
We have gone through the said documentation, these analytics are with respect to the entire repository as a whole and not focus on a certain branch, 
My fault not mentioning the complete details, we need analytics on a certain branch in the repo, not the repo as a whole

**Comment by s-t-e-v-e-n-k** [comment]
Branches are only a pointer to a certain commit in a Repository, so any operation you do will almost certainly be on the repository, but you can find the HEAD of a branch using https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.get_git_ref , and then inspecting the parents of that reference.
