### ISSUE TITLE
Access the `assets` field in releases response to avoid extra requests

### ISSUE THREAD

**Issue by green-green-avk** [PyGithub/PyGithub#1898]
1. A response to `GET /repos/{owner}/{repo}/releases` already contains an assets list for each release.
2. **GitHub** has [Rate limiting](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting).

So, it's better to have an ability to access this list.

**Comment by green-green-avk** [comment]
Pull request: <https://github.com/PyGithub/PyGithub/pull/1899>

**Comment by Felixoid** [comment]
The issue is not solved yet and the PR wasn't merged
