### ISSUE TITLE
installing PyGithub via .zip from github doesnt work for v2.0.0-alpha.4 (No module named 'uritemplate')

### ISSUE THREAD

**Issue by macolo** [PyGithub/PyGithub#1900]
- No module named 'uritemplate'
- v2.0.0-alpha.4

Workaround:

- requirements.txt: 
```
https://github.com/PyGithub/PyGithub/archive/refs/tags/v2.0.0-alpha.4.zip#egg=PyGithub
uritemplate  # this should be part of PyGithub's setup.py - for some reason it is not
```
- import as `from PyGithub.Blocking import Github`

**Comment by s-t-e-v-e-n-k** [comment]
The v2.0.0-alpha4 tag was created in 2014, and that branch hasn't been touched since roughly that long. The current release is v1.54.1.

**Comment by walterrowe** [comment]
@s-t-e-v-e-n-k you can update which commit is associated with a given tag.

```shell
$ git tag -a -f -m 'tag message' 'tag'
$ git push -f --tags
```

For 'tag' it will force updating the tag to be associated with the latest commit.

I don't know that it makes sense to do it for this case. Just stating that they can be updated.
