### ISSUE TITLE
Modify existing issue

### ISSUE THREAD

**Issue by johnnyjacq16** [PyGithub/PyGithub#1903]
Is there a way to modify existing GitHub issues?
Example add more text to the body, change the labels and assignees of issue.
I am not seeing any examples in the documentation https://pygithub.readthedocs.io/en/latest/examples.html
@s-t-e-v-e-n-k @sfdye @dhruvmanila

**Comment by s-t-e-v-e-n-k** [comment]
Please don't tag us when filing issues, we will see it.

Everything you're asking about is documented in the reference -- the examples are more to get you started.

The at least three methods you are interested in are:
https://pygithub.readthedocs.io/en/latest/github_objects/Issue.html#github.Issue.Issue.add_to_assignees
https://pygithub.readthedocs.io/en/latest/github_objects/Issue.html#github.Issue.Issue.add_to_labels
https://pygithub.readthedocs.io/en/latest/github_objects/Issue.html#github.Issue.Issue.edit
