### ISSUE TITLE
Modify existing issue (update)

### ISSUE THREAD

**Issue by johnnyjacq16** [PyGithub/PyGithub#1904]
Thank s-t-e-v-e-n-k  for your help, I am new to this api and still am learn the Bells and whistles.
I have set the following which is currently working:

` g = Github(my github token)`
` repo = g.get_repo(my repo)`

The below is not working but I don't know what I am doing wrong
 edit(title=NotSet, body=NotSet, assignee=NotSet, state=NotSet, milestone=NotSet, labels=NotSet, assignees=NotSet)

![image](https://user-images.githubusercontent.com/46075870/113464600-b9fd0600-9425-11eb-9f39-881b67969fc4.png)

**Comment by s-t-e-v-e-n-k** [comment]
You can't use `edit()` to change labels or assignees, that was the other two methods. Further more, that is `Repository.edit()`, if you want to edit an issue, you need to fetch it:

```
>>> repo = g.get_repo("PyGithub/PyGithub")
>>> issue = repo.get_issue(1904)
>>> issue.title
'Modify existing issue (update)'
```
