### ISSUE TITLE
Rate.reset is missing a timezone

### ISSUE THREAD

**Issue by lazka** [PyGithub/PyGithub#1905]
```pycon
>>> from github import Github
>>> gh = Github()
>>> limit = gh.get_rate_limit()
>>> print(limit.core.reset)
2021-04-03 09:16:53
>>> print(limit.core.reset.tzinfo)
None
>>>
```

It seems like pygithub throws away the timezone information (UTC) so I have to use `limit.core.reset.replace(tzinfo=timezone.utc)`

**Comment by s-t-e-v-e-n-k** [comment]
Actually any date returned is naive, there's a PR up, I need more time to review it and contemplate its consequences.

**Comment by lazka** [comment]
Yeah, tricky. There is a chance that existing code might break when comparing to other naive datetime objects:

```py
>>> from datetime import datetime, timezone
>>> datetime.utcnow() - datetime.now(timezone.utc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't subtract offset-naive and offset-aware datetimes
```

**Comment by viniciusd** [comment]
> ```
> >>> from github import Github
> >>> gh = Github()
> >>> limit = gh.get_rate_limit()
> >>> print(limit.core.reset)
> 2021-04-03 09:16:53
> >>> print(limit.core.reset.tzinfo)
> None
> >>>
> ```
> 
> It seems like pygithub throws away the timezone information (UTC) so I have to use `limit.core.reset.replace(tzinfo=timezone.utc)`

Are we guaranteed the rate.reset comes in UTC? I can't find information on the Github docs indicating the timezone, but they do affirm some resources use the last known timezone for the authenticated user, I wonder if it is the case for rate limiting as well, I am seeing some weird rate.reset values

**Comment by EnricoMi** [comment]
Docs have been updated, reset is in UTC:

https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limit-headers

> x-ratelimit-reset | The time at which the current rate limit window resets in UTC epoch seconds.
