### ISSUE TITLE
Get when an issue's labels changed, and what those changes were

### ISSUE THREAD

**Issue by Joshuaalbert** [PyGithub/PyGithub#1908]
Hi, I love this project. Would it be possible to determine when label change events occurred, and what the changes were?
Simple scenario would be to return for each such event a date, labels removed, and labels added. Super useful for tracking ticket status as it migrates through a ticket tracking system, e.g. Yoda. 

Here's an example of the events that I'm referring to:

![Screenshot from 2021-04-06 12-57-22](https://user-images.githubusercontent.com/14807032/113749539-08eaba00-970a-11eb-8796-43c4d4b1a3bc.png)

**Comment by s-t-e-v-e-n-k** [comment]
The `Issue` object has a method `get_events()` that allows you see that -- which returns a PaginatedList of https://pygithub.readthedocs.io/en/latest/github_objects/IssueEvent.html . If you filter on status being labelled and unlabelled as documented at https://docs.github.com/en/developers/webhooks-and-events/issue-event-types#labeled , that should allow you to collect the information you're after.
