### ISSUE TITLE
Error 401: "message: requires authentication"

### ISSUE THREAD

**Issue by maooam27** [PyGithub/PyGithub#1910]
Ok so, I'm trying to pull one of my repositories and when I try to print my repos, it says this:
`GET https://api.github.com/user/repos {'Authorization': 'Basic (login and password removed)', 'User-Agent': 'PyGithub/Python'} None ==> 401 {'server': 'GitHub.com', 'date': 'Tue, 06 Apr 2021 10:14:55 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '149', 'x-github-media-type': 'github.v3; format=json', 'x-ratelimit-limit': '60', 'x-ratelimit-remaining': '51', 'x-ratelimit-reset': '1617706651', 'x-ratelimit-used': '9', 'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'access-control-allow-origin': '*', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'x-frame-options': 'deny', 'x-content-type-options': 'nosniff', 'x-xss-protection': '0', 'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'content-security-policy': "default-src 'none'", 'vary': 'Accept-Encoding, Accept, X-Requested-With', 'x-github-request-id': 'DA55:162D:AD01A6C:AFA4B43:606C349F'} {"message":"Requires authentication","documentation_url":"https://docs.github.com/rest/reference/repos#list-repositories-for-the-authenticated-user"}
Traceback (most recent call last):
  File "<pyshell#15>", line 1, in <module>
    for repo in repos:
  File "C:\Users\mfede\AppData\Local\Programs\Python\Python38\lib\site-packages\github\PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "C:\Users\mfede\AppData\Local\Programs\Python\Python38\lib\site-packages\github\PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "C:\Users\mfede\AppData\Local\Programs\Python\Python38\lib\site-packages\github\PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "C:\Users\mfede\AppData\Local\Programs\Python\Python38\lib\site-packages\github\Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "C:\Users\mfede\AppData\Local\Programs\Python\Python38\lib\site-packages\github\Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 401 {"message": "Requires authentication", "documentation_url": "https://docs.github.com/rest/reference/repos#list-repositories-for-the-authenticated-user"}`

Could anybody help me?

Edit: I checked and I found that I've activated the 2FA but I dunno how to continue now, cuz I need it.

**Comment by then4p** [comment]
Having the same issue. This seems to be due to the new token formats. With an old token without the ghp_ prefix everything works. 

The new token is valid (tested with a curl) but does not work with pygithub.

**Comment by maooam27** [comment]
So what should I do?
Do I have to implement curl, or it's better to let the repo public and download it with curl?

**Comment by s-t-e-v-e-n-k** [comment]
@maooam27 You need to generate a token, that Authorization header says you're using login and password, which will not work with 2FA.

@then4p What ghp_ prefix? Every token I've generated for GitHub is a 40 character hex string?

**Comment by then4p** [comment]
@s-t-e-v-e-n-k https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/

You can still use 'old' tokens, but every newly generated one following the above format does not work anymore.

**Comment by s-t-e-v-e-n-k** [comment]
@then4p I just generated a new one, and it worked fine?

```
>>> from github import Github
>>> g = Github("ghp_<rest of token removed>")
>>> repo = g.get_repo("PyGithub/PyGithub")
>>> repo
Repository(full_name="PyGithub/PyGithub")
```
