### ISSUE TITLE
PullRequest `totalCount` not correct for larger repos

### ISSUE THREAD

**Issue by sc250024** [PyGithub/PyGithub#1911]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

I'm using the `totalCount` attribute of the [`PullRequest`](https://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html) class, and I noticed that sometimes the count is wrong.

Here's some very simple example code I'm using:

<details>
<summary>Code for my org</summary>

```python
import github
import os

gh = github.Github(os.environ["GITHUB_TOKEN"])
org = gh.get_organization("my-company-org")

# PR count is currently at 2119
repo = org.get_repo("some-large-repo")

prs_all = repo.get_pulls(state="all")
prs_open = repo.get_pulls(state="open")
prs_closed = repo.get_pulls(state="closed")

print(prs_all.totalCount)    # Returns '2018'
print(prs_open.totalCount)   # Returns '10'
print(prs_closed.totalCount) # Returns '2008'
```

</details>

<details>
<summary>Code for PyGitHub</summary>

```python
import github
import os

gh = github.Github(os.environ["GITHUB_TOKEN"])
org = gh.get_organization("PyGithub")

# PR count is currently at 1909
repo = org.get_repo("PyGithub")

prs_all = repo.get_pulls(state="all")
prs_open = repo.get_pulls(state="open")
prs_closed = repo.get_pulls(state="closed")

print(prs_all.totalCount)    # Returns '795'
print(prs_open.totalCount)   # Returns '25'
print(prs_closed.totalCount) # Returns '770'
```

</details>

That's off by 101 pull requests.

* **What is the expected behavior?**

The `totalCount` _should_ be `2119` as seen above and by checking it manually in the browser.

* **Please tell us about your environment:**
  
- `PyGithub==1.54.1`
- `Python 3.9.2`
- macOS Catalina 10.15.7

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I noticed that this `PyGithub` repo has the same issue. Is this about how the underlying GitHub API counts PR numbers?

Here are some screenshots that show the current pull request numbers on the repo in question.

<details>
<summary>PR with the largest number 2119</summary>

<img width="889" alt="Screen Shot 2021-04-06 at 18 13 56" src="https://user-images.githubusercontent.com/8792243/113744278-e013f600-9704-11eb-9928-d7f66ec8e3a5.png">

</details>

**Comment by s-t-e-v-e-n-k** [comment]
Issues and Pull Requests share numbers, as in as much that every pull request is an issue, but not every issue is a pull request. Have you factored that into your counts at least for this repository?

**Comment by YoungBrady** [comment]
> Issues and Pull Requests share numbers, as in as much that every pull request is an issue, but not every issue is a pull request. Have you factored that into your counts at least for this repository?

So how can I  know which is an Issue or a Pull Request?

**Comment by s-t-e-v-e-n-k** [comment]
There is a `pull_request` method that is not None if it's a PR, like so:

```
>>> repo = g.get_repo("PyGithub/PyGithub")
>>> issues = repo.get_issues(state="open")
>>> for i in issues[:5]:
...     kind = "Issue"
...     if i.pull_request:
...             kind = "PR"
...     print(f"{kind}: {i.title}")
... 
PR: Add comment on issue example
PR: github/MainClass: Fix GitHubException instantiation
PR: Move lint and docs to Python 3.8
PR: ADD code scanning results
Issue: Provide a way to make a "raw" request
```
