### ISSUE TITLE
Files in git repo issues 

### ISSUE THREAD

**Issue by johnnyjacq16** [PyGithub/PyGithub#1912]
Hi s-t-e-v-e-n-k
How to create an issue with a file, the file itself will be posted and not the contents of the file.

**Comment by johnnyjacq16** [comment]
Hi s-t-e-v-e-n-k,
I did some research and found this article, https://github.community/t/how-to-upload-a-file-using-github-api/14031

The command is:
`http PUT https://api.github.com/repos/lee-dohm/test-repo/contents/hello.txt \
  "Authorization: token REDACTED-TOKEN" \
  message="my commit message" \
  committer:="{ \"name\": \"Lee Dohm\", \"email\": \"1038121+lee-dohm@users.noreply.github.com\" }" \
  content="bXkgbmV3IGZpbGUgY29udGVudHM="`

The hello.txt file is uploaded 
How can this be applied?

**Comment by s-t-e-v-e-n-k** [comment]
So searching our documentation for that API path, leads me to https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.create_file
