### ISSUE TITLE
getting a 404 while trying to archive a repo using API

### ISSUE THREAD

**Issue by abhishekv7763** [PyGithub/PyGithub#1916]
I am using a python script to archive repos using their repo ID. I am able to access the attributes of the repo just fine:

for repo in repos: '''List of repos'''
        response=g.get_repo(repo)
        print(repo.html_url)  '''This works'''
        print("done!")

However, the below code gives me a 404 : github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://developer.github.com/enterprise/2.16/v3/repos/#edit"}

for repo in repos: 
        response=g.get_repo(repo)
        response.edit(archived=True)
        print("done!")

Please help!

**Comment by srisaravananwt** [comment]
Hi,
I am as well received 404. Could you please guide to resolve this issue?

github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://developer.github.com/enterprise/2.20/v3/repos/#edit"}

**Comment by BlakeBLuther** [comment]
Experiencing this as well.

```
import github
import os

gh_apikey = os.getenv('GH_APIKEY')
gh = github.Github(gh_apikey)

with open('test_gh_repos.txt') as f:
    for line in f:
        line = line.strip()
        repo = gh.get_repo(line)
        repo.edit(archived=True)
```

The above is failing at the `repo.edit` line:

```
Traceback (most recent call last):
  File "/Users/blake.luther/code/github-repo-archiver/./archiver.py", line 17, in <module>
    repo.edit(archived=True)
  File "/Users/blake.luther/code/github-repo-archiver/.venv/lib/python3.9/site-packages/github/Repository.py", line 1606, in edit
    headers, data = self._requester.requestJsonAndCheck(
  File "/Users/blake.luther/code/github-repo-archiver/.venv/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/Users/blake.luther/code/github-repo-archiver/.venv/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#update-a-repository"}
```
