### ISSUE TITLE
fork_collab Fork collab can't be granted by someone without permission

### ISSUE THREAD

**Issue by Luffffffy** [PyGithub/PyGithub#1921]
Hello!!!

I encountered this error while trying to create a pull request

But the official did not give 422 error code solution

![image](https://user-images.githubusercontent.com/49063302/115111903-3f032600-9fb5-11eb-8755-5082b766deae.png)

it seems that's the problem

"fork_collab Fork collab can't be granted by someone without permission"

**Comment by s-t-e-v-e-n-k** [comment]
A 422 error returned from GitHub means some server-side validation failed. In this case you need to pass the `maintainer_can_modify` parameter and set it to False since your user lacks permissions on the source branch.
