### ISSUE TITLE
GithubIntegration: Could not deserialize key data

### ISSUE THREAD

**Issue by raphsilva** [PyGithub/PyGithub#1929]
I tried [this solution](https://github.com/swinton/pygithub-playground/blob/main/demo.py) to get a Github app installation token:

```python
from github import GithubIntegration

# Get the App
id = APP_ID
private_key = "GITHUB_APP_PRIVATE_KEY"
app = GithubIntegration(id, private_key)

# Get the installation
owner = "GITHUB_OWNER"
repo = "GITHUB_REPO"
installation = app.get_installation(owner, repo)
```

but I get: 

>  Traceback (most recent call last):
>   File "/home/us/test-github-api/jj.py", line 15, in <module>
>     installation = app.get_installation(owner, repo)
>   File "/home/us/.local/lib/python3.8/site-packages/github/MainClass.py", line 893, in get_installation
>     "Authorization": f"Bearer {self.create_jwt()}",
>   File "/home/us/.local/lib/python3.8/site-packages/github/MainClass.py", line 836, in create_jwt
>     encrypted = jwt.encode(payload, key=self.private_key, algorithm="RS256")
>   File "/usr/lib/python3/dist-packages/jwt/api_jwt.py", line 64, in encode
>     return super(PyJWT, self).encode(
>   File "/usr/lib/python3/dist-packages/jwt/api_jws.py", line 113, in encode
>     key = alg_obj.prepare_key(key)
>   File "/usr/lib/python3/dist-packages/jwt/algorithms.py", line 207, in prepare_key
>     key = load_pem_public_key(key, backend=default_backend())
>   File "/home/us/.local/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 25, in load_pem_public_key
>     return backend.load_pem_public_key(data)
>   File "/home/us/.local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1247, in load_pem_public_key
>     self._handle_key_loading_error()
>   File "/home/us/.local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1490, in _handle_key_loading_error
>     raise ValueError(
> ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.

I have tried different versions of the package 'cryptography': 2.2, 2.3, 2.8, 3.4.
Also tried different versions of PyGithub: 1.54.1, 1.54.0, 1.53, 1.50.

**Comment by rileydakota** [comment]
Any solution to this?

**Comment by rileydakota** [comment]
Solution - if you are here, its likely because you supplied a GitHub Client Secret (at the top of the settings page) to the AppAuth class and not the string contents of a GitHub App Private Key (at the very bottom of the app settings page)
