### ISSUE TITLE
SLOC in the API

### ISSUE THREAD

**Issue by sandeshRazorpay** [PyGithub/PyGithub#1933]
There is no easy way to get LOC/SLOC for each repo in an organization without cloning it in the local machine. Would be awesome if the API provided an easy way to do it 

Essentially
repo.size -> size of the repo in KB (exists today)
repo.sloc -> Source lines of code in the repository (does not exist)

**Comment by s-t-e-v-e-n-k** [comment]
If the GitHub API doesn't provide it, and it doesn't look like it does, then we can't expose it, I'm sorry.
