### ISSUE TITLE
Make `len()` compatible with `PaginatedList` (as an alias for `totalCount`)

### ISSUE THREAD

**Issue by xtuchyna** [PyGithub/PyGithub#1939]
Hello :wave: ,

since the `PaginatedList` is considered iterable, I think it is reasonable to be able to call `len()` on it.

**Comment by s-t-e-v-e-n-k** [comment]
We have tried to implement `__len__` on PaginatedList a few times, last time I tried it ended up with wide-spread test failures and tears.

**Comment by EnricoMi** [comment]
Adding `__len__` to `PaginatedList` will allow calling `len(pl)` on `pl: PaginatedList`.

However, turning the `PaginatedList` into a list like

    list(pl)

calls `len(pl)` first. In cases where `totalCount` is not known, this induces another API call, which breaks tests and is undesired in general.

Calling `list(pl)` should call `pl.__len__()` only if `totalCount` is known, that would be ideal. But there is no way to implement that.
