### ISSUE TITLE
cherry-pick support request

### ISSUE THREAD

**Issue by petricm** [PyGithub/PyGithub#1940]
Hi,
would it be possible to implement a cherry-pick handle
```py
repo = github.get_repo('some-repo')
repo.cherry_pick(cherry_pick_branch, commit.sha)
```
in the same manner as the merge for repositories.
```py
repo = github.get_repo('some-repo')
repo.merge(cherry_pick_branch, commit.sha)
```
Thank you.

**Comment by s-t-e-v-e-n-k** [comment]
If you mean like 'git cherry-pick', that function is not supported by the GitHub API, so we can't add it, sorry.

**Comment by petricm** [comment]
thank you for the quick feedback, I have opened a [topic](https://github.community/t/do-a-cherry-pick-via-the-api/14573/4) with this with GitHub, and it's advised to open a support request to expose an endpoint. I have already done it, it would be greatly appreciated if somebody from PyGithub could also do it... would be a nice feature to have.
