### ISSUE TITLE
limited output listed in "Repository" when apply "get_contents" metoth [get_contents]

### ISSUE THREAD

**Issue by kascesar** [PyGithub/PyGithub#1950]
Hi, and thank for readme.
I want to list all files in a repo, the repo has a count grather than 1000 files. When i try to do this, i only get the firts 1000 files.

_REPRODUCE ME_:

`
from github import Github
`
`
g = Github()
`
`
repo = g.get_repo("thebezelproject/bezelproject-MegaDrive", lazy=False)
`
`
cont = repo.get_contents("retroarch/overlay/GameBezels")[0].path
`
`
files = repo.get_contents("retroarch/overlay/GameBezels/retroarch/overlay/GameBezels/Megadrive")
`
`
print(len(files), files[-1])
`

out:

`
1000 ContentFile(path="retroarch/overlay/GameBezels/Megadrive/Midnight Resistance (USA).png")
`

if you see in the page you can see the leng of the file list (infiered from this message)
_ Sorry, we had to truncate this directory to 1,000 files. 776 entries were omitted from the list. _

Some one can help me with this ?

Thanks a lot! :D

**Comment by kascesar** [comment]
some one give a hand plz! u.u

**Comment by s-t-e-v-e-n-k** [comment]
We're at the mercy of whatever data GitHub sends -- most of their API methods do seem to limit at 1,000 items. If this is a deal-breaker, I'd suggest you investigate operating on the git repository directly, by using for example https://pypi.org/project/GitPython/

**Comment by kascesar** [comment]
Thnaks! :D thats helps!
