### ISSUE TITLE
Installing on iPad?

### ISSUE THREAD

**Issue by ateteen-plus** [PyGithub/PyGithub#1956]
It seems that I cannot install PyGithub on iPad using a Linux-like shell on iPad (I'm using iSH). I think the reason is that there isn't a c compiler on iPad, as the installation returns exit status 1, after the command

`gcc -Who-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -03 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/user/include/ffi -I/usr/include/libffi -I/usr/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-i686-8.8/c/_cffi_backend.o`

And, naturally, this is followed by
`unable to execute 'gcc': No such file or directory`
`error: command 'gcc' failed with exit status 1`

Is there any way to skip this part and successfully install PyGithub without a c compiler?

**Comment by s-t-e-v-e-n-k** [comment]
It isn't PyGithub that requires a C compiler, but our dependencies. It is possible, but you'd need to build wheels (a binary Python package) for the target -- I think that is cffi, required by nacl.

**Comment by s-t-e-v-e-n-k** [comment]
https://github.com/pyca/pynacl/issues/601 is a related issue.
