### ISSUE TITLE
branch.commit.last_modified not populated?

### ISSUE THREAD

**Issue by MikeTheGreat** [PyGithub/PyGithub#1967]
Hello!

I'm trying to iterate through all the branches in a repo, and when I ask the commit object for the last_modified date it consistently says that it's None, and that the branch.commit.last_modified is None as well.

This code:

```
                        branches = repo.get_branches()
                        for branch in branches:
                            print("branch.last_modified: " + str(branch.last_modified))
                            print("branch.commit: " + str(branch.commit))
                            print("branch.commit.last_modified: " + str(branch.commit.last_modified))

                            # WHAT IF I USE .get_commit() TO GET THE SAME COMMIT?  DOES THAT HAVE A last_modified FIELD?
                            HEAD = repo.get_commit( str(branch.commit.sha))
                            print(f"HEAD.last_modified: {str(HEAD.last_modified)}")
```

Produces this output:

```
branch.last_modified: None
branch.commit: Commit(sha="9107696ab93b630df5446c29b9ff2b4b780dbece")
branch.commit.last_modified: None
HEAD.last_modified: Thu, 10 Jun 2021 07:50:58 GMT
```

I'm using PyGitHub 1.55 on Windows 10, alongside whatever version of GitHub.com is running today at 4pm Pacific time, June 12, 2021.

**It seems like `branch.last_modified` and `branch.commit.last_modified` should be filled in (or else the readthedocs site should clearly document when we can expect these to be filled in**)

**Comment by thisisrachelramos** [comment]
I have also noticed this issue - I imagine there is some lazy loading/async code that is causing this?

**Comment by mirousek** [comment]
Yes, it is lazy loading. Don't know it can be requested at once along with branch, but this causes the commit fetch:
```
branch.commit.commit
```

The code in `Commit` class:
```
    @property
    def commit(self) -> GitCommit:
        self._completeIfNotSet(self._commit)
        return self._commit.value
```
