### ISSUE TITLE
Feature request: Github template repo

### ISSUE THREAD

**Issue by Hanaasagi** [PyGithub/PyGithub#1974]
Template repository is a quick way to generate new repositories with the same directory structure, branches, and files. And Github REST API gives a way to using this feature:

> 
> Creating and using repository templates is currently available for developers to preview. To access this new endpoint during the preview period, you must provide a custom media type in the Accept header:
> 
> application/vnd.github.baptiste-preview+json

I think the change involves:

1. Add `is_template` property in `Repository` class 
2. Add `is_template` param in `Repository.edit` method
3. Add new function `create_repo_from_template`

Reference:
https://docs.github.com/en/rest/reference/repos#create-a-repository-using-a-template
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-template-repository

**Comment by Hanaasagi** [comment]
@s-t-e-v-e-n-k What do you think about it?

**Comment by simkimsia** [comment]
I need this as well. I don't mind sending a PR. How do I go about doing this roughly? How do I add unit test for this behavior?
