### ISSUE TITLE
GithubException headers / annotations are incompatible with the actual code

### ISSUE THREAD

**Issue by rs2** [PyGithub/PyGithub#1977]
https://github.com/PyGithub/PyGithub/blob/0245b758ca323dfa18cd7910d50300ca42514999/github/GithubException.pyi#L4
suggests that `headers` arg is `Optional` (technically, `None` value is acceptable), yet
https://github.com/PyGithub/PyGithub/blob/0245b758ca323dfa18cd7910d50300ca42514999/github/GithubException.py#L41
implies that positional `headers` arg is mandatory.

Which one is more correct?

Note that adding a new mandatory arg breaks backwards-compatibility.

**Comment by Hanaasagi** [comment]
`Optional[T]` is just a Union type means either `None` or `T`. It does not matter whether the parameter is positional. And it not require the parameter has a default value, like `headers=None`. Further more,  I think `GithubException` is a internal exception, should only be created by this lib.
