### ISSUE TITLE
feature request: archive notification

### ISSUE THREAD

**Issue by Granitosaurus** [PyGithub/PyGithub#1980]
Github notications can be marked as done and are archived to the abyss:
![image](https://user-images.githubusercontent.com/5476164/123413650-3a727380-d5dd-11eb-8f49-d55ff163c594.png)

Would be nice to have that in `PyGithub` as currently we can only mark them as read (`notification.mark_as_read()`)

This seems to be beta feature? I could not find any API docs for this but web inspector is showing request to:
```
POST https://github.com/notifications/beta/archive
CONTENT TYPE:
content-type: multipart/form-data; boundary=----WebKitFormBoundaryENbHpeZfWuCRkIpx
BODY:
------WebKitFormBoundaryENbHpeZfWuCRkIpx
Content-Disposition: form-data; name="authenticity_token"

REDACTED
------WebKitFormBoundaryENbHpeZfWuCRkIpx
Content-Disposition: form-data; name="notification_ids[]"

REDACTED
------WebKitFormBoundaryENbHpeZfWuCRkIpx--
```

I don't think currently PyGithub can deal with these sort of endpoints?

**Comment by s-t-e-v-e-n-k** [comment]
Correct, we can't, and likely will not. I would suggest asking GitHub nicely for an API endpoint, sorry.
