### ISSUE TITLE
repo.get_issues() is not returning correct values

### ISSUE THREAD

**Issue by Prince2347X** [PyGithub/PyGithub#1981]
# See the original repo on github:
![image](https://user-images.githubusercontent.com/68418241/123436090-ea4edd80-d5eb-11eb-9640-86361620346d.png)
## it's showing sixty three opened and 2252 closed issues.

# But when i'm trying to get this with PyGithub, it's returning something else..
![image](https://user-images.githubusercontent.com/68418241/123435994-cc817880-d5eb-11eb-9e33-6b17971450a0.png)

### Any comments on this? or am i doin' something wrong?

**Comment by peterjc** [comment]
It counts issues and pull requests (which share the same numbering scheme):

https://github.com/Rapptz/discord.py/issues = 63 open + 2252 closed
https://github.com/Rapptz/discord.py/pulls = 46 open + 1615 closed

Grand total 63 + 2252 + 46 + 1615 = 3976

Closed total 2252+1615 = 3867

**Comment by Prince2347X** [comment]
But there's get_pulls method for counting PRs😅.. Btw is there a way to get the "issues" only without the PRs?🤔

**Comment by s-t-e-v-e-n-k** [comment]
From https://docs.github.com/en/rest/reference/issues#list-repository-issues -- `Note: GitHub's REST API v3 considers every pull request an issue, but not every issue is a pull request. For this reason, "Issues" endpoints may return both issues and pull requests in the response. You can identify pull requests by the pull_request key. Be aware that the id of a pull request returned from "Issues" endpoints will be an issue id. To find out the pull request id, use the "List pull requests" endpoint.`

**Comment by NadrahAlshitwi** [comment]
You can write a condition before count closed issues
like:
if not issue.pull_request:
