### ISSUE TITLE
total number of pages in paginatedList

### ISSUE THREAD

**Issue by Simply-divine** [PyGithub/PyGithub#1982]
Currently in a paginatedList I am calculating the total number of pages using totalCount and per_page. It would be really great if there was a method called total_pages that would result how many pages are there in the paginatedList. Also please suggest if there is already any other method for getting totalNumber of pages.

**Comment by s-t-e-v-e-n-k** [comment]
The easiest way is to fetch the last page:

```
>>> repo = g.get_repo("PyGithub/PyGithub")
>>> paginated_list = repo.get_workflow_runs()
>>> paginated_list._getLastPageUrl()
'https://api.github.com/repositories/3544490/actions/runs?page=24'
```

**Comment by Simply-divine** [comment]
Hey, Thanks that looks a better method than what I was doing. But I guess adding a new method would be better.
