### ISSUE TITLE
PyGithub doesnot support setting Accept headers?

### ISSUE THREAD

**Issue by Simply-divine** [PyGithub/PyGithub#1991]
I want to get the result of the below API using PyGithub. Is there a way to set accept header in pygithub? I want the output in diff format and I don't want to use compare API. 

So is there a way to make below request using pygithub? 
```
curl \
  -H "Accept: application/vnd.github.diff" \
  http(s)://{hostname}/api/v3/repos/octocat/hello-world/commits/REF
```

**Comment by Hanaasagi** [comment]
Emm, maybe not. Which header to use has been written in the method.
E.g.
https://github.com/PyGithub/PyGithub/blob/83d6e0719cb7bfee57af398f93a73516b62af5f2/github/Repository.py#L3081-L3091

**Comment by Simply-divine** [comment]
Oh I see. Thanks a lot for clarifying.
