### ISSUE TITLE
Implement PullRequestReview.get_dismissals()

### ISSUE THREAD

**Issue by staticshock** [PyGithub/PyGithub#1995]
I haven't found a way to tell if any given PR review has been dismissed or not. The github API supports it, but PyGithub only supports the action of creating a dismissal (a PUT to `.dismiss("message")`).

**Comment by sshekdar-VMware** [comment]
From my understanding if a PR review has been dismissed then the state would be dismissed. So a `PullRequestReview` has the attribute `state` which for dismissed be `state='DISMISSED'`.

**Comment by staticshock** [comment]
Ah, indeed! Thanks for helping me find this.
