### ISSUE TITLE
Adding project_card object to IssueEvents Class

### ISSUE THREAD

**Issue by drakonhg** [PyGithub/PyGithub#1997]
When does someone want to iterate over issues and get their events, not all of the JSON data returns.

This is related to issues that were added to projects
https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types#added_to_project

**Comment by kenliu** [comment]
This seems to be some missing functionality in the IssueEvents class.

**Comment by kenliu** [comment]
The workaround for this is to call `event.raw_data['project_card']` to access the raw ` project_card` data from the response.
