### ISSUE TITLE
From issue ID, how do I get Project > Card name?

### ISSUE THREAD

**Issue by riz-hossain** [PyGithub/PyGithub#2004]
Hello,
Please accept my apologies if this is not the right medium to get support.  I could not find any way to get an issues' column name.

Please see attached image:

Thanks!
![githubcolumnName](https://user-images.githubusercontent.com/5302523/127043038-97134c8f-c397-4269-8796-ebd4491554dc.png)

**Comment by alexanderkainsky** [comment]
I would like to know this too!

**Comment by alexanderkainsky** [comment]
See my answer in #1969. There seems to be no direct way at this time.
