### ISSUE TITLE
Support for Environments + Environment secrets

### ISSUE THREAD

**Issue by anovis** [PyGithub/PyGithub#2067]
Would be nice to have support for environment secrets or environments in general  

https://docs.github.com/en/rest/reference/repos#environments

https://docs.github.com/en/rest/reference/actions#get-an-environment-secret

**Comment by Adib234** [comment]
Hi, I would like to tackle this feature request. The first link appears to be invalid, I've tried searching the environments section and got nothing. My approach to this would be to create a method in the Repository class for the management of environment secrets, I originally planned on having an Environment class but there seems to be not that much information about environments other than handling environment secrets in the Github API docs.

**Comment by tomkennes** [comment]
HI there, thumbs up for this feature! Any update @Adib234 ? Or is there anything I can do to help out?

**Comment by Adib234** [comment]
Hi, I'm not working on this feature anymore since life got in the way, it's all yours!

**Comment by alson** [comment]
I needed environments, so I have [added support for environments](https://github.com/PyGithub/PyGithub/pull/2223), but not environment secrets. It should be easy to add support for environment secrets on top of this. Also, if necessary help with getting this PR ready and merged by someone more experienced in this project would be appreciated.

**Comment by sandesvitor** [comment]
This feature is great @alson , it would be awesome if it got approved! Me and my team are in need for environment creation to be used as Stackstorm Github Exchange

**Comment by lukaszraczylo** [comment]
@alson would you kindly try rebasing your code? Can't wait for it to be merged

**Comment by alson** [comment]
@lukaszraczylo Of course, I just pushed a version rebased on top of the latest PyGithub master.

**Comment by alson** [comment]
If the branch you want to limit deployment to is covered by branch protection rules, then setting `protected_branches=True` like [in this test](https://github.com/PyGithub/PyGithub/blob/main/tests/Environment.py#L137C17-L137C40) might work. See [documentation](https://docs.github.com/en/rest/deployments/environments?apiVersion=2022-11-28#create-or-update-an-environment) under "properties of deployment_branch_policy". If not, then you might have to implement [deployment branch policies](https://docs.github.com/en/rest/deployments/branch-policies?apiVersion=2022-11-28).

The way we solved this is by just specifying branches in the Github Actions workflow and let that determine to what environment a particular branch is deployed. We are not so defensive that we want to protect against developers modifying the workflow to deploy their development branch to production.

**Comment by ssbarnea** [comment]
Does anyone know an alternative way to update secrets from environments using python, even if this requires use of another library or just producing REST HTTP api call manually?

**Comment by alson** [comment]
You should be able to use the REST calls documented [here](https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#list-environment-secrets). I don't think it would be difficult to add to PyGithub.
