### ISSUE TITLE
Provide a way to make a "raw" request

### ISSUE THREAD

**Issue by vandmo** [PyGithub/PyGithub#2071]
There will always take a while from when new endpoint or parameter is available in the GitHub API until it is supported by a released version of PyGithub.

Something as simple as providing a "public" accessor for __requester that is guaranteed not to change it's name would suffice.
Another possibility would be that the Requester object is, optionally, created by the user and then used to create the GitHub object.

**Comment by danieljamesscott** [comment]
A public accessor for `Requester` would be really helpful. If I make a PR for this is it likely to be accepted?
