### ISSUE TITLE
How to get the diff of a pull request?

### ISSUE THREAD

**Issue by grantjenks** [PyGithub/PyGithub#2083]
How to get the diff of a pull request? I can get the `diff_url` pretty easily but how do I make PyGithub request the url...
```python
from github import Github
from getpass import getpass
token = getpass()
base_url = 'https://internal-github-domain.com/api/v3'
g = Github(base_url=base_url, login_or_token=token)
repo = g.get_repo('repo-name')
pull = list(repo.get_pulls())[0]
diff_url = pull.diff_url
# What do I do with diff_url?!?
```
Is there like a `g.get(diff_url)` that'll reuse the token-based authentication?

**Comment by awais786** [comment]
@s-t-e-v-e-n-k in case of private repo request does not work with auth and token. It returns 404.

**Comment by awais786** [comment]
@grantjenks how did you solve this problem ?

**Comment by grantjenks** [comment]
@awais786 , with all error handling and business logic removed, it looks like:

```python
from github import Github
github = Github(base_url=github_base_url, login_or_token=github_token, per_page=100)
organization = github.get_organization(organization_login)
repo = organization.get_repo(repository_name)
pull = repo.get_pull(number)
head_sha = pull.head.sha
files = list(islice(pull.get_files(), 51))
for file in files:
    path = file.filename
    patch = file.patch
    contents = repo.get_contents(path, ref=head_sha)
    content = contents.decoded_content.decode()
    analyze(path, patch, content)
```

**Comment by awais786** [comment]
> @awais786 , with all error handling and business logic removed, it looks like:
> 
> ```python
> from github import Github
> github = Github(base_url=github_base_url, login_or_token=github_token, per_page=100)
> organization = github.get_organization(organization_login)
> repo = organization.get_repo(repository_name)
> pull = repo.get_pull(number)
> head_sha = pull.head.sha
> files = list(islice(pull.get_files(), 51))
> for file in files:
>     path = file.filename
>     patch = file.patch
>     contents = repo.get_contents(path, ref=head_sha)
>     content = contents.decoded_content.decode()
>     analyze(path, patch, content)
> ```
@grantjenks I am not able to find `analyze` function is it coming from library ?

**Comment by grantjenks** [comment]
“analyze(…)” is yours to write. You’ve got the file path, the patch (aka diff), and the file content for analysis.
