### ISSUE TITLE
Multiline Comment

### ISSUE THREAD

**Issue by sangwoo-joh** [PyGithub/PyGithub#2095]
Thanks for the great package!
It seems like there is no support for multi-line comments yet.
In [GitHub Docs](https://docs.github.com/en/rest/reference/pulls#create-a-review-comment-for-a-pull-request), we can create a comment that applies to more than one line in the pull request diff, by specifying `line`, `side`, `start_line` and `start_side` instead of a single parameter `position`.
Is there any plan to support this API?

**Comment by sangwoo-joh** [comment]
I found some [related](https://github.com/PyGithub/PyGithub/issues/1805) [issues](https://github.com/PyGithub/PyGithub/issues/1803), and maybe this feature is not supported deliberately because it is a preview feature? 😅

**Comment by sangwoo-joh** [comment]
Hmm.. but it seems like some features are actually based on [preview features](https://github.com/PyGithub/PyGithub/pull/1433), so if it is ok to have a preview feature, I think I can contribute.

**Comment by sangwoo-joh** [comment]
### Possible combinations of parameters
 - Required: `owner`, `repo`, `pull_number`, `body`, `commit_id`, `path`
 - `position` (if this is used, the parameters below are ignored)
 - `side` (`LEFT` or `RIGHT`) + `line`  (just like one-line comment using `position` only)
 - `side` + `start_side` + `line` + `start_line` (multi-line comment)

**Comment by heitorpolidoro** [comment]
Hi,

I created this pull request #2540 that might fix this issue

**Comment by EnricoMi** [comment]
This has been fixed in #2540.
