### ISSUE TITLE
Event object have no repository

### ISSUE THREAD

**Issue by gabrielsmenezes** [PyGithub/PyGithub#2097]
When we look for `event.repo` we got a None repository:

![image](https://user-images.githubusercontent.com/40703319/139967477-1b309009-b34b-4079-97fc-7f8908345c93.png)

But, we can see that information is arriving, by raw_data variable. So, I think it is a binding problem:

![image](https://user-images.githubusercontent.com/40703319/139967636-55d82c45-6bca-4ef2-9ca0-86a89a37d726.png)

**Comment by s-t-e-v-e-n-k** [comment]
It is not a binding problem, the problem is we are returned extremely limited information from the event:

```
>>> events[0].raw_data['repo']
{'id': 3544490, 'name': 'PyGithub/PyGithub', 'url': 'https://api.github.com/repos/PyGithub/PyGithub'}
```

Calling any property or calling any method will fetch the full object from the API.
