### ISSUE TITLE
Visibility is always None

### ISSUE THREAD

**Issue by bwheelz36** [PyGithub/PyGithub#2099]
Hi all
I saw #1872 was recently merged. I would like to detect private repos in our enterprise github organization. 
However, every repo has visibility=None.
A code snippet to reproduce is below:

```python
all_repos = g.get_user().get_repos()  # assume that the log in details etc. are sorted out upstream
list_of_vis_status= [item.visibility for item in all_repos ]
```

Any advice? I should mention I am an admin on the organization being scanned...

**Comment by s-t-e-v-e-n-k** [comment]
Have a look at `raw_data` for a few repositories -- this is the raw JSON that GitHub returns, see if `visibility` is returned.

**Comment by bwheelz36** [comment]
no, I can't see anything - so does this just mean that for whatever reason this enterprise version is not returning this data?

**Comment by s-t-e-v-e-n-k** [comment]
Sadly, yes -- we can't populate it if the server doesn't return it :-)

**Comment by bwheelz36** [comment]
thanks for the help :-)
