### ISSUE TITLE
Getting USER who approved a PR

### ISSUE THREAD

**Issue by valeedmalik** [PyGithub/PyGithub#2100]
Way to get the event or related user who approved a pull request

Looking through the docs, haven't found much related to approvals. Is this supported?

**Comment by s-t-e-v-e-n-k** [comment]
The object this is referenced as is called `PullRequestReview`, and can be fetched as such:

```
>>> repo = g.get_repo("PyGithub/PyGithub")
>>> pr = repo.get_pull(2006)
>>> reviews = pr.get_reviews()
```

This returns a PaginatedList of any reviews, and their state, so to return who approved it:

```
>>> [r.user for r in reviews if r.state == "APPROVED"]
[NamedUser(login="s-t-e-v-e-n-k")]
```

**Comment by jakwozny** [comment]
Just be aware that this doesn't work if you're looking for current approvals. E.g. if user approves it and then request changes the NamesUser will still be returned. This is the function I use if anybody needs it:
```
user_approvals = set()
for review in sorted(reviews, key=lambda r: r.submitted_at):
    state = review.state.lower()
    if state == "approved":
        user_approvals.add(review.user.login)
    elif state == "dismissed" or state == "changes_requested":
        user_approvals.discard(review.user.login)
```
