### ISSUE TITLE
Exporting CSV file extracted from a pandas DataFrame using python script.

### ISSUE THREAD

**Issue by AdhaarSharma** [PyGithub/PyGithub#2101]
Does this library have a functionality to import pandas dataframe directly to the github repository? I know that we can create a new file using PyGithub.

**Comment by s-t-e-v-e-n-k** [comment]
This library does not have that functionality. https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.create_file or https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.update_file
