### ISSUE TITLE
NamedUser has_in_following error

### ISSUE THREAD

**Issue by ariv797** [PyGithub/PyGithub#2102]
I am trying to check whether `first_user` follows `second_user`. 

```
user = api.get_user(first_user)
info = user.has_in_following(second_user)

if info:
    console.print(first_user + " is Following " + second_user)
else:
    console.print(first_user + " is Not Following " + second_user)
```

But when I run it I get this:

```
File "C:\Users\Lenovo\Documents\PycharmProjects\GitLookup\venv\lib\site-packages\github\NamedUser.py", line 620, in has_in_following
    assert isinstance(following, github.NamedUser.NamedUser), following
AssertionError: nat
```
In your code, the response type is supposed to be a boolean value, can somebody pls tell me what I am doing wrong.

**Comment by s-t-e-v-e-n-k** [comment]
You're passing a string, I'm guessing? The type for that is a `NamedUser`,  https://pygithub.readthedocs.io/en/latest/github.html#github.MainClass.Github.get_user

**Comment by ariv797** [comment]
Yes I am passing a string. Both `first_user` and `second_user` are strings.
