### ISSUE TITLE
Misleading `Repository.create_fork` docstring?

### ISSUE THREAD

**Issue by xmo-odoo** [PyGithub/PyGithub#2116]
I'm currently exploring the behaviour of GH's edge cases, and figured PyGithub was a more convenient way to access it than raw `requests` calls, however in looking at `create_fork` I stumbled upon something odd: the docstring says

>     :param organization: string or "none" or "*"

however:

* `*` is mentioned nowhere in github's own documentation
* there seems to be no special codepath inside pygithub special-casing this, the string is just passed directly to the API
* when calling `repo.create_fork("*")` I get the same error as passing in any other non-existent organisation name:
  ```
  github.GithubException.GithubException: 422 {
      "message": "Validation Failed", 
      "errors": [{
          "resource": "Fork",
          "code": "invalid",
          "field": "organization"
      }],
      "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-fork"
  }
  ```

Is this a remnant of an older revision or somesuch? I think this section of docstrings should probably be updated to:

```reStructuredText
:param str organization: name of the organisation to create the fork in, omit to fork in the current user's account
```
(after some testing, specifying the current user's login explicitely fails, and the error message explicitely notes that the error comes from it being a *user account* a opposed to an organisation)

/cc @timgates42

**Comment by xmo-odoo** [comment]
Also maybe this paramete could / should take an actual `Organization` object for better typing?

**Comment by s-t-e-v-e-n-k** [comment]
That is very odd. Since the history has been squashed of the commit that merged it, I don't have history of that docstring changing during development, and digging into GitHub developer docs from the past also doesn't match anything like that. I agree with you, it should be a string of an org name or an Organization object.

**Comment by timgates42** [comment]
I recall the behaviour being a little odd and the api call being new when I added it, I’m guessing they fixed up the call after my testing

**Comment by xmo-odoo** [comment]
> I recall the behaviour being a little odd and the api call being new when I added it, I’m guessing they fixed up the call after my testing

Definitely possible, given the REST API remains... pretty rough (and ill documented) any time you get close to edge cases.
