### ISSUE TITLE
get_pulls failed to get latest PR with both reversed and get_page

### ISSUE THREAD

**Issue by trongbang86** [PyGithub/PyGithub#2121]
I'm trying to get all the latest PRs that have been merged but the following code is giving me the opposite which is all the oldest PRs.

`
pr_list = repo.get_pulls(state='closed', sort='merged', base='develop').reversed.get_page(0)
`

output:

`
[PullRequest(title="", number=1), PullRequest(title="", number=2), ]
`

I even tried to .get_page(last_page_number) but same output.

I'm expecting to get back:

`
[PullRequest(title="", number=1000), PullRequest(title="", number=999), ]
`

**Comment by s-t-e-v-e-n-k** [comment]
get_pulls() returns in descending order by default? So this is expected behaviour.

```
>>> repo = g.get_repo("PyGithub/PyGithub")
>>> pulls = repo.get_pulls()
>>> [pr.number for pr in pulls[:5]]
[2120, 2118, 2115, 2111, 2098]
```

**Comment by trongbang86** [comment]
I managed to resolved this by removing sort param.
`
pr_list = repo.get_pulls(state='closed', base='develop')
for pr in pr_list:
    print(pr.number)

`
