### ISSUE TITLE
How can I change a public repo to a private one?

### ISSUE THREAD

**Issue by reuven** [PyGithub/PyGithub#2134]
I know that the GitHub API makes it possible to change a public repo to be a private one. And according to the docs (https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html), it seems like it should be possible to set the visibility from 'public' to 'private', But I can't figure out how to get this to work.  Is this functionality available, or should I use the REST API in this case?

Thanks!

**Comment by Adib234** [comment]
The functionality is available, to change visibility from 'private' to 'public', you can do this
```
from github import Github

g = Github("token")
repo = g.get_repo("username/repo")
repo.edit(private=True)
```
To change any other property of a repository you can go here use the edit function, here's the [link](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.edit). Feel free to ask any more questions

**Comment by reuven** [comment]
Thanks *SO* much. Both this answer, and your work, are greatly appreciated.
