### ISSUE TITLE
Is there an example of editing a file?

### ISSUE THREAD

**Issue by chaoranxie** [PyGithub/PyGithub#215]
I been able to get the content of a file by getting a repo first and then use the get_file_contents method to get the content, is there sample on how to update the content of the file? i tried to set the content attribute but got the "can't set attribute" error. Thanks

**Comment by ahmad88me** [comment]
@chaoranxie I added it and created a pull request https://github.com/PyGithub/PyGithub/pull/316

**Comment by ChannyAzar** [comment]
Any news?
When will it be available?

**Comment by nottrobin** [comment]
There's now an "update_file" method - added in #379.
