### ISSUE TITLE
Add branch protection support for required_status_checks `checks` object

### ISSUE THREAD

**Issue by testworksau** [PyGithub/PyGithub#2157]
It's possible to set [branch protections](https://pygithub.readthedocs.io/en/latest/github_objects/BranchProtection.html#github.BranchProtection.BranchProtection.required_status_checks) using the [contexts](https://pygithub.readthedocs.io/en/latest/github_objects/RequiredStatusChecks.html#github.RequiredStatusChecks.RequiredStatusChecks.contexts) field within the `RequiredStatusChecks` class, however, according to the documentation, [contexts is deprecated](https://docs.github.com/en/rest/reference/branches#update-branch-protection).

`checks` (an array of objects) will replace `contexts` as it allows you to configure the source of the check. 

An example of the raw request to set required status checks using the `checks` object is:

```
    "required_status_checks":{
        "strict": false,
        "checks": [
            {
                "context": "A Required Check set to a given app id",
                "app_id": 3414
            },
            {
                "context": "A Required Check set to any source",
                "app_id": -1
            }
        ]
    }
```

![image](https://user-images.githubusercontent.com/11973031/149074928-b8fd68dc-9e0b-4add-94ad-176b993b345a.png)

**Comment by EnricoMi** [comment]
@testworksau Would you like to provide a PR to fix this? The existing `context` parameter should become `Opt[list[Union[str, Tuple[str, int]]]]` so that the `app_id` can be omitted for individual contexts.

**Comment by EnricoMi** [comment]
Note: Method `edit_required_status_checks` has to be migrated as well.

**Comment by treee111** [comment]
will tackle this, see comment https://github.com/PyGithub/PyGithub/pull/2873#issuecomment-1906795864
