### ISSUE TITLE
IImportError: cannot import name 'Github' from partially initialized module 'github' (most likely due to a circular import)

### ISSUE THREAD

**Issue by myatthiha1998** [PyGithub/PyGithub#2164]
<b>ImportError: cannot import name 'Github' from partially initialized module 'github' (most likely due to a circular import)</b>

![image](https://user-images.githubusercontent.com/55624042/151322175-4295f1e7-4d7b-4f4f-bdbc-5821e1e83a11.png)

The above error cause when running python file with batch file.

P.S Without batch file , it's ok. Have already installed PyGithub.

![image](https://user-images.githubusercontent.com/55624042/151321766-08dd9855-a57e-471f-b2bc-b22a7aab3f7f.png)

**Comment by EnricoMi** [comment]
What do you mean with "batch file"? Can you provide steps to reproduce the issue?

As you say, the given `from github import Github` works, so how to reproduce the "batch" bit? Maybe you can provide the batch file where as much is removed as possible while still breaking.

**Comment by myatthiha1998** [comment]
@EnricoMi I run my python file with batch file and` from github import Github` code cause errors. 

<details><summary>my batch file code</summary>

```
@echo off <br/>
pip install -r "your path \requirements.txt"<br/>
"your path\python.exe" "your path\test.py"<br/>
pause
```
</details>

<details><summary>test.py</summary>

`from github import Github`

</details>

**Comment by EnricoMi** [comment]
Understood, so you can run `python.exe test.py` on a Windows command shell (`cmd`) but you cannot run a batch file `test.bat` in the exact same command shell that executes `python.exe test.py`.

Which version of PyGithub do you install via pip install?

**Comment by brendancol** [comment]
@myatthiha1998 if your python script was named `github.py` it would cause the circular import error described above

**Comment by harryzjm** [comment]
@brendancol Thanks for you, same question
