### ISSUE TITLE
为什么总是报"API rate limit exceeded for user"这样的错误？

### ISSUE THREAD

**Issue by zhangchangwei** [PyGithub/PyGithub#2165]
我查看了实际的请求次数还是5000，为什么一执行，进行数据过滤整合时就报这个错误呢？API rate limit exceeded for user

**Comment by EnricoMi** [comment]
How did you check that limit was not hit? What was your call that failed with the error? Did you mix search limit with core limit? Maybe this is caused by #1988.

**Comment by zhangchangwei** [comment]
以下是我通过调用get_rate_limit() 方法所返回的rate信息，如下所示:
速率限制: RateLimit(core=Rate(reset=2022-01-28 01:52:49, remaining=5000, limit=5000))，这不能说明是core limit 是5000吗？

**Comment by zhangchangwei** [comment]
![Uploading image.png…]()
我想知道我user = g.search_repositories(query=q)通过关键字搜索repo，然后进行数据获取、循环处理(我的code如上图所示)，就请求了一次接口为什么循环一次就耗掉10几次接口调用次数呢？

**Comment by zhangchangwei** [comment]
my code 如下:

user = g.search_repositories(query=q)
github_list = []

print("总匹配条数为:", user.totalCount)


for i in range(0, user.totalCount):
    print('search速率', g.get_rate_limit().search)
    github_list.append({
        "id": user.reversed.__getitem__(i).id,
        "name": user.reversed.__getitem__(i).name,
        "full_name": user.reversed.__getitem__(i).full_name,
        "login": user.reversed.__getitem__(i).owner.login,
        "avatar_url": user.reversed.__getitem__(i).owner.avatar_url,
        "html_url": user.reversed.__getitem__(i).html_url,
        "created_at": user.reversed.__getitem__(i).created_at,
        "updated_at": user.reversed.__getitem__(i).updated_at
    })
    print("进度:", i)





总匹配条数为: 9
search速率 Rate(reset=2022-01-28 01:25:17, remaining=29, limit=30)
进度: 0
search速率 Rate(reset=2022-01-28 01:25:17, remaining=13, limit=30)
