### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by gerardsegarra** [PyGithub/PyGithub#2170]
Hi! There's been a few since a new version was released. There are some interesting features in the main branch. Are you planning on releasing a new one any time soon?

Thanks in advance!

**Comment by dclayton-godaddy** [comment]
cc @xmo-odoo @s-t-e-v-e-n-k

**Comment by alexef** [comment]
duplicate of: https://github.com/PyGithub/PyGithub/issues/2139

**Comment by jeffwidman** [comment]
This should be closed now that https://pypi.org/project/PyGithub/1.56/ was tagged.

**Comment by s-t-e-v-e-n-k** [comment]
And doing so, thanks!
