### ISSUE TITLE
github.GithubException.UnknownObjectException: 404 {"message": "Not Found"

### ISSUE THREAD

**Issue by jaychandra86** [PyGithub/PyGithub#2176]
I wrote the following code that updates a file on GitHub, it is still working fine on my windows pc but is giving an error if I do the same thing on google cloud f1 micro instance running ubuntu 18.04 LTS. How do I fix this? This is only happening for updating the files on the repo. If I want to create a new repo then it is working fine on both window and gcp linux.

I thought it was due to permissions of personal access tokens but it is not, updating the file from my pc with the same code works fine, but doing the same thing on gcp is returning the following error.

Here's the error
```
Traceback (most recent call last):
  File "gitup.py", line 48, in <module>
    updateRepo("testttt", "api.json", "update api.json")
  File "gitup.py", line 38, in updateRepo
    fileContents = repo.get_contents("/home/manideeppatnam123/crypto-whales-api/api.json", ref="master")
  File "/usr/local/lib/python3.6/dist-packages/github/Repository.py", line 1792, in get_contents
    parameters=url_parameters,
  File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 355, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-repository-content"}
```

and here's the code
```
from github import Github

def loginToGitHub():
    g = Github("personal-access-token-redacted")
    print("--- Login successful")

    return g

def updateRepo(repoName, fileName, commitMessage):
    g = loginToGitHub()

    user = g.get_user()

    repo = g.get_repo(f"{user.login}/{repoName}")

    fileContents = repo.get_contents(f"./{fileName}")

    f = open(fileName, "r")
    newContent = f.read()
    f.close()

    repo.update_file(fileContents.path, commitMessage, newContent, fileContents.sha)
    print("--- File updated successfully")


#here testttt is the repo name, api.json is the file that I'm updating
updateRepo("testttt", "api.json", "update api.json")
```

any help would be appreciated. Thanks!

**Comment by EnricoMi** [comment]
Is this path expected and exists in your repo?

```
/home/manideeppatnam123/crypto-whales-api/api.json
```

Maybe calling `github.enable_console_debug_logging()` before running `updateRepo` would help to spot differences between Windows and Linux.

**Comment by jaychandra86** [comment]
yes, that path is correct, I tried it by giving the path as `api.json`, then `./api.json` and then `/home/manideeppatnam123/crypto-whales-api/api.json` and still the output is same. It is only happening for updating the repo while it is working fine on my pc. 
I will try `github.enable_console_debug_logging()` and will let you know about the output log.
