### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by ghost** [PyGithub/PyGithub#219]
Below is my hacked together version to deal with two-factor authentication. Is there is a better way to use PyGithub to handle this or is this feature needed?

Basically, you run this twice, The first time without code_2fa. If you get the Require2FAError then you run it again with code_2fa. the code_2fa is put into the header of the next authentication request.

``` python
def request_token(
        username, password, scopes, user_agent, code_2fa=None,
        base_url=MainClass.DEFAULT_BASE_URL,
        timeout=MainClass.DEFAULT_TIMEOUT,
        client_id=None, client_secret=None,
        per_page=MainClass.DEFAULT_PER_PAGE):

    requester = Requester(username, password, base_url, timeout,
            client_id, client_secret, user_agent, per_page)

    if code_2fa:
        request_header = {'x-github-otp': code_2fa}
    else:
        request_header = None

    status, headers, data = requester.requestJson(
            "POST", "/authorizations",
            input={"scopes": scopes, "note": str(user_agent)},
            headers=request_header)

    try:
        if status == 401 and re.match(r'.*required.*', headers['x-github-otp']):
            raise Require2FAError()
        else:
            data = json.loads(data)
            return Authorization(requester, headers, data, True)
    except KeyError:
        raise AuthenticationError()
```

**Comment by ctubbsii** [comment]
> This is going to be in v2 (expect the first alpha this week-end), including the 2fa_disabled filter

Hey @jacquev6 , any chance of a v2 release? I see some activity in the repo, but no new tags or releases since 2014. And, the v2 tags are all alpha. I'm hoping to use the '2fa_disabled' filter feature you mentioned.
