### ISSUE TITLE
How do I correct issues that do not contain pull requests?

### ISSUE THREAD

**Issue by Hiroki-Kuramoto** [PyGithub/PyGithub#2206]
I want to collect issues that do not contain pull requests with GitHub API v3. 
However, the get_issue method, which can be used to collect issues, returns issues that contain pull requests(e.g., #2010).

How do I distinguish between issues and pull requests?

I am thinking of several ways such as the following code:
```
github = Github("token")
repo = github.get_repo(full_name_or_id="reponame")
issue = repo.get_issue(issue_number)

if issue.pullrequest == None:
    # this issue is a true issue!
else: # issue.pullrequest != None
    # this issue actually is a pull request!
```
Does this code work well?

**Comment by JoshuaMulliken** [comment]
That seems to work correctly for me but I bet this would go better in the Discussion forum.

**Comment by Diwasdrpm** [comment]
....done!!!

**Comment by marcorosa** [comment]
Seems good to me as well. The [doc](https://docs.github.com/en/rest/issues/issues#list-organization-issues-assigned-to-the-authenticated-user) says: _"Issues" endpoints may return both issues and pull requests in the response. You can identify pull requests by the pull_request key_

**Comment by Hiroki-Kuramoto** [comment]
Thank you for your help !!
his issue has been resolved.
