### ISSUE TITLE
issue in branch protection rules

### ISSUE THREAD

**Issue by ankitkumar16012000** [PyGithub/PyGithub#2239]
Under branch protection rule GitHub provide   **Require conversation resolution before merging** .
But I am not able to access it through parameters of    **.edit_protection()**  (a method of branch object), although I can access other branch protection rules.

**Comment by andrewthetechie** [comment]
There are a couple of parameters missing from edit_protection

require_linear_history
allow_force_pushes
allow_deletions
block_creations
require_conversation_resolution

This is from https://docs.github.com/en/rest/branches/branch-protection#update-branch-protection

**Comment by kgal-pan** [comment]
See https://github.com/PyGithub/PyGithub/pull/2378

**Comment by treee111** [comment]
> There are a couple of parameters missing from edit_protection
> 
> required_linear_history allow_force_pushes allow_deletions block_creations required_conversation_resolution
> 
> This is from https://docs.github.com/en/rest/branches/branch-protection#update-branch-protection

https://github.com/PyGithub/PyGithub/pull/2512 writes `required_conversation_resolution`, I linked a PR that also reads the attribute. After merging, this can be closed in my opinion.
Also the other field in this quote are done than (expect for block_creations).
