### ISSUE TITLE
how to rename a file 

### ISSUE THREAD

**Issue by Fareed-Ahmad7** [PyGithub/PyGithub#2259]
Hello there!
There exists very good explanation for updating a file in documentation but no example for renaming a file.
thank you!

**Comment by marcorosa** [comment]
Hi, there isn't an API for directly renaming a file

**Comment by Fareed-Ahmad7** [comment]
so only way to rename is deleting the file and then upload that same file with new name??

**Comment by marcorosa** [comment]
Yes it is. [In this discussion](https://stackoverflow.com/questions/31563444/rename-a-file-with-github-api), a workaround is described where you can do it with 1 commit, but it requires several API calls.

**Comment by Fareed-Ahmad7** [comment]
Ok Alright 👍
