### ISSUE TITLE
Please update pyjwt to 2.4,0 or later

### ISSUE THREAD

**Issue by mariaolivero** [PyGithub/PyGithub#2260]
https://github.com/advisories/GHSA-ffqj-6fqr-9h24
Key confusion through non-blocklisted public key formats

Considered a high priority update.

**Comment by hugovk** [comment]
PyGithub requires `pyjwt>=2.0`, so there's nothing to stop end users updating, and if they do a fresh install they'll get a newer version.

But it's a good idea to require at least the fixed 2.4.0 as a minimum version too.

Please see PR #2333.
