### ISSUE TITLE
Missing documentation for class GitHub

### ISSUE THREAD

**Issue by buhtzz** [PyGithub/PyGithub#2262]
https://github.com/PyGithub/PyGithub/blob/001970d4a828017f704f6744a5775b4207a6523c/github/MainClass.py#L108

This is just an example while reading the docs at readthedocs. The arguments for the class `Github` are not documented. The description is missing.

**Comment by oriash93** [comment]
looks like this is not an issue anymore - https://pygithub.readthedocs.io/en/latest/github.html
