### ISSUE TITLE
Python cannot import github

### ISSUE THREAD

**Issue by Riffecs** [PyGithub/PyGithub#2279]
Hi guys,

Do you know how to fix this? The error only occurs with the project. Other pypi packages like numpy or pandas work fine. What am I doing wrong?

Greetings [Riffecs](https://github.com/Riffecs)

# System Info:
```
> lsb_release -a    
  Distributor ID: Ubuntu 
  Description:    Ubuntu 20.04.4 LTS
  Release:        20.04
  Codename:       focal

> python --version
  Python 3.10.5 

> pip --version
  pip 20.0.2 from /usr/lib/python3/dist-packages/pip
```
# Code executed:
## pip
```zsh
pip install PyGithub
```
## Python Code
```python
from github import GitHub as g
# import pathlib

print(g.get_user("Riffecs"))
```

# Error
```
> python repo.py                                                          
  Traceback (most recent call last):
    File "<PATH>/repo.py", line 1, in <module>
      from github import GitHub as g
  ModuleNotFoundError: No module named 'github'
```

# ZSH Config
```zsh
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$HOME/bin:/home/riffecs/.local/bin:$PATH
```

**Comment by jl-applied** [comment]
My guess is an unfortunate `python` install.

What does `python -c 'import sys;print(sys.path)'` give?
For example, mine gives,
```
euclid% python -c 'import sys;print(sys.path)' 
['', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/jamison/.local/lib/python3.10/site-packages', '/usr/lib/python3.10/site-packages']
```
which includes the path which my `pygithub` is installed,
```
euclid% pip show pygithub
Name: PyGithub
Version: 1.55
...
Location: /home/jamison/.local/lib/python3.10/site-packages
...
```
---
fwiw, I _might_ have been able to reproduce this the first time I started a `zsh` shell. I patched the script to,
```
import github

print(github.Github.get_user("Riffecs"))
```
(this is how I personally prefer important packages), and it's worked since, but probably just coincidence.

**Comment by Riffecs** [comment]
Hi @jl-applied 
I took a picture for the sake of simplicity. 


```python -c 'import sys;print(sys.path)'```
<img width="952" alt="image" src="https://user-images.githubusercontent.com/102326693/180667180-58809141-987a-439c-b73e-ead02eb4c5d4.png">


```pip show pygithub```
<img width="419" alt="image" src="https://user-images.githubusercontent.com/102326693/180667256-fd7e8997-f7af-4111-b535-2b0c66c1b447.png">

**Comment by Riffecs** [comment]
Sorry. I pressed the wrong button.
Even if I add the path in the ZSH as Python Path it does not work. What am I doing wrong?

**Comment by jmelahman** [comment]
Something seems strange with your environment/python install. The original post showed `python --version` pointing to `python3.10` and now it is not found.

I'm not an expert here, but I don't think your shell's `PATH` is all that relevant. Maybe python relies on it to infer what the `sys.path` should be, but that inevitably is where it will look for packages to `import` -- (there is also an analogous `PYTHONPATH` variable to append a path through the shell env).

Given the outputs above, I would suspect `python3 -c 'import github'` should work. If not, maybe also try `python3.8 -c 'import github'`

---
Also, it you want to use `python3.10`, you'll probably want to explicitly install `pip3.10`. Using `python3.10` will not be aware of packages installed with `pip3.8` (unless you explicitly allow this i.e. with altering your `PYTHONPATH` which is probably not recommended).

**Comment by marcorosa** [comment]
It seems to me that you installed correctly the packages for python3.10, but in your environment python3.8 has a higher priority so it gets executed (and there you don't have the packages you need).

Launch your script as `python3.10 repo.py` or, if you want to use the interpreter manually, `python3.10` instead of `python3`.
If it correctly works, you may want to update the reference to python3.10 with `update-alternatives` ([here](https://www.kalilinux.in/2021/05/update-alternatives-error-no-alternatives-for-python3.html) you find an example for kali, but for ubuntu the steps are the same).

**Comment by Riffecs** [comment]
Thank you for your help. I just reinstalled Ubuntu. Thereby there was only the 3.8 version. Well, then I just live with it. Apparently it can import github as PyGitHub. The code below is from @jl-applied from the issue. But what I don't understand is why this doesn't work with Python 3.10. 
Greetings @Riffecs

![image](https://user-images.githubusercontent.com/102326693/180860125-f04410bd-cff8-453e-b8fe-a14ed9c97d8f.png)

**Comment by jmelahman** [comment]
To be clear, it is perfectly normal to have multiple versions of python installed (I have `3.6`-`3.10` installed personally). That being said, it can definitely complicates things a bit.

Moreover, similar to python, the minor version of `pip` is also relevant here and must match the version of python you intended to use.

Whenever in doubt, you can always invoke the specific versions of either directly with `python3.10` and `pip3.10`. If you installed `python3.10` and `pip3.10` now and use them directly, I suspect it would work (it worked for me at least).

---

As for you new issue, I too was getting this when debugging and seems like the code provided has some issue (maybe you're missing initializing this `Github` object without an access_token,
```
print(g('your_access_token_here').get_user("Riffecs"))
```
), but I'll let someone with more experience with this particular package speak to that. Good luck :)

**Comment by Riffecs** [comment]
Hello people. 
Thanks for all your help. I will now close the issue. 
With kind regards
Riffecs
