### ISSUE TITLE
Support GraphQL Repository Discussions

### ISSUE THREAD

**Issue by milosmns** [PyGithub/PyGithub#2283]
Is there a plan to support repository discussions? So not teams but repositories.

Example: https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions

**Comment by EnricoMi** [comment]
Looks like this project has never called into the GraphQL API, and the REST API does not seem to provide this feature yet.

**Comment by EnricoMi** [comment]
PyGithub now has its first GraphQL call, see https://github.com/PyGithub/PyGithub/commit/232df79a2947dc96363bdc6f51a6f446ff2b241f#diff-90017b18548bd848900b7cffd7fe86a610dc20e5d228663dfb429a47cdf65a20R767-R772 for reference.

**Comment by ibaguio** [comment]
Hey legends, thank you for the work on this one. When will this go live into a release? cheers.
