### ISSUE TITLE
Feat Request : add support for required_conversation_resolution in edit branch protection rules

### ISSUE THREAD

**Issue by RoyBg** [PyGithub/PyGithub#2299]
the field required_conversation_resolution <bool> is supported by the REST API 
(see https://docs.github.com/en/rest/branches/branch-protection#update-status-check-protection) 

please add this property for the branch.edit_protection() method

**Comment by testworksau** [comment]
Looks like this was implemented by https://github.com/PyGithub/PyGithub/pull/2512

**Comment by treee111** [comment]
#2512 only writes that attribute, I linked a PR that also reads the attribute. After merging, this can be closed in my opinion.
