### ISSUE TITLE
Artifact support ?

### ISSUE THREAD

**Issue by lelegard** [PyGithub/PyGithub#2313]
Hello,

Is there any support for artifacts? Meaning request `/repos/{owner}/{repo}/actions/artifacts` . I could not find anything and I would like to rewrite an existing script which purges artifacts using module `requests` into one using module `github`.

**Comment by lexa** [comment]
Hi @lelegard, I've made a PR for adding artifacts support: https://github.com/PyGithub/PyGithub/issues/2313. I will appreciate if you can check it out.

**Comment by lelegard** [comment]
Hi @lexa 

Thanks a lot for the prompt improvement, much appreciated.

I have a few questions. To give you a idea of what is done, the script I would like to update is here: https://github.com/tsduck/tsduck/blob/master/.github/maintenance/purge-artifacts.py

This script still uses the `requests` module. The other scripts in the same directory were already converted to `PyGithub`.

The required methods for the artifacts script are (with links to the API docs):
1. [List all artifacts of a repo](https://docs.github.com/en/rest/actions/artifacts#list-artifacts-for-a-repository)
2. [Delete an artifact](https://docs.github.com/en/rest/actions/artifacts#delete-an-artifact)

Quickly browsing through the changes in your PR, I do not see the way to achieve this.
- There is a method to get the artifacts of a workflow run, but no method `get_artifacts()` in class `Repository`, for all artifacts in the repository (requirement 1).
- I see no method to delete an artifact in class `Artifact`. 
- Given the [way it works in the REST API](https://docs.github.com/en/rest/actions/artifacts#delete-an-artifact), it could be appropriate to add a method `remove_artifact(int_id)` in class `Repository`, consistent with other "remove" methods in that class (requirement 2).

Thanks for your help.

**Comment by lexa** [comment]
Thanks @lelegard  for checking out my PR.

>There is a method to get the artifacts of a workflow run, but no method get_artifacts() in class Repository, for all artifacts in the repository (requirement 1).

added in the commit https://github.com/lexa/PyGithub/commit/b07bdf3f4e0dcd63db245c59d8e72a8263b895e0

>I see no method to delete an artifact in class Artifact.

added in the commit https://github.com/lexa/PyGithub/commit/fc4e77fb0e13e11ce057cafc65786b98f9e0d28e

Unfortunately I can't test it, because I don't have any artifacts to delete. Could you please test if for me?

To run the test you need to amend https://github.com/PyGithub/PyGithub/pull/2319/commits/36f7fefb8fd78e2b421f38d296b2eb30639f2d10#diff-290729c59eb604d2187e1aa53a36ad692922094ca021239df18330436df52429R45

to set `artifact_id` and `repo_name` to the repo and artifact id you want to remove and then run:
```
pytest  tests/Artifact.py -k testDelete --record
```

It should pass. As the result of the run you will get a recording file `tests/ReplayData/Artifact.testDelete.txt` which i need to include in my PR.

> Given the [way it works in the REST API](https://docs.github.com/en/rest/actions/artifacts#delete-an-artifact), it could be appropriate to add a method remove_artifact(int_id) in class Repository, consistent with other "remove" methods in that class (requirement 2).

I think that is enought to have `delete` method on the `Artifact` itself. What is the point of having `remove_artifact()` in `Repository` if you need to create `Artifact` to get its id?

**Comment by lelegard** [comment]
Hi @lexa 

I will have a look at the update.

> I think that is enought to have delete method on the Artifact itself. What is the point of having remove_artifact() in Repository if you need to create Artifact to get its id?

Functionally, you are right. This was just a suggestion.

In principle, it would match the REST API where there is a call on the repo, specifying the id of the artifact to delete. But you may consider that the class structure in PyGithub is designed to hide this functional approach.

In practice, this is a way to simplify the code structure when you have to browse through all artifacts of a repo and delete some of them. There is a pitfall in the Github API about "paginated" lists. When you iterate page by page (say 100 items per page), reading the "next page" is not "starting after the last returned item", this is "page number 2", meaning "starting at item number 101". If you iterate on items without deleting or creating any, it does not make a difference. However, when you list all "items" (artifacts for instance), decide which should be deleted and delete them, then you have a problem. Let's take an example: in the first page (items 1 to 100), you decide to delete 10 of them. Then, moving to "next page" means "start at item 101, _after the deletion_, meaning that items which were numbered 101 to 110 before deletion are missed because they are now numbered 91 to 100.

The problem is real, I ran into it with the REST API and with PyGithub `PaginatedList`. It took me some time to understand why my purge script randomly missed some artifacts and I had to run it several times to do a complete purge.

So, in practice, you need a first pass where you read the items to delete, store their id in some list. Then, during a second pass, you delete the items by id. This is [what my script does](https://github.com/tsduck/tsduck/blob/master/.github/maintenance/purge-artifacts.py) and now it always works at the first run.

I also had the issue, initially, with [this script](https://github.com/tsduck/tsduck/blob/master/.github/maintenance/close-pending.py) which closes issues with a certain label (and then remove the label). Since the issues are browsed using `repo.get_issues(labels = ['close pending'])`, removing the label of one issue while browsing changes the numbering of issues with that label when the next page is transparently fetched by the iterator at some point.

This is a particularly nasty behaviour that I haven't seen documented anywhere, neither in the Github API doc nor in the PyGithub doc. Once you understand it, it makes sense. But it may take some time to understand it.

If is perfectly possible to build and store a list of instances of `Artifact` during the first pass and then invoke their `delete()` method in the second pass. I thought it would be faster and less resource-demanding to store only a list of integer ids during the first pass and then delete them by id using the instance of `Repository`.

However, this is just the rationale for my suggestion. We can live without it and feel free to ignore it if you do not like it.

**Comment by lelegard** [comment]
Hi @lexa,

I have converted my [purge-artifact script here](https://github.com/tsduck/tsduck/blob/master/.github/maintenance/purge-artifacts-new.py). It works perfectly.

Forget about the suggestion to provide a delete_artifact method by id in the ` Repository` class. I used a list of `Artifact` instances.

Currently, I keep the two versions of the scripts, one using the REST API and one using your updated `PyGithub`. When do you think the updated version of `PyGithub` will be available in PyPI?

Thanks again @lexa for the update.

**Comment by lexa** [comment]
>Currently, I keep the two versions of the scripts, one using the REST API and one using your updated PyGithub. When do you think the updated version of PyGithub will be available in PyPI?

No idea, but considering that the last activity on this repo was in december 2021 you shouldn't expect that it will ever reach the upstream.

**Comment by lelegard** [comment]
> No idea, but considering that the last activity on this repo was in december 2021 you shouldn't expect that it will ever reach the upstream.

Too bad... Any idea on who is managing the project these days ?

**Comment by thburghout** [comment]
I noticed that the WorkflowRun.pyi file is still missing the description of `get_artifacts()`.
