### ISSUE TITLE
PyGithub project status ?

### ISSUE THREAD

**Issue by lelegard** [PyGithub/PyGithub#2320]
Hello @adamtheturtle, @jacquev6, @JPWKU, @sfdye

What is the current status of the PyGithub project ?

The project seems quite used and appreciated (5.5k stars). However, the most recent commit in the project dates back from 2021, one year ago. In the meantime, the Github REST API evolves and several users provided pull requests. 50 of them are waiting for integration.

The community seems active. I recently asked a question about a missing feature (#2313) and a user, @lexa, immediately provided a pull request with the missing feature (#2319).

It is a pity that 50 pull requests, probably mostly improvements, are queuing for one year. In the meantime, users doing `pip install PyGithub` (as I did a couple of weeks ago) do not benefit from them. How could we unblock the situation, let the waiting PR's being reviewed and integrated and let PyPI get updated with a bright new version?

Thanks all,

**Comment by sfdye** [comment]
This is fair. Simply put, the maintainers are busy with their lives. If any of you want to get this project moving, consider joining the team or sponsoring via Github sponsors. 

However I can get the PR review going when I have some free time towards the end of the year. In particular which ones would like to have  first and released to PyPI? Let me know so I can prioritize.

**Comment by sfdye** [comment]
Merge with #2178
