### ISSUE TITLE
Mismatch typing of Requester's __init__ method.

### ISSUE THREAD

**Issue by sahiljoster32** [PyGithub/PyGithub#2322]
In the main file ( Requester.py ), Requester's `__init__` method can accept `pool_size` argument
https://github.com/PyGithub/PyGithub/blob/001970d4a828017f704f6744a5775b4207a6523c/github/Requester.py#L303
but in its type file ( Requester.pyi ), pool_size argument is missing from `__init__` method https://github.com/PyGithub/PyGithub/blob/001970d4a828017f704f6744a5775b4207a6523c/github/Requester.pyi#L97

**Comment by EnricoMi** [comment]
This is fixed by #2151, but maintainers don't have time to review and approve, so the PR went stale.

Please add :+1: to #2151's description if you [want maintainers attention](https://github.com/PyGithub/PyGithub/issues/2178#issuecomment-1263184406).
