### ISSUE TITLE
Drop support for Python 3.6?

### ISSUE THREAD

**Issue by sfdye** [PyGithub/PyGithub#2329]
What do you guys thinks? Python 3.6 is already EOL as of 23 Dec 2021.  We can drop support for Python 3.6 in the latest version.

https://endoflife.date/python

**Comment by hugovk** [comment]
Please see PR https://github.com/PyGithub/PyGithub/pull/2332.

**Comment by sfdye** [comment]
Got it, thanks! @hugovk
