### ISSUE TITLE
Organization exists but still getting Unknown Object Error 404

### ISSUE THREAD

**Issue by Abe410** [PyGithub/PyGithub#2344]
Hi guys

I am trying to get data about a few repositories through the following method:

```
gh = Github(TOKEN)
    
org = gh.get_organization('0xMonero')
```

If I run the above code on any other organization, I get a valid result. But running the above code with the `0xMonero` organization, I get the following error:

`UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest"}`

Going to the actual URL of the organization (https://github.com/0xMonero), I can see that it indeed is a valid public organization, so why is it throwing an error?

Or does the pygithub API only return results for the past 1 year? Because that then makes sense because the organization has not activity for the past 2 years.

Thanks for your help!

**Comment by nitr7gen** [comment]
![image](https://user-images.githubusercontent.com/115389864/199754671-8ea4dac8-3f37-4986-a8cb-2b6ca67f7cbe.png)

the issue is with the Github rest api
