### ISSUE TITLE
PR get_comments() paginated list returns empty while pull.comments shows more

### ISSUE THREAD

**Issue by niro-lightspin** [PyGithub/PyGithub#2371]
I have a PR with 1 comment but failed to get it using `pull.get_comments()` while `pull.comments` returns 1

> pull = github_repo.get_pull(39)
> pull.comments
> 1
> pull.get_comments().totalCount
> 0
> for c in pull.get_comments():
> ...     print(c)
> prints nothing...

**Comment by chouetz** [comment]
Hello @niro-lightspin, is it possible to access the PR you mention in your comment? Is the repo a public one and is the PR still available, to investigate?

**Comment by niro-lightspin** [comment]
Hi @chouetz the repo I used is a private one
I guess we can try to replicate on a public one.. should we?

**Comment by chouetz** [comment]
> Hi @chouetz the repo I used is a private one
> I guess we can try to replicate on a public one.. should we?

Yes if you don't mind it would give me something to work on, many thanks in advance!

**Comment by niro-lightspin** [comment]
@chouetz you can do something like:
`github_client.get_repo("PyGithub/PyGithub").get_pull(2387).comments`
it will return 1 while
`github_client.get_repo("PyGithub/PyGithub").get_pull(2387).get_comments()[0]`
returns `IndexError: list index out of range`

**Comment by chouetz** [comment]
@niro-lightspin indeed, the values are confusing, as the comments retrieved by `get_comments` are **review comments** and not commit comments neither issue comments as mentioned [here](https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#about-pull-request-review-comments)
API that gets pull_request also retrieve the number of review_comments, I'll do a PR to change this, let's see if it will be accepted. I'd say we should probably rename the `get_comments` on `get_review_comments` but this is a major change

**Comment by niro-lightspin** [comment]
thanks @chouetz it works

**Comment by chouetz** [comment]
you can maybe close the issue if it's solve, thanks in advance
