### ISSUE TITLE
github.BranchProtection.BranchProtection missing 3 attributes

### ISSUE THREAD

**Issue by ruben-chainalysis** [PyGithub/PyGithub#2373]
This is duplicate of issue [1716](https://github.com/PyGithub/PyGithub/issues/1716) (closed by StaleBot).

GitHub api provides to do the following:

    required_linear_history: true,
    allow_force_pushes: true,
    allow_deletions: true

https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection

The functions related to this 3 branch protection rules are not added in the class mentioned in the title.

PR #1723 was closed by the author, but this feature is still missing.

**Comment by gidonk-pr** [comment]
also missing `bypass_pull_request_allowances` option..

**Comment by treee111** [comment]
If I am right, adding these attributes to `github.BranchProtection.BranchProtection.py` will give read access for them, whilst adding them to `github.BranchProtection.Branch.py` will give write access.

The read part is in #2793, the write part has been done in https://github.com/PyGithub/PyGithub/pull/2098 but was not merged

is this issue about only reading, only writing or both actions on the named attributes?
