### ISSUE TITLE
`create_git_release` lacks the `generate_release_notes` parameter

### ISSUE THREAD

**Issue by WojciechBarczynski** [PyGithub/PyGithub#2383]
[`create_git_release`](https://github.com/PyGithub/PyGithub/blob/master/github/Repository.py#:~:text=def%20create_git_release) lacks the `generate_release_notes` parameter specified in [GitHub API reference](https://github.com/PyGithub/PyGithub/blob/master/github/Repository.py#:~:text=def%20create_git_release). Since it's common to create a release with autogenerated release notes, adding the boolean parameter to `create_git_release` function seems to be a meaningful life improvement for PyGithub users (We want to use it ourselves in one project).

**Comment by Zethson** [comment]
This only generates the "Full changelog link" sentence but not the actual "What's changed" list, right?

Is there a way to support the latter?
