### ISSUE TITLE
API call returns 502 server error intermittently

### ISSUE THREAD

**Issue by Abe410** [PyGithub/PyGithub#2400]
Hi all,

I have a script running where I collect stats for different organizations on a weekly basis. The script has run fine multiple times, but only recently there has been a problem where the API call returns a 502 server error.

As an example, for a certain organization and it's repos, I ran the script and it gave me a 502 error, but then a few minutes later it ran as intended and gave me the correct results.

Any idea what could be the issue here? Is it totally on Github's end, or is there something I am missing on my end? Since the script has ran as intended a fair few times before, don't think it can be an issue on my end.

Anyone else facing this issue?

Thanks for the help!

**Comment by EnricoMi** [comment]
The 502 error is on GitHub's end, and as you say it is transient. It can happen any time. Retrying your request should be the best strategy here.

Provide a `urllib3.util.retry.Retry` instance to PyGithub, that is configured to retry 5xx responses on all types of requests:

```python
from urllib3.util.retry import Retry
g = Github("access_token", retry=Retry(status_forcelist=list(range(500, 600)), allowed_methods={'DELETE', 'GET', 'HEAD', 'OPTIONS', ,'POST', 'PUT', 'TRACE'}))
```

Then PyGithub will retry requests that fail with 5xx errors for you.

https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html

**Comment by Abe410** [comment]
Thank you very much, will implement this!
