### ISSUE TITLE
Missing new options for controlling the default commit title on the Repository

### ISSUE THREAD

**Issue by raulcd** [PyGithub/PyGithub#2403]
Hi,

I was investigating how to implement the new options around default commit messages when merging a pull request:

https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/ 

Based on the above this can be implemented via the API using:
`squash_merge_commit_title` and `squash_merge_commit_message` as seen on the API: https://docs.github.com/en/rest/repos/repos#update-a-repository

I can't find this being implemented on `PyGithub` but I can see we can modify on the `edit` repo the type of merge: https://github.com/PyGithub/PyGithub/blob/master/github/Repository.py#L1564-L1566

Is this something that people would be interested about?

Thanks,

**Comment by tekumara** [comment]
+1 

hacking this for now with:
```python
        requester: Requester = self._client._Github__requester     # type: ignore

        # squash merging commits default to pull request title and description
        post_parameters = {
            "squash_merge_commit_title": "PR_TITLE",
            "squash_merge_commit_message": "PR_BODY"
        }
        _, _ = requester.requestJsonAndCheck(
            "POST", f"{requester.base_url}/repos/{org_name}/{repo_name}", input=post_parameters
        )
```

**Comment by EnricoMi** [comment]
Looks like all is needed here is adding the `squash_*` attributes to `Repository`. Any volunteers?

https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#update-a-repository

**Comment by tekumara** [comment]
Thanks @EnricoMi I've raised #2700 for this.
