### ISSUE TITLE
Create a review comment for a pull request using deprecated position parameter

### ISSUE THREAD

**Issue by niro-lightspin** [PyGithub/PyGithub#2404]
according to [API docs](https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#create-a-review-comment-for-a-pull-request) the `position` parameter is deprecated but PyGithub is still using it so I get this error:

> TypeError: create_review_comment() missing 1 required positional argument: 'position'

New API arguments are not working:

> TypeError: create_review_comment() got an unexpected keyword argument 'line'

**Comment by heitorpolidoro** [comment]
Hi,

I created this pull request #2540 that might fix this issue

**Comment by EnricoMi** [comment]
This has been fixed in #2540.
