### ISSUE TITLE
ProjectsV2 uses GraphQL. will this project support that? 

### ISSUE THREAD

**Issue by rheophile10** [PyGithub/PyGithub#2405]
this project supports projects (classic) but not ProjectsV2

Do we want to extend this project to support ProjectsV2? 

[github api docs](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects)

**Comment by rheophile10** [comment]
I no longer have a need for it to

**Comment by Alex-ley-scrub** [comment]
I need to manage ProjectsV2 - is there any plan to support it?
