### ISSUE TITLE
v2 module names do not conform to PEP8

### ISSUE THREAD

**Issue by singingwolfboy** [PyGithub/PyGithub#241]
I noticed that the module names in version 2 do not conform to [PEP8](http://legacy.python.org/dev/peps/pep-0008/#package-and-module-names): "Modules should have short, *all-lowercase* names." The files in the `develop_v2` branch are camel-cased. Can the filenames be changed to lowercase?

**Comment by jzelinskie** [comment]
v2 is dead

**Comment by Borda** [comment]
Can we please still not use camel cases for module names? It is very confusing, especially when the module name is identical to the class inside, so while you import it, you never know if it is class or module :(
