### ISSUE TITLE
#1986 seems to break setting GitHub base URL

### ISSUE THREAD

**Issue by bluek1te** [PyGithub/PyGithub#2420]
#1986 seems to break setting base URL.

What I did:
```
auth = AppAuthentication(int(os.getenv("GITHUB_APP_ID")),
                         t,
                         int(os.getenv("GITHUB_APP_INSTALLATION_ID")))
g = Github(base_url="https://test.somegit.com/api/v3", app_auth=auth)
```

When I turn on debugger, the base URL for requester seems to be set to api.github.com. Lmk if I am doing something wrong here, thanks!

**Comment by EnricoMi** [comment]
Looks like the Requester does not pass the base url to `GithubIntegration`:

https://github.com/PyGithub/PyGithub/blob/c7e3ae94214eaa702121d6ff08c92d83af47ebd9/github/Requester.py#L375-L379
https://github.com/PyGithub/PyGithub/blob/c7e3ae94214eaa702121d6ff08c92d83af47ebd9/github/GithubIntegration.py#L19-L26

@dblanchette

**Comment by bluek1te** [comment]
I took a stab at it: https://github.com/PyGithub/PyGithub/pull/2425
