### ISSUE TITLE
Connect through a proxy

### ISSUE THREAD

**Issue by sanuma02** [PyGithub/PyGithub#2426]
While reading https://github.com/PyGithub/PyGithub/pull/309 it looked like https://github.com/PyGithub/PyGithub/issues/172 was addressed however I am still unable to find a way to set up a proxy. Was this never done? or am I just not finding how to set up a proxy?

**Comment by EnricoMi** [comment]
PyGitHub uses Python package requests under the hood to do the HTTP calls. The requests supports environment variables to configure proxies:

https://requests.readthedocs.io/en/latest/user/advanced/#proxies

It also supports HTTP basic auth. See the docs above on how to setup proxy settings.

**Comment by sanuma02** [comment]
Many thanks for taking the time to reply

The issue I was having was not while running local, a Flask application using PyGitHub had no problem to pick up the Proxy variables 

The issue was with the application deployed, the inner request PyGitHub was doing was not picking up the proxy 

Just sharing in case anyone else is having this issue, my problem was that I was missing to add the proxy settings in my program.service

```
[Service]
User=XXXXXx
Group=XXXXX
WorkingDirectory=/home/XXXXX/XXXX
Environment=https_proxy=http://XXX.XXX.XX.X:XXXX
Environment=https_proxy=http://XXX.XXX.XX.X:XXXX
```

Thanks again for the help!
