### ISSUE TITLE
Cannot import name 'Github' from 'github'

### ISSUE THREAD

**Issue by judemont** [PyGithub/PyGithub#2427]
I have installed PyGithub but when I run : `from github import Github` I have this error : 
`Traceback (most recent call last):
  File "/home/user/projects/main.py", line 1, in <module>
    from github import Github
ImportError: cannot import name 'Github' from 'github' (unknown location)`

OS : Ubuntu, linux
Python3 version : Python 3.10.7
PyGithub==1.57

**Comment by EnricoMi** [comment]
Can you please provide the steps you used to install PyGithub? Are you using a virtual env environment?

**Comment by judemont** [comment]
To install it I simply used pip.
`pip install pyGithub`

**Comment by EnricoMi** [comment]
Without reproducing this, it is very hard to debug.

Running the following on a clean Ubuntu 22.10, it works just fine:

Start shell on a clean Ubuntu:
```
docker run --rm -it ubuntu:22.04
```

In that shell, run this:
```
# setup python and pip
apt update
apt install -y python3.10 curl
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3.10 get-pip.py

# install pygithub
pip install pygithub

# test pygithub
python3.10 -c 'from github import Github; repo="PyGithub/PyGithub"; print(f"Repo {repo} has {len(list(Github().get_repo(repo).get_issues()))} issues")'
```

**Comment by EnricoMi** [comment]
instead of

    pip install pyGithub

can you run the following?

    python3.10 -m pip install pyGithub

where `python3.10` is he same command that you use to run

    python3.10 -c 'from github import Github'

**Comment by judemont** [comment]
> Without being able to reproduce this, it is very hard to debug.
> 
> Running the following on a clean Ubuntu 22.10 works just fine:
> 
> Start a shell on a clean Ubuntu:
> 
> ```
> docker run --rm -it ubuntu:22.04
> ```
> 
> In that shell, run this:
> 
> ```
> # setup python and pip
> apt update
> apt install -y python3.10 curl
> curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
> python3.10 get-pip.py
> 
> # install pygithub
> pip install pygithub
> 
> # test pygithub
> python3.10 -c 'from github import Github; repo="PyGithub/PyGithub"; print(f"Repo {repo} has {len(list(Github().get_repo(repo).get_issues()))} issues")'
> ```
> 
> ```
> Repo PyGithub/PyGithub has 209 issues
> ```

I am trying.

**Comment by judemont** [comment]
> 



> Instead of
> 
> ```
> pip install pyGithub
> ```
> 
> can you run the following?
> 
> ```
> python3.10 -m pip install pyGithub
> ```
> 
> where `python3.10` is he same command that you use to run
> 
> ```
> python3.10 -c 'from github import Github'
> ```

When I try `python3.10 -m pip install pyGithub` there is the same result as with pip (Requirement already satisfied)

`python3.10 -c 'from github import Github'` : still the same error.

**Comment by EnricoMi** [comment]
When you run

    python -c "import sys; print(sys.path)"

you get a list of directories. Can you look into each of those directories if the subdirectory `github` exists and paste the directory listing of it here?

**Comment by EnricoMi** [comment]
Btw., does this work?

    import github

What is the content of `/home/user/projects/`?

**Comment by judemont** [comment]
`
['', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/judemont/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/share/panda3d']`

No he don't have github

**Comment by judemont** [comment]
> import github

Yes, it work !

**Comment by EnricoMi** [comment]
Running

    pip show pygithub

shows where pygithub has been installed. Where is that?

**Comment by judemont** [comment]
`Name: PyGithub
Version: 1.57
Summary: Use the full Github API v3
Home-page: https://github.com/pygithub/pygithub
Author: Vincent Jacques
Author-email: vincent@vincent-jacques.net
License: 
Location: /home/judemont/.local/lib/python3.10/site-packages
Requires: deprecated, pyjwt, pynacl, requests
Required-by: `

**Comment by EnricoMi** [comment]
Does `/home/judemont/.local/lib/python3.10/site-packages/github` exist?

**Comment by judemont** [comment]
Yes it exist

**Comment by EnricoMi** [comment]
You just said it doesn't: https://github.com/PyGithub/PyGithub/issues/2427#issuecomment-1435703119

Anyway, run this:

    ls /home/user/projects/ /home/judemont/.local/lib/python3.10/site-packages/github

**Comment by judemont** [comment]
> You just said it doesn't: [#2427 (comment)](https://github.com/PyGithub/PyGithub/issues/2427#issuecomment-1435703119)
> 
> Anyway, run this:
> 
> ```
> ls /home/user/projects/ /home/judemont/.local/lib/python3.10/site-packages/github
> ```

Oh yes, sorry, I didn't quite understand.

> lib/python3.10/site-packages/github
/home/judemont/.local/lib/python3.10/site-packages/github:
AccessToken.py                 IssueEvent.py
AccessToken.pyi                IssueEvent.pyi
ApplicationOAuth.py            IssuePullRequest.py
ApplicationOAuth.pyi           IssuePullRequest.pyi
Artifact.py                    Issue.py
Artifact.pyi                   Issue.pyi
AuthenticatedUser.py           Label.py
AuthenticatedUser.pyi          Label.pyi
AuthorizationApplication.py    License.py
AuthorizationApplication.pyi   License.pyi
Authorization.py               MainClass.py
Authorization.pyi              MainClass.pyi
Autolink.py                    Membership.py
Autolink.pyi                   Membership.pyi
BranchProtection.py            Migration.py
BranchProtection.pyi           Migration.pyi
Branch.py                      Milestone.py
Branch.pyi                     Milestone.pyi
CheckRunAnnotation.py          NamedUser.py
CheckRunAnnotation.pyi         NamedUser.pyi
CheckRunOutput.py              Notification.py
CheckRunOutput.pyi             Notification.pyi
CheckRun.py                    NotificationSubject.py
CheckRun.pyi                   NotificationSubject.pyi
CheckSuite.py                  Organization.py
CheckSuite.pyi                 Organization.pyi
Clones.py                      PaginatedList.py
Clones.pyi                     PaginatedList.pyi
CommitCombinedStatus.py        Path.py
CommitCombinedStatus.pyi       Path.pyi
CommitComment.py               Permissions.py
CommitComment.pyi              Permissions.pyi
Commit.py                      Plan.py
Commit.pyi                     Plan.pyi
CommitStats.py                 ProjectCard.py
CommitStats.pyi                ProjectCard.pyi
CommitStatus.py                ProjectColumn.py
CommitStatus.pyi               ProjectColumn.pyi
Comparison.py                  Project.py
Comparison.pyi                 Project.pyi
Consts.py                      PublicKey.py
ContentFile.py                 PublicKey.pyi
ContentFile.pyi                PullRequestComment.py
Deployment.py                  PullRequestComment.pyi
Deployment.pyi                 PullRequestMergeStatus.py
DeploymentStatus.py            PullRequestMergeStatus.pyi
DeploymentStatus.pyi           PullRequestPart.py
Download.py                    PullRequestPart.pyi
Download.pyi                   PullRequest.py
Event.py                       PullRequest.pyi
Event.pyi                      PullRequestReview.py
File.py                        PullRequestReview.pyi
File.pyi                       __pycache__
GistComment.py                 py.typed
GistComment.pyi                RateLimit.py
GistFile.py                    RateLimit.pyi
GistFile.pyi                   Rate.py
GistHistoryState.py            Rate.pyi
GistHistoryState.pyi           Reaction.py
Gist.py                        Reaction.pyi
Gist.pyi                       Referrer.py
GitAuthor.py                   Referrer.pyi
GitAuthor.pyi                  RepositoryKey.py
GitBlob.py                     RepositoryKey.pyi
GitBlob.pyi                    RepositoryPreferences.py
GitCommit.py                   RepositoryPreferences.pyi
GitCommit.pyi                  Repository.py
GithubApp.py                   Repository.pyi
GithubApp.pyi                  Requester.py
GithubException.py             Requester.pyi
GithubException.pyi            RequiredPullRequestReviews.py
GithubObject.py                RequiredPullRequestReviews.pyi
GithubObject.pyi               RequiredStatusChecks.py
GitignoreTemplate.py           RequiredStatusChecks.pyi
GitignoreTemplate.pyi          SelfHostedActionsRunner.py
GitObject.py                   SelfHostedActionsRunner.pyi
GitObject.pyi                  SourceImport.py
GitRef.py                      SourceImport.pyi
GitRef.pyi                     Stargazer.py
GitReleaseAsset.py             Stargazer.pyi
GitReleaseAsset.pyi            StatsCodeFrequency.py
GitRelease.py                  StatsCodeFrequency.pyi
GitRelease.pyi                 StatsCommitActivity.py
GitTag.py                      StatsCommitActivity.pyi
GitTag.pyi                     StatsContributor.py
GitTreeElement.py              StatsContributor.pyi
GitTreeElement.pyi             StatsParticipation.py
GitTree.py                     StatsParticipation.pyi
GitTree.pyi                    StatsPunchCard.py
HookDescription.py             StatsPunchCard.pyi
HookDescription.pyi            Tag.py
Hook.py                        Tag.pyi
Hook.pyi                       TeamDiscussion.py
HookResponse.py                TeamDiscussion.pyi
HookResponse.pyi               Team.py
__init__.pyi                   Team.pyi
InputFileContent.py            TimelineEvent.py
InputFileContent.pyi           TimelineEvent.pyi
InputGitAuthor.py              TimelineEventSource.py
InputGitAuthor.pyi             TimelineEventSource.pyi
InputGitTreeElement.py         Topic.py
InputGitTreeElement.pyi        Topic.pyi
InstallationAuthorization.py   UserKey.py
InstallationAuthorization.pyi  UserKey.pyi
Installation.py                View.py
Installation.pyi               View.pyi
Invitation.py                  Workflow.py
Invitation.pyi                 Workflow.pyi
IssueComment.py                WorkflowRun.py
IssueComment.pyi               WorkflowRun.pyi

/home/judemont/projet/python/test/:
github_test.py

**Comment by EnricoMi** [comment]
It does not look like there is a `__init__.py` in `/home/judemont/.local/lib/python3.10/site-packages/github`, only `__init__.pyi`.

**Comment by EnricoMi** [comment]
Try t reinstall it:

    pip install --force --no-cache pygithub

**Comment by judemont** [comment]
YES it's work, Tank you very much !
