### ISSUE TITLE
v1.58.0 TypeError: create_jwt() got an unexpected keyword argument 'expiration'

### ISSUE THREAD

**Issue by andrewlarry** [PyGithub/PyGithub#2432]
The `expiration` keyword argument was removed in v1.58.0. The interface defined in GithubIntegration.pyi is no longer accurate.

**Comment by EnricoMi** [comment]
@andrewlarry  Would you mind creating a PR to fix the typing? I'm happy to approve.

**Comment by s-t-e-v-e-n-k** [comment]
v2.0.0 has had some beta tags, so I'd rather avoid it. We should add it back, I'm not sure we need to deprecate it.

**Comment by EnricoMi** [comment]
Sure, does not hurt to keep it. Lets make it optional, though.
