### ISSUE TITLE
Field 'required_linear_history' missing from 'Branch.edit_protection'

### ISSUE THREAD

**Issue by kszonek** [PyGithub/PyGithub#2448]
GitHub API documents`required_linear_history` field as `bool` to toggle this option in branch protection rules. It is missing in PyGitHub `Branch.edit_protecion()`

**Comment by juanpflores** [comment]
Wonder if it would be of help to mention that GitHub released [org-wide branch protections](https://github.blog/changelog/2023-04-17-introducing-repository-rules-public-beta/) today.

**Comment by EnricoMi** [comment]
This has been fixed in https://github.com/PyGithub/PyGithub/pull/2512.
