### ISSUE TITLE
The specific number of contributors corresponding to the 403 error code when using the repo.get_contributors( ) function.

### ISSUE THREAD

**Issue by AndyLuo1029** [PyGithub/PyGithub#2454]
I use PyGithub as an API to crawl data for research. But during use of get_contributors( ) function, I got this exception:

> 403 {"message": "The history or contributor list is too large to list contributors for this repository via the API.", "documentation_url": "https://docs.github.com/rest/reference/repos#list-repository-contributors"}
github.GithubException.GithubException: 403 {"message": "The history or contributor list is too large to list contributors for this repository via the API.", "documentation_url": "https://docs.github.com/rest/reference/repos#list-repository-contributors"}

I can't find any specific limit on the number of contributors in the documentation or in the exception script. Since I will be using the data to train some models, I would like to have a specific limit on the number of contributors.

How many contributors to a repository force the API to return a "403 Too Large to List" error code?

Thanks!

**Comment by EnricoMi** [comment]
This is a question for GitHub, who maintains the API that responds with 403: https://support.github.com/

The PyGitHub project is an independent open source project that calls that API.

**Comment by AndyLuo1029** [comment]
Thank you!
