### ISSUE TITLE
Does PyGitHub follow semantic versioning?

### ISSUE THREAD

**Issue by rite2hhh** [PyGithub/PyGithub#2472]
The changelog for the project states it ["switched" to semantic versioning](https://pygithub.readthedocs.io/en/latest/changes.html#version-1-8-0-september-30th-2012) in version 1.8

I'm seeing a lot of new versions listing "Breaking Changes" without an actual bump to the major version.
Some example releases that mention breaking changes:
https://pygithub.readthedocs.io/en/latest/changes.html#version-1-57-november-05-2022
https://pygithub.readthedocs.io/en/latest/changes.html#version-1-55-april-26-2021

Is there a way that users can shield themselves from breaking changes excluding pinning a fixed version in their project's dependency?

**Comment by EnricoMi** [comment]
You are right, from the change log it looks like this project does not follow semantic versioning any more.

Even for unintended breaks like #1986 it takes maintainers a month to review, merge and release quick fixes. So it is unlikely to get quick patch releases fixing unintended breaks.

From this experience, I recommend to pin the PyGithub version, and brace for integration work when upgrading to a higher minor version.
