### ISSUE TITLE
Add clone_to() method for cloning repositories

### ISSUE THREAD

**Issue by yus4u** [PyGithub/PyGithub#2474]
Currently, the PyGithub library does not provide a method for cloning a repository to a local directory. This feature would be useful for a variety of use cases, such as automated backups, data processing, or testing.

The `clone_to()` method would allow users to clone a repository to a local directory using the GitHub API, without requiring the use of the `git` command line tool. This method would simplify the process of cloning a repository and make it more accessible to users who are not familiar with `git`.

It is important to note that the `clone_to()` method should be designed to run in a single-threaded environment since Cloud functions do not support multiprocessing. However, the method should be optimized for performance and resource usage.

## Example Usage

```python
from github import Github

g = Github("<access_token>")
repo = g.get_repo("<repo_owner>/<repo_name>")
repo.clone_to("<local_directory>")

```

This method would be particularly useful for automated processes that require the use of GitHub repositories, such as continuous integration or deployment pipelines. It would allow users to automate the process of cloning repositories without relying on external tools.

**Comment by s-t-e-v-e-n-k** [comment]
This would require support from the GitHub REST API, and I can't see anything like that in the official docs. I would suggest reaching out to https://support.github.com/
