### ISSUE TITLE
Leverage PEP 484 inline types instead of `.pyi` files

### ISSUE THREAD

**Issue by JLLeitschuh** [PyGithub/PyGithub#2481]
[PEP 484](https://www.python.org/dev/peps/pep-0484/) support was added in Python 3.5, and this library supports 3.7+, as such the `.pyi` files are now redundant and types can be included in line directly in the source files.

I'd like to propose that new classes use [PEP 484](https://www.python.org/dev/peps/pep-0484/), and old classes are slowly migrated to use [PEP 484](https://www.python.org/dev/peps/pep-0484/) over time.

Thoughts?

**Comment by EnricoMi** [comment]
@s-t-e-v-e-n-k @sfdye what are your thoughts?

**Comment by JLLeitschuh** [comment]
I'm working on some new classes here and my plan was to not add the `.pyi` files

https://github.com/PyGithub/PyGithub/pull/2483

**Comment by sfdye** [comment]
Sounds good to me, please go ahead
