### ISSUE TITLE
Support Oauth apps with Github Enterprise

### ISSUE THREAD

**Issue by davidxia** [PyGithub/PyGithub#2485]
Hi, I see `github.com` hardcoded in [places like this](https://github.com/PyGithub/PyGithub/blob/822fc05cd5aaf20c87317b32cd897b5a95bd8c60/github/ApplicationOAuth.py#L75). Are you open to a feature request that supports Oauth apps with Github Enterprise where the API URL is something else like https://my-ghe.example.com/login/oauth/authorize?client_id=XXX?

**Comment by EnricoMi** [comment]
Certainly! Firstly, using `github.com` hardcoded is bad, I agree. The `MainClass` and `GithubIntegration` use `base_url` for this. That is passed to the requester, so I think removing both occurrences of `https://github.com` (so the url becomes relative) from that file should fix this.
