### ISSUE TITLE
Branch edit Protection not having required_linear_history and apps 

### ISSUE THREAD

**Issue by alvarocabanas** [PyGithub/PyGithub#2486]
The [edit protection method from Branch](https://github.com/PyGithub/PyGithub/blob/822fc05cd5aaf20c87317b32cd897b5a95bd8c60/github/Branch.py#L112) doesn't have:
- required_linear_history _-> I've seen there is an open PR to solve this, so I guess this ones is being tackled._
- dismissal_apps
- app_push_restrictions

We would like to know if there is a reason for it and if it's okey to create a PR adding them.
Thanks.

**Comment by juanpflores** [comment]
_Not a maintainer_ but it would be great to have them added as a PR

**Comment by juanpflores** [comment]
Adding #2448 here as well. Both issues are mentioning the same problem.

**Comment by EnricoMi** [comment]
This has been fixed in #2512.
