### ISSUE TITLE
repo

### ISSUE THREAD

**Issue by ChibuezeOnejeme** [PyGithub/PyGithub#2491]
We want to be able to create standardized repositories in my company and we have rules that each repository needs some branch protection rules e.g. on release/* set up. How to add branch protection rule on these nonexistent branches (containing asterisk) with this library?

**Comment by treee111** [comment]
see my comment here: https://github.com/PyGithub/PyGithub/issues/2415#issuecomment-1894460779

it is also a dublicate of #2415, one of them should be closed @EnricoMi
