### ISSUE TITLE
Definition of the initial population for the genetic algorithm by the user

### ISSUE THREAD

**Issue by zsbeheshti** [PyGithub/PyGithub#2494]
Dear all,

I am using Python's pypi genetic algorithm 1.0.2 and I want to run this genetic algorithm with my default initial population. How can I do this?

And is it possible that, for example, out of 70 populations, I introduce only one and the genetic algorithm produces the other 69?

Regards

**Comment by s-t-e-v-e-n-k** [comment]
This is the wrong issue tracker for this problem, please file it at https://github.com/rmsolgi/geneticalgorithm/issues
