### ISSUE TITLE
PullRequest create_comment to support new changes

### ISSUE THREAD

**Issue by talboren** [PyGithub/PyGithub#2517]
Seems like PullRequest `create_comment` (`create_review_comment`) is outdated according to https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#create-a-review-comment-for-a-pull-request (for instance, the `subject_type` option or `position` -> `line`)

I can open a PR from my forked version--looking to see if it's relevant or someone is already working on it.

**Comment by heitorpolidoro** [comment]
Hi,

I created this pull request #2540 that might fix this issue

**Comment by EnricoMi** [comment]
This has been fixed in #2540.
