### ISSUE TITLE
SSL error:Max retries exceeded with url

### ISSUE THREAD

**Issue by zhangdanni1129** [PyGithub/PyGithub#2526]
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Glimpse/xxx (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

i have tried to set the retry parameter in 2 ways below,but it seem didn't work

g1 = Github(access_token1,retry=Retry(100))
g1 = Github(access_token1,retry=100)

**Comment by EnricoMi** [comment]
This looks like a SSL error, which is probably not retry-able, so increasing the retry limit won't fix the problem.

Maybe your system has an old SSL lib installed. Is there any more context than this?

Have you tried to call `github.enable_console_debug_logging()` before using `Github`?

**Comment by EnricoMi** [comment]
Maybe this helps: https://stackoverflow.com/questions/33410577/python-requests-exceptions-sslerror-eof-occurred-in-violation-of-protocol

**Comment by zhangdanni1129** [comment]
> Maybe this helps: https://stackoverflow.com/questions/33410577/python-requests-exceptions-sslerror-eof-occurred-in-violation-of-protocol

thanks!The newest answer in the post works for me!
 just installed urllib3==1.25.11.
