### ISSUE TITLE
Problems with watchers_count property

### ISSUE THREAD

**Issue by oskar-j** [PyGithub/PyGithub#253]
Hi,

I checked with newest 1.25 version. I have some questions:

1) Whats the difference between watchers and watchers_count in Repository.py?
2) Why both return number of stars while number of watchers is much different in reality for a repo ? (checked on resume/resume.github.com/)

regards,
Os.J.

**Comment by X-ration** [comment]
Hello, I just use pygithub to get repositories' statistics, but I found that result of repo.stargazers_count and repo.watchers_count are totally same, so weird... And I wanna know how to solve it.
![default](https://user-images.githubusercontent.com/18644614/34834796-ec827562-f72d-11e7-84da-468855b3c7fa.png)
![2](https://user-images.githubusercontent.com/18644614/34834890-39f2ba46-f72e-11e7-81fb-7615f996ae99.png)
