### ISSUE TITLE
Creating cross-repo Pull Request

### ISSUE THREAD

**Issue by parteekcoder** [PyGithub/PyGithub#2538]
I have 2 repositories 

    repo1 = Organization/project
    repo2 = user/project  (it is forked of repo1)

Can I create a Pull Request from repo2 to repo1 using a Fine-Grained token with the required access of repo2 using PyGithub, If yes can you please help me to do that

**Comment by parteekcoder** [comment]
Here is what  I am doing:

g = Github("token")                                        (token of repo2)
repo1 = g.get_repo("organization/project")
repo2 = g.get_repo("user/project")
repo1.create_pull(title="PR_TITLE", body="PR_BODY", base="main",head="user/project:main")

I am getting this error 
```
github.GithubException.GithubException: 403 {"message": "Resource not accessible by personal access token", "documentation_url": "https://docs.github.com/rest/reference/pulls#create-a-pull-request"}
```

**Comment by EnricoMi** [comment]
Have you tried

    repo1.create_pull(title="PR_TITLE", body="PR_BODY", base="main",head="user:main")

Maybe it is a permission issue. Not sure which fine grained permissions are needed to create a pull request on a public repo.

**Comment by parteekcoder** [comment]
Yeah Thanks @EnricoMi , i figured out another way to do that.

**Comment by EnricoMi** [comment]
Would you like to share your findings?

**Comment by parteekcoder** [comment]
yeah , I used github cli 

```
gh pr create --repo "project" --base "user:main" --head "main"
```
Make sure  before running this command you have access to create PR to upstream repo

**Comment by EnricoMi** [comment]
From looking at the Github REST API docs, this should also work with PyGithub.
