### ISSUE TITLE
[BUG] Rate limit changes after `PaginatedList.totalCount`

### ISSUE THREAD

**Issue by LucBerge** [PyGithub/PyGithub#2548]
I have a rate limite issue in my app. While debuging, I found a weird behaviour.
The rate limit changes after a call to `totalCount`.

```python
client = Github("TOKEN")
commits = client.search_commits(query = 'author:LucBerge')
print(client.rate_limiting)
commits.totalCount
print(client.rate_limiting)
```

Output
> (4344, 5000)
(28, 30)

I know the [rate limit changes if the user is authenticated or not.](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting) Could it be related ?

Maybe the call to `totalCount` unauthentify the client (remove the token) ?
Or the `totalCount` request is performed without the token ?

**Comment by LucBerge** [comment]
[It looks like the rate limit is not the same for search requests](https://docs.github.com/en/rest/search?apiVersion=2022-11-28)

**Comment by LucBerge** [comment]
In Requester.py:581, rate_limit is set to last returned value. This value detends on the request type.

```python
        status, responseHeaders, output = self.__requestRaw(
            cnx, verb, url, requestHeaders, encoded_input
        )

        if (
            Consts.headerRateRemaining in responseHeaders
            and Consts.headerRateLimit in responseHeaders
        ):
            self.rate_limiting = (
                int(responseHeaders[Consts.headerRateRemaining]),
                int(responseHeaders[Consts.headerRateLimit]),
            )
        if Consts.headerRateReset in responseHeaders:
            self.rate_limiting_resettime = int(responseHeaders[Consts.headerRateReset])

        if Consts.headerOAuthScopes in responseHeaders:
            self.oauth_scopes = responseHeaders[Consts.headerOAuthScopes].split(", ")
```

**Comment by LucBerge** [comment]
**It would be nice to make the difference between search requests and others.**

**Comment by EnricoMi** [comment]
Yes, I think this is bug #1988. Would you like to sketch a pull request to fix this?
