### ISSUE TITLE
Using as_pull_request is not working

### ISSUE THREAD

**Issue by shoroogAlghamdi** [PyGithub/PyGithub#2552]
Hello, 
I have a link for an issue as -> https://github.com/psf/requests/issues/4006 and I am trying to get its pull request ID which should be 4007 according to this link -> https://github.com/psf/requests/pull/4007.

The problem is that when I try to use the following code 
`repo = g.get_repo("psf/requests")
issue = repo.get_issue(number=4006)
pr = issue.as_pull_request()
`

I get a 404 error because the URL resulting from as_pull_request() is https://api.github.com/repos/psf/requests/pulls/4006
**which is WRONG as 4006 is the issue ID not the PR ID**, the correct call should be https://api.github.com/repos/psf/requests/pulls/4007, can someone support me please?

**Comment by EnricoMi** [comment]
Please reopen if questions remain.
