### ISSUE TITLE
NamedUser.contributions attribute does not work

### ISSUE THREAD

**Issue by goldtan** [PyGithub/PyGithub#2572]
I tried to use this feature to count the number of contributions made by a user, but all of them are returning None.

I think I had a similar issue before, but when I checked the change log it says it was restored.

https://github.com/PyGithub/PyGithub/issues/622

**Comment by EnricoMi** [comment]
I cannot see in the Github REST API docs that the contributions field exists for a user: https://docs.github.com/en/rest/users/users?apiVersion=2022-11-28#get-a-user

**Comment by goldtan** [comment]
@EnricoMi Thanks for the reply!

Does this mean I can no longer see the number of contributions aggregated by user?

**Comment by EnricoMi** [comment]
It looks like it. Best to check with Github support.

**Comment by goldtan** [comment]
@EnricoMi Thank you for the quick response. :)

I'll check with Github support.
