### ISSUE TITLE
Repository.size is not returning a correct/useful value

### ISSUE THREAD

**Issue by kamali-sina** [PyGithub/PyGithub#2575]
The Repository class has an attribute called "size." However, this attribute seems to return values that have nothing to do with the size of the repository. 

For example, the repository "papasinku/fp2MBtest" is 2076703 bytes in size, but the value returned by the ".size" attribute is 3!

```Python
assert github.Github().get_repo("papasinku/fp2MBtest").size == 2076703 # fails because returned value is 3
```

**Comment by EnricoMi** [comment]
This value is retrieved from the GitHub REST API and returned as is.

Please contact GitHub support mentioning that the `size` field returned by `/repos/{owner}/{repo}` is wrong: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository

**Comment by kamali-sina** [comment]
Awesome, thanks.
