### ISSUE TITLE
Installation not found - github.GithubException.UnknownObjectException: 404

### ISSUE THREAD

**Issue by AleksandraAleksandrova** [PyGithub/PyGithub#2584]
My GitHub app creates a workflow, when installed on an account. I want to delete that same workflow, when the app is uninstalled. So the webhook event is installation with action deleted. 

My PyGitHub version is 1.59.0. The issue seems to be with the line 
**installation = gi.get_app_installation(installation_id)** 

```
auth = github.Auth.AppAuth(app_id, app_key)
gi = github.GithubIntegration(auth=auth)

def handle_webhooks():
    event_type = request.headers.get("X-GitHub-Event")
    payload = request.json
        ...
        if event_type == "installation" and payload["action"] == "deleted":
            installation_id = payload["installation"]["id"]
            installation = gi.get_app_installation(installation_id)
```

although the same kind of authentication works fine, when creating and committing the workflow, meaning that this function: 

```
def create_workflow():
    installation_id = request.json.get("installationId")
    installation = gi.get_app_installation(installation_id)
    workflow_content = "..."
    for repo in installation.get_repos():
        new_file = repo.create_file(
            path=".github/workflows/my-workflow.yml",
            message="Add workflow file",
            content=workflow_content,
            branch="main"
        )
```
works as expected. 

I can provide full error message, if needed.

**Comment by EnricoMi** [comment]
Can you confirm the installation ids are the same in both cases?

**Comment by AleksandraAleksandrova** [comment]
Yes.
I think the problem is in the logic, but I am not sure how to fix it - I am trying to delete the workflow along with the app deletion.

My handle webhooks function is waiting for installation event with delete action. 
But by the time i receive the event, the installation is already deleted. So I no longer can access the installation and therefore the repositories to remove the workflow file. I get the exception, because github probably has deleted the object before my call. The way to fix this would be to pause the actual deletion from github, delete the workflow in the installation's repos and then let github delete the installation. But I am not sure this is possible with this approach (event-listening), probably not.

Open to ideas though.

**Comment by AleksandraAleksandrova** [comment]
So to summarize:

- the exception is exactly what one should get when trying to access an installation after receiving this event
- the event may be helpful if you have your own database, to remove any records associated with this installation id

This issue isn't related directly to the PyGithub library, so I am going to close it.

Thanks!

**Comment by EnricoMi** [comment]
Yes, that makes sense. Your code acts on the installation deletion webhook, so the installation does not exist any more at that point in time. You cannot do any clean-up at that point. There would need to be some kind of pre-delete webhook to do the clean-up before deletion, but that would need to defer the deletion. And since webhooks are async by design, that would be undesirable.

I fear there is currently no way to implement this. Please refer to Github Support, they are very good at pointing to existing functionality or best practice. At least, they can assure you that there is no way to implement this.
