### ISSUE TITLE
Mypy errors on some exception in 1.59.0

### ISSUE THREAD

**Issue by sodul** [PyGithub/PyGithub#2589]
After upgrading to 1.59.0 we got a mypy error on our code catching `UnknownObjectException`:

```
    except github.UnknownObjectException as err:
        message = err.data['message']
```

Now mypy is raising:
```
error: Invalid index type "str" for "str | dict[str, str | list[str] | list[dict[str, str]]]"; expected type "SupportsIndex | slice"  [index]
```

This seems to be caused by the improved type annotation of the `GithubException` base class introduced in #2463:

```
    @property
    def data(
        self,
    ) -> Union[str, Dict[str, Union[str, List[str], List[Dict[str, str]]]]]:
```
Also declared in the `__init__()` signature.

AFAIK `UnknownObjectException` is only raised by `Requester.py` always returning `data` as `output: Dict[str, Any]` so `UnknownObjectException` could be updated to clarify this more accurately so that mypy will not raise typing errors that cannot occur at runtime.

**Comment by EnricoMi** [comment]
@trim21 can you take a look, please?

**Comment by trim21** [comment]
> AFAIK UnknownObjectException is only raised by Requester.py always returning data as output: Dict[str, Any] so UnknownObjectException could be updated to clarify this more accurately so that mypy will not raise typing errors that cannot occur at runtime.

Yes, I think you are right about this.

**Comment by Borda** [comment]
In this moce, may I ask what was the motivation for moving typing to pyi files when the min supported python is 3.7 and it effectively doubles the number of files in the package (and personally, it makes it harder to read as all nested in a single folder)

**Comment by trim21** [comment]
> In this moce, may I ask what was the motivation for moving typing to pyi files when the min supported python is 3.7 and it effectively doubles the number of files in the package (and personally, it makes it harder to read as all nested in a single folder)

because pyi are added before pygithub drop previous python version, they are essential at that time.

**Comment by Borda** [comment]
docs suggest it was added recently in 1.59 release: https://github.com/PyGithub/PyGithub/blob/main/doc/changes.rst#version-1590-june-22-2023

**Comment by trim21** [comment]
> docs suggest it was added recently in 1.59 release: https://github.com/PyGithub/PyGithub/blob/main/doc/changes.rst#version-1590-june-22-2023

https://github.com/PyGithub/PyGithub/tree/v1.57/github

**Comment by trim21** [comment]
pyi are removed, inline types are added in 1.59 release

**Comment by Borda** [comment]
> pyi are removed, inline types are added in 1.59 release

you are right, was reading it wrong, sorry :chipmunk:
