### ISSUE TITLE
Integrate and display external tools

### ISSUE THREAD

**Issue by jacquev6** [PyGithub/PyGithub#261]
Coveralls
Travis
Waffle?
Bountysource? GitTip?

Brag a bit with https://pypip.in  [![Downloads](https://pypip.in/d/PyGithub/badge.svg)](https://pypi.python.org/pypi/PyGithub)

Review everything available at http://shields.io

https://caniusepython3.com/project/PyGithub

**Comment by jzelinskie** [comment]
pretty sure we have this for the important things
