### ISSUE TITLE
Running `mypy` complains about untyped functions not being checked

### ISSUE THREAD

**Issue by EnricoMi** [PyGithub/PyGithub#2628]
Running mypy (e.g. `tox -e lint`) complains:

    github/AccessToken.py:37: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]

Adding `--check-untyped-defs` to `mypy` raises a lot of errors:

    Found 112 errors in 27 files (checked 256 source files)

**Comment by EnricoMi** [comment]
@trim21 can you take a look, please?

**Comment by trim21** [comment]
> @trim21 can you take a look, please?

again, please read https://github.com/PyGithub/PyGithub/pull/2607 first, this PR fix this.

**Comment by trim21** [comment]
I ping you twice in this PR but didn't get any response. 

https://github.com/PyGithub/PyGithub/pull/2607#issuecomment-1626856727

**Comment by EnricoMi** [comment]
Please use the "request review" function of PRs, I get special notification that stands out the ordinary activity on this project:

![grafik](https://github.com/PyGithub/PyGithub/assets/44700269/3495dbec-4bd3-436d-a331-d8efca576e33)

**Comment by trim21** [comment]
> Please use the "request review" function of PRs, I get special notification that stands out the ordinary activity on this project:
> 
> ![grafik](https://user-images.githubusercontent.com/44700269/253547867-3495dbec-4bd3-436d-a331-d8efca576e33.png)

If you never reviewed a PR, I can't request your review, I can only mention you by `@...`

![image](https://github.com/PyGithub/PyGithub/assets/13553903/d3e35fa5-6eda-4313-82e1-ac3999153b59)

**Comment by trim21** [comment]
I don't have any permission in this PR, I can't request a review you never reviewed.

**Comment by trim21** [comment]
for example, A PR no one reviewed, I can request no one's review.

![image](https://github.com/PyGithub/PyGithub/assets/13553903/7360ddcb-54ac-469b-9298-473c5da98921)
