### ISSUE TITLE
progress of removing type stub

### ISSUE THREAD

**Issue by trim21** [PyGithub/PyGithub#2636]
- [ ] `github/Organization.pyi`(8.6 KiB) https://github.com/PyGithub/PyGithub/pull/2744
- [ ] `github/Repository.pyi`(27.6 KiB) https://github.com/PyGithub/PyGithub/pull/2749
- [ ] `github/StatsContributor.pyi`(853.0 B)
- [x] `github/AuthenticatedUser.pyi`
- [x] `github/Branch.pyi`
- [x] `github/CheckRun.pyi`
- [x] `github/CheckSuite.pyi`
- [x] `github/CodeScanAlert.pyi`
- [x] `github/CodeScanAlertInstance.pyi`
- [x] `github/CodeScanAlertInstanceLocation.pyi`
- [x] `github/CodeScanRule.pyi`
- [x] `github/CodeScanTool.pyi`
- [x] `github/Commit.pyi`
- [x] `github/CommitCombinedStatus.pyi`
- [x] `github/CommitComment.pyi`
- [x] `github/CommitStatus.pyi`
- [x] `github/Comparison.pyi`
- [x] `github/ContentFile.pyi`
- [x] `github/Deployment.pyi`
- [x] `github/DeploymentStatus.pyi`
- [x] `github/Download.pyi`
- [x] `github/Event.pyi`
- [x] `github/File.pyi`
- [x] `github/Gist.pyi`
- [x] `github/GistComment.pyi`
- [x] `github/GistFile.pyi`
- [x] `github/GistHistoryState.pyi`
- [x] `github/GitCommit.pyi`
- [x] `github/GitRelease.pyi`
- [x] `github/GitReleaseAsset.pyi`
- [x] `github/GithubApp.pyi`
- [x] `github/GithubIntegration.pyi`
- [x] `github/Hook.pyi`
- [x] `github/Installation.pyi`
- [x] `github/Invitation.pyi`
- [x] `github/IssueComment.pyi`
- [x] `github/IssueEvent.pyi`
- [x] `github/Label.pyi`
- [x] `github/License.pyi`
- [x] `github/MainClass.pyi`
- [x] `github/Membership.pyi`
- [x] `github/Migration.pyi`
- [x] `github/Milestone.pyi`
- [x] `github/NamedUser.pyi`
- [x] `github/Notification.pyi`
- [x] `github/Path.pyi`
- [x] `github/Permissions.pyi`
- [x] `github/Plan.pyi`
- [x] `github/Project.pyi`
- [x] `github/ProjectCard.pyi`
- [x] `github/ProjectColumn.pyi`
- [x] `github/PullRequest.pyi`
- [x] `github/PullRequestComment.pyi`
- [x] `github/PullRequestMergeStatus.pyi`
- [x] `github/PullRequestReview.pyi`
- [x] `github/Referrer.pyi`
- [x] `github/RepositoryKey.pyi`
- [x] `github/RequiredStatusChecks.pyi`
- [x] `github/SourceImport.pyi`
- [x] `github/StatsCodeFrequency.pyi`
- [x] `github/Team.pyi`
- [x] `github/TeamDiscussion.pyi`
- [x] `github/TimelineEvent.pyi`
- [x] `github/Topic.pyi`
- [x] `github/Workflow.pyi`
- [x] `github/WorkflowJob.pyi`
- [x] `github/WorkflowStep.pyi`
- [x] `github/__init__.pyi`

(https://github.com/PyGithub/PyGithub/pull/2602 is ignored)
todo=1
in_progress=2

**Comment by EnricoMi** [comment]
What does the number in brackets refer to?

**Comment by trim21** [comment]
> What does the number in brackets refer to?

size of pyi file
