### ISSUE TITLE
Git Refs and :ref

### ISSUE THREAD

**Issue by ivankravets** [PyGithub/PyGithub#268]
Let's go to API: https://developer.github.com/v3/git/refs/

> The ref in the URL must be formatted as `heads/branch`, not just `branch`. For example, the call to get the data for a branch named skunkworkz/featureA ...

Your Doc:

> `Repository.get_git_ref(ref)`
> Calls the GET /repos/:owner/:repo/git/refs/`:ref` end point.
> This is the only method calling this end point.
> Parameters:   `ref` – mandatory string
> Return type:  GitRef

Let's implement GitHub's examples:

``` python
repo = instance.get_repo(("octocat", "Hello-World")
ref = repo.get_git_ref("heads/skunkworkz/featureA")
```

**Expected**: `GitRef` Instance
**Received**: AssertionError - `assert ref.startswith("refs/")`

**Proposition**: Refactor behaviour of [get_git_ref](https://github.com/jacquev6/PyGithub/blob/develop_v2/PyGithub/Blocking/Repository.py#L1597) accordingly to GitHub API Docs (remove "requirements" of `ref/` in `:ref`).

**Comment by SumanGitHub** [comment]
Thanks .it is working fine  ..

gitref=i.get_git_ref('heads/'+str(branch.name));
