### ISSUE TITLE
Provide versioned docs in readthedocs.io

### ISSUE THREAD

**Issue by jhoffmann** [PyGithub/PyGithub#2694]
1.59 is a month old and already the 1.58 docs are gone from readthedocs.  While I understand you consider 1.59 stable, there are many distribution managed installations out there where 1.58.2 is still the latest available package.

Yes, I'm aware I could create a virtualenv and pip install a non-managed package, but that doesn't really excuse blowing away document ion that's _still relevant_.

**Comment by EnricoMi** [comment]
I agree, it is annoying that there are no versioned docs, only latest and stable. I'll keep pinging the maintainers on that one.

**Comment by EnricoMi** [comment]
I have recreated docs for version 1.57 and newer, and added a rule to add any new version.

https://readthedocs.org/projects/pygithub/
