### ISSUE TITLE
WorkflowStep.conclusion says "success" but the step has failed with exit code 1.

### ISSUE THREAD

**Issue by gs-attripathi** [PyGithub/PyGithub#2706]
Sadly, there is no way to verify if the individual step failed or not. The conclusion variable should be used for that. But that is not true. The step returned non zero exit code but still the conclusion variable says "success".

**Comment by EnricoMi** [comment]
The `conclusion` represents the result after applying `continue-on-error`, you might want to look at `outcome`: https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context

The `outcome` attribute of a workflow step is not exposed by the API: https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28#get-a-job-for-a-workflow-run

You might want to get in touch with Github support.
