### ISSUE TITLE
Point to an example of the oAuth feature.

### ISSUE THREAD

**Issue by nhomar** [PyGithub/PyGithub#271]
Hello.

Can you please point me to an example of oauth new feature on v2, I really want start to test it in our internal enviroment (making public the code) to allow us propose improvements and allow create v2 ASAP, but I could not understand the logic behind what is already done, user:password authentication is not enought for us already and we think we can help a lot in finish your amazing pythonistic implementation.

Thanks in advance.

**Comment by thegrims** [comment]
@jacquev6 Links to the example are now broken

**Comment by kbessas** [comment]
+1
