### ISSUE TITLE
Make `Branch.edit_*` return Branch objects

### ISSUE THREAD

**Issue by EnricoMi** [PyGithub/PyGithub#2735]
The API returns the `BranchProtection` object, the `Branch.edit_protection` method should return it:
https://github.com/PyGithub/PyGithub/blob/294c0cc9c5a0a5f127dd12ab2cc7ac7ca9c3e59c/github/Branch.py#L272-L277

The same holds for the other `edit_` methods in `Branch`.

**Comment by luna215** [comment]
Hi @EnricoMi, 

first of all, thanks so much for keeping this project going. Also, am I understanding this correctly that 
 `Branch.edit_protection` needs to have a return statement similar to:
```python
  return github.BranchProtection.BranchProtection(self._requester, headers, data, completed=True)
```
