### ISSUE TITLE
Add `code_search` to `RateLimit`

### ISSUE THREAD

**Issue by rappie** [PyGithub/PyGithub#2745]
There is a separate rate limit for code search:
https://docs.github.com/en/rest/rate-limit/rate-limit?apiVersion=2022-11-28

It is not in the `RateLimit` object:
```
(Pdb) gh.get_rate_limit().code_search
*** AttributeError: 'RateLimit' object has no attribute 'code_search'
```

But it is available in the data:
```
(Pdb) gh.get_rate_limit().raw_data["code_search"]
{'limit': 10, 'used': 0, 'remaining': 10, 'reset': 1693823606}
```

**Comment by EnricoMi** [comment]
Would you like to draft a PR?

**Comment by rappie** [comment]
Honestly, I'm a bit too busy for that right now :disappointed: 

I can work around this by looking in the raw data right now.

If nobody else can/wants to do it I can look into it later, but I was mostly sharing this because I figured you'd want to know :slightly_smiling_face:
