### ISSUE TITLE
README mentions close(), which doesn't exist

### ISSUE THREAD

**Issue by jelkin99** [PyGithub/PyGithub#2769]
In README.md, the "Simple Demo" illustrates using a close() method:

```
# To close connections after use
g.close()
```

Maybe that existed in the past, but it doesn't currently, so that should be removed from the README.

**Comment by EnricoMi** [comment]
You are probably looking at the README.md in master. This feature has not been released yet.

**Comment by EnricoMi** [comment]
Just released.
