### ISSUE TITLE
Incomplete API documentation on stable PyGithub

### ISSUE THREAD

**Issue by chaffees** [PyGithub/PyGithub#2782]
I'm trying to update my code with the latest PyGithub classes however documentation is missing on the new authentication methods.

jwt – string deprecated, use auth=github.Auth.AppAuth(…) or auth=github.Auth.AppAuthToken(…) instead
app_auth – github.AppAuthentication deprecated, use auth=github.Auth.AppInstallationAuth(…) instead

There isn't any documentation on:
AppAuthToken
AppInstallationAuth

**Comment by EnricoMi** [comment]
Right, docs should be here: https://pygithub.readthedocs.io/en/stable/github_objects/Auth.html

For the time being, the authentication examples might help: https://pygithub.readthedocs.io/en/stable/examples/Authentication.html

**Comment by EnricoMi** [comment]
How about https://pygithub--2783.org.readthedocs.build/en/2783/utilities.html#authentication?

**Comment by chaffees** [comment]
@EnricoMi  Thank you. I'll work with these links for now. Cheers.
