### ISSUE TITLE
Feature Request- Request to support pull request reviews

### ISSUE THREAD

**Issue by axp972** [PyGithub/PyGithub#2784]
## Request to add functionality to perform actions on pull request reviews - Feature Request
I can see there is API published by Github to be able to work with reviews for a pull request (LIST, GET, POST etc).
It would be great if that functionality can be supported within PyGithub as well.

Here is [link](https://docs.github.com/en/rest/pulls/reviews?apiVersion=2022-11-28#create-a-review-for-a-pull-request) to Github APIs.

**Comment by WatreYoung** [comment]
Maybe this class can satisfy your requirements for the actions on pull request reviews?
https://pygithub.readthedocs.io/en/stable/github_objects/PullRequest.html

**Comment by axp972** [comment]
Thank you @WatreYoung! This seems exactly what I was looking for (not sure why I didn't find it when searching for this info).
I will test it and close this issue.

**Comment by axp972** [comment]
This worked perfectly, here is sample code I used for anybody to refer.

```
    auth = Auth.Token("token_string")
    g = Github(auth=auth)
    repo = g.get_repo("org/repo")
    pr = repo.get_pull(1) #Pull request number
    pr.create_review(body="Looks Good.", event="APPROVE")
```
