### ISSUE TITLE
Variable modification results in 404 due to malformed URL

### ISSUE THREAD

**Issue by a-chaudhari** [PyGithub/PyGithub#2785]
The `url` attribute in the Variable class already has the form of `https://api.github.com/repos/OWNER/REPO/actions/variables/VAR_NAME`

However the edit and delete commands also append `/actions/variables/VAR_NAME` onto this leading to `https://api.github.com/repos/OWNER/REPO/actions/variables/VAR_NAME/actions/variables/VAR_NAME`

This causes a 404 and so the commands don't work.  Either the edit/delete commands need to no longer append this string or the self.url attribute should not include it

**Comment by EnricoMi** [comment]
Would you mind sketching a quick PR to fix this?
