### ISSUE TITLE
commit.author returns NoneType, if author is not an active GitHub username

### ISSUE THREAD

**Issue by tomibgt** [PyGithub/PyGithub#279]
The only way to find the date of the commit is to get the author or commiter and get the date from either one. For https://api.github.com/repos/jacquev6/PyGithub/git/commits/e6520adb487e49188913905af6f028ef8b7e9582 the commit.author appears to return 'NoneType' object, as Adrian Petrescu seems to be an inactive user in GitHub. 

https://github.com/jacquev6/PyGithub/commit/e6520adb487e49188913905af6f028ef8b7e9582

With an active author NamedUser like, for example, akfish, this problem doesn't occur

https://github.com/jacquev6/PyGithub/commit/ea4bd8c9ad94a2e38bc272c9f9ff8cfdccea4c03

An error in my own project (that uses PyGithub as a library), where I discovered this:

Attribute Error for sha(e6520adb487e49188913905af6f028ef8b7e9582) 'NoneType' object has no attribute 'created_at'
Traceback (most recent call last):
  File "/Users/bgt/git/GitHubResearchDataMiner/src/GitHubResearchDataMiner.py", line 19, in <module>
    connection.getCsv()
  File "/Users/bgt/git/GitHubResearchDataMiner/src/GitHubConnection.py", line 41, in getCsv
    fileh.write(self.getCsvLineFromCommit(commit)+'\n')
  File "/Users/bgt/git/GitHubResearchDataMiner/src/GitHubConnection.py", line 65, in getCsvLineFromCommit
    reva = commit.sha+";"+str(commitauthor.created_at)+";"+commitfiles+";"+commitadds+";"+commitdels+";"+commitchanges+";"+commitcommit.message
AttributeError: 'NoneType' object has no attribute 'created_at'

**Comment by jacquev6** [comment]
Please see #297.

**Comment by Nukesor** [comment]
I'll probably take a look at this, as I use this project for my BA thesis and stumble upon this issue all the time.
