### ISSUE TITLE
Organization.name gives None

### ISSUE THREAD

**Issue by jagajeet-kuppala-gilead** [PyGithub/PyGithub#2803]
**Issue:** Instances of class pygithub.Organization has value `None` for property `name`

For the code,
```py
from github import Github

gh = Github(gh_token)
gh_organization = gh.get_organization("MY_GH_ORG")

print(gh_organization.name)
```

Actual Output is,
```sh
None
```

Expected Output should be,
```sh
MY_GH_ORG
```

PyGithub version used: 1.59.0

**Comment by efinskiy** [comment]
@jagajeet-kuppala-gilead 
Organization.name appears only when you fill it in orgranization settings, until use Organization.login

**Comment by jagajeet-kuppala-gilead** [comment]
That's right @efinskiy. The `Display Name` was empty in settings page. 
Also, the `Organization.login` also worked 👍🏼 
Thanks.
