### ISSUE TITLE
Cache, load/save, rate limit, oh my.

### ISSUE THREAD

**Issue by bhyde** [PyGithub/PyGithub#282]
I don't think I'm asking for more than a discussion about how to approach the problem I'm working on ... but here goes.

I copy my issues for reporting and housekeeping purposes into a local database.   PyGithub made this easy and fun.  But then I ran up against the rate limit.  I can slow things down and spread copy work over some hours; so there's that.

I don't think it matters to what follows but I'm adding fields for things like priority, and adding a more complex set of states an issue can move thru.  Those are derived from labels on the issues.  From time to time I fetch recent events and if is issue related I regenerate it's entry in my db; so I don't need to do a full copy that often.   My db is designed so i can discard it at any time and regenerate it - at the cost of a few hours.  Imperfections mean that happens: a) I'm imperfect, and b) at least one change to an issue doesn't generate an event.

All my report generation runs without contacting github.  I have one script that contacts github which can bootstrap my db, update it, and make misc. updates that arise out of the housekeeping.

Reading #26 was interesting.

I noticed update,save and load methods, and thinking of ways to make the full copy less rate limited.

I figured the scan that does the copy could check a cache of pickles (key'd by URL), and use 'em + update to reduce the load.   So I cheerfully went off and built my cache of pickled issues.

The scan is roughly:

``` python
for github_issue in repo.get_issues(state=u'all'):
    digest(github_issue)
```

Naively I now yearn to write `repo.get_urls_of_issues(state_u'all')`

The wonder of pygithub is that I really didn't need to read the github doc at all; but I feel there may well be more to this.  For example how deep is the save/load?  Do I have to cache users, milestones, label objects too?  If so patching the restored objects looks tedious.

In more grandiose thinking ... it might be possible ... to plumb a mode into pygit that always has a cache of pickled objects and which try those+update whenever possible.  Looking at the fetching code made it clear that I shouldn't try to do that and I really ought to get back to the real work.

**Comment by jacquev6** [comment]
Please see #297.
