### ISSUE TITLE
GraphQL API for Enterprise GitHub

### ISSUE THREAD

**Issue by shicholas** [PyGithub/PyGithub#2870]
When using the GraphQL API such as for features like `enable_auto_merge`, a user should be allowed to specify the URL. AFAICT it's hardcoded https://github.com/PyGithub/PyGithub/blob/603896f44541740d72aa441ed60c698760a1393e/github/Requester.py#L543C81-L543C81

**Comment by samad-yar-khan** [comment]
@EnricoMi  I have been using PyGithub in our project for over a year. If no one is working on this, can I open a PR and try to resolve this issue ?

**Comment by EnricoMi** [comment]
@shicholas are you planning to create a PR?

**Comment by samad-yar-khan** [comment]
@EnricoMi Thanks, I will look into into it and try solving this issue.

**Comment by samad-yar-khan** [comment]
@shicholas @EnricoMi I couldn't open a PR within time as I was still navigating the cod, had some other time constraints and saw a PR already opened for the issue. Thanks for the PRs, went through them to learn a bit about the codebase.
