### ISSUE TITLE
Dependabot alert API support

### ISSUE THREAD

**Issue by coopernetes** [PyGithub/PyGithub#2872]
Hi,
We're using PyGithub to scrape a large amount of GitHub repos. It would be useful to be able to capture open vulnerability alerts from the [Dependabot alerts API](https://docs.github.com/en/rest/dependabot/alerts?apiVersion=2022-11-28#about-dependabot-alerts). I see there is support for Dependabot secrets so this would round out that feature support.

**Comment by EnricoMi** [comment]
Would you like to open a PR to add the needed features?

**Comment by coopernetes** [comment]
@EnricoMi Sure thing - give me some time to get more familiar with the code base and I'll open a PR.
