### ISSUE TITLE
Support Environment Secrets and Variables

### ISSUE THREAD

**Issue by nagibyro** [PyGithub/PyGithub#2883]
# Issue
I'd like to be able to use pygithub to create, modify and delete secrets and variables for a repo's environments.

See:
 - https://docs.github.com/en/rest/actions/variables?apiVersion=2022-11-28#create-an-environment-variable
 - https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#create-or-update-an-environment-secret

**Comment by EnricoMi** [comment]
Have you tried `Repository.get_environment(...).create_variable(...)`?

**Comment by EnricoMi** [comment]
You are right, this has not been released, yet. I should cut a release, soon.

**Comment by EnricoMi** [comment]
This has just been released as v2.2.0.
