### ISSUE TITLE
documentation link DNE

### ISSUE THREAD

**Issue by pwnetrationguru** [PyGithub/PyGithub#291]
I started looking into using PyGithub for somethings. While digging around in documentation, I found a dead link (that seems pretty important from a reference stand point).

https://github.com/jacquev6/PyGithub/blob/master/doc/introduction.rst#what-next has a ```reference of classes``` link that goes to:
https://github.com/jacquev6/PyGithub/blob/master/doc/github_objects.html

The above link returns a 404 for me. It seems like the following issue previously reported it:
https://github.com/jacquev6/PyGithub/issues/248

**Comment by jacquev6** [comment]
Please see #297.

**Comment by adamtheturtle** [comment]
Thank you @pwnetrationguru for the report. I am closing this in favour of the more recent https://github.com/PyGithub/PyGithub/issues/373 which now has more information on it.
