### ISSUE TITLE
Org Repository Pagination Only Returns First Page

### ISSUE THREAD

**Issue by squatched** [PyGithub/PyGithub#2963]
My org has hundreds of repositories, but when I call `Github().get_organization(org_slug).get_repos(sort="full_name", type="all")`, the resulting object only ever has at most 50 objects in it (`repos.totalCount` is 50 as well as the size of the resulting `get_page(0)`) and when I try and get any page other than `1`, I get an empty list returned.

I would expect this to work:
```python
repos = github.Github().get_organization("my_org").get_repos(sort="full_name", type="all")

assert repos.totalCount > 50
assert len(repos.get_page(1)) != 0
```

**Comment by hodeinavarro** [comment]
As of today with `v2.3.0`

```python
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> from github import Github
>>> github = Github(os.getenv('GITHUB_TOKEN'))
>>> repos = github.get_organization('microsoft').get_repos(sort='full_name', type='all')
>>> assert repos.totalCount > 50
>>> assert len(repos.get_page(1)) != 0
>>> repos.totalCount
6212
>>> len(repos.get_page(1))
30
```

I'm thinking it could be about the token permissions and repository visibility [as mentioned in the docs](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-organization-repositories)

> The token must have the following permission set:
>
> - metadata:read
>
> This endpoint can be used without authentication or the aforementioned permissions if only public resources are requested.

Maybe your token could list 50 public repos, but not the others? Seems too much of a coincidence, but just trying to throw some light

**Comment by hodeinavarro** [comment]
I just noticed that you don't use a token in your example, which I assumed you'd since you do not provide organization name, but I get the same result without a token.

```python
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from github import Github
>>> github = Github()
>>> repos = github.get_organization('microsoft').get_repos(sort='full_name', type='all')
>>> assert repos.totalCount > 50
>>> assert len(repos.get_page(1)) != 0
>>> repos.totalCount
6212
>>> len(repos.get_page(1))
30
```

**Comment by EnricoMi** [comment]
@squatched can you confirm pagination works with a token?
