### ISSUE TITLE
How to create a check run linked to an already existing check suite

### ISSUE THREAD

**Issue by sbrunner** [PyGithub/PyGithub#2981]
Currently, it's possible to create a check suite.
When we create a check run, a check suite is automatically created.
But I didn't find a way to create a check run related to an already existing check suite,
then it's not possible to create a check suite with more than one check run.

Did I miss something?

Method found to create check run:
https://pygithub.readthedocs.io/en/stable/github_objects/Repository.html?highlight=checksuite#github.Repository.Repository.create_check_run

Note that when I ready the REST API documentation, I see the same thing.

**Comment by EnricoMi** [comment]
This is currently not supported by Github and not planned to be implemented. Full discussion can be found here: https://github.com/orgs/community/discussions/24616
