### ISSUE TITLE
Can't access the contents of gist files

### ISSUE THREAD

**Issue by Natman64** [PyGithub/PyGithub#299]
I'm trying to access the full content of my gists' files from a Python program. I can retrieve the Gist and GistFile objects alright, but the GistFile objects are missing the `content` attribute.

Everything else seems to be working fine. Here's what I'm doing.
```
g = Github(username, password)
gists = g.get_gists()
gist = gists[0]
file = gist.files[filename]
```

And that all seems to work fine. file.type outputs at "text/plain" as expected, but there's simply no file.content attribute.

So is there something I'm doing wrong here? How do I access the content of gist files?

**Comment by jacquev6** [comment]
No `content` attribute? Weird. Is it `None` or do you get an exception?

For reference, this works:

    >>> import github
    >>> g = github.Github()
    >>> gist = g.get_gist("5339374")
    >>> gist.files
    {u'baz.txt': <github.GistFile.GistFile object at 0xffccfcac>}
    >>> gist.files["baz.txt"].content
    u'Bar -> baz'

**Comment by Natman64** [comment]
Welp, this one seemed to fix itself. The weird thing is I went to open the terminal and test your sample code myself, and found `import github` failing. (Though this is the same computer I was working on before!) After a reinstall with `easy_install` your code works fine, and my old code also works as expected. I really don't have any explanation.
