### ISSUE TITLE
Github API commit comments endpoint don't work

### ISSUE THREAD

**Issue by AutoScrape123TX** [PyGithub/PyGithub#3016]
Hello,

I try to gather a commit's comment list for analysis.
Seems GitHub API is broken. 

Example : 

[https://api.github.com/repos/vercel/next.js/commits/2aaa4263918427ee5164f12573e1dd719d365a1b](https://api.github.com/repos/vercel/next.js/commits/2aaa4263918427ee5164f12573e1dd719d365a1b)
[https://api.github.com/repos/vercel/next.js/commits/2aaa4263918427ee5164f12573e1dd719d365a1b/comments](https://api.github.com/repos/vercel/next.js/commits/2aaa4263918427ee5164f12573e1dd719d365a1b/comments)

While we see clearly there's comments on the commit present on GitHub... Check in conversation tab.

[https://github.com/vercel/next.js/pull/33240/commits/2aaa4263918427ee5164f12573e1dd719d365a1b](https://github.com/vercel/next.js/pull/33240/commits/2aaa4263918427ee5164f12573e1dd719d365a1b)

If anyone has an idea or a workaround...

**_With PyGithub it looks like :_** 

```
for commit in pull_request.get_commits():
    ....
    for commit_comment in commit.get_comments():
    ...
```

**Comment by jmreddy2106** [comment]
The below snippet may resolve your issue. Try to use specific `pull request number` and get the comments per file. If you would like to pull the all the commits, PyGitHub has to run through all the commit `sha`, instead you can target specific pull request ID.  

```
pull_request = repo.get_pull(33240)
print(f"Pull Request: #{pull_request.number} - {pull_request.title}")

review_comments = pull_request.get_comments()
    
    if review_comments.totalCount > 0:
        print("\nReview Comments:")
        for comment in review_comments:
            print(f"  - Author: {comment.user.login}")
            print(f"    Created at: {comment.created_at}")
            print(f"    File: {comment.path}")
            print(f"    Comment: {comment.body}")
            print("---")
    else:
        print("\nNo review comments on this pull request.")
```

**Comment by AutoScrape123TX** [comment]
Forgot to close this issue but this is resolved...

```
pull_request = issue.as_pull_request()
review_comments = pull_request.get_review_comments(sort="created", direction="asc")
```
