### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by tedivm** [PyGithub/PyGithub#3023]
There are some features, such as the support for `custom_properties` on enterprise repositories, that would be really useful. Can you tag a new release please?

Thanks!

**Comment by dawngerpony** [comment]
➕ to this! I'd love to see support for custom properties (implemented in #2968) made available. Much gratitude to the author of that PR and the maintainers of this project!

**Comment by EnricoMi** [comment]
I'll try to find some time over the weekend.

**Comment by EnricoMi** [comment]
Done: https://github.com/PyGithub/PyGithub/releases/tag/v2.4.0

**Comment by tedivm** [comment]
Thank you!
