### ISSUE TITLE
How could a noob start learning PyGithub?

### ISSUE THREAD

**Issue by eduOS** [PyGithub/PyGithub#304]
Hello, everyone,

Sorry to disturb you asking such a simple question.

I'm a non computer science major, but may need employ PyGithub(according to [this](http://stackoverflow.com/questions/10625190/most-suitable-python-library-for-github-api-v3)) to conduct my experiment without knowing that if PyGithub would help me capture data I need from GitHub. 
More background: I know Python, and am familiar with basic command line skills of GitHub.

I've found little tutorial or documentation straightforward and useful to me, including [this one](http://jacquev6.net/PyGithub/v1/). 

All relevant info about the aforementioned experiment is detailed [here](https://github.com/opencollaborativeclass/OpenResearch/issues/3). Anyone who would help to provide any suggestions or tips is highly appreciated. And more, should anyone show any interest in our attempt, please just let me know, I would send you a member invitation of our organization. 

Thanks for your time and attention. Millions of thanks in advance.

**Comment by Rahul91** [comment]
Do you mean noob and not nood ?

Also i am interested in this endeavour of yours. My skill set matches yours, except I have Computer Science as my majors.


All the very best :)
Cheers :+1:

**Comment by eduOS** [comment]
@Rahul91 
Thanks. Please keep in touch on this.

**Comment by mandeeps708** [comment]
I have recently started working on PyGithub. Using ipython autocompletion helps very much.

My personal reference: https://mandeep7.wordpress.com/tag/pygithub/

**Comment by eduOS** [comment]
Oh, that's great. Thanks for your warnhearted recommendation.

**Comment by mandeeps708** [comment]
Hi @eduOS 
Didn't see the date of issue. Have you used it somewhere till now? Or still it's somewhere in your subconscious todo-list.

Hope you are doing well now.

**Comment by eduOS** [comment]
Sorry. I have already kind of given up and don't know when I will resume this task. Had I closed this issue in time it would not waste your time. I'll come back to this issue later when it becomes necessary again. 

Thanks again.

**Comment by mandeeps708** [comment]
@eduOS 
No problem at all. I like to help. There is nothing to waste. If I thought of it as a waste of time, then I would not have replied here.

Thank you.
