### ISSUE TITLE
Support repository un-archive (requires GraphQL)

### ISSUE THREAD

**Issue by gaborbernat** [PyGithub/PyGithub#3052]
Seems the REST API does not support this and fails with an error. Given a repository, the following GraphQL works around the issue:

```python
def un_archive_repo(remote_repo: Repository) -> None:
    req = remote_repo._requester  # noqa: SLF001
    query = f'{{ repository(owner:"{remote_repo.owner.login}", name:"{remote_repo.name}") {{ id }}}}'
    _, data = req.graphql_query(query, variables={})
    variables = {"input": {"repositoryId": data["data"]["repository"]["id"]}}
    _, data = req.graphql_named_mutation("unarchive_repository", variables, "repository {isArchived}")
    assert not data["data"]["unarchiveRepository"]["repository"]["isArchived"]  # noqa: S101
```

We should either make `repo.edit(archive=False)` under the hood call this or add a dedicated method to achieve this.

**Comment by gaborbernat** [comment]
Huh! https://github.blog/changelog/2022-12-13-unarchive-a-repository-via-the-rest-api/ says it should be possible. I wonder if my GHE is just lagging behind this feature.

**Comment by EnricoMi** [comment]
The `archived` attribute is already supported by the `Repository` class.

**Comment by gaborbernat** [comment]
I know but does not work on GHE 3.7....

**Comment by EnricoMi** [comment]
GHE 3.7 has been deprecated beginning of this year, so upgrading is your best option.

https://docs.github.com/en/enterprise-server/admin/all-releases#releases-of-github-enterprise-server
