### ISSUE TITLE
Recording new unit tests fails for accounts with 2-factor

### ISSUE THREAD

**Issue by korfuri** [PyGithub/PyGithub#306]
Today I tried to add some unit tests and the --record option would fail as Github requires an OTP, which can't be provided via GithubCredentials.py.

I solved the issue by hacking support to tests using the token by default instead of the username/password. I'll create a pull request with my hack, but it's likely that it doesn't cover all cases cleanly, since there are some tests that explicitly test token authentication, etc.

**Comment by sfdye** [comment]
Closed in #307
