### ISSUE TITLE
Moved repositories, get new full_name instead of "not found"

### ISSUE THREAD

**Issue by oskar-j** [PyGithub/PyGithub#311]
Hey,

after getting UnknownObjectException with PyGithub, is there a way check whether repository simply changed owner / was renamed, without writing a sophisticated custom webscrapper? 

I noticed that if accesing github.com/oldowner/oldname, github simply redirects to new page github.com/newowner/propername, but I want to recognize this in a KISS way in my python programs.

Best Regards,
Oskar

**Comment by oskar-j** [comment]
I wrote a script which checks for that

https://gist.github.com/oskar-j/28673f37c1e2cb0e2acd

And as far as I know, this check is not implemented in PyGithub.

I believe we can close this issue or leave it as a feature request.

Thanks!.

**Comment by CMB** [comment]
I just had this problem and fixed it.
For me, the basic issue was that the build/ directory is used regardless
of which version of python you are building for.
My build/ directory had files for Python 2 in it.
You really need to flush it every time you do an install.
So nuke build/ and try a reinstall.
Hopefully this will fix things for you as well.

**Comment by oskar-j** [comment]
@CMB I don't understand how is this connected with redirects.

Guys, news from the GitHub Developer Progam newsletter:

>(...)Repository redirects are coming on July 21
>
>From time to time, repository names change. If you make a GitHub API request using a repository's old >name in the URL, the API has historically responded with 404 Not Found. To help API clients gracefully >handle renamed repositories, the API will soon begin redirecting to the repository's new location.
>
>In April, we made these redirects available for developers to preview. Starting July 21, 2015, the API >will automatically provide these redirects for all API consumers.

**Comment by oskar-j** [comment]
@CMB I don't understand how is this connected with redirects.

Guys, news from the GitHub Developer Progam newsletter:

>(...)Repository redirects are coming on July 21
>
>From time to time, repository names change. If you make a GitHub API request using a repository's old name in the URL, the API has historically responded with 404 Not Found. To help API clients gracefully handle renamed repositories, the API will soon begin redirecting to the repository's new location.
>
>In April, we made these redirects available for developers to preview. Starting July 21, 2015, the API will automatically provide these redirects for all API consumers.

**Comment by CMB** [comment]
Oskar Jarczyk <notifications@github.com> writes:

> @CMB I don't understand how is this connected with redirects.

I replied to the wrong issue.  Meant #314, not this one.  Sorry for the
noise.

**Comment by sfdye** [comment]
This is now implemented.
