### ISSUE TITLE
ImportError: No module named 'MainClass'

### ISSUE THREAD

**Issue by robbyki** [PyGithub/PyGithub#314]
Getting below error after installing GitHub and trying to run `from github import GitHub` on Python3.4

```
In [1]: from github import Github
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-04bd0daea4a5> in <module>()
----> 1 from github import Github

/ebs/PyGithub/github/__init__.py in <module>()
     34 import logging
     35
---> 36 from MainClass import Github
     37 from GithubException import GithubException, BadCredentialsException, UnknownObjectException, BadUserAgentException, RateLimitExceededException, BadAttributeException
     38 from InputFileContent import InputFileContent

ImportError: No module named 'MainClass'

In [2]: from GitHub import *
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-c0ff318d59b4> in <module>()
----> 1 from GitHub import *

ImportError: No module named 'GitHub'

In [3]: from github import *
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-51000bb5e3c9> in <module>()
----> 1 from github import *

/ebs/PyGithub/github/__init__.py in <module>()
     34 import logging
     35
---> 36 from MainClass import Github
     37 from GithubException import GithubException, BadCredentialsException, UnknownObjectException, BadUserAgentException, RateLimitExceededException, BadAttributeException
     38 from InputFileContent import InputFileContent

ImportError: No module named 'MainClass'
```

**Comment by mikecroucher** [comment]
I think that this is because your current working directory is `/ebs/PyGithub/github/` and so when you do the import, it is picking up the `__init__.py` for the package from there. Since this was written for Python 2, it doesn't work! In particular, the problem here is that the Python 2 code is a sibling import and Python 3 needs a relative import.

When you install to your environment using

`python setup.py install`

all of the .py files, __init__.py included, gets passed through the `2to3` script which makes them work for Python 3. Thus, Python 3 compatible versions of the module will get installed.

As such, I think your fix is to install as per the command above and make sure you are not in the source directory for the module when you do the import. I can reproduce all of this in my own Python 3.4 environment.

Hope this helps,
Mike

**Comment by TimoKramer** [comment]
Hi,
I've got the same problem with Python3.4 on Ubuntu 14.04. Is there a possibility to use this module with Python 3.4?
Thanks and regards

**Comment by CMB** [comment]
I just had this problem and fixed it.
For me, the basic issue was that the build/ directory is used regardless
of which version of python you are building for.
My build/ directory had files for Python 2 in it.
You really need to flush it every time you do an install.
So nuke build/ and try a reinstall.
Hopefully this will fix things for you as well.

**Comment by qlstudio** [comment]
So, you can just run the directory through the 2to3 script, right?

**Comment by abersh** [comment]
Hi gays I'm using django 1.6.11 python 2.7 and when python manage.py runserver i get 
this error but i install django-registration how to fix ??????
Not enabling BingMaps base layer as a BING_API_KEY is not defined in local_settings.py file.
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/geonode/venv/local/lib/python2.7/site-packages/guardian/__init__.py", line 5, in <module>
    from . import checks
  File "/home/geonode/venv/local/lib/python2.7/site-packages/guardian/checks.py", line 2, in <module>
    from django.core.checks import register, Tags, Warning
ImportError: cannot import name register

**Comment by arpit1997** [comment]
I had the same issue while contributing to this repo. Possible reason is that you are in the source directory of the the module where your both the files are conflicting with each other. So maybe you can try importing outside the repository's directory.
Hope it helps
