### ISSUE TITLE
get_dir_contents seem to build wrong file URLs

### ISSUE THREAD

**Issue by ekmartin** [PyGithub/PyGithub#317]
When trying to access the content of a file retrieved with `get_dir_contents` the resulting URL looks something like this:
https://api.github.com/repos/owner/repo/contents/requirements.txt?ref=master?client_id=clientid&client_secret=secret - i.e. with a ? instead of an & after `ref=master`, causing GitHub to think the ref includes the client id, resulting in a `No commit found for the ref master?client_id=clientid` error.

Seems like the ref is already set here: https://github.com/PyGithub/PyGithub/blob/master/github%2FRequester.py#L243

I'm using version 1.25.2.

**Comment by ekmartin** [comment]
Example:
```python
client = github.Github(login_or_token=access_token,
                                   client_id=settings.SOCIAL_AUTH_GITHUB_KEY,
                                   client_secret=settings.SOCIAL_AUTH_GITHUB_SECRET)
repo = client.get_repo(identifier)
files = repo.get_dir_contents('some_folder_name')
for github_file in files:
  print(github_file.decoded_content)
```

**Comment by era** [comment]
I think this could fix the problem https://github.com/era/PyGithub/commit/edcaffe1c6e2f9bfdbd44601846b4a1581c17ef2. But I'm not sure if it's safe to just search for the '?' in the URL.
