### ISSUE TITLE
Repository object seems to be missing 'subscribers_count'

### ISSUE THREAD

**Issue by justinclift** [PyGithub/PyGithub#318]
Just noticed the Repository object seems to be missing 'subscribers_count'.  (this is what shows up in the GitHub UI as the number of Watchers)

eg:

repo_data = gh.get_repo('sqlitebrowser/sqlitebrowser')

repo_data **should** have an integer property 'subscribers_count' containing the number of subscribers.  But it doesn't (on OSX 10.9 anyway). :frowning: 

Directly calling the API using a browser shows the property:

&nbsp; &nbsp; https://api.github.com/repos/sqlitebrowser/sqlitebrowser

It's just not getting into the Repository object.

**Comment by lipis** [comment]
:100: Yes please!

**Comment by Sylvus** [comment]
I also need this. Implementation is super easy but I guess the tests have to be updated as well.

**Comment by jzelinskie** [comment]
This was merged and will be in the next release! Thanks!

**Comment by justinclift** [comment]
Awesome, thanks @Sylvus. :smile:
