### ISSUE TITLE
Add support for repository hooks

### ISSUE THREAD

**Issue by jantman** [PyGithub/PyGithub#324]
As far as I can tell, pygithub lacks support for repository hooks (both get and POST).

**Comment by markfink** [comment]
the functionality is there and at least the create works fine:
http://pygithub.readthedocs.io/en/latest/github_objects/Hook.html#github.Hook

**Comment by sfdye** [comment]
Repository hooks is there, but lacks org hook.

**Comment by sfdye** [comment]
Closed in #729
