### ISSUE TITLE
get_stats_contributors() not iterable

### ISSUE THREAD

**Issue by Shengjiezh** [PyGithub/PyGithub#328]
Hi,

I want to create a iterable object 'contributors' for particular repo using 'get_stats_contributors()'. However, when I loop through contributors object, it always returns a 'TypeError: 'NoneType' object is not iterable' for the first contributor. When I ran a second time, first contributor is fine but second will returns the same error. So on and so forth. 
Is that normal? Is there any trick to fix this error?

Thanks a lot!

**Comment by tinecidy627** [comment]
I have the same issue. It seems the first time it won't work. But if you run again it will catch on. Not sure why.

**Comment by Shengjiezh** [comment]
Please check this thread. I hope it would help. 
http://stackoverflow.com/questions/31442518/python-need-to-request-github-api-repo-statistics-contributors-url-twice-to-get/31464160#31464160
