### ISSUE TITLE
the code doesn't work with python3

### ISSUE THREAD

**Issue by LocutusOfBorg** [PyGithub/PyGithub#331]
Hi, following up on bugs.debian.org/790655 I noticed that the code has many python3 incompatibilities
e.g.
"import httplib" is now "import http.client"
and urlparse is not inside urllib
-        o = urlparse.urlparse(base_url)
+        o = urllib.parse(base_url)

but I stopped to this problem 
```
python3 github/__init__.py 
Traceback (most recent call last):
  File "github/__init__.py", line 36, in <module>
    from MainClass import Github
  File "/tmp/pygithub-1.25.2/github/MainClass.py", line 32, in <module>
    import AuthenticatedUser
  File "/tmp/pygithub-1.25.2/github/AuthenticatedUser.py", line 30, in <module>
    import github.GithubObject
  File "/usr/lib/python3/dist-packages/github/__init__.py", line 36, in <module>
    from MainClass import Github
ImportError: cannot import name 'Github'
```

can you please update the package to a python3 version?

**Comment by jacquev6** [comment]
Just a note from the initial author : pip install PyGithub works with
python3 because 2to3 is ran during the install. I think writing code to be
compatible with python3 as-is would be a large task, but maybe 2to3 could
be used during the packaging process.

**Comment by LocutusOfBorg** [comment]
Hi, isn't is possible to run 2to3 and commit the result in the repo? isn't that compatible with python2 too?

I'm not a python coder, so I can't help too much, but Debian disallows usage of pip, and running 2to3 might be hacky :)

**Comment by jacquev6** [comment]
Once modified by 2to3, the code is definitely not compatible with python2.
I'll let the current maintainers decide what's good.

**Comment by LocutusOfBorg** [comment]
Ok I get the point.. so what about running 3to2 or 2to3 (I would prefer the former) in your setup.py script?

I think you can do something like this https://sources.debian.net/src/python-guess-language/0.5.2-3/setup.py/

after converting the code to python3 (note, I'm not a python developer so I might find really difficult giving a patch)

**Comment by LocutusOfBorg** [comment]
We found out that 2to3 wasn't run at build time due to a packaging bug :) sorry for the noise!
