### ISSUE TITLE
travis status API isn't working

### ISSUE THREAD

**Issue by jzelinskie** [PyGithub/PyGithub#338]
I think it needs to be deleted and remade because of the repo rename.

**Comment by arpit1997** [comment]
I guess travis api status is working pretty fine. I checked in [build history](https://travis-ci.org/PyGithub/PyGithub/builds) which shows that last build was on 9 days gao with commit https://github.com/PyGithub/PyGithub/commit/612befe650a16ffa54453339846d9c72b8546180
Please check again @jzelinskie and respond

**Comment by jzelinskie** [comment]
Yep, this was fixed a while ago, but this issue was never closed. Thanks.
