### ISSUE TITLE
How could I rename a file?

### ISSUE THREAD

**Issue by primalmotion** [PyGithub/PyGithub#348]
I tried a lot of things, but I can't figure out how to simply rename a file in a repo using PyGithub.

Any pointer?

**Comment by acsrujan** [comment]
I'm afraid that's not so trivial. Github API doesn't provide a way to rename a file directly. You can create new file and delete old one, but it would be of two commits.

To accomplish this in single commit, you might need to use low level git api. https://developer.github.com/v3/git/

**Comment by primalmotion** [comment]
Yeah.. I ended up deleting/recreating the file. Not very optimal but hey.. it's working

Thanks

**Comment by Jie-Yang** [comment]
Hi, 
I am looking at renaming files, just wondering whether there is any better way yet for the same problem, since it has been 3 years:)
Thanks
