### ISSUE TITLE
[Need Help] How should I close one issue given its name or id? 

### ISSUE THREAD

**Issue by OldPanda** [PyGithub/PyGithub#349]
I'm using version 1.25.2, but I didn't find a proper [API](http://jacquev6.net/PyGithub/v1/apis.html) to do this. Any advice will be appreciated.

**Comment by OldPanda** [comment]
Ah, I just figured it out. I should call this function: http://jacquev6.net/PyGithub/v1/github_objects/Issue.html#github.Issue.Issue.edit with `state="closed"`

**Comment by OldPanda** [comment]
@p00j4 On my intuition, as for the operation of pull request, you should find a method in a file named like "pullrequest.py" instead of `GithubObject.py`

**Comment by p00j4** [comment]
thanks @OldPanda, yes had checked pullrequest.py as well, and hadn't find any update, however through re scan reveals probably "edit" is the method. Will try out and keep posted. 
#Time to contribute to the documentation.

**Comment by p00j4** [comment]
yes *edit* is the function for Pull request. 
https://github.com/PyGithub/PyGithub/pull/772
