### ISSUE TITLE
Release needed

### ISSUE THREAD

**Issue by sils1297** [PyGithub/PyGithub#351]
Hi,

I'm using PyGitHub and found myself in the position of needing Commit Status Contexts desperately, eventually copying code from your development version into my prototype application. On long term it would be awesome if you could do a release :) (Given the last one was a year ago)

**Comment by jzelinskie** [comment]
Hi,
Sorry about the delay in releases. We've had a change of maintainer-ship and a few other changes with the project. I plan to get a release out sometime this week.

**Comment by sils1297** [comment]
That is super awesome! Thanks!

2015-11-03 16:09 GMT+01:00 Jimmy Zelinskie <notifications@github.com>:

**Comment by andi-bigswitch** [comment]
Cool! Same here, waiting for the status context, release would be much appreciated.

**Comment by gforcada** [comment]
Seems this is the week of people needing a status context on pygithub, I'm also waiting for it!

**Comment by adamtheturtle** [comment]
Thank you all - I am going to look into whether I can do or help with a release sometime soon (no promises / deadlines though :smile: ). For now I will close this in favour of the more recently updated duplicate https://github.com/PyGithub/PyGithub/issues/391.
