### ISSUE TITLE
Unification of PR and ISSUE objects??

### ISSUE THREAD

**Issue by babineaum** [PyGithub/PyGithub#356]
Hi we use the pygithub lib a lot, infact we have built our own tool on top of it. We did this because collecting data on PRs was getting difficult with 2 possible objects to look for information in. The PR obj contains lots of helpful info but doesn't contain the "Labels" or "comments" that aren't inline comments. These are contained in the "Issue" obj.

So my question/suggestion is would it be too much to add a sort of "super class" that would be a PR_ISSUE object that could contain a combination of the two together so that collecting multiple objects are not required? If this is just and insane idea and other people have implemented other ways to handle this we would love to hear about them. We understand that it's just a few calls to github but with our scripts we are making a lot of calls at once and hitting our max limits quickly. Any suggestions are very helpful and we would also be willing to contribute to the community as well. Thanks.

Matt Babineau 
Release Engineer
DataXu

https://github.com/dataxu/github-pr

**Comment by AraHaan** [comment]
Well it makes sence as:

> As far as the API is concerned, every pull request is an issue, but not every issue is a pull request.

here is a link to where it says [this](https://developer.github.com/v3/issues/#list-issues-for-a-repository).

**Comment by bbi-yggy** [comment]
You can also use the `as_pull_request()` method of the [issue class](https://pygithub.readthedocs.io/en/latest/github_objects/Issue.html), which lets you use the same object through either interface.
