### ISSUE TITLE
Sort direction in Repository.get_issues()

### ISSUE THREAD

**Issue by droegier** [PyGithub/PyGithub#362]
Hi,

I have a problem that I can't really figure out. This is all new for me and I am posting for the first time ever on GitHub. If this is not the right place for my question: apologies. 

My goal is to get all Issues from a project starting with the oldest one.

When calling the function get_issues() on a Repository, I set the 'direction' parameter to the two possible values "asc" and "desc". However this doesn't change anything in the eventual order. Do you know on which property the sort takes place (creation date?). I understand this relates more to the GitHub api then the PyGithub library, but I wasn't able to find an answer, so I thought I just try here.

Another approach would maybe be to get the final page and call 'reverse' provided by the Pagination class? Or did I get that wrong.

Thanks for the help in advance.

**Comment by bweir** [comment]
Why not just iterate over the Pagination class backwards?
http://effbot.org/pyfaq/how-do-i-iterate-over-a-sequence-in-reverse-order.htm

On Tue, Dec 8, 2015 at 10:19 AM, droegier <notifications@github.com> wrote:

> Hi,
>
> I have a problem that I can't really figure out. This is all new for me
> and I am posting for the first time ever on GitHub. If this is not the
> right place for my question: apologies.
>
> My goal is to get all Issues from a project starting with the oldest one.
>
> When calling the function get_issues() on a Repository, I set the
> 'direction' parameter to the two possible values "asc" and "desc". However
> this doesn't change anything in the eventual order. Do you know on which
> property the sort takes place (creation date?). I understand this relates
> more to the GitHub api then the PyGithub library, but I wasn't able to find
> an answer, so I thought I just try here.
>
> Another approach would maybe be to get the final page and call 'reverse'
> provided by the Pagination class? Or did I get that wrong.
>
> Thanks for the help in advance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyGithub/PyGithub/issues/362>.
>



-- 
*Brett Weir*, Founder


Engineering Made Awesome
310.245.1775  • brett@lamestation.com • lamestation.com

**Comment by bbi-yggy** [comment]
The `search_issues` method supports `sort` and `order` parameters, perhaps that would meet your needs?
