### ISSUE TITLE
How can I check a valid account?

### ISSUE THREAD

**Issue by mxui** [PyGithub/PyGithub#366]
Hi,

I am writing a script to unfollow all of followings and stars and I used the basic authentication like the example in the introduction.
```
from github import Github

g = Github("user", "password")
for repo in g.get_user().get_repos():
    print repo.name
    repo.edit(has_wiki=False)
```
But when I enter an incorrect password, I can also get a GitHub instance and a user.
Is there a method that validates the user? 

Thank you!

**Comment by sparkline-charlie** [comment]
I think based you will encounter an error if the username and password is invalid.
I don't know if this is a correct approach. But this may help.
def validate_login():
    try:
        g = Github(username, password)
        data = [(s.name, s.name) for s in g.get_user().get_repos()]
        return True
    except:
        return flask.render_template('login_error.html', html_class='welcome')

**Comment by mxui** [comment]
@sparkline-charlie Thank you for your solution.

I hava solve the problem without using PyGithub.

 I am inspired by the example in requests [README](https://github.com/kennethreitz/requests)
```
>>> r = requests.get('https://api.github.com', auth=('user', 'pass'))
>>> r.status_code
204
>>> r.headers['content-type']
'application/json'
>>> r.text
```

So I can verify GitHub accounts using the returned **status_code**.Requests is awesome!

**Comment by sparkline-charlie** [comment]
Yes you can use either of the two methods.
