### ISSUE TITLE
Repository.watchers_count and Repository.stargazers_count are always the same

### ISSUE THREAD

**Issue by lipis** [PyGithub/PyGithub#367]
.. and obviously wrong! The right number for the watchers should be the `subscribers_count`.

Related #318

**Comment by Sylvus** [comment]
This is not wrong but the way the API works. Check our https://api.github.com/repos/Lasagne/Lasagne for example. Watchers are stargazers and it is there for compatibility.  Further reading https://developer.github.com/changes/2012-09-05-watcher-api/

**Comment by lipis** [comment]
I see.. thanks :)

**Comment by tik9** [comment]
What is the watch number in the api? 
![image](https://user-images.githubusercontent.com/3178925/101276691-ee7def80-37ae-11eb-8564-98417223fed3.png)

**Comment by nokome** [comment]
> What is the watch number in the api? 

`subscribers_count`
