### ISSUE TITLE
Links don't work in introduction.rst

### ISSUE THREAD

**Issue by BGR360** [PyGithub/PyGithub#373]
In the documentation section, the [introduction.rst file](doc/introduction.rst) has links to pages which say "Which class implements which API feature?" They redirect to a 404 error page.

**Comment by qlstudio** [comment]
The entire "https://github.com/PyGithub/PyGithub/issues/doc/introduction.rst" site redirects to a 404 error

**Comment by adamtheturtle** [comment]
Thank you for this report.

@qlstudio This is unfortunately just @BGR360 's markup not working, I am fairly sure that https://github.com/PyGithub/PyGithub/blob/master/doc/introduction.rst is the intended link.

Note that this is rendered at http://pygithub.readthedocs.org/en/latest/introduction.html. I believe that http://pygithub.readthedocs.org/en/latest/apis.html is the page which should be linked to and I will create a Pull Request for this when I have some time.

This also makes me think that perhaps some other links are broken. Sphinx has a link checker which can be set up to run as part of the CI system. See http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.linkcheck.CheckExternalLinksBuilder.
