### ISSUE TITLE
UnknownObjectException

### ISSUE THREAD

**Issue by jfach** [PyGithub/PyGithub#385]
I am trying to make an object out of a repository as follows: 

``` python
g = Github(username, password)
g.get_user().get_repo("testrepo")
```

This returns the following error:

``` python
github.GithubException.UnknownObjectException: 404 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Not Found'}
```

Am I using get_repo incorrectly?

**Comment by jacquev6** [comment]
This looks correct and you do have a repo named "testrepo" so my only hypothesis is that username and/or password are wrong. (Maybe you're testing your "isebot"?)

Can you please ``print(g.get_user().name)``?
