### ISSUE TITLE
Is there a better way of listing my own repos?

### ISSUE THREAD

**Issue by pelson** [PyGithub/PyGithub#390]
The github API supports an affiliations parameter when requesting repos, but that doesn't seem to be part of the pygithub API.

I therefore copied the contents of AuthenticatedUser, and added the capability:

```
def my_repos(gh_user):
    import github
    return github.PaginatedList.PaginatedList(
                github.Repository.Repository,
                gh_user._requester,
                gh_user.url + "/repos",
                dict(affiliation="owner"))
```

Is there a better way?

Thanks!

**Comment by adamtheturtle** [comment]
Hi @pelson, and thank you for your question. Please bear with me as I am new to
this project.

In experimenting with this, I have found that the following works, at least for
my account. Please let me know if this is or is not suitable.

```python
import github

from github import Github

g = Github(token)

gh_user = g.get_user()

pelson_example = github.PaginatedList.PaginatedList(
            github.Repository.Repository,
            gh_user._requester,
            gh_user.url + "/repos",
            dict(affiliation="owner"))
pelson_repos = [repo for repo in pelson_example]

adamtheturtle_repos = [
    repo for repo in gh_user.get_repos() if
    repo.owner.login == gh_user.login
]

assert pelson_repos == adamtheturtle_repos
```

Adam

**Comment by pelson** [comment]
Thanks @adamtheturtle. I guess the question was more about the fact that [the ``get_repos`` method](https://github.com/PyGithub/PyGithub/blob/master/github/AuthenticatedUser.py#L849-872) doesn't expose all of the options that the GitHub API does (namely affiliations). If we don't pass that parameter through, then inevitably the GitHub API is going to return more repositories than it needs to, and we are going to have to filter them on client side.

I really like your solution of using a list comprehension. @nhomar in general if the API is missing parameters, should I just add a PR to add them?
