### ISSUE TITLE
Release needed

### ISSUE THREAD

**Issue by lost-a-tooth** [PyGithub/PyGithub#391]
It would be great if we can do a release.  I need the code for combined CommitStatus and get pull requests with head branch.

Thanks!

**Comment by khornberg** [comment]
:+1:

**Comment by nhomar** [comment]
I will try to make a release for end of March.

**Comment by ashwin31** [comment]
:+1:

**Comment by nibalizer** [comment]
:-1:

**Comment by SegFaultAX** [comment]
@nhomar @jacquev6 @jzelinskie @adamtheturtle Any chance we'll see a release of PyGithub this month?

**Comment by jakirkham** [comment]
Also would love to see a release. 😄

**Comment by jakirkham** [comment]
Should add I need the merged PR ( https://github.com/PyGithub/PyGithub/pull/379 ) in there if at all possible.

**Comment by AraHaan** [comment]
It would be nice if it was simple to get all open / closed Issues (including PR's) and to somehow have a event for if and when a new issue/ PR is open for a timely response. Why? Because I want my Discord Bot to utilize it making it also look cool at the same time.

So, yeah that is what I would like in a nutshell.

**Comment by jayfk** [comment]
Maybe we could switch to a release process based on git tags and let travis issue new releases.

There's a pretty straightforward recipe here: https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/travis_pypi_setup.py

@jzelinskie, @jacquev6 I'd be happy to set that up with you. It's basically just encrypting the PyPi password and adding the publik key to travis.

**Comment by SegFaultAX** [comment]
This project hasn't seen a release on [PyPI since 2015-11-06](https://pypi.python.org/pypi/PyGithub). Is the core team for this project looking for additional maintainers? I'd happily commit time to help keep things rolling along smoothly (and it sounds like a few other community members would as well).

**Comment by nikogura** [comment]
👍   What can we do to help get a release cut?  Personally, I'd like to see repo.update_file() available from PyPI

**Comment by jzelinskie** [comment]
@jayfk what prevents someone from posting a PR that changes the .travis.yml to ship off the decrypted pypi credentials to wherever they want? If this system is robust against that attack, I'm totally fine with it.

**Comment by jayfk** [comment]
@jzelinskie the commit has to be tagged to start the deploy process:

```
deploy:
  ...
  on:
    tags: true
```
 Tags can only be pushed by owners/members of the repository which makes the group of attackers relatively small, but nevertheless it would be possible for someone from this group to extract your password this way (but not silently, unless they have access to the travis environment).

To make the attack vector even smaller, you could create a new pypi account and run the process with the credentials of the new user.

For more info, see

- https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables
- https://github.com/audreyr/cookiecutter-pypackage/blob/master/docs/travis_pypi_setup.rst

**Comment by jzelinskie** [comment]
@jayfk I'm totally for this. Email me, and I'll send you the credentials for a pypi account with maintainer that I just created. That cookiecutter template looks great and removing some of the needless scripts lying around like our twitter script would be nice.

**Comment by SegFaultAX** [comment]
Fantastic, thanks for working on this everyone!

**Comment by jayfk** [comment]
I'm happy to announce that PyGithub `1.27.1` is out :)

**Comment by AraHaan** [comment]
About time. >.>
