### ISSUE TITLE
Add support for adding/updating organization membership

### ISSUE THREAD

**Issue by sidewinder12s** [PyGithub/PyGithub#399]
Add support for this endpoint. 

https://developer.github.com/v3/orgs/members/#add-or-update-organization-membership

**Comment by ckmason** [comment]
I'd really like to see this in PyGithub too...

**Comment by alertedsnake** [comment]
So.. this seems to work fine, can we get it merged in?  It's been months...

**Comment by moghya** [comment]
how to invite someone with just email id using PyGithub ?

**Comment by tjboring** [comment]
Hmm, what's the status of this issue? I see the following PRs that appear to address it:

- https://github.com/PyGithub/PyGithub/pull/424
- https://github.com/PyGithub/PyGithub/pull/726

Neither of the above have unittests.

But these 2 commits referenced above add the tests:
- https://github.com/jbweston/PyGithub/commit/c1ce18a24632e8d4b0752b19ab3fec9806e54593
- https://github.com/jwplayer/PyGithub/commit/3fb0e82d71bb112f3d4632e6b5883fd98d680866

**Comment by sfdye** [comment]
@tjboring You are right. Would you like to glue the pieces together so we can merge this change?

**Comment by tjboring** [comment]
@sfdye Sure. Let me figure out the best way to proceed. I'll update this thread with the steps once I figure it out.

**Comment by tjboring** [comment]
I'm open to other suggestions, but what I've come up with is this:

- create a new fork
- copy/paste the changes from PRs 424 and 726
- write tests and get them to pass
- create new PR

**Comment by tjboring** [comment]
@sfdye I'm getting a 404 trying to create the replay data:

```
$ python -m github.tests Organization.testAddMembers --record --auth_with_token
GET /orgs/BeaverSoftware None {'Authorization': 'token XXXXXX', 'User-Agent': 'PyGithub/Python'} => 404
```

**Comment by sfdye** [comment]
@tjboring As I mentioned in another thread, the `BeaverSoftware` organization does not seem to exist anymore. 

Maybe you can open a PR to merge the commits first and I will take a look?

**Comment by tjboring** [comment]
I figured out a workaround. PR forthcoming.

**Comment by tjboring** [comment]
@sfdye https://github.com/PyGithub/PyGithub/pull/741

**Comment by sfdye** [comment]
I will make a release today.
