### ISSUE TITLE
Please don't ask people to send me email

### ISSUE THREAD

**Issue by jacquev6** [PyGithub/PyGithub#401]
Hello,

in the readme, you're asking people to send me an e-mail if they want to contribute. I'm afraid I'm doing a terrible job at replying their messages, so you should handle this without involving me.

@jzelinskie you're now an admin of the org so that you can add people and make them admins as well if appropriate. Please let me know in this issue if you need me to do anything else.

Thanks,

**Comment by jzelinskie** [comment]
I've updated a few of the project files and removed this section of the README.

**Comment by jacquev6** [comment]
Thanks!
