### ISSUE TITLE
N_TOKENS is not defined

### ISSUE THREAD

**Issue by jfach** [PyGithub/PyGithub#402]
When calling `help()` on anything within the repo, for example `help(github)`, I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.6/site.py", line 432, in __call__
    import pydoc
  File "/usr/lib64/python2.6/pydoc.py", line 52, in <module>
    import sys, imp, os, re, types, inspect, __builtin__, pkgutil
  File "/usr/lib64/python2.6/inspect.py", line 39, in <module>
    import tokenize
  File "/usr/lib64/python2.6/tokenize.py", line 38, in <module>
    COMMENT = N_TOKENS
NameError: name 'N_TOKENS' is not defined
```

**Comment by jepler** [comment]
The module where the problem occurs, `tokenize`, is a built-in module in Python 2.6.

Does this problem occur if you execute `python2.6 -c 'import tokenize'`?  If so, it could indicate a damaged Python installation.

`N_TOKENS` is expected to be imported into tokenize by `from tokens import *`.  A file `tokens.py` in PYTHONPATH that is not the system `tokens.py` could cause this problem.  `python -c 'from tokens import *; print N_TOKENS` could test this specifically, and `python -c 'import tokens; print tokens.__file__'` will show you if tokens.py is coming from an unexpected location.

**Comment by neoranger** [comment]
I have this problem. What is the solution?

Cheers.
