### ISSUE TITLE
Check if PaginatedList isEmpty

### ISSUE THREAD

**Issue by joshfrazier-navera** [PyGithub/PyGithub#406]
How would I go about verifying if a PaginatedList is empty, or returned nothing from my repo? I have tried the usual python mechanisms for checking if a list is empty like: if not <listObject>: and so on, but they do not seem to work on the PaginatedList. The tool I am building grabs the latest pull request and commit information from a given repo. If there are no open pull requests, I would like to do something other than throwing a list index out of range exception every time.

**Comment by jloh** [comment]
Did you ever manage to figure this out? I'm running into this issue at the moment.

**Comment by davidxia** [comment]
@joshfrazier-navera You can simply iterate through and break out of the loop after the first iteration.

```python
for  pull in pulls:
    # do stuff
    break
```
