### ISSUE TITLE
Using Registered App?

### ISSUE THREAD

**Issue by mandeeps708** [PyGithub/PyGithub#410]
I was using PyGithub for a while now. Lately, I was using Personal
Access tokens for doing authentication.

Now I want to use it as a registered application. Can you provide a
hint of how to do this? I used the Client ID in place of token but it
didn't work out.

I am working on an application that is in command-line interface currently.

**Comment by arpit1997** [comment]
As much as i understand you want to distribute your application to other users. If so then you can use Github OAuth for this purpose. You can generate a link from your application which will redirects user to authorise your application for his account. Once you have recieved OAuth token yuo can exchange it with access otken from Github api or this python wrapper (PyGithub). 
Note: you must create a new application for your Github API key and secret.
For more details you can refer to [this](http://developer.github.com)

**Comment by mandeeps708** [comment]
Hello @arpit1997 
Thanks for replying.

What if I am working on a CLI application?

**Comment by arpit1997** [comment]
@mandeeps708 
whether you are working on a CLI application on GUI application the back-end of your application won't change. You can use some library like [Python-requests](https://github.com/kennethreitz/requests) or Curl if you are a linux user for your api requests and authorization.. You can view some python requests example and Github api [example](http://developer.github.com). I would like to help you need any further help.

**Comment by mandeeps708** [comment]
Thanks @arpit1997 

You mean to say I can have give user a link in the command-line that he would open in the browser and authorize the application?

Then how the auth token will get there in my application?

**Comment by arpit1997** [comment]
there are two ways that you can use for your application to authorise the use

- first is basic authentication: this way every time user has to enter his password or you can cache the passwords here is an example.
`curl -u username https://api.github.com/user`
this will prompt you for password corresponding to that user. when password is correct you can access the user account from your application

- another way is a two factor authentication which is OAuth. Even though it is cumbersome and lengthy it is a very good choice for security reason and user's trust on your application. Since OAuth is a big procedure you can read it by yourself [here on github](https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization)

**Comment by mandeeps708** [comment]
I meant I tried following the docs a few time back and I think I couldn't find a way to have OAuth working through CLI application.

Maybe you can give me some overview of how it will work?

Anyways, thank you.

**Comment by arpit1997** [comment]
Here are some examples, I suppose these can help you out from your problem
you need to create an OAuth token using [Github API OAuth](http://developer.github.com/v3/oauth/#oauth-authorizations-api) once per user then you can store it with some mechanism
`curl https://api.github.com/authorizations \
--user "caspyin" \
--data '{"scopes":["gist"],"note":"Demo"}'`
You can change the data parameter depending upon which user data you want to access.
The above will prompt user for his account password, after entering the password a JSON response is returned containing a token field. Now that you have the OAuth token yuo can use it to access user data like this
`curl -H "Authorization: token OAUTH-TOKEN" https://api.github.com/gists/starred`
replace OAUTH-TOKEN field with the token that you recieved in json response. 
you can also list out authorisations that you have for a user
`curl --user "USERNAME" https://api.github.com/authorizations`
in this example this should return that you have access to user's gists

**Comment by xor2003** [comment]
The below works for me:
import requests, jwt, github3, cryptography, time
import config

def get_github3_client():
    """See
    
           https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app
    
       for an explanation of how/why this is like it is.
       
       Requires: requests pyjwt github3 cryptography"""

    payload = {
        # issued at time
        'iat': int(time.time()),
        # JWT expiration time (10 minute maximum)
        'exp': int(time.time() + (10 * 60)),
        # GitHub App's identifier
        'iss': str(config.GITHUB_ID)
    }
    
    url = "https://github.com/api/v3/app"
    jwt_payload = jwt.encode(payload, config.GITHUB_PRIVATE_KEY, algorithm="RS256").decode("utf-8") 
    #print (jwt_payload)
    headers = {"Authorization": "Bearer {jwt}".format(jwt=jwt_payload),
               "Accept": "application/vnd.github.machine-man-preview+json"}

    # Requests "helpfully" clobbers Authentication headers if you don't use your own
    # authentication method. Thanks, requests.
    class CustomJWTAuth(requests.auth.AuthBase):
        def __call__(self, r):
            r.headers['Authorization'] = headers['Authorization']
            return r
    #print(url)
    #print(headers)
    response = requests.get(url, headers=headers, auth=CustomJWTAuth())
    response.raise_for_status()

    installations_url = "https://github.com/api/v3/app/installations"
    installations_response = requests.get(installations_url, headers=headers, auth=CustomJWTAuth())
    installations_response.raise_for_status()

    for item in installations_response.json():
        installation_id = item['id']
        #print (installation_id)
        access_tokens_url = "https://github.com/api/v3/app/installations/{installation_id}/access_tokens".format(
            installation_id=installation_id)
        access_tokens_response = requests.post(access_tokens_url, headers=headers, auth=CustomJWTAuth())
        access_tokens_response.raise_for_status()
        #print (access_tokens_response.json())


        token = access_tokens_response.json()['token']
        #print (token)
        #return github3.login(token=token)
        return token

    raise Exception("No app installations")

**Comment by jonashartwig** [comment]
Here is an updated version of the above provided python script:

```python
def get_token_from_application(app_id: str, app_private_key: str) -> str:
    """
    See
    https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app
    for an explanation of how/why this is like it is.
    Requires: requests pyjwt github3 cryptography
    """

    payload = {
        # issued at time
        'iat': int(time.time()),
        # JWT expiration time (10 minute maximum)
        'exp': int(time.time() + (10 * 60)),
        # GitHub App's identifier
        'iss': str(app_id)
    }

    url = "https://api.github.com/app"
    jwt_payload = jwt.encode(payload, app_private_key, algorithm="RS256")
    # print (jwt_payload)
    headers = {"Authorization": "Bearer {jwt}".format(jwt=jwt_payload),
               "Accept": "application/vnd.github.machine-man-preview+json"}

    # Requests "helpfully" clobbers Authentication headers if you don't use your own
    # authentication method. Thanks, requests.
    class CustomJWTAuth(requests.auth.AuthBase):
        def __call__(self, r):
            r.headers['Authorization'] = headers['Authorization']
            return r

    response = requests.get(url, headers=headers, auth=CustomJWTAuth())
    response.raise_for_status()

    installations_url = "https://api.github.com/app/installations"
    installations_response = requests.get(installations_url, headers=headers, auth=CustomJWTAuth())
    installations_response.raise_for_status()

    print(installations_response.json())

    for item in installations_response.json():
        access_tokens_url = item["access_tokens_url"]
        access_tokens_response = requests.post(access_tokens_url, headers=headers, auth=CustomJWTAuth())
        access_tokens_response.raise_for_status()

        token = access_tokens_response.json()['token']

        return token

    raise Exception("No app installations")
```
