### ISSUE TITLE
Example using OAUTH Access Token with Enterprise Installation

### ISSUE THREAD

**Issue by lnunno** [PyGithub/PyGithub#411]
I have had no success getting PyGithub to work with an Enterprise installation and am having difficulty debugging the issue. I have tried the example in the introduction. For example:

``` python
from github import Github
access_token = 'BLAH'
gh = Github(access_token, base_url='https://myorg.github.com/api/v3')
gh.get_user().name
```

And then I get:

```
/home/llnunno/.local/lib/python2.7/site-packages/github/GithubObject.pyc in _storeAndUseAttributes(self, headers, attributes)
     84         self._headers = headers
     85         self._rawData = attributes
---> 86         self._useAttributes(attributes)
     87 
     88     @property

/home/llnunno/.local/lib/python2.7/site-packages/github/AuthenticatedUser.pyc in _useAttributes(self, attributes)
   1085 
   1086     def _useAttributes(self, attributes):
-> 1087         if "avatar_url" in attributes:  # pragma no branch
   1088             self._avatar_url = self._makeStringAttribute(attributes["avatar_url"])
   1089         if "bio" in attributes:  # pragma no branch

TypeError: argument of type 'NoneType' is not iterable
```

Do I need additional information in the `Github` constructor? There is no documentation for any of the constructor arguments.

Where the access token is generated via Account Settings -> Applications -> Personal access tokens. I know the access token is valid because I can send requests to the API manually and get responses.

**Comment by jzelinskie** [comment]
What version of Python and GH Enterprise?

**Comment by lnunno** [comment]
Python version 2.7.5
Github Enterprise 11.10.353

**Comment by psalaberria002** [comment]
@lnunno Try the folowing. It works for me.

```
gh = Github(username, access_token, base_url='https://myorg.github.com/api/v3')
```

**Comment by sfdye** [comment]
Added in de6c2ec4e2b939cdc24da9802cfab2704d32ad80
