### ISSUE TITLE
Docstrings problem

### ISSUE THREAD

**Issue by RSully** [PyGithub/PyGithub#427]
I'm using PyCharm for my development environment. I noticed that your code is rather well documented using docstrings. For example:

``` python
    def get_user(self, login=github.GithubObject.NotSet):
        """
        :calls: `GET /users/:user <http://developer.github.com/v3/users>`_ or `GET /user <http://developer.github.com/v3/users>`_
        :param login: string
        :rtype: :class:`github.NamedUser.NamedUser`
        """
```

However, this seems to not be the appropriate syntax, as my IDE still thinks the result could be Any. However, if I remove the `:class:`, it works properly. Could you send me any links that point to the `:class:` standard? I am going off of [this](https://www.jetbrains.com/help/pycharm/2016.1/type-hinting-in-pycharm.html#legacy).

**Comment by RSully** [comment]
Same again.

**Comment by RSully** [comment]
:(

**Comment by RSully** [comment]
.

**Comment by RSully** [comment]
cool

**Comment by RSully** [comment]
.

**Comment by s-t-e-v-e-n-k** [comment]
It's hinting for our docs build -- see https://pygithub.readthedocs.io/en/latest/github_objects/Branch.html#github.Branch.Branch.get_required_status_checks, without the :class: it doesn't link the return type to the class.

**Comment by RSully** [comment]
Is it possible that during the 3 years since this issue was filed that the syntax has changed? More-so, I was more interested in finding a link to the documentation that shows it is necessary (not a link to where your docs show it in us), as - at least 3 years ago - this syntax broke PyCharm. I imagine it must be standardized by now. 

PS: I must say I am quite surprised to see any activity on this, me and stale bot have become quite good friends in the meantime 😊

**Comment by s-t-e-v-e-n-k** [comment]
It's possible the syntax has changed, but I can't find any documentation for Sphinx about it, and it works, so I'm loathe to change it. Also, it pre-dates my involvement in the project, so that goes double.

**Comment by RSully** [comment]
Do as you wish, but I'd encourage you to use a syntax that IDEs use to make things easier for contributors. I'm not sure if PyCharm supports this syntax or not, but at the time it definitely did not.

**Comment by RSully** [comment]
wheee

**Comment by Croydon** [comment]
Hi! This is my generic reply for every issue which is still relevant and is on the edge of getting closed by a stale bot.

**Comment by RSully** [comment]
.

**Comment by RSully** [comment]
Why don't other issues get marked as stale?

**Comment by s-t-e-v-e-n-k** [comment]
Ah ha, I found the documentation. https://www.sphinx-doc.org/en/1.5/domains.html#python-roles

Have you considered filing a bug against PyCharm for this?

**Comment by RSully** [comment]
From what I can tell, the `:class:` syntax is to create a link to a class within Sphinx documentation, not to actually designate a return type in `:rtype:`.

For example, I would expect this is how it would be used (not tested):

```
:rtype: github.NamedUser.NamedUser The rest of this text is describing the return type and may contain links to other classes like :class:`github.CommitStatus.CommitStatus` which would show up in the Sphinx documentation.
```

**Comment by RSully** [comment]
Bad bot.

**Comment by Croydon** [comment]
Hi! This is my generic reply for every issue which is still relevant and is on the edge of getting closed by a stale bot.

**Comment by RSully** [comment]
This is my default response to stale bot for issues that are not resolved.

**Comment by RSully** [comment]
...
