### ISSUE TITLE
Two-Factor Authentication should be available for all commands

### ISSUE THREAD

**Issue by blast-hardcheese** [PyGithub/PyGithub#429]
The current implementation of 2FA is to generate an authorization token and use that for subsequent commands. Unfortunately, this is incompatible with the authorizations API itself:

```
    github = Github(args.username, args.password)
    user = github.get_user()

    try:
        otp_auth = user.create_authorization(scopes=['user'], note='otp_auth')
    except GithubException as e:
        # Unable to import TwoFactorAuthentication for some reason. Just assume anything
        # that goes wrong is due to 2fa.
        otp_key = raw_input("Enter github Two-Factor Auth key: ")
        otp_auth = user.create_authorization(scopes=['user'], note='otp_auth', onetime_password=otp_key)

    github = Github(otp_auth.token)
    for authorization in github.get_user().get_authorizations():
        authorization.delete()
```

results in

```
github.GithubException.GithubException: 403 {
    u'documentation_url': u'https://developer.github.com/enterprise/2.6/v3/oauth_authorizations/#oauth-authorizations-api',
    u'message': u'This API can only be accessed with username and password Basic Auth'
}
```

I see two options:
- Adding a top-level `otp_key` parameter that gets passed down into the `Requester`
  - This would be easy to implement, but the github object would have to be reinitialized frequently as OTP keys changed
- Permitting all API methods to specify their own `otp_key`, which gets added to `requestHeaders`
  - This would be frustrating, but would ensure that there are no API calls that can't be used via this API.

**Comment by dadokkio** [comment]
There is any update on this issue? I tried to use TwoFactorAuthentication and pratically it works only the first time. As soon I try to get old authorization or delete the actual one it fails:

`
github.GithubException.TwoFactorException: 401 {u'documentation_url': u'https://developer.github.com/v3/auth#working-with-two-factor-authentication', u'message': u'Must specify two-factor authentication OTP code.'}
`

And I need to delete actual token from my github setting page.

**Comment by sfdye** [comment]
@blast-hardcheese Good point. I am closing this for now.
