### ISSUE TITLE
Add support for multiple assignees

### ISSUE THREAD

**Issue by erelson** [PyGithub/PyGithub#439]
Is officially part of the API as per:
https://developer.github.com/changes/2016-07-12-ending-multiple-assignees-preview-period/

Also possibly deprecate the assignee keyword for issue creation. Item 25 here: https://developer.github.com/v3/versions/#v3-deprecations

**Comment by cheungpat** [comment]
This seems to be a duplicate of #404

**Comment by erelson** [comment]
Indeed. My quick check for a similar topic was too quick. :+1:
