### ISSUE TITLE
Add a link to the documentation?

### ISSUE THREAD

**Issue by jacebrowning** [PyGithub/PyGithub#440]
I found the documentation here (http://pygithub.readthedocs.io/), but I didn't see a link to there from GitHub. Perhaps this could be added to the README or set as the project's website on GitHub?

**Comment by gtalarico** [comment]
Thank you for posting this @jacebrowning 
For a moment I thought there was no documentation.
I actually came here to propose we start one

**Comment by zhangoose** [comment]
Hmm, it's not that easily noticeable but it's a badge on the README

![image](https://cloud.githubusercontent.com/assets/2905198/20821061/9f329586-b80d-11e6-8af1-70facfbf00b7.png)


Maybe it should be more obvious?

**Comment by gtalarico** [comment]
Wouldn't hurt!

**Comment by jacebrowning** [comment]
Or just make it the repository's website:

![screen shot 2016-12-01 at 9 41 01 pm](https://cloud.githubusercontent.com/assets/939501/20821232/e976d9b2-b80e-11e6-8e72-10e6c6ed7f34.png)

**Comment by jzelinskie** [comment]
Closed by #499
