### ISSUE TITLE
Set permissions when adding a repository to a team

### ISSUE THREAD

**Issue by fvanboven** [PyGithub/PyGithub#441]
Currently it is not possible to specify, set or update the permissions of a team for a repository. The team's default permissions are used:

This is possible in the GitHub API:
https://developer.github.com/v3/orgs/teams/#parameters-3

Idea to add this to: https://github.com/PyGithub/PyGithub/blob/master/github/Team.py#L137
?

**Comment by NegatioN** [comment]
This is very useful for us as well. I would like to migrate all repos of our organization while giving certain teams admin-permissions. Doing this manually for hundreds of repos is not desirable.

**Comment by gunkl** [comment]
this appears to be fixed in 1.35, it doesn't seem documented, but set_repo_permission is in the code. tested and works.

`    def set_repo_permission(self, repo, permission):
        """
        :calls: `PUT /teams/:id/repos/:org/:repo <http://developer.github.com/v3/orgs/teams>`_
        :param repo: :class:`github.Repository.Repository`
        :param permission: string
        :rtype: None
        """
        assert isinstance(repo, github.Repository.Repository), repo
        put_parameters = {
            "permission": permission,
        }
        headers, data = self._requester.requestJsonAndCheck(
            "PUT",
            self.url + "/repos/" + repo._identity,
            input=put_parameters
        )`

**Comment by sfdye** [comment]
It's in the docs now: http://pygithub.readthedocs.io/en/latest/github_objects/Team.html#github.Team.Team.set_repo_permission

**Comment by daniel-torresc** [comment]
This should work:

`g.get_organization(org-name).get_team(team-id).set_repo_permission(
        g.get_organization(org-name").create_repo(repo-name),
        "admin")`

It is deprecated, but still works.
