### ISSUE TITLE
Follow PEP8

### ISSUE THREAD

**Issue by mingrammer** [PyGithub/PyGithub#446]
Some codes (variables, methods) don't follow PEP8.

Why the codes don't follow PEP8?

**Comment by arpit1997** [comment]
I ran some inspections and found some PEP8 code style violation like: 

- Function name should be lowercase 

- variable in function name should be lowercase

- CamelCase variable imported as constant

while we ignore line length limit for all files

**Comment by mingrammer** [comment]
Yes those are

Are you contributor of here? @arpit1997

**Comment by arpit1997** [comment]
No I am not a contributor of here but if this issue is correct and need to be solved then i can try to solve it  @mingrammer

**Comment by mingrammer** [comment]
Oh, welcome! @arpit1997. Are you willing to resolve the issues with me?

**Comment by arpit1997** [comment]
i will first try to resolve with some of my tools including pycharm, PEP8 command line etc and we can discuss it later on for further corrections

**Comment by mingrammer** [comment]
79 lines limits applied?

**Comment by arpit1997** [comment]
Sorry i did not understand clearly what you are saying. Can you please explain?

**Comment by mingrammer** [comment]
Ah, sorry.
Um, your PR seems like to resolve the problems related to line limits of PEP8 (79 lines). But, I can not see the fixed codes for camelCase related problems.

**Comment by arpit1997** [comment]
I saw that mistake just now. Thanks for for your advice, i will try to resolve this by tomorrow or in 2-3 days

**Comment by mingrammer** [comment]
Ye, thanks for your efforts.
