### ISSUE TITLE
Guide or documentation for . . . . .

### ISSUE THREAD

**Issue by timsmith00** [PyGithub/PyGithub#456]
my objective is to automate the following, but the documentation isnt clear/has gaps
1.  Create a tag
2.  Create a branch
3.  Touch a version file
4.  Commit version touch from step 3
5.  Build and deploy apps
6.  Push branch upon successful build & deploy

does anyone have a functioning example - I have searched all the links posted previously and they all link back to the very trivial hello world example in the documentation.

**Comment by RayBB** [comment]
I've also been looking for a while on how to make a branch and it's obvious. I think this could be helpful.

**Comment by sfdye** [comment]
See #874
