### ISSUE TITLE
Fetching the Organization's members does not return the email address

### ISSUE THREAD

**Issue by fvanboven** [PyGithub/PyGithub#457]
Hi, 

Fetching the organization members does not return the email address of the github user (which is correct according to the documentation: https://developer.github.com/v3/orgs/members/#response)

It is an idea to add an additional call tot fetch the user itself (https://developer.github.com/v3/users/#get-a-single-user) so completed NamedUser objects are returned?

**Comment by sfdye** [comment]
@fvanboven Yes, you are right.

Since the member API does not give email. You need get the user using `g.get_user(username)` and pass in the `login` attribute from the previous call as the username.
