### ISSUE TITLE
Delete a repository

### ISSUE THREAD

**Issue by arpit1997** [PyGithub/PyGithub#464]
Github API provides the feature for deleting a user repository. I can not find any method corresponding to this in the documentation. So if it is not yet implemented then i request for this feature to be added for [PyGithub](https://github.com/PyGithub/PyGithub) 
If so then i will be happy to implement this feature.
If it is already implemented then provide documentation for it

**Comment by jayfk** [comment]
You just need to get the repo and then call `delete` on it.

```python
from github import Github
gh = Github("<token>")

repo = gh.get_repo(full_name="what/ever")
repo.delete()
```
