### ISSUE TITLE
More portable LICENSE?

### ISSUE THREAD

**Issue by tony** [PyGithub/PyGithub#468]
Didn't know this was a GPL license, as they're pretty rare to find in python.

www.github.com/tony/patches is MIT and can't use viral code. I originally wanted to pull this lib in thinking it was permissively licensed, but it won't work.

Not sure why a client lib (or anything python FWIW) needs to be virally licensed, even LGPL is strict relative to other python libs. Don't want to introduce troubles for downstream users down the road.

I'm kind of going to be stuck using direct API calls / wrappers, but it'd be nice to have this on a more portable license to not reinvent the wheel.

I recommend something like zlib, MIT, BSD, Apache 2, etc.

**Comment by jzelinskie** [comment]
It's difficult to get all contributors to PyGithub to sign off and changing the license this late into the game. You may find by reading a bit more that the LGPL isn't viral for languages like Java or Python: http://stackoverflow.com/a/12167947/877887

**Comment by tony** [comment]
>It's difficult to get all contributors to PyGithub to sign off on changing the license this late into the game.

yea i've shepherded a few projects over the years. Lots of gray hairs, and often I moved on to something else by the time its done.

I do think more permissive tends to be the better choice in the long run, and if its in the realm of reason, should be done sooner rather than later.

LGPL really does close doors. By the time we have a license with viral clauses, we've crossed the rubicon from bikeshedding to ramifications that could effect downstream projects.

> You may find by reading a bit more that the LGPL isn't viral for languages like Java or Python: http://stackoverflow.com/a/12167947/877887

I've read up on it, some of these prior issues are LGPL+python related: https://github.com/ScottDuckworth/python-anyvcs/issues/32, https://github.com/urwid/urwid/issues/41, https://github.com/django-wiki/django-wiki/issues/454, https://github.com/jgm/peg-markdown/issues/35, https://github.com/saitoha/canossa/issues/1, https://github.com/pytest-dev/pytest-mock/issues/45

(Not a lawyer) Ultimately, FSF isn't what dictates the language, that'd be done in the license itself by articulating things beyond the realm of ambiguity and uncertainty. Individual courts are the the deciders, and the scenario I'm trying to avoid is a couple of things:

- A big guy (company, a lawsuit troll) could use the GPL as a way to file suits against a little guy (startup, open source project, developer). Stress and costs incurred aren't worth it
- Make it hard down the road for license changes and portability. MIT / zlib / etc. can fit right into LGPL and GPL, but the other way around requires a big process that scales proportionally as more contributors send in backwards-incompatible patches.
- Misunderstandings on licensing period tend to get averted completely. 
- Its rare to see licenses go from permissive to viral (even soft ones like LGPL). Then again, WINE did it. Its hard to make a case on the merits to go from permissive to viral.
- While it's a temptation deter freeloaders who don't give contributions back, the evidence is overwhelming that the viral terms do more harm and little evidence they result in useful reciprocity upstream. Look at Apple and Clang, look at Apple/Canonical and ZFS.

The big thing about licenses is ambiguity and lack of specificity gives every jurisdiction ample legroom to disagree. Even if cases prevail, I'm assuming LGPL is meant in the best faith possible, but someone who complains still a right to use the vagueness as a weapon. It'd be distracting and costly, and the precedent may not be of much value outside of jurisdictions where the decision was made.

Maybe I'm the one who misunderstands the license. But I don't want to expose my own downstream users' with the legalities / headaches down the road.

IMO its ok if this closes, if https://github.com/sigmavirus24/github3.py gets the same thing done.
