### ISSUE TITLE
Python 2.7 Error - ImportError: cannot import name Github

### ISSUE THREAD

**Issue by azatelli** [PyGithub/PyGithub#472]
import github works but nothing seems to be under github. Using Python 2.7. 

pip install PyGithub

Thoughts?

**Comment by andrewgross** [comment]
`from github import Github` is the best way to get started.  Check the documentation for some examples of how to use different auth types.

**Comment by 10c8** [comment]
`from github import Github` will result in an error stating that `MainClass` doesn't exist.

**Comment by andrewgross** [comment]
Hmm, that is very strange, possible that you have conflicting dependencies?  Can you list the results of `pip freeze`?

**Comment by azatelli** [comment]
pip freeze:

prettytable==0.7.2

PyGithub==1.29

requests==2.11.1

**Comment by andrewgross** [comment]
In the directory you are working in, do you have a file called `github.py`? (or a folder with an `__init__.py` inside of it?

**Comment by azatelli** [comment]
Yes sir.

**Comment by azatelli** [comment]
Yes sir, github.py

**Comment by andrewgross** [comment]
Yep, that'll do it.  Python will try to import from that file first, try changing the name of your local file and it should work.

**Comment by azatelli** [comment]
Awesome! Thank you. :)

**Comment by tzatter** [comment]
I met the same problem. then I got here. Thank you!

**Comment by nirzari18** [comment]
I was facing the similar issue. This helped. Thanks

**Comment by AsinRay** [comment]
I met the same problem. then I got here. Thank you!

**Comment by prakhar21** [comment]
Thanks @andrewgross

**Comment by enricorotundo** [comment]
LOL we all got into the `github.py` trap 🤖

**Comment by jbradforddillon** [comment]
Haaaaaa. yep. Thanks for this!

**Comment by Priyanka-xlnx** [comment]
wow thanks for this !

**Comment by abubelinha** [comment]
[me too](https://stackoverflow.com/questions/68532135/pygithub-cant-import-github-from-github/68532816?noredirect=1#comment123333271_68532816)

**Comment by neiltranter** [comment]
me too!

**Comment by toughjay318** [comment]
@andrewgross so I don’t have a file named github.py, but I do have a folder labeled ‘’’__init__.py’’’. I am receiving the same Import error for github

**Comment by andrewgross** [comment]
Is your folder named `github`?

**Comment by toughjay318** [comment]
I believe it is. I will check again tomorrow at school. I will let you know when I am 100% sure. Sincerely, Jalen GriffinOn Apr 2, 2023, at 11:58 AM, Andrew Gross ***@***.***> wrote:﻿
Is your folder named github?

**Comment by andrewgross** [comment]
Ok, you should make sure you don't have a folder, file or class named Github to avoid the import issues.

**Comment by rparamanandam-equinix** [comment]
This is fixed my issue
pip3 install --upgrade pip
pip3 install --upgrade pygithub

**Comment by kumgaurav** [comment]
This is fixed my issue
pip3 install --upgrade pip
pip3 install --upgrade pygithub
