### ISSUE TITLE
has_downloads is True, but apparently no downloads

### ISSUE THREAD

**Issue by kdottiemo** [PyGithub/PyGithub#477]
Hi there,

I check a repo's downloads status by checking the Repository class's `has_downloads` attribute, which is True. However, there is apparently nothing in the list. Sample code:

```
# Is true: 
print str(repo.has_downloads)

# Is apparently empty:
dwnlds = repo.get_downloads()
for d in dwnlds:
   print dwnld.id
```

Am I missing something?
Repo is: https://github.com/NASA-DEVELOP/dnppy/

**Comment by jzelinskie** [comment]
Seems like a bug on Github's side:

https://api.github.com/repos/NASA-DEVELOP/dnppy
returns an object that has `downloads` set to True, but if you go to https://api.github.com/repos/NASA-DEVELOP/dnppy/downloads you get an empty list.

**Comment by kdottiemo** [comment]
Interesting...guess I'll bring it up with them! Thanks @jzelinskie.
