### ISSUE TITLE
Adding Some Traffic Info. - Attributes Error?

### ISSUE THREAD

**Issue by kdottiemo** [PyGithub/PyGithub#478]
Towards expansion of the library for handling the experimental "Traffic" API (https://developer.github.com/v3/repos/traffic/), I wanted to take a stab at adding a "Clones.py" to extract clone information (https://developer.github.com/v3/repos/traffic/#clones). 

I retrieve the parent information fine via the following added funtion in Repository.py:

```
    def get_clones(self, per):
        """
        :calls: `GET /repos/:owner/:repo/traffic/clones
        :rtype: :class:`github.PaginatedList.PaginatedList` of :class:`github.Clone.Clone`
        """
        return github.PaginatedList.PaginatedList(
            github.Clone.Clone,
            self._requester,
            self.url + "/traffic/clones?per=" + str(per),
            None,
            headers={'Accept': 'application/vnd.github.spiderman-preview'}
        )
```

That's all fine I think. But in creating Clones.py, I don't think I have the syntax right. Say I just want the class to be able to get the number of "uniques." I have this:

```
class Clone(github.GithubObject.CompletableGithubObject):
    def __repr__(self):
        return self.get__repr__({"uniques": self._uniques.value})

    @property
    def uniques(self):
        """
        :type: integer
        """
        return self._uniques.value

    def _initAttributes(self):
        self._uniques = github.GithubObject.NotSet

    def _useAttributes(self, attributes):
        if "uniques" in attributes:
            self._uniques = self._makeIntAttribute(attributes["uniques"])
```

But when I test it by creating a clone object, it fails with: 
    **self._uniques = self._makeIntAttribute(attributes["uniques"])
    TypeError: string indices must be integers**

What am I missing? Just jumping into this; can't admit that I know if, for instance, Clones should be a "CompletableGithubObject," the nuances of the nested clone information, etc. I'd like to get the basics of this working though and contribute to PyGithub however.

Thanks.

**Comment by alanbernstein** [comment]
I'm interested in this. @kdottiemo, did you make any progress in resolving this error?

**Comment by gomesfernanda** [comment]
I'm also interested! :)

**Comment by Jessime** [comment]
I'd love to have access to traffic info!
