### ISSUE TITLE
Where is the documentation???

### ISSUE THREAD

**Issue by GreenJoey** [PyGithub/PyGithub#480]
Where is the Documentation for the library??

**Comment by MichaelPereira** [comment]
http://pygithub.readthedocs.io/en/latest/introduction.html

**Comment by ericbrandwein** [comment]
Where are the documentation files? I couldn't find them in /doc: https://github.com/PyGithub/PyGithub/tree/master/doc

**Comment by MichaelPereira** [comment]
@ericbrandwein The documentation detail are in the code itself: https://github.com/PyGithub/PyGithub/blob/master/github/Commit.py#L159-L166

**Comment by ericbrandwein** [comment]
@MichaelPereira oh great, then the documentation on ReadTheDocs needs an update, because the  "edit on github" button sends me to the `/doc` directory in this repo 😕

**Comment by MichaelPereira** [comment]
Which is fine because this is where the introduction, table of contents, etc are located, but the location of the code documentation could be made a little more explicit

**Comment by ericbrandwein** [comment]
But when I go here: http://pygithub.readthedocs.io/en/latest/apis.html, and click that button, it takes me to a 404: https://github.com/PyGithub/PyGithub/blob/master/doc/apis.rst

**Comment by gvanrossum** [comment]
Would be nice if the README contained a link to the docs.

**Comment by Quentin-M** [comment]
@gvanrossum There you go.

![2016-11-01 19-35-43](https://cloud.githubusercontent.com/assets/1332289/19902343/aa8fd85e-a06a-11e6-9758-ae10932d2577.png)

**Comment by jzelinskie** [comment]
That's the problem when you have too many badges. I think docs is a bit more important than a badge, so this should definitely be expanded on more in the readme.

**Comment by tmshn** [comment]
In addition to the README, it would be nicer if the link to the doc is added here:
<img width="642" alt="url_here" src="https://cloud.githubusercontent.com/assets/3760893/20648716/d5010694-b4f1-11e6-9d85-80b6a76957e6.png">

**Comment by blaisep** [comment]
IMHO @gvanrossum  and @tmshn are spot on. 
In fact, the description in the `readme.md` could be nothing more than the link to the correct docs.(because the current description contains only links to super well-known sources. 
Please approve @gamefiend 's https://github.com/PyGithub/PyGithub/pull/499

**Comment by jzelinskie** [comment]
Closed by #499
