### ISSUE TITLE
Get pulls missing params

### ISSUE THREAD

**Issue by ericbrandwein** [PyGithub/PyGithub#481]
I can't pass the `base` or the `head` query parameters to the call to `Repository.get_pulls()`, or at least it doesn't say anything about it in [the docs](http://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.get_pulls)
They are defined by the documentation on GitHub's API [here](https://developer.github.com/v3/pulls/#list-pull-requests).

**Comment by sfdye** [comment]
This was fixed in master.
