### ISSUE TITLE
Pull request get_comments() method returning no results

### ISSUE THREAD

**Issue by kennknowles** [PyGithub/PyGithub#484]
It seems that the `get_comments()` and `get_review_comments()` methods have an issue in the latest release.

For a pull request with a number of comments (https://github.com/apache/incubator-beam/pull/1013) these APIs return no results.

```python
In [4]: len(list(Github().get_repo('apache/incubator-beam').get_pull(1013).get_comments()))
Out[4]: 0

In [5]: len(list(Github().get_repo('apache/incubator-beam').get_pull(1013).get_review_comments()))
Out[5]: 0
```

**Comment by sfdye** [comment]
There are some confusion of the method name. The correct one to retrieve comments for an issue would be `get_issue_comments`. Actually `get_comments` is just an alias of `get_review_comments` so there will always return you the same results.
