### ISSUE TITLE
Can't use 'in' qualifier to search code.

### ISSUE THREAD

**Issue by tasugi** [PyGithub/PyGithub#489]
I have tried to search code like
```
g.search_code(query='addClass', language='js', repo='jquery/jquery', in='file')
```
However, I can't do that because the word 'in' conflicts Python's syntax.
Are there any method to solve this probrem?

**Comment by ClaudiuCreanga** [comment]
it should be like this
`g.search_code("keyword in:filename.php language:xml")`
