### ISSUE TITLE
Get pull requests on the basis of some parameter

### ISSUE THREAD

**Issue by Harshdeep1996** [PyGithub/PyGithub#502]
Can we get a paginated list of all the pull requests within a certain date? 
```
g = Github(token, per_page=100)
org = g.get_organization('cloudant')
code = org.get_repo('chef-repo')
paignated_list = code.get_pulls(state='closed') ```

like can we use `get_pulls` for a certain date range?

**Comment by sfdye** [comment]
Yes there is.

use the `g.search_issues()` method:
https://developer.github.com/v3/search/#search-issues

Because pull request IS also considered an issue.
