### ISSUE TITLE
Repository.get_license() not supported

### ISSUE THREAD

**Issue by tedg-cisco** [PyGithub/PyGithub#508]
GitHub License API is not supported:  https://developer.github.com/v3/licenses/#get-the-contents-of-a-repositorys-license

We need to programmatically determine the open source license associated with a repository where the open source license was specified when the repository was created.
When would that be possible?

**Comment by sfdye** [comment]
@tedg-cisco I am aware of this. See #724 

If you really want this feature, you could submit a PR and I will review or someone else could take it but that will take some time.
