### ISSUE TITLE
Refactor managing of repository.

### ISSUE THREAD

**Issue by nhomar** [PyGithub/PyGithub#517]
Hello.

We have a lot of things to improve, I ask for permission to refactor some things in order to take care of them.

1. Coverage, we use internally codecov as here: https://github.com/vauxoo/cfdilib
2. Convert all a little more like what is proposed here: https://jeffknupp.com/blog/2013/08/16/open-sourcing-a-python-project-the-right-way/
3. Automate the publish process to pypi with a -dev for master.
4. Follow more stuff as cookiecutter.
5. Document the release process and the maitainance environment as here: https://github.com/Vauxoo/cfdilib/blob/master/PREPARE_RELEASE.md
6. Enable changelog and bumpversion.
7. Include doctest and autodoc, and its automation to gh-pages as I have it here: https://github.com/Vauxoo/odoo/commit/4db163c40689a6c8d03bce22066c9dfbcb74460e (that's for translations but it can be easily be sent with raw version what I want to show is the process itself).

I can do that this weekend, but I want ask to maintainers if it is ok for you guys? or maybe you can enlight me a little bit how is the current process for that, maybe it is being done but I do not understand pretty well how.

Regards.

**Comment by jayfk** [comment]
Most of the things you mention are already there:

Take a look at [manage.sh](https://github.com/PyGithub/PyGithub/blob/master/manage.sh#L4) on how the release process looks like. Running `sh manage.sh publish` runs tests, lets you pick a new version, tags the release, creates a changelog and travis publishes the release to PyPi.

Adding some automation to this project is a very good Idea, especially when it comes to tools like Coverage.

If I had unlimited time I'd probably:
 - Rewrite the testing framework and all the tests, switching to something like betamax et. al. and document how to create tests.
 - Rip out all the stuff that's in [Requester.py](https://github.com/PyGithub/PyGithub/blob/master/github/Requester.py) and move to requests with sessions.



> Follow more stuff as cookiecutter.

What does this mean?

**Comment by labrys** [comment]
> Follow more stuff as cookiecutter.

@jayfk [cookiecutter](https://github.com/audreyr/cookiecutter) as described by the readme:

>A command-line utility that creates projects from cookiecutters (project templates), e.g. creating a Python package project from a Python package project template.

It's mostly used with templates like [ionelmc](https://github.com/ionelmc/cookiecutter-pylibrary) to set up a new project with things like Tox, Travis, Coveralls etc.
