### ISSUE TITLE
Docs link is broken

### ISSUE THREAD

**Issue by T3KN0KRAT** [PyGithub/PyGithub#521]
Hi,

I don't know if this is the right place to notify someone that the links on https://pygithub.readthedocs.io/en/latest/introduction.html that points to http://jacquev6.net/PyGithub/v1 are dead.  Both links are in the What's Next? section.

Perhaps they should point to https://pygithub.github.io/PyGithub/v1/reference.html instead?

If this isn't the right place, could you please let me know whom I should advise?

**Comment by sfdye** [comment]
This is fixed.
