### ISSUE TITLE
Missing support for release asset APIs

### ISSUE THREAD

**Issue by thehighlander** [PyGithub/PyGithub#526]
API Documentation found here:
https://developer.github.com/v3/repos/releases/#list-assets-for-a-release
https://developer.github.com/v3/repos/releases/#upload-a-release-asset
https://developer.github.com/v3/repos/releases/#get-a-single-release-asset
https://developer.github.com/v3/repos/releases/#edit-a-release-asset
https://developer.github.com/v3/repos/releases/#delete-a-release-asset

I've created the following PR with the APIs added in:
https://github.com/PyGithub/PyGithub/pull/525

**Comment by sfdye** [comment]
Fixed in #525
