### ISSUE TITLE
get_repo sends 404 for repos from organizations

### ISSUE THREAD

**Issue by mlainez** [PyGithub/PyGithub#534]
Hi,

I'm having trouble calling get_repo with the name of a repo I have access to in an organization.

Here's what I simply do:
```python
repo = me.get_user().get_repo(name_of_organization_repo_i_have_access_to)
```

This is what I get:
````
github.GithubException.UnknownObjectException: 404 {'documentation_url': 'https://developer.github.com/v3', 'message': 'Not Found'}
````
It works fine with a repo associated to my own account. But as soon as I need one from an organization it fails.

What is strange to me is that:
```python
repos = me.get_user().get_repos()
```
Shows the repo in the list as expected.

Am I missing something obvious?

**Comment by RichardJTorres** [comment]
+1 I am having the same issue. The problem is that this line sets the user to be the authenticated user explicitly. I can't seem to find another method in the API that allows this. 

https://github.com/PyGithub/PyGithub/blob/master/github/AuthenticatedUser.py#L851

**Comment by RichardJTorres** [comment]
This seems to fix it: 

<pre>
   def get_repo(self, name, org=None):
        """
        :calls: `GET /repos/:owner/:repo <http://developer.github.com/v3/repos>`_
        :param name: string
        :rtype: :class:`github.Repository.Repository`
        """
        assert isinstance(name, (str, unicode)), name
        username = org if org else self.login

        headers, data = self._requester.requestJsonAndCheck(
            "GET",
            "/repos/" + username + "/" + name
        )
        return github.Repository.Repository(self._requester, headers, data, completed=True)
</pre>

**Comment by RichardJTorres** [comment]
@mlainez Actually, looks like we should be using the `get_repo()` method on the main class. So it would be:

<pre>
>> g = Github("user", "password")
>> repo = g.get_repo("Org/RepoName", lazy=False)
>> repo 
Repository(full_name="Org/RepoName")
</pre>

**Comment by sfdye** [comment]
I will probably add this to some example usage page.

**Comment by PedroGFonseca** [comment]
I'm trying @RichardJTorres's solution, but still get a 404. Can access non private repos, but not organization repos.

**Comment by PedroGFonseca** [comment]
Ah, the problem was that I hadn't given the token the right permissions. Clear.

**Comment by thecturner** [comment]
> Ah, the problem was that I hadn't given the token the right permissions. Clear.

@PedroGFonseca do you remember what permissions the token needed for this? I'm experiencing the same issue.

**Comment by sgupta-wish** [comment]
@thecturner It works for me with the `repo` [scope](https://docs.github.com/en/developers/apps/scopes-for-oauth-apps#available-scopes).
