### ISSUE TITLE
Automated Testing fails if http_proxy is set in the environment

### ISSUE THREAD

**Issue by allevin** [PyGithub/PyGithub#539]
When running the [automated testing](https://github.com/PyGithub/PyGithub/blob/master/CONTRIBUTING.md#automated-tests), if http_proxy is setup in the environment, tests will fail with "AttributeError: ReplayingConnection instance has no attribute 'set_tunnel'"

Removing the http_proxy environment variable fixes the problem.

```
> python -s -m github.tests PullRequest
EEEEEEEEEEEE
======================================================================
ERROR: testAttributes (github.tests.PullRequest.PullRequest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "github/tests/PullRequest.py", line 35, in setUp
    self.repo = self.g.get_user().get_repo("PyGithub")
  File "github/AuthenticatedUser.py", line 851, in get_repo
    "/repos/" + self.login + "/" + name
  File "github/AuthenticatedUser.py", line 213, in login
    self._completeIfNotSet(self._login)
  File "github/GithubObject.py", line 251, in _completeIfNotSet
    self._completeIfNeeded()
  File "github/GithubObject.py", line 255, in _completeIfNeeded
    self.__complete()
  File "github/GithubObject.py", line 260, in __complete
    self._url.value
  File "github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "github/Requester.py", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "github/Requester.py", line 252, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "github/Requester.py", line 269, in __requestRaw
    cnx = self.__createConnection()
  File "github/Requester.py", line 345, in __createConnection
    conn.set_tunnel(self.__hostname, self.__port, headers)
AttributeError: ReplayingConnection instance has no attribute 'set_tunnel'

```

**Comment by allevin** [comment]
@sfdye It's been a while since I wrote this.  I don't recall all the details on this issue.  However the recommended change did correct the problem for me.

Also, BTW, thank you for all you are doing for PyGithub.  There has been tremendous progress on the project since you started addressing the issues and PR's!

**Comment by sfdye** [comment]
@allevin Thank you for your comment, it made my day. BTW, we are in the middle of migrating to `requests` from `httplib`, after which the proxy related issues should be addressed automatically. (I hope)

**Comment by allevin** [comment]
@sfdye Glad I could put a smile on your face!

I have been aware of the effort to move to requests. 

One question/request.  Is there a way (or does it already exist) to implement a retry function in the low level communications?  I.e. if a request fails, that the PyGithub library could be setup to automatically retry after a user defined delay and with a limited number of retries?  

Our network is behind an aggressive proxy server/filter and we occasionally lose responses from Github.  This causes comm exceptions that could be avoided if the low level code would just perform an (optional - user configured) retry.  

I was considering trying to address this in the current code set, but feel its a waste since the code is moving to requests.  I have high level solution (extremely ugly) that I implemented a long time ago but a low level solution would be so much more elegant.

**Comment by sfdye** [comment]
How about this:
http://docs.python-requests.org/en/latest/api/?highlight=max_retries#requests.adapters.HTTPAdapter

**Comment by sfdye** [comment]
@allevin Can you help me test the alpha release with `requests`. If anything goes well, we can consider adding the retry option.

`pip install --pre PyGithub==1.40a1`
