### ISSUE TITLE
GitAuthor.date should return datetime, not string

### ISSUE THREAD

**Issue by bilderbuchi** [PyGithub/PyGithub#54]
Hi!

It's great that all date-like objects are datetime.datetime now, makes working with it so easy. However, I think you missed GitAuthor.date, it would be great if this would also return datetimes.

Background: To get the dates of tags, I did `MyTag.commit.commit.committer.date`, and expected this to return a datetime object (like all the others do), but it returns a string.

**Comment by jacquev6** [comment]
@letmaik I'm not working on PyGithub anymore. If you want to open a PR with a documentation change, I'm sure the current maintainers will merge it.

**Comment by sfdye** [comment]
@letmaik Yes, I will be happy to review it.
