### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by McaDipali** [PyGithub/PyGithub#540]
after installing githubpy

next i want to use it
then 
it get error in python like'

 from github import Github
ImportError: cannot import name Github

plz help me if anyone know how to use

**Comment by hreeder** [comment]
This repo is [pygithub](https://pypi.python.org/pypi/PyGithub), not [githubpy](https://pypi.python.org/pypi/githubpy), which is a separate project.

For the documentation in this repo to be valid for your case, you will need to have installed pygithub.
