### ISSUE TITLE
Dependency on python-jose/PyCrypto

### ISSUE THREAD

**Issue by xoviat** [PyGithub/PyGithub#542]
Python-jose depends on pycrypto, which is no longer developed at this time. The developer of that project [has said](https://github.com/mpdavis/python-jose/pull/43#issuecomment-284202876) that he will maintain that dependency because it is available on google app engine standard. However, PyCrypto is insecure and has known vulnerabilities.

If you want, I can publish a python-jose that depends on cryptography and then you can change your dependency to that package. I am open to whatever is acceptable to eliminate PyCrypto.

**Comment by jayfk** [comment]
Thanks for raising this issue.

Given the lack of responsibilty on upstream to use secure transitive dependencies by default, we should probably switch to pyjwt or something else.

On top of that, JWT is needed for integrations support only. We can probably install dependencies for this use case as an extra with pygithub[integrations].

What do you think?

**Comment by jzelinskie** [comment]
Yes, I use pyjwt in another project and highly recommend we switch it out. Cryptography is such a good library.

**Comment by xoviat** [comment]
Currently I've submitted a pull request for python-jose that replaces the backend with cryptography. If it isn't merged soon, then I'll publish a replacement package.

**Comment by jayfk** [comment]
Switched to pyjwt in https://github.com/PyGithub/PyGithub/commit/d447eb13b9f4688a4c981ca03b1b3111fb299142.
