### ISSUE TITLE
create_file fails

### ISSUE THREAD

**Issue by astrofrog** [PyGithub/PyGithub#545]
It looks like ``create_file`` is broken:

```
import github
gh = github.Github('...')
user = gh.get_user()
repo = user.create_repo('testing')
repo.create_file('test', 'commit message', 'banana')
```

gives:

```
Traceback (most recent call last):
  File "test_gh_api.py", line 7, in <module>
    repo.create_file('test', 'commit message', 'banana')
  File "/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/github/Repository.py", line 1310, in create_file
    input=put_parameters
  File "/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/Users/tom/miniconda3/envs/dev/lib/python3.6/site-packages/github/Requester.py", line 180, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3'}
```

**Comment by moghya** [comment]
@astrofrog  you're doing it wrong way.

First parameter is path and it has to be relative from root
simply adding backslash at the start of path works 

`repo.create_file('/test', 'commit message', 'banana')`

happy coding :)

**Comment by moghya** [comment]
@astrofrog  please review the suggested method and close this issue

**Comment by shufanhao** [comment]
> @astrofrog you're doing it wrong way.
> 
> First parameter is path and it has to be relative from root
> simply adding backslash at the start of path works
> 
> `repo.create_file('/test', 'commit message', 'banana')`
> 
> happy coding :)

It doesn't work for me.

**Comment by VSNSAINIVAS** [comment]
> @astrofrog you're doing it wrong way.
> 
> First parameter is path and it has to be relative from root simply adding backslash at the start of path works
> 
> `repo.create_file('/test', 'commit message', 'banana')`
> 
> happy coding :)

This doesnot work for me

**Comment by lendoo73** [comment]
same issue here as well...

```
auth = Auth.Token("token")
g = Github(auth=auth)
repo = g.get_repo('myname/GitTest')

repo.create_file("text.txt", "more tests", "content")
```

github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url"

same result with repo.create_file("/text.txt", "more tests", "content") too
