### ISSUE TITLE
Get commits between two commits.

### ISSUE THREAD

**Issue by yzhao2012** [PyGithub/PyGithub#547]
Hello! 
This is more of a request, but we're currently looking for functionality similar to the functionality of:
`git log <commit hash 1> <commit hash 2>` 
( or this page: https://github.com/octocat/linguist/compare/octocat:96d29b7%5E%5E%5E%5E%5E...octocat:96d29b7 ).

I couldn't find any standing documentation on it for pygithub, but I was wondering if this was something that I could request? We're currently iterating over the parents of a commit, until we get the commit we want, then return all the commits during the iteration. However, this method doesn't work when the commits are on a different branch. 

Thanks!

**Comment by nguyenl95** [comment]
Yeah I'm interested in this too
