### ISSUE TITLE
Guidelines for creating a repo

### ISSUE THREAD

**Issue by adriens** [PyGithub/PyGithub#548]
Hi,

first thanks a lot for having developed this api, it really rocks and makes things easy to do ! The only thing i have not found in your examples is how to create a repo : i have found how to delete on but not how to create. Indeed it seems like the Github API does allow it.

So my question is : did you implement this method, ... and if yes, can you point me to a code snippet please ?

Thanks in advance for you help.

Kind Regards,

Adrien

**Comment by singh1114** [comment]
I have used this library and used the `user.create_repo(reponame)` method. My user is authenticated but I am still unable to create the repo.

The error looks like this:
`404 {u'documentation_url': u'https://developer.github.com/v3/repos/#create', u'message': u'Not Found'}`

**Comment by sfdye** [comment]
I just checked, it should work. Check whether you personal access token has the correct permission, and whether you want to create a personal repo or org repo.

https://developer.github.com/v3/repos/#create
