### ISSUE TITLE
remove_from_members stopped working

### ISSUE THREAD

**Issue by TheNotTooDistantFuture** [PyGithub/PyGithub#552]
remove_from_members seems to have stopped working. 
Command:
import github
from github import Github
token = 'github-token' # token from an org owner
github = github.Github(token)
org = github.get_organization('org-name')
user = github.get_user('test-username')
print org.has_in_members(user) # Returns True
org.remove_from_members(user)

Doesn't remove member for org and produces the following error:
Traceback (most recent call last):
  File "github-authenticator.py", line 51, in <module>
    check_github_membership('test-username')
  File "github-authenticator.py", line 40, in check_github_membership
    org.remove_from_members(user)
  File "/Library/Python/2.7/site-packages/github/Organization.py", line 608, in remove_from_members
    self.url + "/members/" + member._identity
  File "/Library/Python/2.7/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/Library/Python/2.7/site-packages/github/Requester.py", line 180, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {u'documentation_url': u'https://developer.github.com/v3/orgs/members/#remove-a-member', u'message': u'Not Found'}

From the looks of other issues, this seems to happen when there's a change to the github api - is that right?

**Comment by talipomin** [comment]
cant reproduce, cat you post debug info?
you can switch on debug logging using `github.enable_console_debug_logging()`

**Comment by TheNotTooDistantFuture** [comment]
Thanks for the quick reply. Here's the debug result of remove_from_members(user):

DELETE https://api.github.com/orgs/shopkeep/members/test-username {'Authorization': 'token (oauth token removed)', 'User-Agent': 'PyGithub/Python'} null ==> 404 {'status': '404 Not Found', 'x-accepted-oauth-scopes': 'admin:org, repo', 'content-length': '107', 'x-github-media-type': 'github.v3; format=json', 'x-content-type-options': 'nosniff', 'content-security-policy': "default-src 'none'", 'access-control-expose-headers': 'ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval', 'x-github-request-id': 'EB23:1253B:1E14381:25CFE37:58EB523B', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'x-ratelimit-remaining': '4932', 'server': 'GitHub.com', 'x-ratelimit-limit': '5000', 'x-oauth-scopes': 'admin:org, admin:org_hook, admin:public_key, admin:repo_hook, gist, notifications, repo, user', 'date': 'Mon, 10 Apr 2017 09:36:59 GMT', 'x-frame-options': 'deny', 'access-control-allow-origin': '*', 'content-type': 'application/json; charset=utf-8', 'x-xss-protection': '1; mode=block', 'x-ratelimit-reset': '1491818400'} {"message":"Not Found","documentation_url":"https://developer.github.com/v3/orgs/members/#remove-a-member"}
Traceback (most recent call last):
  File "debug.py", line 14, in <module>
    org.remove_from_members(user)
  File "/Library/Python/2.7/site-packages/github/Organization.py", line 608, in remove_from_members
    self.url + "/members/" + member._identity
  File "/Library/Python/2.7/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/Library/Python/2.7/site-packages/github/Requester.py", line 180, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {u'documentation_url': u'https://developer.github.com/v3/orgs/members/#remove-a-member', u'message': u'Not Found'}

**Comment by TheNotTooDistantFuture** [comment]
My mistake. My authenticated user wasn't an Owner. Thanks for your help. 

Unrelated question - is there no method to add a user to an organization? I see a way to add them to a team, but they need to be added to the org first.
