### ISSUE TITLE
GitHub Integration raises "NotImplementedError Algorithm not supported"

### ISSUE THREAD

**Issue by paulortman** [PyGithub/PyGithub#554]
We have working github integration code using PyGithub v1.32 that does essentially:

```python
integration = github.GithubIntegration(settings.GITHUB_INTEGRATION_ID, settings.GITHUB_INTEGRATION_PRIVATE_PEM)
inst_token = integration.get_access_token(installation_id).token
```
After upgrading to v1.34 this code raises "NotImplementedError Algorithm not supported"

I suspect it has to do with the [switch to pyjwt from python-jose](https://github.com/PyGithub/PyGithub/commit/d447eb13b9f4688a4c981ca03b1b3111fb299142)

**Comment by jayfk** [comment]
Could you post a stacktrace?

**Comment by paulortman** [comment]
Yeah, my bad.  Here is the relevant info:
```
inst_token = integration.get_access_token(installation_id).token
File "github/MainClass.py", line 657, in get_access_token
                  "Authorization": "Bearer {}".format(self.create_jwt()),
File "github/MainClass.py", line 638, in create_jwt
              algorithm="RS256"
File "jwt/api_jwt.py", line 56, in encode
              json_payload, key, algorithm, headers, json_encoder
File "jwt/api_jws.py", line 102, in encode
              raise NotImplementedError('Algorithm not supported')
NotImplementedErrorAlgorithm not supported
```

**Comment by jayfk** [comment]
Ah, I see. `RS256` requires cryptography to be installed:

```
pip install cryptography
```

We should make that an extra that can be installed via `pygithub[integrations]` and document it.

**Comment by paulortman** [comment]
Great, thanks for looking into it so quickly.  It's very much appreciated.  Thank you for the project as well, it's a great tool.
