### ISSUE TITLE
I think input() and print() in python is misleading

### ISSUE THREAD

**Issue by JianXin-Yun** [PyGithub/PyGithub#556]
I think `input()`  and `print()`  in python is misleading,I think `input()` should be called `keyboard()` because this function provides a keyboard interface to react keyboard thing,read most keys of keyboard excluding Enter key(Enter key is used to end keyboard input),as for `print()` ,I thinought this should be called `output()` long ago,now I think it's better to be called `screen()` because this function name implies that its argument will be shown on the screen.  `keyboard()` and `screen()` sound very hardware,they are associated with PC I/O hardware(everyone knows keyboard is a classic input hardware and screen is a classic output hardware),if `print()` be called `output()` ,it will be less misleading,but `keyboard()` and `screen()` will be more straightforward and exact.I hope python organization will see my advise,hoping they are in GITHUB

**Comment by jayfk** [comment]
This may very well be the case, but it's not the right place to discuss it. You are probably looking for [CPython](https://github.com/python/cpython).

**Comment by JianXin-Yun** [comment]
@jayfk 
thank you for your advise,I'll talk it on CPython

**Comment by JianXin-Yun** [comment]
![image](https://cloud.githubusercontent.com/assets/26893563/24984429/ecfa2e4e-201f-11e7-9185-e76db3c1e197.png)
but [https://github.com/python/cpython](url) has no issue mudule
