### ISSUE TITLE
create_pull() requires a GitHub.Issue, contra the API

### ISSUE THREAD

**Issue by pmlandwehr** [PyGithub/PyGithub#558]
`github.Repository.Repository.create_pull()` requires that you provide it an Issue; this is contra [the corresping API call](https://developer.github.com/v3/pulls/#create-a-pull-request), which only requires a head, base, and title.

**Comment by pmlandwehr** [comment]
The relevant line is [here](https://github.com/PyGithub/PyGithub/blob/master/github/Repository.py#L993)

You *can* omit a `github.Issue.Issue`, but if so you need to include a body string. However, body strings are optional in the official API, so should perhaps be optional here.

**Comment by s-t-e-v-e-n-k** [comment]
I understand what is going on here. Since the code for create_pull() checks the number of arguments passed, not what they are, and that body is optional, the code should call the relevant method correctly based on which arguments are passed, not the count.

**Comment by sfdye** [comment]
Is it? I thought there are two ways you can create a pull request, one is from head/title/base, the other is from an issue:

https://developer.github.com/v3/pulls/?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc#alternative-input

**Comment by s-t-e-v-e-n-k** [comment]
Yes, exactly -- either title or issue is required, but if a title is passed the body is optional. Consider:

```repo.create_pull(title="New PR", base=foo, head=bar)```

That will call __create_pull_2 expecting an issue, when one is not provided.

**Comment by s-t-e-v-e-n-k** [comment]
@sfdye I've pushed up two branches that show the problem, and also solve it in two different ways. They both have downsides and upsides, but I can't decide between them, so I've held off creating a pull request. I can do that once we have chosen a victor.

Allowing body to be optional: https://github.com/s-t-e-v-e-n-k/PyGithub/commit/2a915804984bb59ad244dbec1924853cfa93f5f7

Refactoring Repository.create_pull() entirely: https://github.com/s-t-e-v-e-n-k/PyGithub/commit/5eba0f0f783578fee7d64176e51c3c7fc8fa1ca8

Note these two commits are not related in any way, they just share the same testcase.
