### ISSUE TITLE
What is the difference between forks and forks_count?

### ISSUE THREAD

**Issue by ritiek** [PyGithub/PyGithub#563]
Hi, thanks for developing this!

I was wondering what is the difference between `repo.forks` and `repo.forks_count` in `class github.Repository.Repository`? I tested them and they both seem to return the number of forks of repo..

Here is an example of quick testing:

```
gh = Github("<user>", "<pass>")
for repo in (gh.get_user()).get_repos():
        print(repo.forks == repo.forks_count)
```

**Comment by sfdye** [comment]
Thanks for reporting.

Please use `forks_count` according to the latest API. I suspect `forks` was an out-dated property, which we should properly depreciate and remove.
