### ISSUE TITLE
No HTTP status checks in statistics

### ISSUE THREAD

**Issue by fridex** [PyGithub/PyGithub#564]
For statistics such as `contributors` or `commit_activity`, there are no checks whether the API responded with 200. In a lot of cases, GitHub API responds with 202 as some statistics are computed asynchronously on demand [1]. Even if PyGithub does not perform waits, I would expect notification that I should retry after some time.

[1] https://developer.github.com/v3/repos/statistics/#a-word-about-caching

**Comment by sfdye** [comment]
Good catch! @fridex Would you like to submit a PR?

**Comment by fridex** [comment]
> Good catch! @fridex Would you like to submit a PR?

If time allows why not. However I don't see it doable in the near future so if someone is interested, feel free to pick this item.

**Comment by mfonville** [comment]
I think it could be done with a relatively simple modification in `__requestRaw` where currently a `301` redirect is handled, a similar line could be added to check for a `202`, wait a few moments, and then retry until no `202` is returned anymore.

**Comment by mfonville** [comment]
I made a PR to fix this issue:
https://github.com/PyGithub/PyGithub/pull/791
