### ISSUE TITLE
Can we support `ContentFile.download_url`?

### ISSUE THREAD

**Issue by davidxia** [PyGithub/PyGithub#575]
`ContentFile`'s corresponding API response has `download_url`. See https://developer.github.com/v3/repos/contents/#get-contents. Can we add this to `ContentFile`? Compare http://pygithub.readthedocs.io/en/latest/github_objects/ContentFile.html

**Comment by csidell-playq** [comment]
@sfdye Was this added or dropped?

**Comment by sfdye** [comment]
@csidell-playq It was added in ca6fbc4
