### ISSUE TITLE
Implement `__len__` (and/or `__bool__`) on PaginatedList

### ISSUE THREAD

**Issue by SylvainDe** [PyGithub/PyGithub#579]
From what I understand, there is no easy/efficient way to know if a PaginatedList is empty (and or to know the length of the list).
The best solution I have found is to try to access the first element and detect IndexError exceptions. This is what I have done in https://github.com/SylvainDe/CIthon/blob/master/cithon.py .
(A better looking - yet potentially inefficient - way to do it would be to create a list out of the PaginatedList and call bool/len from that list).

It is quite usual for container-like object to behave as True-ish object if and only if they are non-empty. This can be done by implementing the `__bool__` special method (or even easier to implement `__len__` and let the Python magic happens).

Would you reckon it would make sense and be possible to implement `__bool__` and/or `__len__` ? If that looks like a good idea, I do not mind trying to implement it myself if needed.

Python References:

- https://docs.python.org/3/reference/datamodel.html#object.__len__

- https://docs.python.org/3/reference/datamodel.html#object.__bool__

PyGithub References:

- doc : http://pygithub.readthedocs.io/en/latest/utilities.html#github.PaginatedList.PaginatedList

- code : https://github.com/PyGithub/PyGithub/blob/656e70e16d199232258d5ba0c3e9e126b1d7fa25/github/PaginatedList.py#L85

**Comment by ChiKenNeg** [comment]
Is there any progress with this?

**Comment by SylvainDe** [comment]
So far, I am just waiting for the opinion of the project owners before going any further.

@sfdye Do you reckon this is a valid issue that one could start working on ? I will not have much time in the next days but I guess this is not a critical/urgent issue.

**Comment by sfdye** [comment]
see #820

**Comment by SylvainDe** [comment]
https://github.com/PyGithub/PyGithub/issues/415 / https://github.com/PyGithub/PyGithub/issues/487

**Comment by sfdye** [comment]
Good news, this is done with the help of #820

**Comment by sfdye** [comment]
Unfortunately I have to re-open (reverted in 8a589c9d735eb815610aa0910cccc61f1842314a) this as this are some issues with the tests. Will definitely revisit and re-implement this later.

**Comment by sfdye** [comment]
Removing the stale label..
