### ISSUE TITLE
Delete/restore branch associated with a pull request

### ISSUE THREAD

**Issue by wrjohnson** [PyGithub/PyGithub#580]
GitHub Pull Request page provides a [Delete Branch] that invokes ..../pull/:number/cleanup

Need equivalent Pull Request methods to remove and/or restore the branch associated with the pull request

**Comment by wrjohnson** [comment]
With a little help from http://stackoverflow.com/questions/39065544/how-do-i-remove-all-stale-branches-from-github.   

One covoluted recipe to delete the branch for pull request "pr_num" is:
```
repo.get_git_ref( "heads/%s"%(repo.get_pull(pr_num).head.ref) ).delete()
```

**Comment by sfdye** [comment]
@wrjohnson This is very useful! Would you like to make an PR? I will be happy for review.

**Comment by austinsasko** [comment]
@sfdye is this issue still something that can be worked on/contributed to? If so, mind if I submit the work for the tests/code in a PR?

**Comment by sfdye** [comment]
@austinsasko Go for it!

**Comment by chouetz** [comment]
@sfdye this issue seems closed, could it be possible to close it?

**Comment by austinsasko** [comment]
The PR for this was never merged, is this expected? https://github.com/PyGithub/PyGithub/pull/1784
