### ISSUE TITLE
Can't access corporate github with SSL

### ISSUE THREAD

**Issue by mattroid** [PyGithub/PyGithub#583]
Our github is hosted on a server that causes a:
`SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)
`
Error. 

The api doesn't expose a way to not verify the ssl cert if I trust it.

**Comment by peymanmortazavi** [comment]
I have the same problem with github.com as well. I only get this issue in Django apps though.

**Comment by connaryscott** [comment]
Pretty sad for me too, i did this:

```
+
+        import ssl
+        context = ssl._create_unverified_context()
+        kwds["context"] = context
+
+
```  in github/Requester.py's  __createConnection(self):

and the last thing i want to hear is how unsafe it is.

**Comment by sivy** [comment]
Ditto, for our corporate Github Enterprise servers. Unlike `requests` for which you can pass `verify=False` for servers with self-signed certificates, PyGithub does not expose a way to do this. So I'm having to patch together my own api wrapper when I'd much rather use a well-maintained API.

**Comment by daniyalj** [comment]
Anyone found a solution for this issue?

**Comment by seenaomi** [comment]
Boo same issue..

**Comment by sfdye** [comment]
Sorry guys I don't have a Github enterprise that I can use to test. Anyone willing to make a PR I am more than happy to review. Meanwhile, will porting to `requests` solve this issue? See #664

**Comment by glennmatthews** [comment]
Can confirm that for my github enterprise, `pip install --pre PyGithub==1.40a1` (as suggested in #664) resolves this issue for me. 👍

**Comment by sfdye** [comment]
Nice! Can other confirm the same?

**Comment by sfdye** [comment]
Fixed in #758 thanks to the awesome `requests`.

Available NOW in version `1.40a3`:
`pip install pygithub --pre`

**Comment by sfdye** [comment]
Marking it as resolved for now.

**Comment by Marx314** [comment]
for anyone looking for a better method:
pip install python-certifi-win32

and if your project is run on linux and windows environnement 
requirements.txt
`python-certifi-win32;platform_system == 'Windows'`

**Comment by supersciencegrl** [comment]
Using `pip install --pre` and/or specifying the above versions doesn't help me for some reason. 

I haven't tried importing certificates... I plan to distribute this script as a PyInstaller .exe file so would have to bundle the certificate file with it. I'm not well-versed in security so don't know whether that's any sort of an issue or not. In my use case I have a workaround that doesn't involve searching Github from Python, so I'll continue to use that for now...
