### ISSUE TITLE
Caching HTTP requests to Github

### ISSUE THREAD

**Issue by ab9-er** [PyGithub/PyGithub#585]
Hi Guys,

I was wondering if there are means to have a cache for frequent HTTP requests to the Github API built in PyGithub. Otherwise I'll stick to a local cache server to help me out.

**Comment by JWCook** [comment]
There is an example of adding caching to PyGithub with [requests-cache](https://github.com/requests-cache/requests-cache) here:
https://requests-cache.readthedocs.io/en/stable/examples.html#pygithub

Direct link to script here:
https://github.com/requests-cache/requests-cache/blob/main/examples/pygithub.py
