### ISSUE TITLE
Add support for advanced branch protection APIs

### ISSUE THREAD

**Issue by harlowja** [PyGithub/PyGithub#586]
It seems like the following APIs exist in github v3 (as beta?) but are not yet reflected in this library.

- https://developer.github.com/v3/repos/branches/#get-pull-request-review-enforcement-of-protected-branch
- https://developer.github.com/v3/repos/branches/#update-pull-request-review-enforcement-of-protected-branch
- https://developer.github.com/v3/repos/branches/#get-admin-enforcement-of-protected-branch
- https://developer.github.com/v3/repos/branches/#get-restrictions-of-protected-branch
- and a few others....

It'd be great to have full support of this API (especially since it allows controlling PR reviews and how many are needed and by who).

**Comment by a13m** [comment]
@harlowja I did a little bit of this in https://github.com/a13m/PyGithub/commit/3af108372a5179e16fc093b78568c8e45a3a91ca

It was enough for me to at least audit our branch protections. YMMV.

**Comment by harlowja** [comment]
Ya, it'd be supernice to have something like that merged in (and released); this library seems to lag behind the actual API and/or capabilities, which makes me a little sad :-/

**Comment by harlowja** [comment]
Especially would like this since I've been trying to ensure all my github configuration for my group is in a yaml format, and not hidden away in the github UI, and then having a program that parses said yaml format and adjusts various github repositories. This creates continuity (and sanity) across my groups repositories and having the ability to programmatically adjust the reviewer protections would logically be something a team would want to do (so that the reviewer list can be controlled & managed via a similar yaml format).

**Comment by tomgoren** [comment]
Nice work @a13m!
Meanwhile: https://developer.github.com/changes/2017-09-06-protected-branches-preview-end/.

Looks like we're stuck until someone musters the energy to tackle this.

**Comment by s-t-e-v-e-n-k** [comment]
This is in fact a large mess. Repository.protect_branch() calls into an endpoint that has probably been removed, since GitHub blogged that it would be when Branch Protection graduated. I've been wondering why the API docs and the code are completely at odds with each other.

 I'm going to add a new method Repository.edit_branch_protection() to call the new endpoint with the new data structures, and I'm tempted to remove Repository.protect_branch() at the same time for being broken.

**Comment by JPWKU** [comment]
Hi folks, My patch is incomplete as yet but I thought it would be nice to have early feedback ^

**Comment by s-t-e-v-e-n-k** [comment]
I've also been working on this, approaching it in a different way -- by adding the methods to Branch, and dropping Repository.protect_branch()

**Comment by JPWKU** [comment]
@s-t-e-v-e-n-k ah I see that now.  Hmm don't want to duplicate work.  My intention was to keep the library api the same.  How do you want to go about it?

**Comment by JPWKU** [comment]
@s-t-e-v-e-n-k no worries, since you've already got work in this area I'll close my PR and comment/help out on yours.

**Comment by prburgu** [comment]
@s-t-e-v-e-n-k Do you plan to merge this soon? I'm in need of this functionality.

**Comment by s-t-e-v-e-n-k** [comment]
@prburgu It isn't up to me when it merges. @JPWKU when do you have some time to continue reviewing the attached PR?

**Comment by JPWKU** [comment]
@prburgu @s-t-e-v-e-n-k I'm gonna try to carve out time today or this evening to finish the review.

**Comment by rt-alex** [comment]
Any update on this?
