### ISSUE TITLE
Integration support does not work in python 3

### ISSUE THREAD

**Issue by impala2** [PyGithub/PyGithub#588]
The token (?) created by the jwt library is a `bytes` object in python 3 so instead of the header being `Authorization: Bearer kajshdkshkshkhd` it's `Authorization: Bearer b'kajshdkshkshkhd'`.

Need to update the function like so:

    def create_jwt(self):
        """
        Creates a signed JWT, valid for 60 seconds.
        :return:
        """
        now = int(time.time())
        payload = {
            "iat": now,
            "exp": now + 60,
            "iss": self.integration_id
        }
        encrypted = jwt.encode(
            payload,
            key=self.private_key,
            algorithm="RS256"
        )
        
        if atLeastPython3:
            encrypted = encrypted.decode('utf-8')
            
        return encrypted

I'd make a pull request, but I'm rather confused by how the tests are supposed to be written. To have deterministic results you'd need to mock `time.time()` and you don't seem to have it as part of your test dependencies (not in stdlib in python 2).

**Comment by jasonwhite** [comment]
Should be fixed in the next release.
