### ISSUE TITLE
API for Pull Request Checks?

### ISSUE THREAD

**Issue by grayaii** [PyGithub/PyGithub#594]
I'm trying to find a PR that has a **specific** failing check.

Is there a way to get information of the checks for a Pull Request?

Here is a screenshot:
![pr_check](https://user-images.githubusercontent.com/847072/28041211-d2edfcd0-65c8-11e7-8aaf-fa6463a0f5f6.jpg)

I didn't see anything obvious from the PR object:
```
g = Github("user", "password")
user = g.get_user()
org = g.get_organization('my_org')
repo = org.get_repo('myrepo')
for pr in repo.get_pulls():
    print(pr)
    for el in dir(pr):
        print(el)
    sys.exit()
```

**Comment by thewarpaint** [comment]
The way I understand it, in the API statuses belong to commits, not to PRs per se. Try getting the last commit in a PR, and then using http://pygithub.readthedocs.io/en/latest/github_objects/Commit.html#github.Commit.Commit.get_statuses.

**Comment by grayaii** [comment]
Cool. Good catch.  Feel free to close this badboy then!
Thanks for looking into this!

**Comment by grayaii** [comment]
One minor thing:  It looks like you can now POST to create/update statuses:
https://developer.github.com/v3/repos/statuses/#create-a-status
It would be great if PyGithub supported this :)

**Comment by sfdye** [comment]
@grayaii This is already there. You can use `Commit.create_status` method to create a status check for your PR. The trick however is you need to find the correct commit to create the status on.

This is what I did in one of my projects:
```
sha = pr.head.sha
repo.get_commit(sha=sha).create_status()
```
