### ISSUE TITLE
Wrong value for issue.closed_at

### ISSUE THREAD

**Issue by 1605200517** [PyGithub/PyGithub#600]
**Goal:** print issues of a repo, id and state.

**Code:**

```
from github import Github
g = Github("xxx", "yyyy")

for repo in g.get_organization("PyGithub").get_repos():
    print (repo.name)
    for issue in repo.get_issues():
        data = [repo.name , issue.id, issue.title, issue.state, issue.created_at, issue.closed_at]
        print (issue.id, issue.closed_at)
```

**Output:**
(for all issues in this repo!)

```
93819916 None
91127791 None
90858230 None

```
**Expected output:** open etc. for open issues.

**Comment by sfdye** [comment]
@1605200517 

This is expected as described in the docs:
https://developer.github.com/v3/issues/#parameters-1

If you wanna inspect the state of the issue, you should use `issue.state` property instead, the `closed_at` is `None` for open issues.
