### ISSUE TITLE
Add method to set permission level of an organization repository collaborator

### ISSUE THREAD

**Issue by rpocase** [PyGithub/PyGithub#604]
There is currently no method in PyGithub to set the permission level of a collaborator on a repository. 

At a minimum, the method `github.Repository.Repository.add_to_collaborators` should take an optional parameter `permission=str` to set the permission level of a collaborator. The current default appears to be `push`.

A new method to update a collaborators permission would also be helpful.

Relevent API reference: https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator

**Comment by jasonwhite** [comment]
Fixed in #699.
