### ISSUE TITLE
Working with projects?

### ISSUE THREAD

**Issue by isbm** [PyGithub/PyGithub#606]
Hi,
is there any way to list projects, its columns, add/remove stuff to the columns etc? I kind of can't find that...

**Comment by sfdye** [comment]
Project endpoint is not implemented yet. I am open for any PR.

**Comment by bbi-yggy** [comment]
For reference, these are the API's to be wrapped:
https://developer.github.com/v3/projects
https://developer.github.com/v3/projects/cards

Would also be nice to be able to get the project associated with a pull request, unfortunately that is not (currently) supported by the Github API v3.

**Comment by bbi-yggy** [comment]
I've started looking at this. Should have at least a preliminary pull request in the not too distant future.

**Comment by bbi-yggy** [comment]
Here's a pull request on my own fork to demonstrate what I've done so far. Needs more work (see "To Do" list) but is now functional.
https://github.com/bbi-yggy/PyGithub/pull/1

@sfdye Please let me know how this is looking. Does the overall approach and implementation seem ok? Am I sticking with PyGithub and python conventions to your satisfaction? (I'm a bit of a python noob, so bear with me ...)

**Comment by bbi-yggy** [comment]
BTW, can someone tell me how I can test my in-development version of PyGithub with other scripts I'm working on? Normally I "pip install PyGithub" and then python just knows where to find it.

Should I use "pip install --editable" as described [here](https://pip.pypa.io/en/stable/reference/pip_install/#options)?

**Comment by sfdye** [comment]
@bbi-yggy can you open your PR against PyGithub, not your fork?

**Comment by bbi-yggy** [comment]
@sfdye I planned to wrap up the "to do" items before opening up the PR against the main repo - if you prefer then I'm happy to the put the work-in-progress PR against main (just don't merge it yet!)

**Comment by bbi-yggy** [comment]
Pull request opened as #854.

**Comment by sfdye** [comment]
#854 is merged. For those who wanna try: `pip install pygithub==1.43.1`

**Comment by scjody** [comment]
Remaining work:
* [ ] [Create an organization project](https://developer.github.com/v3/projects/#create-an-organization-project)
* [ ] [Create a user project](https://developer.github.com/v3/projects/#create-a-user-project)
* [ ] [List user projects](https://developer.github.com/v3/projects/#list-user-projects)
* [ ] [Update a project](https://developer.github.com/v3/projects/#update-a-project)
* [ ] [Delete a project](https://developer.github.com/v3/projects/#delete-a-project)
* [ ] [Update a project card](https://developer.github.com/v3/projects/cards/#update-a-project-card) #1418

**Comment by s-t-e-v-e-n-k** [comment]
@scjody Looks lke org projects are it and we can mark this as closed?

**Comment by scjody** [comment]
Sounds good, that's great!
