### ISSUE TITLE
1.35 release is not tagged

### ISSUE THREAD

**Issue by sgleske-ias** [PyGithub/PyGithub#612]
I installed PyGithub from `pip` and noticed it was revision 1.35.  I went to look at GitHub tags and noticed this project has not tagged the 1.35 release.

**Comment by jasonwhite** [comment]
Looks like it was named [`1.35`](https://github.com/PyGithub/PyGithub/releases/tag/1.35) instead of `v1.35`.

I pushed up a `v1.35` tag to be consistent with the rest.
