### ISSUE TITLE
Unavalivable link

### ISSUE THREAD

**Issue by Armatorix** [PyGithub/PyGithub#617]
Don't know, if it's good place to post it, but two links from [this](http://pygithub.readthedocs.io/en/latest/introduction.html#what-next)  ("What next?") does not work.

**Comment by jasonwhite** [comment]
Looks like ReadTheDocs just needs to rebuild the documentation. Not sure why this hasn't happened yet.

**Comment by AnneTheAgile** [comment]
this should be closed, hopefully with a renamed ticketname, eg "Documentation page link not updated."
It works now.
