### ISSUE TITLE
A humble project to collect repos metrics

### ISSUE THREAD

**Issue by gomesfernanda** [PyGithub/PyGithub#636]
Hello! I have a small project that gathers metrics for repos on an organization, all using PyGithub.
It's under https://github.com/gomesfernanda/some-github-metrics

If it's pertinent, it could be on the documentation page under Projects using PyGithub

Thanks!

**Comment by AnneTheAgile** [comment]
lgtm, why don't you submit a PR to this page; https://github.com/PyGithub/PyGithub/blob/master/doc/introduction.rst
and reference this ticket as well so they can be merged/closed together?

**Comment by sfdye** [comment]
@gomesfernanda Merged!
