### ISSUE TITLE
Support for maintainer_can_modify arg with create_pull 

### ISSUE THREAD

**Issue by ruffsl** [PyGithub/PyGithub#639]
As defined in the github API, there is the ability to permit maintainer to modify the head branch for the PR: https://developer.github.com/v3/pulls/#create-a-pull-request

Currently, I don't see this defined:
https://github.com/PyGithub/PyGithub/blob/3437a7030f02a1648290db581621936eb5771b69/github/Repository.py#L983

**Comment by sfdye** [comment]
Closed in #703
