### ISSUE TITLE
push project to github

### ISSUE THREAD

**Issue by mmmce1994** [PyGithub/PyGithub#641]
hi every one
how to push a project from local to github repository using pygithub library ?
is there any sample code ?

**Comment by jasonwhite** [comment]
I don't think that is possible using only the GitHub API. It is possible to create a *new*, empty repository using [AuthenticatedUser.create_repo](http://pygithub.readthedocs.io/en/stable/github_objects/AuthenticatedUser.html#github.AuthenticatedUser.AuthenticatedUser.create_repo), then use Git itself to set the remote and push up an existing repository.

**Comment by ts0818** [comment]
Am I correct in understanding that the PyGitHub API does not have a git push function?
(In other words, the git push part needs to be implemented using something other than PyGitHub.)

**Comment by EnricoMi** [comment]
That is right, PyGithub is to be used to interact with the Github Web API, not a local Git repository. Git and Github are separate things. Github is a Web frontend for a Git server hosted by Github. PyGithub does not interact with Git infrastructure.

**Comment by ts0818** [comment]
@EnricoMi 

Thank you for your reply.
We understand.
