### ISSUE TITLE
Need to update the protected branch  to allow a team to have push access

### ISSUE THREAD

**Issue by anilchauhangit** [PyGithub/PyGithub#642]
I have a protected branch which has no push access to anyone. I want to update this to have a team with push access to this branch. I want to know the function name to be called to accomplish this.

**Comment by sfdye** [comment]
I believe it's this endpoint:
https://developer.github.com/v3/repos/branches/#add-team-restrictions-of-protected-branch

However currently this is not implemented yet, see #736 

Closing this as a duplicated, please see that other issue for updates!
