### ISSUE TITLE
Accept "page" argument in stargazer calls

### ISSUE THREAD

**Issue by alanbernstein** [PyGithub/PyGithub#652]
`get_stargazers` and `get_stargazers_with_dates` use endpoints that support the `page` parameter, but the functions don't accept it.

I'd be happy to submit a pull request, if someone could point me a place to get started.

**Comment by sfdye** [comment]
Hi @alanbernstein you don't need to implement the page parameter, it's a standard parametr for all endpoint that has pagination which is already implemented in this library at a `PaginatedList` class.
