### ISSUE TITLE
2FA failed in sample script

### ISSUE THREAD

**Issue by juhlee-microsoft** [PyGithub/PyGithub#656]
Can you fix for 2FA account?
from github import Github

# First create a Github instance:
g = Github("user", "password")

# Then play with your Github objects:
for repo in g.get_user().get_repos():
    print repo.name

**Comment by sfdye** [comment]
If you enabled 2FA (like myself), maybe using token to authenticate instead of username and password?

**Comment by bbi-yggy** [comment]
@sfdye is correct - token-based authentication works in conjunction with 2FA. Go to your GitHub profile, select Developer Settings on the left, then click Personal Access Tokens. You can generate a token and then use it in place of the password when connecting to the API.
https://github.com/settings/tokens
