### ISSUE TITLE
get_collaborators does not return permissions information on users

### ISSUE THREAD

**Issue by jmhossler** [PyGithub/PyGithub#659]
When accessing the rest API, I get back an attribute called "permissions". This information is very valuable, and it is missing when I call get_collaborators for a repository. Instead, I get back a list of NamedUser, which doesn't contain all the information I need.

**Comment by iraquitan** [comment]
working on it

**Comment by iraquitan** [comment]
#676

**Comment by jasonwhite** [comment]
Fixed in #676.
