### ISSUE TITLE
self._url is not a valid attribute

### ISSUE THREAD

**Issue by helloworld2003** [PyGithub/PyGithub#660]
(Pdb) for i in each_pull_request.get_reviews(): i.update()
*** AttributeError: 'PullRequestReview' object has no attribute '_url'
(Pdb)

**Comment by awesometim1** [comment]
<img width="562" alt="screen shot 2018-01-04 at 11 56 27 pm" src="https://user-images.githubusercontent.com/25408591/34596087-fe86ddb2-f1aa-11e7-8cf1-46da3eab09fb.png">

I was not able to replicate the error. Could you specify the conditions that caused the error?

**Comment by jasonwhite** [comment]
Although not very intuitive, this error usually indicates a permissions problem on the API credentials.
