### ISSUE TITLE
Downloading large files

### ISSUE THREAD

**Issue by psychemedia** [PyGithub/PyGithub#661]
Using the `.get_contents()` method to try to download a large file raises the error:

```
{'errors': [{'code': 'too_large', 'field': 'data',
     'resource': 'Blob'}],
     'message': 'This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.',
     'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents'}
```

Is there a way of detecting this and passing over to another handler that *can* download the file?

For example, if something like this fails:
```
contents = repository.get_dir_contents(urllib.parse.quote(server_path), ref=sha)

for content in contents:
   if content.type != 'dir':
     file_content = repository.get_contents(urllib.parse.quote(content.path), ref=sha)
```

optionally revert to:

```
file_content = repository.get_git_blob(content.sha)
```

**Comment by jasonwhite** [comment]
I've run into this problem before too. In my case, since I always had the SHA of the blob, I just used `git_git_blob` instead.

However, `get_git_blob` doesn't work for any object type besides `blob` (hence the name). You need to know the type of the object before attempting to call it.

To do the fallback, you need to know two pieces of information:
 1. The type of the object.
 2. The SHA of the object.

If `get_contents` fails, it doesn't tell you either of these things. There isn't really any good way of doing the fallback as far as I can tell.

**Comment by jasonwhite** [comment]
Closed as `wontfix`. If anyone has a good idea on how to solve this, I'm happy to reopen. As far as I can tell, it doesn't look like it's possible to do in a clean way.

**Comment by BoPeng** [comment]
I have the same problem and end up doing something along the line of

```
    file_content = repo.get_contents(path_name, ref=branch)
    try:
        if file_content.encoding != 'base64':
            # some error ...
        # ok... 
    except GithubException:
        # if file_content DOES NOT HAVE encoding, it is a large file 
        blob = repo.get_git_blob(file_content.sha)
        # do something with blob
```

Basically the `sha` value is already in `file_content` if the content is too big, so the fall-back call is pretty simple. I do not understand why @jasonwhite said "There isn't really any good way of doing the fallback as far as I can tell."

**Comment by eeechoo** [comment]
When get the blob, following code will be useful.

```python
    blob = repo.get_git_blob(sha[0])
    b64 = base64.b64decode(blob.content)
    return b64.decode("utf8")
```

**Comment by bhushanladdad** [comment]
raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-repository-content"} getting this error when trying to download a got repository files for master branch

**Comment by deed02392** [comment]
> Also, update file will also encounter with this problem.

https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#create-or-update-file-contents

Doesn't look like it affects update file – there's no distinction for different file sizes when updating file contents mentioned on the REST API, and I'm able to update the contents of files when they are >1MB.
