### ISSUE TITLE
Maintenance of this project

### ISSUE THREAD

**Issue by jasonwhite** [PyGithub/PyGithub#663]
@adamtheturtle @jacquev6 @JPWKU @jayfk @jzelinskie @MichaelPereira @nhomar 

Hello! First of all, *thank you* for this project. It has saved me (and many others) a ton of time.

Unfortunately, this project hasn't received much love for over 5 months. Pull requests have been sitting in the queue untouched. I've had to work around many bugs that would have been fixed by some merged pull requests. I understand that it's tough to keep up with these mundane things, but as the GitHub API evolves so must this wrapper.

I'd be happy to help out with maintaining this project. I'm a ruthless code reviewer, I have an interest in keeping this up-to-date, and I'd really prefer not to maintain my own fork of this. Thanks in advance!

**Comment by jayfk** [comment]
Yup, we need more people looking at pull requests. I've added you as a collaborator.

**Comment by jasonwhite** [comment]
@jayfk Thanks!

**Comment by jasonwhite** [comment]
@jayfk It seems I wasn't given write access. There's not much I can do without that.

**Comment by jayfk** [comment]
Have you accepted the invite? You are still showing up as "awaiting response".

<img width="739" alt="screen shot 2017-11-22 at 21 21 11" src="https://user-images.githubusercontent.com/2930472/33148203-34af3738-cfcb-11e7-95dc-9ba81ad680fd.png">

**Comment by jasonwhite** [comment]
Oopsie. Didn't see that. I'm off to a great start. Thanks again!
