### ISSUE TITLE
Repo hooks api not working

### ISSUE THREAD

**Issue by sfdye** [PyGithub/PyGithub#666]
```
from github import Github
g = Github()
assert len(list(g.get_repo('PyGithub/PyGithub').get_hooks())) == 0
```

Running this will encounter 
> github.GithubException.UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/hooks/#list-hooks'}

I am just taking `PyGithub` as an example, it doesn't work for all repos, including public and private repos.

Same for all the repo hooks api, like `create_hook` and `get_hook`.

I just checked GitHub v3 repo hooks api:
https://developer.github.com/v3/repos/hooks/

It seems there is an additional attribute `ping_url` and this repo is not updated for it. Not sure if this is the cause or some other changes I am not aware of.

**Comment by MisterBianco** [comment]
Just so you know this is issue #666, just thought that was pretty cool.

**Comment by sfdye** [comment]
Seems to be a permission issue, I initialied with a token which does not have the create_hook scope.

```
g = Github(access_token)
```
change to username and password:
```
g = Github(username, password)
```
or 
```
g = Github(access_token) # with the correct scope, which you can specify when creating a personal token
```
fixed it.
