### ISSUE TITLE
Organization webhooks support?

### ISSUE THREAD

**Issue by turly221** [PyGithub/PyGithub#680]
Hi,

Does it support organization webhook to listen to repository delete event?

**Comment by sfdye** [comment]
See https://github.com/PyGithub/PyGithub/issues/324

**Comment by sfdye** [comment]
@turly221 A PR would be much appreciated.

**Comment by namratachaudhary** [comment]
Taking this up.

**Comment by sfdye** [comment]
@namratachaudhary any update on this?

**Comment by namratachaudhary** [comment]
Writing tests for the same. A little stalled. Will try to raise a PR in couple of days
