### ISSUE TITLE
Unable to use get_issues() passing labels parameter

### ISSUE THREAD

**Issue by possebon** [PyGithub/PyGithub#683]
I'm trying to use this:

`repo = ghub.get_user().get_repo('myrepo')
 repo.get_issues(state='open',sort='created',direction='asc',labels=['faq'])`

When I do that I'm getting this error message:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/github/Repository.py", line 1649, in get_issues
    assert labels is github.GithubObject.NotSet or all(isinstance(element, github.Label.Label) for element in labels), labels
AssertionError: ['faq']`

I also tried this way:

`repo.get_issues(state='open',sort='created',direction='asc',labels='faq')`

Same error message.

I'm using the PyGithub 1.35 version and Python 3.6.2

**Comment by sfdye** [comment]
Hi @possebon the label parameter is expecting a list of `github.Label` type, not a string. So you can do something like:

```
label = repo.get_label('faq')
repo.get_issues(state='open',sort='created',direction='asc',labels=[label])
```

**Comment by vlerenc** [comment]
@sfdye How would you do that with orgs, please? Repos have labels, but orgs have not and the API is the same. I also can't create a label by name.
