### ISSUE TITLE
Is there a way to login using a Deploy Key?

### ISSUE THREAD

**Issue by skjerns** [PyGithub/PyGithub#685]
I want to access Issues and PRs from a private repository, without making an account a collaborator (granting it push rights). One such way would be a Deploy Key.

Is is possible to login using PyGithub using a Deploy Key?

**Comment by sfdye** [comment]
@skjerns Can you please elaborate on your use case? I don't feel deploy key is suitable for this use. Normally it's granting you read/white access to the repo code. You will want to use either OAuth or a personal access token.

**Comment by skjerns** [comment]
@sfdye it is possible to use a `read-only` deploykey https://github.com/blog/2024-read-only-deploy-keys

I wanted to use this key to have safe access to a repo I'm working on. The advantage is that I do not have to create an own account for this.

For now I have settled on using an additional Github account that has limited rights to the repo and that works as well, so for me the issue is resolved. For some operations (setting git-status) I have to have write access anyway, so I indeed started using `OAuth` keys. For me the issue is therefore no longer relevant! Thanks!

**Comment by sfdye** [comment]
@skjerns Great to hear your issue is resolved now.

**Comment by ryan-williams** [comment]
I thought I had the same need (to authenticate with a deploy key); [this SO](https://stackoverflow.com/questions/69227780/how-can-i-use-deploy-key-for-authentication-to-use-github-api) clarified:

> You cannot use a deploy key to access the GitHub API. Deploy keys are SSH keys, and they allow access only over SSH. The GitHub API operates only over HTTPS, and so you'll be unable to authenticate with a deploy key.
>
> You can either use a personal access token or some other sort of OAuth token to access the GitHub API. GitHub documents various methods of authentication you can use and how they work.
