### ISSUE TITLE
name 'unicode' is not defined error

### ISSUE THREAD

**Issue by MattPhillips1** [PyGithub/PyGithub#694]
The `asserts` that check against `(str, unicode)` throw the above exception when using python3
e.g
`assert description is github.GithubObject.NotSet or isinstance(description, (str, unicode)), description` when creating a repo for an organisation.

**Comment by labrys** [comment]
@MattPhillips1 contrary to the README stating the package is PY3 compatible, it is not.  It will be if #705 gets merged.  In the meantime if you would like to assist me in PY3 testing, check out the develop branch of my fork.
