### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sfdye** [PyGithub/PyGithub#696]
It's been some time since the last release. I don't really want my project to depend on the master. Who needs it too?

**Comment by modrzew** [comment]
:+1: to that. Most recent changes to the Review Requests API broke one part of our application, and ideally we'd want to fix it with just bumping the version in our `requirements.txt`.

**Comment by jasonwhite** [comment]
A release? Yes! A release! Yup. It's time for a release.

@jayfk Can you give me access to upload releases to PyPI? (My username is `jasonwhite0`.)

**Comment by jayfk** [comment]
Can’t do that as I don’t have the permissions. 

In order to issue a new release, simply tag it and push the tags to github. If all tests are passing, travis will deploy the package to pypi.

**Comment by jasonwhite** [comment]
Thanks. Releasing is easier than I thought.

**Comment by sfdye** [comment]
Also @jayfk @jacquev6 is this repo still seeking active maintainership? I can help with things like triage issues/PR and cut releases.

**Comment by jasonwhite** [comment]
@sfdye I would love some help. I have a hard time keeping up with it.

I just published a new release (v1.36). There was quite a bundle of changes in this one.

(For future reference, publishing a release is as easy as `./manage.sh publish`.)

**Comment by sfdye** [comment]
@jasonwhite Thanks for the release, already bumped my version. You will get the help from me for future releases 😄

**Comment by jayfk** [comment]
Yeah, welcome @sfdye!

**Comment by sfdye** [comment]
@jayfk Thanks for the invite!
