### ISSUE TITLE
No exception raised for trying to make public fork private?

### ISSUE THREAD

**Issue by tsiq-acheung** [PyGithub/PyGithub#700]
Using the GitHub API I received a 422 when trying to privatize a public fork, but when doing so with PyGithub client it responds with no error (and no change to repository private status).  This was done with an organization.

To reproduce:
```
repo = github_client.get_organization(org_name).get_repo("name-of-public-fork")
repo.edit(private=True)
bool(repo.private) is True
False
```

**Comment by sfdye** [comment]
It's probably a bug, as public forks can’t be made private. We should provide the correct response code in the sense. A PR to fix will be welcomed.

**Comment by sfdye** [comment]
@tsiq-acheung I tried to reproduce this but I only got a 404 from both calling API and using this library.

**Comment by tsiq-acheung** [comment]
@sfdye I ageee a 404 is good enough, I’ll give it another shot and close this out if so.

The repo was only temporary as its under the organization, but if I have another successful test I’ll leave it up to confirm.

**Comment by tsiq-acheung** [comment]
Looks to be the same, but maybe it's a GitHub problem and not PyGithub. After stepping into the `repo.edit()` I get to `__requestRaw()` in Requester.py with these arguments:
`verb: 'PATCH', url: '/repos/tsiq/acheung-test-repo-1', input: '{"name": "acheung-test-repo-1", "private": true}'`

Then after `cnx.getresponse()` I have a response status of 200, so nothing is thrown when it goes up the stack.

Maybe I'm doing something incorrectly? I would expect at this point to get the 422 from GitHub.

**Comment by sfdye** [comment]
@tsiq-acheung 

From https://developer.github.com/v3/repos/#edit
> Either true to make the repository private or false to make it public. Creating private repositories requires a paid GitHub account. Default: false.
Note: You will get a 422 error if the organization restricts changing repository visibility to organization owners and a non-owner tries to change the value of private.

It looks like this constraint only applies for a repo under a organization, since you are always the owner of your own repo, so you should be able to change the visibility of your repo too.

**Comment by sfdye** [comment]
@acheung456 This will give me a 404. Maybe add me as a non-owner member and I will try again.
