### ISSUE TITLE
Get list of protected branches

### ISSUE THREAD

**Issue by daniyalj** [PyGithub/PyGithub#708]
:wave: 

I am doing an audit of list of protected branches in my organization. Is there any way to accomplish this?

Here's what I have so far

```
g = Github(access_token, base_url='<github-enterprise-url>/api/v3')
for repo in g.get_organization('orgName').get_repos():
    print (repo.name)

for branch in g.get_organization('orgName').get_repo('puppet').get_branches():
    print (branch)
```

I am able to get a list of my branches in specific repos. Is there any function within PyGitHub to get the protection? I dont see it in the docs

**Comment by res0nance** [comment]
https://github.com/PyGithub/PyGithub/blob/0e5a1d1d53853153863ca8e446e00c71e6eaaa45/github/Branch.py#L57

The branch object has a property protected which should fit your needs.

**Comment by daniyalj** [comment]
@res0nance How do I use this in my current script? I don't see any documentation about this

**Comment by res0nance** [comment]
`protected_branches = []
for branch in g.get_organization('orgName').get_repo('puppet').get_branches():
    if branch.protected:
        protected_branches.append(branch)`

I've not tested this but from how the code looks i would think this would be the right answer since get_branches returns a paginatedlist of branch objects

**Comment by daniyalj** [comment]
Thanks for your help @res0nance !

But I'm getting Branch has no attribute '_protected'

```
AttributeError: 'Branch' object has no attribute '_protected'
```

Looking at the documentation and I don't see anything for protected http://pygithub.readthedocs.io/en/latest/github_objects/Branch.html

**Comment by res0nance** [comment]
According to https://developer.github.com/v3/repos/branches/#list-branches
it does return the protected flag I'm unsure of why the attribute does not exist which according to the code implies the protected field was not returned. Ill look into this when I have the time.

The documentation looks outdated the changelog was last updated in 2014

**Comment by res0nance** [comment]
@daniyalj I have no idea why github's api doesnt seem to return the protection status but I can offer a workaround.
```
repo = g.get_organization('orgName').get_repo('puppet')
protected_branches = []
for branch in repo.get_branches():
    b = repo.get_branch(branch.name)
    if b.protected:
        protected_branches.append(b)
```
From what i see get_branch seems to get the protection status while get_branches does not

**Comment by daniyalj** [comment]
@res0nance I greatly appreciate the help!

I'm trying the snippet  you posted above. I have two branches in my puppet repository and theyre both protected. Printing `protected_branches.append(b)` returns "None" for both of them which is weird.

```
g = Github(access_token, base_url='<github-enterprise-url>/api/v3')
repo = g.get_organization('orgName').get_repo('puppet')
protected_branches = []
for branch in repo.get_branches():
    b = repo.get_branch(branch.name)
    if b.protected:
        print(protected_branches.append(b))
```

**Comment by res0nance** [comment]
@daniyalj
Ahh if I misunderstood i thought you needed it as a list object if all you needed to do was to print it, it will be

```
g = Github(access_token, base_url='<github-enterprise-url>/api/v3')
repo = g.get_organization('orgName').get_repo('puppet')
for branch in repo.get_branches():
    b = repo.get_branch(branch.name)
    if b.protected:
        print(b) #this has a lot of information
        print(b.name) # only gets the name
```

In my above example the list of protected branches is protected_branches at the end of the code.

I have contacted github and it seems that protection information is only returned from the branches endpoint when the protected=true param is passed.

**Comment by daniyalj** [comment]
Thank you @res0nance that works!

Much appreciated!

**Comment by gatsbyz** [comment]
thank you and god bless you for this thread. i love you all

**Comment by CsBigDataHub** [comment]
```
g = Github(access_token, base_url='<github-enterprise-url>/api/v3')
repo = g.get_organization('orgName').get_repo('puppet')
protected_branches = []
for branch in repo.get_branches():
    if branch.protected:
        print(branch) #this has a lot of information
        print(branch.name) # only gets the name
        protected_branches.append(branch.name)
```

This will work as well, you do not need to call ` b = repo.get_branch(branch.name)` again.
