### ISSUE TITLE
Why does Branches endpoint only return name?

### ISSUE THREAD

**Issue by daniyalj** [PyGithub/PyGithub#710]
## Summary

Branches endpoint only returns the name of the Branches.

## Issue

I am getting a list of Branches in my repositories, but it seems to be only returning the name of the branches instead of the plethora information provided by the API https://developer.github.com/v3/repos/branches/#get-branch

## Code
```
for branch in g.get_organization('orgName').get_repo('repoName').get_branches():
    print (branch) 
```
## Actual output
```
Branch(name="dev")
Branch(name="master")
```

## Expected output

Something similar to the JSON here https://developer.github.com/v3/repos/branches/#get-branch

How would I go about this if, as an example, I want to get the author of the branch?

**Comment by sfdye** [comment]
This is only the string representation of the actual object.

To see all available attributes:
`print(dir(branch))`

You should be able to access a whole range of attributes like `branch.protected`.

**Comment by sfdye** [comment]
What do you need exactly?
