### ISSUE TITLE
Organization Outside Collaborators

### ISSUE THREAD

**Issue by timball** [PyGithub/PyGithub#715]
https://developer.github.com/v3/orgs/outside_collaborators/

There is no matching method for this in PyGithub. I need this to make a chatops bot that polls who in an org has 2fa enabled. 

--timball

**Comment by sfdye** [comment]
You are right, this is not supported yet. We need a PR for it.

**Comment by res0nance** [comment]
I've attempted to implement them here but have yet to test any of it or start on its unit tests.

https://github.com/res0nance/PyGithub/tree/feature/outside_collaborators

**Comment by sfdye** [comment]
@res0nance Nice! I am waiting for your PR.

**Comment by sfdye** [comment]
@res0nance @timball I just realized #533 will fix it.

**Comment by res0nance** [comment]
@sfdye no worries my branch still implements the remaining 2 functions we should still merge the other PR if it has no conflicts and look at the remaining PRs there could be more API updates hidden in there.

**Comment by sfdye** [comment]
@res0nance Okay then, still waiting for your PR 😄

**Comment by timball** [comment]
this is very exciting thank you

**Comment by res0nance** [comment]
When I found out @jappievw was working on it I stopped work on mine.

**Comment by jappievw** [comment]
Yeah, will process the feedback in the PR tonight!
