### ISSUE TITLE
Add a way to get a list of all public repositories on github

### ISSUE THREAD

**Issue by moijes12** [PyGithub/PyGithub#723]
How do we find the list of all repositories in github. 

Using the command line it is possible, see https://developer.github.com/v3/repos/#list-all-public-repositories

I am not able to do it with pygithub

**Comment by sfdye** [comment]
Yes, you can do it with PyGithub with `get_repos()`:
http://pygithub.readthedocs.io/en/latest/github.html#github.MainClass.Github.get_repos
