### ISSUE TITLE
github.search_repositories returned empty with combined queries

### ISSUE THREAD

**Issue by zhangysh1995** [PyGithub/PyGithub#730]
**Expected behavior:**
`results = g.search_repositories(query) ` returns correct results for `q=topic:cmake+language:cpp`

**Error behavior:**
None results received.

**Expected url**:
`https://api.github.com/search/repositories?q=topic:cmake+language:cpp`

**Code:**
``` Python
query = 'topic:cmake+language:cpp'
results = g.search_repositories(query)
for repo in results.get_page(1):
	print(repo.name)
```
**Result:** 
`none output`

**Notes:**
Here is the code that works:
```` Python
query = 'topic:cmake'
results = g.search_repositories(query)
for repo in results.get_page(1):
	print(repo.name)
````

**======= update =======**
with fix `topic:cmake+language:cpp` to `topic:cmake language:cpp` the code works.

**Could you please add example usage to the doc?**

**Comment by sfdye** [comment]
@zhangysh1995 We don't have a section on the documentation itself on code examples as of now.

Feel free to checkout this [repo](https://github.com/sks444/Pygithub-Examples) and contribute.
