### ISSUE TITLE
Branch Protection calls missing

### ISSUE THREAD

**Issue by kbessas** [PyGithub/PyGithub#736]
I believe these are still missing:

https://developer.github.com/v3/repos/branches/#get-branch-protection
https://developer.github.com/v3/repos/branches/#update-branch-protection
https://developer.github.com/v3/repos/branches/#remove-branch-protection
https://developer.github.com/v3/repos/branches/#get-required-status-checks-of-protected-branch
https://developer.github.com/v3/repos/branches/#update-required-status-checks-of-protected-branch
https://developer.github.com/v3/repos/branches/#remove-required-status-checks-of-protected-branch

Anyone willing to create a pr for these?

**Comment by sfdye** [comment]
Link to #527

**Comment by sfdye** [comment]
Closing this as a duplicate of #586
