### ISSUE TITLE
Add support for searching topics

### ISSUE THREAD

**Issue by edanhauon** [PyGithub/PyGithub#744]
Searching by topic is a feature offered in the beta version of the API.  We need this feature in order to collect data about repositories from a topic point of view.

[Searching Topics](https://help.github.com/articles/searching-topics/)
[Searching Topics by API](https://developer.github.com/v3/search/#search-topics)

Example of use:
```
g = Github()
# will return all machine-learning related topics
topics = g.search_topics(query=machine-learning) 

for topic in topics:
    print(topic.display_name)
    print(topic.featured)
    print(topic.curated)
```

**Comment by sfdye** [comment]
@edanhauon Thanks for reporting. If you can put in a PR I will be willing to review it.
