### ISSUE TITLE
Missing zipball_url and tarball_url in python 3

### ISSUE THREAD

**Issue by bushig** [PyGithub/PyGithub#745]
I am using PyGithub version 1.38 and I am doing the following:
```python
from github import Github

repo_name = 'godotengine/godot'
github = Github(TOKEN)
repo = github.get_repo(repo_name)
releases = repo.get_releases()
for release in releases:
    print(release.zipball_url)
```
gives me 'GitRelease' object has no attribute 'zipball_url'. This problem is valid for python 3.6 and 3.5. On python 2.7 works just fine

**Comment by sfdye** [comment]
This was fixed #522, so update PyGithub to the latest version 1.39 will do.
