### ISSUE TITLE
get_latest_release() returns error 404 if there is only one release

### ISSUE THREAD

**Issue by stsdc** [PyGithub/PyGithub#750]
from github import Github

    gh = Github()

    organization = gh.get_organization("PyGithub")
    # organization = gh.get_organization("TurtleRover")
    repository = organization.get_repo("PyGithub")
    # repository = organization.get_repo("Turtle-Rover-Mission-Control")
    latest = repository.get_latest_release()

    print (latest.tarball_url)

**Comment by stsdc** [comment]
@sfdye updated. When using PyGithub repo everything is ok.

**Comment by sfdye** [comment]
This is not a PyGithub issue. I tried calling the API directly also returns 404.

https://developer.github.com/v3/repos/releases/#get-the-latest-release
> View the latest published full release for the repository. Draft releases and prereleases are not returned by this endpoint.

This endpoint only returns full release, maybe your repo only has pre-release?

**Comment by stsdc** [comment]
Yes, it is a prerelease, but shouldn't it return all releases? even prereleases?
also this works for me: https://api.github.com/repos/TurtleRover/Turtle-Rover-Mission-Control/releases
or I'm using API in wrong way

**Comment by stsdc** [comment]
You're right.

**Comment by sfdye** [comment]
@stsdc no problem
