### ISSUE TITLE
How can I delete all releases of a repository?

### ISSUE THREAD

**Issue by CapitanLiteral** [PyGithub/PyGithub#751]
I want to delete all releases but I dont know how to, I've been looking in docs but didint found how to.

Thanks.

**Comment by sfdye** [comment]
Here you go
```
g = Github()
repo = g.get_repo('yourname/repo') 
for release in repo.get_releases():
	release.delete_release()
```

**Comment by CapitanLiteral** [comment]
Sorry, but probably I'm missundertanding something. I want to delete tags too and I dont know how.

Thanks for your support.
