### ISSUE TITLE
For the new "requests" communications engine, implement a developer controlled retry feature.

### ISSUE THREAD

**Issue by allevin** [PyGithub/PyGithub#757]
Reference comments in #539, conversation moved to this issue for discussion.

Request a feature to the new **_requests_** implementation for low level communications to implement a developer controlled retry feature when communication POST/GET fail.

The feature should allow the developer via a high level interface to control retry operations (number of retrys, time between retrys, etc.).  

Our network is behind an aggressive proxy server/filter and we occasionally lose responses from Github. This causes comm exceptions that could be avoided if the low level code would just perform an (optional - user configured) retry.

**Comment by mfonville** [comment]
Indeed a controlled retry would be very welcome. Today I hit on the Github API (without any proxy or such) a 502 error on a trivial operation, but it would be ridiculous to try to catch those for literally API command I execute in my program:

```
  File "/home/maarten/Development/PyGithub/build/lib/github/Repository.py", line 1317, in get_commit
    self.url + "/commits/" + sha
  File "/home/maarten/Development/PyGithub/build/lib/github/Requester.py", line 258, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/home/maarten/Development/PyGithub/build/lib/github/Requester.py", line 269, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 502 {'message': 'Server Error'}
```

**Comment by mfonville** [comment]
See https://github.com/PyGithub/PyGithub/pull/803 to at least cover the retries on commands that failed on Github's side
