### ISSUE TITLE
Please handle unexpected response codes, particularly 302

### ISSUE THREAD

**Issue by time4tea** [PyGithub/PyGithub#769]
When using github enterprise, if the base_url is specified without the /api/v3 then very strange things happen, and it is hard to debug wht is happening.

What is happening is that a 302 page is being returned, which is full of HTML, and the library accepts this, returning various objects full of None.

**Comment by sfdye** [comment]
I believe the correct format for `base_url` is `http(s)://hostname/api/v3/
`, why would you set it without the `api/v3`?

https://developer.github.com/v3/enterprise/#endpoint-urls

**Comment by sfdye** [comment]
I agree, took me a while to find out as well. Good news is I now have a GHE instance to play with. Will improve the documentation on Github enterprise first 😀

**Comment by sfdye** [comment]
Closed in #de6c2ec4e

**Comment by time4tea** [comment]
that was fast!
