### ISSUE TITLE
repo.stargazers_count and repo.watchers_count is the same number of stars

### ISSUE THREAD

**Issue by hren-ron** [PyGithub/PyGithub#770]
I get the same number which is the number of stars from repo.stargazers_count and repo.watchers_count,  i    can't get the number of watchers. In the API of Github, we can get the number from the "subscribers_count‘’，but in PyGithub, i find there is not the function.

**Comment by sfdye** [comment]
Which pygithub version are you using? I believe this attribute is in already in the master, so it should be available to you.

**Comment by sfdye** [comment]
Yes, try latest stable version 1.39

**Comment by sfdye** [comment]
Closing, feel free to re-open if still an issue.

**Comment by hren-ron** [comment]
I have solved it using the latest version

**Comment by sfdye** [comment]
Good to hear
