### ISSUE TITLE
Support for listing a user's repository invitations

### ISSUE THREAD

**Issue by BarbourSmith** [PyGithub/PyGithub#777]
There does not seem to currently be support for listing a users currently open invitations to join a repository as described here:

https://developer.github.com/v3/repos/invitations/#list-invitations-for-a-repository

The invitation object exists:
http://pygithub.readthedocs.io/en/latest/github_objects/Invitation.html#github.Invitation.Invitation

and there is a method to accept an invitation:

http://pygithub.readthedocs.io/en/latest/github_objects/AuthenticatedUser.html#github.AuthenticatedUser.AuthenticatedUser.accept_invitation

but there does not seem to be a way to list which invitations are available to be accepted.

**Comment by sfdye** [comment]
This would be awesome. If you have the time to put up a PR, I will be happy review.

**Comment by BarbourSmith** [comment]
Great, I'm going to close the issue because it's really more of a feature request and I will add this to my todo list.

Thanks!

**Comment by jeffbcit** [comment]
Hi,

I am a marker for 100 students per term, and really need this feature. I found this thread, and just want to post how I did it here: 
(Note: I used a while loop until no new invitations can be found. I print their repo paths to clone later, and accept the invitations.)

`
import sys
import requests

from github import Github

def main():
	user = "user"
	pwd = "password"
	# using username and password
	g = Github(user, pwd)
	url = "https://api.github.com/user/repository_invitations"
	while 1:
		req = requests.get(url, auth=(user, pwd))
		mInv = req.json()
		if not mInv:
			break
		for md in mInv:
			mGit = md['repository']['html_url']
			print (mGit)
			g.get_user().accept_invitation(md['id'])

if __name__  == '__main__':
    sys.exit(main())
`

**Comment by s-t-e-v-e-n-k** [comment]
This is a duplicate of #1120, and was fixed in v1.43.8.

**Comment by flying-sheep** [comment]
This is not closed, there’s no call wrapping the `/user/repository_invitations` API.

**Comment by s-t-e-v-e-n-k** [comment]
Uh, yes there is?

https://pygithub.readthedocs.io/en/latest/github_objects/AuthenticatedUser.html#github.AuthenticatedUser.AuthenticatedUser.get_invitations

**Comment by flying-sheep** [comment]
Huh! I’m sorry then, I really thought I had searched for this exhaustively.
