### ISSUE TITLE
update_file doesn't add the trailing slash after contents

### ISSUE THREAD

**Issue by shane-gearon-hs** [PyGithub/PyGithub#786]
The path variable should be preceded by a forward slash to create a valid url for the PUT call.

Steps to Reproduce:
github.get_repo("my_repo").update_file("README.md", "Updating readme.", base64.b64encode(content), sha)

Result:
https://github.com/api/v3/repos/my_repo/contentsREADME.md

Expected Result:
https://github.com/api/v3/repos/my_repo/contents/README.md

Looks like it's happening here.
https://github.com/PyGithub/PyGithub/blob/master/github/Repository.py#L1504

**Comment by sfdye** [comment]
It seems for some historical reasons, the path has to include the `/` (although it's contradictory to the API). Also you don't need to encode the content, this library does it for you.

So this:
`github.get_repo("my_repo").update_file("/README.md", "Updating readme.", content, sha)` should work.

**Comment by mfonville** [comment]
I think it might be practical to harden PyGithub a bit, and try to detect if a `path` value starts with a `/`, and either reject any input that does not start with a `/` or to add it to the start of the string internally within PyGithub.

**Comment by mfonville** [comment]
Pity stale bot closed this issue. I think the least we should do is add an assert that checks if the first character is `/` in the method.

**Comment by sfdye** [comment]
@mfonville this is a great idea.
