### ISSUE TITLE
create PullRequest between forked repo to original

### ISSUE THREAD

**Issue by Chrislevi** [PyGithub/PyGithub#792]
is there a method to create a pull request with the original repo as the base and a forked branch as the head? 

I tried this line, but it threw a 'Validation Error'
`repo.create_pull("Title", "Body", '{}:{}'.format(original_repo, master), '{}:{}'.format(forked_user, feature), True)`

**Comment by mfonville** [comment]
I think the way you wanted this, it's not possible when reading the API at https://developer.github.com/v3/pulls/#input for the `base` you can only pass a branch of the repository you are creating the PR on.

So you can only do:
```python
original_repo.create_pull("Title", "Body", '{}:{}'.format(master), '{}:{}'.format(forked_user, feature), True)
```

**Comment by evandrocoan** [comment]
Just clarifying, I tried this and ended up backwards.

From fork `evandroforks` to upstream `tox-dev`:
```python
upstream_user = github_api.get_user('tox-dev')
upstream_repo = upstream_user.get_repo('tox')

upstream_pullrequest = upstream_repo.create_pull("Title", "Body", 'master', 
          '{}:{}'.format('evandroforks', 'master'), True)
```

From upstream `tox-dev` to fork `evandroforks`:
```python
fork_user = github_api.get_user('evandroforks')
fork_repo = fork_user.get_repo('tox')

fork_pullrequest = fork_repo.create_pull("Title", "Body", 'master', 
          '{}:{}'.format('tox-dev', 'master'), False)
```

**Comment by edwardchalstrey1** [comment]
Can this issue be reopened? It would be a nice feature to have

**Comment by evandrocoan** [comment]
@edwardchalstrey1 , I am already using to create pull-requests from my forks the original repositories. here is the code: https://github.com/evandrocoan/githubpullrequests/blob/61e583f2247d252633d7a17f3345acadaf707dd6/source/githubpullrequests/__init__.py#L359

This is an example pull-request created with it: https://github.com/evandroforks/vscode-textmate/pull/2

Perhaps you are trying to do something else?
