### ISSUE TITLE
`pip install pygithub` failing

### ISSUE THREAD

**Issue by zkurtz** [PyGithub/PyGithub#800]
The command runs with no warnings, but `import github` subsequently complains that there is no such module.

By contrast, cloning and installing as `python setup.py develop` works fine. But it would be nice to be able to skip the cloning step.

I'm on OSX 10.13.04.

**Comment by eamanu** [comment]
what is the version of  your pip?

**Comment by zkurtz** [comment]
Must have been old. Everything is working now.
