### ISSUE TITLE
any plans for version 4?

### ISSUE THREAD

**Issue by ahmad88me** [PyGithub/PyGithub#804]
Hello Guys, 
    Are you planning to support version 4 of GitHub APIs? I would like to contribute in the development if so.

Thanks,

**Comment by sfdye** [comment]
Version 4 is GraphQL if I am not wrong. This library is only for v3 which is REST API. If you want to contribute to v4, I suggest you look for a GraphQL library instead.

**Comment by YakDriver** [comment]
Note that the GraphQL API (v4) is still very basic with almost no important mutators. The type of functionality that PyGithub provides could not be done with pure v4 yet. Here are examples of mutations that aren't available:

- Create/edit/delete repositories
- Create/edit/delete releases
- Create/update/merge pull requests
- Create tags
- Create files/blobs

https://stackoverflow.com/questions/49944137/few-mutations-in-github-api-v4-graphql

**Comment by EnricoMi** [comment]
PyGithub now has its first GraphQL call, see https://github.com/PyGithub/PyGithub/commit/232df79a2947dc96363bdc6f51a6f446ff2b241f#diff-90017b18548bd848900b7cffd7fe86a610dc20e5d228663dfb429a47cdf65a20R767-R772 for reference.
