### ISSUE TITLE
Search repository by label?

### ISSUE THREAD

**Issue by MattAlp** [PyGithub/PyGithub#805]
I currently have some code where a set of label strings is stored in a Python list, and a Repository object obtained through the `search_repositories` method of the `github` object; the method `repo.get_issues()` specifies that a list of `Label `objects can be passed in to limit the issues that come up.

After some searching, I have not found a way to create a Label object from a desired string, and have resorted to creating a list comprehension:

 `labels = [label for label in repo.get_labels() if label.name in json_repo["code_labels"]]`.

Is there a better or official way to create the label objects for the search? Thank you.

**Comment by sfdye** [comment]
Maybe use the `repo.get_label()`?

something like this:
```
labels = [repo.get_label(label_name) for label_name in json_repo["code_labels"]]
```

**Comment by MattAlp** [comment]
This is perfect, thank you!
