### ISSUE TITLE
Project using pygithub - Cardinals

### ISSUE THREAD

**Issue by jpmartins201** [PyGithub/PyGithub#811]
https://github.com/fga-gpp-mds/2018.1-Cardinals - a website that shows metrics for any public repository (issues, commits, pull requests etc)

**Comment by sfdye** [comment]
@jpmartins201 Hi thanks, it will be easier if you can make a PR.

**Comment by webknjaz** [comment]
@sfdye I think the doc should be changed to encourage users to create PRs instead of issues, then.

**Comment by sfdye** [comment]
You are right, will fix that ;)

________________________________

**Comment by webknjaz** [comment]
btw, I've followed this suggestion from the beginning --> #814

**Comment by sfdye** [comment]
Closed in #815
