### ISSUE TITLE
Get topics of a repo?

### ISSUE THREAD

**Issue by silburt** [PyGithub/PyGithub#812]
Is there a way to get a list of topics associated with a given github repo? From here - https://pygithub.readthedocs.io/en/latest/apis.html - it doesn't seem like there's an API for that. For example, in one of my own repos - https://github.com/silburt/DeepMoon - how would I obtain: 
"convnet
tensorflow
moon
deep
learning
astrophysics
keras" 

Thanks very much,

Ari

**Comment by sfdye** [comment]
See #635

**Comment by wyardley** [comment]
FYI, this is now merged via #832
