### ISSUE TITLE
[FR] Checks API integration

### ISSUE THREAD

**Issue by webknjaz** [PyGithub/PyGithub#813]
The lib is missing Checks API. If someone is up to implementing wrappers for it, I've got some example code.

I wrote a CLI for this API https://pypi.org/p/check-in and here's how I hack around missing methods (+custom Accept header):
https://github.com/webknjaz/check-in/blob/4d11a0a/check_in/github_api.py#L35-L65

**Comment by atmishra** [comment]
Hi, I would like to work on this.

**Comment by hawkins** [comment]
@atmishra Did you ever wind up making a PR for this or hitting a roadblock? I'm also in need of this API and could support.

**Comment by s-t-e-v-e-n-k** [comment]
Closing in favour of #1063.
