### ISSUE TITLE
Unable to list issues passing milestone as parameter

### ISSUE THREAD

**Issue by bvsriram** [PyGithub/PyGithub#817]
Trying to get issues assigned to a milestone but says 

```
File "/usr/local/lib/python3.5/dist-packages/github/Repository.py", line 1692, in get_issues
    assert milestone is github.GithubObject.NotSet or milestone == "*" or milestone == "none" or isinstance(milestone, github.Milestone.Milestone), milestone
```

Here's what I have now
```
miles = {}
for mile_ver in repo1.get_milestones(state="open"):
  miles.update({mile_ver.title:mile_ver})

def issues(param1):
   for issue in repo1.get_issues(milestone=param1, sort='created', direction='asc', state="closed"):
     <do stuff here>
return 
```

I am passing the milestone name into param1. If i `print(param1)` after def it shows the milestone name but doesn't pass it to get_issues()

Tried whats mentioned in #683 but didn't work. Any suggestions?

**Comment by sfdye** [comment]
@bvsriram Sorry could not understand your issue, could you elaborate a bit more? more complete example if possible
