### ISSUE TITLE
[FR] Migration API integration

### ISSUE THREAD

**Issue by webknjaz** [PyGithub/PyGithub#818]
The lib is missing Migration API. It also requires custom `Accept: ` header.
* https://developer.github.com/changes/2018-05-24-user-migration-api/
* https://developer.github.com/v3/migrations/users/
* https://developer.github.com/v3/migrations/orgs/

**Comment by webknjaz** [comment]
@sfdye any ETA on cutting a new release?

**Comment by sfdye** [comment]
@webknjaz I will do it later

**Comment by sfdye** [comment]
@webknjaz done
