### ISSUE TITLE
Delete release operation missing

### ISSUE THREAD

**Issue by jglapa** [PyGithub/PyGithub#819]
Could this be added?

Side note:
It might seem odd to remove a release but I'm backfiling releases in an old project and realized that I did it incorrectly and now have to cleanup.

**Comment by mfonville** [comment]
I think this should work, did you check if you can call `delete_release()` on a release?
https://github.com/PyGithub/PyGithub/blob/master/github/GitRelease.py#L168

**Comment by jglapa** [comment]
true, I couldn't find that method in the reference : https://pygithub.readthedocs.io/en/latest/github_objects/GitRelease.html#github.GitRelease.GitRelease

**Comment by mfonville** [comment]
I think the reference misses a lot of about the functions of GitRelease; if you or anyone would have time to update those docs, that'd be great

**Comment by sfdye** [comment]
Indeed, a lot of documentation are missing.

**Comment by hemanthsavasere** [comment]
Can anyone provide me the basic usage example of this library as I am a beginner?

**Comment by sfdye** [comment]
@hemanthsavasere 
https://pygithub.readthedocs.io/en/latest/examples.html

will get you started.

**Comment by hemanthsavasere** [comment]
Hi @sfdye,
I looked into examples, I want to delete the release in Github after executing the command g.create_git_release(). I don't know how to proceed further.

**Comment by sfdye** [comment]
First get that release and then https://pygithub.readthedocs.io/en/latest/github_objects/GitRelease.html#github.GitRelease.GitRelease.delete_release

**Comment by hemanthsavasere** [comment]
Thanks, Can I add this usage example to the documentation part, as it was confusing for a beginner on how to use it.

**Comment by sfdye** [comment]
Sure, feel free to make a PR. Any improvements to the docs is welcomed :)
