### ISSUE TITLE
Add support for pending team invitations

### ISSUE THREAD

**Issue by ghost** [PyGithub/PyGithub#823]
Per the [docs](https://developer.github.com/v3/teams/members/#list-pending-team-invitations), it's just the following call:

```
GET /teams/:team_id/invitations
```

As mentioned in a blog [post](https://developer.github.com/changes/2018-01-25-organization-invitation-api-preview/) earlier this year, there are two new fields added to the response:

- team_count
- invitation_teams_url

These new fields only appear in the response if the following header is added to the request:

```
Accept: application/vnd.github.dazzler-preview+json
```

So I guess the only question would be whether or not to add the header? Given this is an existing endpoint, probably better to NOT include the header; then when Github moves the new "feature" (which includes the new fields) out of preview, it shows up in the response and PyGithub doesn't have to be changed to remove the above header.

**Comment by tjboring** [comment]
I'm happy to pick this up and work on it.

**Comment by singh811** [comment]
I will be working on it.

**Comment by shibasisp** [comment]
I would like to work on this.

**Comment by sfdye** [comment]
Please
