### ISSUE TITLE
How to get both closed and opened issues at a time

### ISSUE THREAD

**Issue by goutham9032** [PyGithub/PyGithub#825]
i am working on an project which requires all the opened and closed issues, but the current version works for only opened issues.

**Comment by sfdye** [comment]
repo.get_issue(state="closed") # or state="all" to return both 

By default it will only return open issues.

https://developer.github.com/v3/issues/#list-issues-for-a-repository

**Comment by Abdur-rahmaanJ** [comment]
ahh thank you! bit weird!

**Comment by 242jainabhi** [comment]
I am getting wrong number of open issues.

g = Github('Access_Token')
repo = g.get_repo('pygithub/pygithub')
open_issues = repo.get_issues(state='open')
print(open_issues.totalCount)

This prints 77, but repo shows open issues as 60.

What is this extra count about?
