### ISSUE TITLE
Error 404 for File.srt and ContentFile.srt

### ISSUE THREAD

**Issue by jpmartins201** [PyGithub/PyGithub#826]
I was trying to edit the http://pygithub.readthedocs.io/en/latest/github_objects/File.html and http://pygithub.readthedocs.io/en/latest/github_objects/ContentFile.html but it says there isn't these files in this repository.

**Comment by sfdye** [comment]
If you see the sphinx configuration:
https://github.com/PyGithub/PyGithub/blob/faa8f2057021e10139ed2f6700830158f5a4a4c1/doc/conf.py#L285

The `github_objects.rst` is dynamically computed rather than placed on the the directory itself. That's why you couldn't find it on Github.

**Comment by jpmartins201** [comment]
Thank you, but how can I contribute to this part of the docs? (sorry for the dumb question, but it's unclear to me)

**Comment by sfdye** [comment]
Where do you wanna change? Just modify the python docs and it will be reflected in the next master build.

**Comment by sfdye** [comment]
You will want to learn about how sphinx works.

**Comment by sfdye** [comment]
The File class is meant for files in a pull request of commits, e.g.:
https://developer.github.com/v3/pulls/#list-pull-requests-files

It's more like an intermediate resource which I don't think Github has any specific section in the documentation. 

For the first question, if you look at the source code of `Repository.py`, `get_contents` method is actually just calling `get_file_contents` inside. Maybe for some historical reasons which I am not too sure. We should probably merge the two for now. Feel free to make a PR if you want to.

**Comment by jpmartins201** [comment]
Everything makes sense now. We were using these 2 functions and never understood why they were doing the same thing. Thank you for the answers, I'll make the PR until tomorrow.
