### ISSUE TITLE
NamedUser.get_repos() returning 403

### ISSUE THREAD

**Issue by J-Ragone** [PyGithub/PyGithub#829]
I'm using the [Github-Flask](http://github-flask.readthedocs.io/en/latest/) and [PyGithub](https://pygithub.readthedocs.io/en/latest/index.html) libraries to write a GitHub app in Python. The issue that I am facing is I cannot get [PyGitHub's simple tutorial code](https://pygithub.readthedocs.io/en/latest/introduction.html) to run correctly. I will paste my code below.

```python
@app.route('/pygit')
def test():
    pygit = Github(login_or_token="USER_ACCESS_TOKEN")
    user = pygit.get_user()
    repos = user.get_repos()
    for repo in repos:
        print(repo.name)
```

I have replaced `USER_ACCESS_TOKEN` with a user access token, which I retrieve through the use of [Github-Flask's example code](https://github.com/cenkalti/github-flask/blob/master/example.py). When I run the above code, I am faced with the following error on the `for repo in repos` line.

```shell
github.GithubException.GithubException: 403 {'message': 'Resource not accessible by integration', 'documentation_url': 'https://developer.github.com/v3/repos/#list-all-public-repositories'}
```

I should note that my GitHub app is installed and authorized on the account from which I am retrieving the user access token. This error led me to believe that my app did not have the correct permissions. However, I tried giving it read & write permissions (when possible) to every element, and still I am faced with this error. **Am I perhaps passing the wrong type of token when I instantiate `pygit` or is this an issue with PyGithub?**

Other methods, such as [`get_repo("REPO_NAME")`](https://pygithub.readthedocs.io/en/latest/github_objects/NamedUser.html#github.NamedUser.NamedUser.get_repo), work as intended and without error. Furthermore, when I run:

```python
for method in dir(user):
    print(method)
```

I can see the `get_repos` method, so I am certain that it should be callable from this object.

Let me know if I can provide any further information, and thanks in advance for any help.

**Comment by sfdye** [comment]
This seems to be a Github issue, not a PyGithub issue. If the issue persists, you may wanna contact Github support.
