### ISSUE TITLE
repository.get_issues() since parameter doesn't seem to work.

### ISSUE THREAD

**Issue by tshrove** [PyGithub/PyGithub#836]
Using this code in python below:

```
g = Github("key")
since = datetime(2018,1,1)
repo = g.get_repo("facebook/react")
issues = repo.get_issues(since=since)
```

I should in my mind get all issues created since 1/1/2018. But instead, I get issues way past 1/1/2018. I think the since parameter is not working or I don't understand the reason for the since parameter.

**Comment by sfdye** [comment]
https://developer.github.com/v3/issues/#list-issues

since should be a string in the format of YYYY-MM-DDTHH:MM:SSZ.

**Comment by mfonville** [comment]
This is then broken in the PyGithub docs: https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html?highlight=get_issues

There it states `since – datetime.datetime`, I guess we could replace with with e.g. `since – datetime.datetime.isoformat()` optionally with `timespec='seconds'` added if Github is as strict as their API documentation seems to imply.

**Comment by tshrove** [comment]
I used a datetime object for the since. It would not let me use a string.

**Comment by mfonville** [comment]
After checking the source code I do indeed see that it expects a `datetime` object.
And in https://github.com/PyGithub/PyGithub/blob/master/github/Repository.py#L1833 it converted from datetime to correct string format. So I don't know why it doesn't work

**Comment by tshrove** [comment]
Did someone else verify (besides me) that it doesn't work?

**Comment by tshrove** [comment]
@mfonville Could it be that the github api is not working correctly?

**Comment by tshrove** [comment]
Other libraries are doing the same thing. I think the "since" object might be on the updated_at field instead of the created_at field.

**Comment by tshrove** [comment]
Yelp. Found it in the github api documentation. 

> Only issues updated at or after this time are returned. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
