### ISSUE TITLE
Add archival support for Repository.edit

### ISSUE THREAD

**Issue by sechastain** [PyGithub/PyGithub#840]
In November 2017, github added the ability to archive a repository via the edit REST API

https://developer.github.com/changes/2017-11-08-archiving-repositories/

The change looks to be relatively simple - I'm just a little hung up on generating the replay file

**Comment by sfdye** [comment]
This will be useful! How can I help？

**Comment by sechastain** [comment]
I just get antsy any time I see code wanting passwords and such ☺️

Any procedures / best practices / things to not do?

I guess what I'm think of right now is generating a temporary token, generate the replay, and then delete the token?

**Comment by sfdye** [comment]
You could. According to the docs:
https://github.com/PyGithub/PyGithub/blob/master/CONTRIBUTING.md#automated-tests

You can generate a personal token and run the test with `--record --auth_with_token`. That's it :)

**Comment by sfdye** [comment]
Closed by #843
