### ISSUE TITLE
Get the authenticated user

### ISSUE THREAD

**Issue by hren-ron** [PyGithub/PyGithub#841]
hi
In the file "Github/AuthenticatedUser.py", an AuthenticatedUser object can be created by calling ``get_user()`` on a Github object. But when calling get_user(), the function return an 'NamedUser' object, so i can not use the ``get_user_issues()``,i want to know how to get the authenticated user object?

**Comment by sfdye** [comment]
Can you provide a specific example of what you wanna achieve?

**Comment by hren-ron** [comment]
`gh=Github(username,password)
user=gh.get_user(name)
issues=user.get_user_issues()
`
When calling ``get_user_issues()``, i find that ``AttributeError: 'NamedUser' object has no attribute 'get_user_issues'``

**Comment by sfdye** [comment]
https://developer.github.com/v3/issues/#list-issues

I believe there is no such API to query issues for a NamedUser.

**Comment by hren-ron** [comment]
In the PyGithub source code file "Github/AuthenticatedUser.py", i find that an AuthenticatedUser object can be created by calling ``get_user()`` on a Github object. And i find there is a ``get_user_issues()`` in the file for an AuthenticatedUser, so i want to know how to create the AuthenticatedUser object?

**Comment by hren-ron** [comment]
`class AuthenticatedUser(github.GithubObject.CompletableGithubObject):
    """
    This class represents AuthenticatedUsers as returned by https://developer.github.com/v3/users/#get-the-authenticated-user
    An AuthenticatedUser object can be created by calling ``get_user()`` on a Github object.
    """`

**Comment by sfdye** [comment]
`gh.get_user()` (without any parameter) will give you `AuthenticatedUser`. What I mean is, according to the official Github documentation, you simply can't get the issues of the non authenticated user.

**Comment by hren-ron** [comment]
OK
