### ISSUE TITLE
Issues in enterprise github reference while updating a new sha

### ISSUE THREAD

**Issue by pxgst128** [PyGithub/PyGithub#847]
>>> print(gea_qa_br.object.sha)
db9e6a0fb74d89619478a2569cc9df85b756a292
>>> print(gea_qa_br.object.url)
https://somehost:someport/api/v3/repos/Corp-GSC-GEA/GSC-GEA-SOA-test-repo/git/commits/db9e6a0fb74d89619478a2569cc9df85b756a292
>>> print(gea_qa_br.object.type)
commit
>>> gea_qa_br.edit(sha=hex_dig,force=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sw/pkg/user_projects/python-3.7.0/lib/python3.7/site-packages/github/GitRef.py", line 97, in edit
    input=post_parameters
  File "/sw/pkg/user_projects/python-3.7.0/lib/python3.7/site-packages/github/Requester.py", line 260, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/sw/pkg/user_projects/python-3.7.0/lib/python3.7/site-packages/github/Requester.py", line 271, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {'message': 'Object does not exist', 'documentation_url': 'https://developer.github.com/enterprise/2.13/v3/git/refs/#update-a-reference'}
>>>

**Comment by mfonville** [comment]
I am not sure why the value of `.url` is `https:///api/v3/repos/Corp-GSC-GEA/GSC-GEA-SOA-test-repo/git/commits/db9e6a0fb74d89619478a2569cc9df85b756a292` but clearly for some erroneous reason the protocol-type (`https://`) got added to the relative url of `/api/`.

**Comment by pxgst128** [comment]
never mind but the private host is hidden for some security reason. But issue is updating the sha doesn't work.

**Comment by mfonville** [comment]
ok, please next time don't remove them, but put some bogus information there please. Like `private-host.org:1337` :-)
