### ISSUE TITLE
how to sort stargazers by date

### ISSUE THREAD

**Issue by HaoChuan9421** [PyGithub/PyGithub#848]
get stargazers of a repo: http://developer.github.com/v3/activity/starring/#list-stargazers 
it seems doesn't list any sort or direction parameter.so how to sort stargazers by date or some else parameters
I couldn't find it in the reference, maybe I missed it?Thanks :)

**Comment by sfdye** [comment]
Looks like you can use a custom header to get the starred date:
https://developer.github.com/v3/activity/starring/#alternative-response-with-star-creation-timestamps

Fortunately someone implemented this so you can use `repo.get_stargazers_with_dates()`. But you probably need to perform the sorting by yourself.

**Comment by HaoChuan9421** [comment]
thank you! I have tried to add `header` `Accept: 'application/vnd.github.v3.star+json'` and got results with `starred_at` field。
![image](https://user-images.githubusercontent.com/28668354/42983744-ed81ce7c-8c1a-11e8-89e6-7be170e5c9c5.png)
but it was not what i expected.i have already find out this API has parameters for pagination whice are `page` and `per_page`,so i wander does parameter like `sort: newest` or `sort: oldest` exist。so that i can get newest starred user like this https://api.github.com/repos/PyGithub/PyGithub/stargazers?page=1&per_page=5&sort=newest

**Comment by sfdye** [comment]
In other words, you want to get the latest stargazer?

**Comment by HaoChuan9421** [comment]
yes,it is the sence!!!

**Comment by sfdye** [comment]
Well then I have a recipe for you. It looks like although Github does not officially support the `sort` parameter, the stargazers are sorted chronologically by default. So we just need to get the last item from the list. 

The following idea is taken from #820 

1. First make a request to stargazers API with a parameter `per_page=1`:
GET https://api.github.com/repos/PyGithub/PyGithub/stargazers?per_page=1
 
In the response, the `Link' header will look something like this:

`<https://api.github.com/repositories/3544490/stargazers?per_page=1&page=2>; rel="next", <https://api.github.com/repositories/3544490/stargazers?per_page=1&page=1930>; rel="last"`

Note: here 1930 is total number of stargazers as of now.

2. Now just retrieve the last page of this result.
GET https://api.github.com/repositories/3544490/stargazers?per_page=1&page=1930

This will give you the "newest" stargazer.

To implement this idea in PyGithub:

```python
g = Github(token, per_page=1)
repo = g.get_repo('PyGithub/PyGithub')
stargazers = repo.get_stargazers_with_dates()
# parse the last page number 
# l._getLastPageUrl() -> 'https://api.github.com/repositories/3544490/stargazers?per_page=1&page=1930'
last = int(l._getLastPageUrl().split("=")[-1])
# retrieve the last page
print(stargazers.get_page(last-1)[0]).starred_at
```

**Comment by HaoChuan9421** [comment]
the `Link' header with total count is really userful!!! Thank you very much!!!

**Comment by HaoChuan9421** [comment]
By the way! If a repository's star count is too large(>40000).[example](https://github.com/vuejs/vue) it's over 10K!this API can get only the 40000th user which is not the true latest one.do you have some suggestion?

![image](https://user-images.githubusercontent.com/28668354/42985939-2060cc3e-8c26-11e8-9063-19f86509f800.png)

https://api.github.com/repositories/11730342/stargazers?page=4001&per_page=10

![image](https://user-images.githubusercontent.com/28668354/42986216-4f2c4538-8c27-11e8-98f4-75016f346aea.png)

**Comment by HaoChuan9421** [comment]
By the way! If a repository's star count is too large(>40000).[example](https://github.com/vuejs/vue) it's over 10K! this API can get only the 40000th user which is not the true latest one.do you have some suggestion?
![image](https://user-images.githubusercontent.com/28668354/42986544-84ecdcae-8c28-11e8-8f27-b1f43208cf08.png)
https://api.github.com/repositories/11730342/stargazers?page=4001&per_page=10
![image](https://user-images.githubusercontent.com/28668354/42986407-004287d8-8c28-11e8-8299-8b5d9628b889.png)

**Comment by sfdye** [comment]
Good find 😂 

Unfortunately unless Github provides a `sort` parameter, I don't see a good way to achieve this for a huge popular repo.

**Comment by HaoChuan9421** [comment]
😄😂it is time for emoji😂😄,thank you all the same
