### ISSUE TITLE
Attributes are lost by PaginatedList

### ISSUE THREAD

**Issue by sergey48k** [PyGithub/PyGithub#850]
A snippet first:

```
g = Github()
r = g.get_repo('sourcerer-io/sourcerer-app')
cc = r.get_contributors()
print(cc[0].raw_data['contributions'])
```
This results in an error: KeyError: 'contributions'. The API call `GET repos/sourcerer-io/sourcerer-app/contributors` returns contributions just fine. 

This happens because of this line in github/PaginatedList.py:191:

`self.__contentClass(self.__requester, headers, element, completed=False)`

That is, each NamedUser is created as incomplete. Whet its attributes are accessed, a new API call is made that overwrites the object, a thus loses 'contributions' attribute.

I would be happy to make a pull request to set completed to True, but I am not sure what this will break since this seems to be used by pretty much everyone. It still needs to be addressed somehow because attributes are lost, and because it inflates the number of calls to the backend.

**Comment by sfdye** [comment]
@sergey48k Seems like we removed the `contributions` attribute from `NamedUser` from #443, as we thought this attribute was not needed anymore.

**Comment by sergey48k** [comment]
Well, I needed it. And I had to abandon pygithub in favor of good old HTTP requests for it.
Also, it's very surprising that NamedUser is created incomplete.

**Comment by s-t-e-v-e-n-k** [comment]
It isn't that the attribute wasn't needed, it wasn't populated. Let me dig into this.

**Comment by sergey48k** [comment]
thank you @s-t-e-v-e-n-k

**Comment by sfdye** [comment]
```
g = Github()
r = g.get_repo('sourcerer-io/sourcerer-app')
cc = r.get_contributors()
print(cc[0].contributions)
```

confirmed it works now
