### ISSUE TITLE
Inviting a user via email address using pygithub.

### ISSUE THREAD

**Issue by UlaganathanNamachivayam** [PyGithub/PyGithub#851]
Hi Team,
Have gone through the documentation and found solutions to invite a nameduser. I have use case where i wanted to invite an external user using his E-mail address. But could not see an option to do the same using pygithub where only nameduser is supported.

Kindly help.

**Comment by sfdye** [comment]
You are right. I guess the following endpoint is yet to be implemented:
https://developer.github.com/v3/orgs/members/#create-organization-invitation
