### ISSUE TITLE
Is there have some static api?

### ISSUE THREAD

**Issue by NKUMBA2017P92320170631** [PyGithub/PyGithub#859]
Hi, PyGithub is a great product, and I need to static some data of repository. But if I use PyGithub 
to collect data directly , I will get a error of timeout from github which ban my request for  frequency problem.

**Is there some static api? Or I miss it?**

**Comment by sfdye** [comment]
What do you mean by static api? Do you mean the requested data does not change frequently?  It seems to be me you are violating the designated API [rate limit](https://developer.github.com/v3/#rate-limiting).

**Comment by NKUMBA2017P92320170631** [comment]
Ohh, my mistake, made a typo , 

> static  api

 should be **statistics api**.
And, yes it is, the rate limit problem.
statistics api: Means statistics data from API,  like [statistics](https://developer.github.com/v3/repos/statistics/).
But I need more complicated statistics data.

Is there anyway or method to solve this?

**Comment by sfdye** [comment]
The stats API are implemented, e.g.:

http://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.get_stats_contributors

All `get_stats_*` methods

**Comment by NKUMBA2017P92320170631** [comment]
OK! Getcha! Thanks a lot, that was I need!
