### ISSUE TITLE
Upload a zip file as content for InputGitTreeElement

### ISSUE THREAD

**Issue by tsiq-cejas** [PyGithub/PyGithub#863]
This is a question:

I am trying to upload zip files to my repo by creating a tree with a bunch of InputGitTreeElement elements. Some of these InputGitTreeElement are zip files. InputGitTreeElement only accepts 'str' for content. How can I do this? 

thanks!

**Comment by sfdye** [comment]
What's your initial use case? Just uploading a file to your repo? If so, there is a upload api you can use. (but limited to upload one file at a time)

**Comment by tsiq-cejas** [comment]
First, I forgot to say that I am using Python3.
I am want to upload a bunch of changed json files plus some zip files as one commit: 

repo.create_git_commit(commit_msg, end_tree, parents=[commit.commit])

end_tree is a list of InputGitTreeElement. Each one corresponds to a file. My problem becomes that the 'content' of InputGitTreeElement can only be of type 'str' or 'unicode'. When I load a file to memory I have type 'bytes'. What is the right way to encode those bytes to str or unicode so InputGitTreeElement can upload my file?

thanks!

**Comment by sfdye** [comment]
You can use blob.

```python 
import base64 

blob = repo.create_git_blob("XXX", encoding='utf-8')
blob = repo.get_git_blob(sha=blob.sha)
tree_element = InputGitTreeElement(path='', mode='100644', type='blob', content=base64.b64decode(blob.content).decode('utf-8'))
```

**Comment by tsiq-cejas** [comment]
It wouldn't be the same problem? `create_git_blob` expects string as content. 
url points to a zip downloadable url.

```
resp = requests.get(url)
blob = repo.create_git_blob(resp.content, encoding='utf-8')
blob = repo.get_git_blob(sha=blob.sha)
tree_element = InputGitTreeElement(path='', mode='100644', type='blob', content=base64.b64decode(blob.content).decode('utf-8'))  


...
    repo.create_git_blob(resp.content, encoding='utf-8')
  File "/usr/local/lib/python3.6/site-packages/github/Repository.py", line 764, in create_git_blob
    assert isinstance(content, str), content
AssertionError: `b'PK\x03\x04\n\x00\x00...`
```

**Comment by sfdye** [comment]
replace `resp.content` with `resp.content.decode("utf-8"）`

**Comment by tsiq-cejas** [comment]
Is not able to decode it as utf-8:
```
blob = repo.create_git_blob(resp.content.decode('utf-8'), encoding='utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 43: invalid start byte
```

**Comment by cosme12** [comment]
Did you manage to solve this? I'm having the same problem. I can't find a way to upload a png file.

**Comment by asfixia** [comment]
I have the same problem, i cant send a simple image file.

**Comment by smbanaie** [comment]
You Can Try This :
` data = base64.b64encode(open(file_name, "rb").read())
path = "{}/{}/h{}_{}".format(now.year, now.month, now.hour, "tweets.zip")
    blob = repo.create_git_blob(data.decode("utf-8"), "base64")
    element = InputGitTreeElement(path=path, mode='100644', type='blob', sha=blob.sha)
    element_list.append(element)

    tree = repo.create_git_tree(element_list, base_tree)`

**Comment by maheshwara-bwd** [comment]
> You Can Try This :
> 
> ```python
> data = base64.b64encode(open(file_name, "rb").read())
> path = "{}/{}/{}".format(now.year, now.month, "tweets.zip")
> blob = repo.create_git_blob(data.decode("utf-8"), "base64")
> element = InputGitTreeElement(path=path, mode='100644', type='blob', sha=blob.sha)
> element_list.append(element)
> tree = repo.create_git_tree(element_list, base_tree)
> parent = repo.get_git_commit(master_sha)
> commit = repo.create_git_commit("commit_message", tree, [parent])
> master_ref.edit(commit.sha)```
> ```

Hi @smbanaie ,
I faced the same issue and it's almost resolved.
Thank you so much for the solution :)
But i have a small issue , In a  scenario where the same zip file is already there,  it s not updated.
how can i do that ?

**Comment by OpetherMB** [comment]
is there any possible solution to this thread? 
when i try to push my zip file i get this error : 

`Traceback (most recent call last):
  File "/home/aird/Documents/bdd/1_week_road/push_data.py", line 44, in <module>
    element = InputGitTreeElement(file_names[i], '100644', 'blob',  content=base64.b64decode(data).decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 1: invalid start byte`
