### ISSUE TITLE
PyGithub example usage

### ISSUE THREAD

**Issue by sfdye** [PyGithub/PyGithub#874]
Motivation:
#862 #456 #321 #584 #762 

PyGithub is a great library, however it may not be intuitive to use at the beginning. Not everyone is a Github API expert, so I am trying to provide some working examples (recipes) that will hopefully help you get started.

The skeleton has been setup [here](https://github.com/PyGithub/PyGithub/tree/master/doc/examples) and the example docs is already live on readthedocs as usual:

https://pygithub.readthedocs.io/en/latest/examples.html

Note that the list will expand and **any PR to add more examples is extremely welcome** 😄 

If you want to see any examples not covered here, just leave a comment.

**Comment by Abdur-rahmaanJ** [comment]
API expect -> API expert

**Comment by sfdye** [comment]
Done thanks @Abdur-rahmaanJ

**Comment by Abdur-rahmaanJ** [comment]
@sfdye readd the login example please ^^_

**Comment by sfdye** [comment]
@Abdur-rahmaanJ What do you mean?

**Comment by mscheper** [comment]
I just started with PyGithub, and [found some examples](https://pygithub.readthedocs.io/en/latest/examples.html), so obviously some work has been done—thanks, people!

But I don't see any examples for how to use events, e.g. [pushevent](https://developer.github.com/v3/activity/events/types/#pushevent) and [pullrequestevent](https://developer.github.com/v3/activity/events/types/#pullrequestevent). Could those be added?

**Comment by mscheper** [comment]
Thanks, @LeviMatus!

**Comment by sfdye** [comment]
this is not stable

**Comment by goodship1** [comment]
Writing Organization examples now

**Comment by yks0000** [comment]
I am new to PyGithub SDK and trying to do below operations. However, having difficulty going through documents to know the usage.

1. get a file content from a specific branch 

command line equivalent: 

`git checkout <<branch>> and then get file content`

**Issue:**

**I am able to get file content from master branch using this sdk but not from specific branch**

2. repo tags and its details 

command line equivalent: 

`git tag -v <<tag_id>>`

3. Update that file

4. Update user details for commit 

```
git config user.email "cicd@example.com"
git config user.name "cicd"
git commit --amend --reset-author --no-edit
```

5. Git pull that branch before commit  as other automation might have committed some other file.
6. git commit in the branch

```
git pull --no-edit
git add $FILE_NAME
git commit -m "updating $FILE_NAME"
git pull --no-edit && git push origin
```

I am also trying to find the method/api of this sdk to do that, but if someone have it ready, please help with the same.

**Comment by mancuss** [comment]
Hello, I'm a relatively new developer and this is helping a lot. Is any one planning to do examples for github app? Thanks!

**Comment by estagumor** [comment]
> I am new to PyGithub SDK and trying to do below operations. However, having difficulty going through documents to know the usage.
> 
> 1. get a file content from a specific branch
> 
> command line equivalent:
> 
> `git checkout <<branch>> and then get file content`
> 
> **Issue:**
> 
> **I am able to get file content from master branch using this sdk but not from specific branch**
> 
> 1. repo tags and its details
> 
> command line equivalent:
> 
> `git tag -v <<tag_id>>`
> 
> 1. Update that file
> 
> I see here the docs `https://pygithub.readthedocs.io/en/latest/examples/Repository.html#update-a-file-in-the-repository`
> 
> 1. Update user details for commit
> 
> ```
> git config user.email "cicd@example.com"
> git config user.name "cicd"
> git commit --amend --reset-author --no-edit
> ```
> 
> 1. Git pull that branch before commit  as other automation might have committed some other file.
> 2. git commit in the branch
> 
> ```
> git pull --no-edit
> git add $FILE_NAME
> git commit -m "updating $FILE_NAME"
> git pull --no-edit && git push origin
> ```
> 
> I am also trying to find the method/api of this sdk to do that, but if someone have it ready, please help with the same.

hi! I'm trying to get the content of an specific branch too. Did you get it? Thanks!

**Comment by gfleetwood** [comment]
@estagumor If you still need this answer the key is the [ref parameter](https://developer.github.com/v3/repos/contents/#get-contents) in the `get_contents` function. The default is "master". Here's an example getting the contents of the "0.6.X" branch of the scikit-learn repo.

```
from github import Github

g = Github("USERNAME", "PASSWORD")
repo = g.get_repo("scikit-learn/scikit-learn")
repo.get_contents("", ref = "0.6.X")
```

**Comment by qbits-rwx** [comment]
@sfdye I just started working with PyGithub and it works great.  However even if i'am familiar with the git api, it would be great if you can provide a working example of how to set create / set branch protection rules.

I tried for example:
g.get_repo('SECRET/SECRET').get_branch('master').add_required_signatures()

**Comment by sfdye** [comment]
@qbits-rwx I think the method you need is:
https://pygithub.readthedocs.io/en/latest/github_objects/Branch.html#github.Branch.Branch.edit_protection

https://developer.github.com/v3/repos/branches/#update-branch-protection

**Comment by qbits-rwx** [comment]
Yes this did the trick. Unfortunately, require signed commits, is not implemented. Would be nice to have, as it is a policy we need to set on every branch.

**Comment by sfdye** [comment]
Feel free to send a FR or PR

**Comment by xpdable** [comment]
#1628 A full example to upload multipe files in one commit

**Comment by NicoWeio** [comment]
Thanks a lot for these examples! What I'm missing is an example for exception handling. For instance, it wasn't immediately clear to me how to catch a `github.GithubException.UnknownObjectException`.

**Comment by nitishagar** [comment]
> Yes this did the trick. Unfortunately, require signed commits, is not implemented. Would be nice to have, as it is a policy we need to set on every branch.

@qbits-rwx Following should help with "require signed commit" setting on a branch: https://pygithub.readthedocs.io/en/latest/github_objects/Branch.html#github.Branch.Branch.add_required_signatures

**Comment by wangzelin007** [comment]
Hi [sfdye](https://github.com/sfdye),
Can you add a example about add comment in pull request and update comment in pull request, many thanks.

**Comment by VarnaX** [comment]
How to download a repo ??

**Comment by skyfall01** [comment]
Hi any pointers in how I can do this

```
git checkout -b subbranch
git add requests/application.yml
git commit 
```

The file `requests/application.yml` already exists in the `main` branch

**Comment by v1s1t0r999** [comment]
@VarnaX 
git clone it or recursively download its files using a for loop

**Comment by kaixinol** [comment]
Test

**Comment by kaixinol** [comment]
Test

**Comment by kaixinol** [comment]
##Test
*super*

**Comment by kaixinol** [comment]
## Test
*super*

**Comment by zain-asif-dev** [comment]
Opened #3543 to add an exception-handling example (catching `UnknownObjectException`, `BadCredentialsException`, `RateLimitExceededException`, and the base `GithubException`), addressing the request from @NicoWeio above.

**Comment by mak1143** [comment]
Hi! I'd like to contribute an example for listing a repository's stargazers (get_stargazers()), which isn't currently shown in the examples docs. Working on it now.

**Comment by LeonxLJX** [comment]
Hi! I'd like to work on this issue. Please let me know if I can be assigned. Thanks!

**Comment by LeonxLJX** [comment]
Hi! I'd like to add PyGithub example usage. Plan: write examples, link from README/docs. May I be assigned?

**Comment by NicoWeio** [comment]
How about you just go ahead and create a PR? Pinging here notifies >15 people every time…
