### ISSUE TITLE
Can I get the limit for search now?

### ISSUE THREAD

**Issue by Strikersb** [PyGithub/PyGithub#895]
I get self.g.rate_limiting got `(4993, 5000)`

But the search limit is different, with only 30 requests per minute.

Excuse me, I didn't find the corresponding document, or PyGithub does not have this function now.

thanks

**Comment by Strikersb** [comment]
document: https://developer.github.com/v3/search/#rate-limit

**Comment by sfdye** [comment]
Possible duplicate of #895

**Comment by Strikersb** [comment]
@sfdye  Thank you very much. By the way, when will `get_search_rate_limit()` be completed?

**Comment by sfdye** [comment]
When I get some free time, will take a look. Merging with #553 .

**Comment by sfdye** [comment]
Fixed in #553
