### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by jimleroyer** [PyGithub/PyGithub#90]
Hello, I am trying to use PyGithub but have been unable to. I got an error upon import:

``` python
Python 3.2.2 (default, Sep  4 2011, 09:07:29) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from github import Github
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python\3.2.2\lib\site-packages\github\__init__.py", line 14, in <module>
    from Github import Github
ImportError: No module named Github
```

I've just installed with `pip` and this one should work fine as I've been able to install other packages successfully. Why it does not work escape me though. There is a _Github.py_ file in the installation path (C:\Program Files\Python\3.2.2\Lib\site-packages\github). And still it complains no module with that name exists. Do you have any suggestions on what I could check to make it work?

**Comment by Krokop** [comment]
try install with pip3
