### ISSUE TITLE
Repository.edit does not let you set merge commit rule booleans to false

### ISSUE THREAD

**Issue by eaceaser** [PyGithub/PyGithub#903]
https://github.com/PyGithub/PyGithub/blob/master/github/Repository.py#L1250-L1252 are the offending lines.

The assertions assert that the provided booleans are set to True, so you can never set them to False :)

This is a simple fix to remove that conditional in the assertion, but maybe there was a reason for this?

**Comment by sfdye** [comment]
Thanks for reporting. I believe that's a typo, unless the PR author thinks otherwise @jacquerie ?

**Comment by jacquerie** [comment]
Uhm, it seems like I mindlessly used the same pattern as for `archived`, for which it makes sense to have that assertion because you can't unarchive through the API. So yes, it's a bug that my PR introduced!

**Comment by sfdye** [comment]
Thanks for confirming! Now I am open for a quick PR to fix it :)

________________________________

**Comment by jacquerie** [comment]
> Thanks for confirming! Now I am open for a quick PR to fix it :)

It happened in https://github.com/PyGithub/PyGithub/pull/904 : )

**Comment by sfdye** [comment]
Merged!

________________________________
