### ISSUE TITLE
Commit.author and Commit.committer lose information

### ISSUE THREAD

**Issue by guyer** [PyGithub/PyGithub#907]
`Commit.author` and `Commit.committer` are converted to `NamedUser`, which gives information about the GitHub account, not about the commit.

In the raw json query, something like this is returned
```
    ...    
    "commit": {
      "author": {
        "name": "Author Name",
        "email": "author.name@institution.org",
        "date": "2018-08-30T18:22:26Z"
      },
     ...
```
where `date` is the time stamp the commit was made, but `Commit.author.created_at` appears to return the date the GitHub account was opened.

As a result, there appears to be no way to determine when a commit was made or repository was tagged, even though this information is trivially obtained with `git log`.

**Comment by sfdye** [comment]
What about `Commit.commit`?

**Comment by guyer** [comment]
Thanks @sfdye, `Commit.commit.author.date` does the trick.
