### ISSUE TITLE
How to get public events?

### ISSUE THREAD

**Issue by anuj-reef** [PyGithub/PyGithub#913]
Is there a way to do this - https://developer.github.com/v3/activity/events/#list-public-events?

**Comment by sfdye** [comment]
Don't think there is. PR are welcome.

**Comment by elfosardo** [comment]
I noticed there's a function get_event in [AuthenticatUser.py](https://github.com/PyGithub/PyGithub/blob/ade78ffb2dc78f02e7ebc3db704900c70e401341/github/AuthenticatedUser.py#L671)
is that what you're looking for ?

**Comment by sfdye** [comment]
Looks promising, could you try?

**Comment by elfosardo** [comment]
I did a quick test and it looks like it's getting all the public events
@anuj-reef if you could also check if that is what you were looking for

**Comment by anuj-reef** [comment]
@elfosardo This works but then this supposed to be returning the public events by a user and not all public events.

https://developer.github.com/v3/activity/events/#list-events-performed-by-a-user
