### ISSUE TITLE
deprecate requirements in favor of pipenv

### ISSUE THREAD

**Issue by elfosardo** [PyGithub/PyGithub#923]
this is more a feature request than an issue
pipenv is the new python packaging tool that solves different known problems using the old pip + virtualenv + requirements.txt mode
would be nice to add the configuration files to the repo and remove requirements.txt

**Comment by elfosardo** [comment]
PR with simple pipenv config files #924

**Comment by sfdye** [comment]
👇 
https://github.com/pypa/pipenv/issues/3369
