### ISSUE TITLE
GitHub Repo Traffic Endpoints are Missing

### ISSUE THREAD

**Issue by loganknecht** [PyGithub/PyGithub#926]
Hello there,

Love the work that's being done here.

It appears that there is a set of endpoints that are from the traffic endpoints.

Specifically
`GET /repos/:owner/:repo/traffic/popular/referrers`
`GET /repos/:owner/:repo/traffic/popular/paths`
`GET /repos/:owner/:repo/traffic/views`
`GET /repos/:owner/:repo/traffic/clones`

These can be found here:
https://developer.github.com/v3/repos/traffic/

Would love to see these added!

Keep up the great work!

**Comment by minno917** [comment]
I am part of a group of five and we would like to attempt to implement this.

**Comment by miguelgfierro** [comment]
@minno917 maybe this can help you https://github.com/miguelgfierro/codebase/blob/master/python/utilities/git_stats.py#L167

**Comment by sfdye** [comment]
@minno917 awesome, PR welcome

**Comment by minno917** [comment]
Thank you for the responses. We were all busy over Thanksgiving break, but we are now actively working on the issue! Expect a PR in the next week.
