### ISSUE TITLE
Couldn't get ContentFile's last_modified attribute directly

### ISSUE THREAD

**Issue by AnYeMoWang** [PyGithub/PyGithub#933]
I've found a weird thing recently, I couldn't get ```last_modified``` unless I called ```update()```function. Is it a bug or something?:
```
In [9]: res = g.search_code('pygithub')

In [10]: files = res.get_page(0)

In [11]: print(files[0].last_modified)
None

In [12]: files[0].update()
Out[12]: True

In [13]: files[0].last_modified
Out[13]: 'Thu, 25 Jan 2018 18:00:05 GMT'
```

**Comment by yangyang-zhang** [comment]
@AnYeMoWang  I have the same problem. Do you have a good solution? It takes a long time to call the update function.
