### ISSUE TITLE
BadCredentialsException not raised on GitHub enterprise

### ISSUE THREAD

**Issue by slinkymanbyday** [PyGithub/PyGithub#934]
On Github Enterprise, the API message does not read "Bad credentials" when incorrect credentials are supplied. It reads "Must authenticate to access this API."

Might be better to just go off of the 401 code as opposed to the error message.

 if status == 401 and output.get("message") == "Bad credentials":

should be
 if status == 401:

**Comment by sfdye** [comment]
PR please I will review

**Comment by Zoom67** [comment]
I think this may have broken something. If I run v1.43.2, my script works; if I run 1.43.3, I get 401 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Bad credentials'}. The credentials are good.

**Comment by sfdye** [comment]
@Zoom67 Can you share the script?

**Comment by sfdye** [comment]
@Zoom67 Found the culprit #948

This PR changes the relative positions of the arguments, so you might want to use keyword arguments instead of positional ones.

This should solve your problem:
`self._connection = Github(username, password, base_url=self.base_url)`

**Comment by Zoom67** [comment]
Yep, that did it - thanks! I changed that line to be fully qualified, just to be sure.

```
        self._connection = Github(login_or_token=username,
                                  password=password,
                                  base_url=self.base_url)
```
