### ISSUE TITLE
review.raw_data returns NoneType on PullRequestReviewObject

### ISSUE THREAD

**Issue by jaxinye** [PyGithub/PyGithub#940]
I've been trying to use below python codes to get pull request reviews of one repository. But the methods raw_data returns 'NoneType' object has no attribute 'startswith' error message.
`    g = Github(token, per_page=100)`
`    res = g.get_repo(int(66293963)).get_pull(46).get_reviews()`
`    page = res.get_page(0)`
`    for review in page:`
`        review_json = json.dumps(review.raw_data)`

**Comment by sfdye** [comment]
Normally you don't need to use the `get_page`.
`get_reviews()` returns a PaginatedList, you can just do:
```python
first_review = get_reviews()[0]
# or
for review in get_reviews():
	print(review)
```
