### ISSUE TITLE
'raw_data' method of PullRequestReview returns Nonetype error

### ISSUE THREAD

**Issue by jaxinye** [PyGithub/PyGithub#941]
I was trying to use following python code to get reviews of one repository. But 'raw_data' method of PullRequestReview object returns 'NoneType' object has no attribute 'startswith' error message.

`    g = Github(token, per_page=100)`
`    res = g.get_repo(id).get_pull(num).get_reviews()`
`    page = res.get_page(0)`
`    for review in page:`
`        review_json = json.dumps(review.raw_data)`

**Comment by sfdye** [comment]
Closing in favor of #940
