### ISSUE TITLE
Clone repository

### ISSUE THREAD

**Issue by DylanMeeus** [PyGithub/PyGithub#951]
I couldn't find this in the examples (or I overlooked it), but I can't see if it is possible to clone the repository using PyGithub.

**Comment by sfdye** [comment]
Don't think it was provided by Github REST API. You will need a python git client.

**Comment by DylanMeeus** [comment]
Alrighty, Thank you!

I went the route of just using python to execute git clone with `system.os("..")` :)

**Comment by tvdsluijs** [comment]
Will there be an option within pygithub to eventually do this?

**Comment by perreault-m** [comment]
I don't think so , the PYGithub API seems to be used only to control the remote and not work locally.

**Comment by mpennington-te** [comment]
I find myself with a similar question... I work for a company that uses GitHub as their online source repository.

This means I work with two Github repositories:
* One repo under our shared corporate username (thousandeyes)
* One repo under my corporate username (mpennington-te)

I have to clone from the thousandeyes repo to the mpennington-te username practically every day.  It would be quite useful to have a github API to do this.

**Comment by sfdye** [comment]
First question, why? What's the use case for?

If you simply want to clone them locally, why not just write a shell script or use [GitPython](https://github.com/gitpython-developers/GitPython)

**Comment by mpennington-te** [comment]
> First question, why?  What's the use case for?

Those questions (and the solution) are answered here:
https://stackoverflow.com/q/61544909/667301
