### ISSUE TITLE
Get all forks of my source repos?

### ISSUE THREAD

**Issue by Bluscream** [PyGithub/PyGithub#955]
I can get notified of people forkinb my repos but thats not half as interesting as knowing when the actually get modified.
Is there a way to get a iterable with all repos on github that are forked from one of my or my organisations repos?

**Comment by sfdye** [comment]
I am afraid you have to do it one by one.

https://developer.github.com/v3/repos/forks/#list-forks
https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.get_forks

**Comment by Bluscream** [comment]
Wouldn't that quickly exceed the api limits?

**Comment by sfdye** [comment]
Unless you can think of a better way? The Github API rate limit is quite generous actually.

**Comment by Bluscream** [comment]
Can pygithub be split in shards? So that two servers share the same tasks

**Comment by sfdye** [comment]
Don’t think so

**Comment by Bluscream** [comment]
Okay, thanks ^^

**Comment by Bluscream** [comment]
Okay, thanks ^^
