### ISSUE TITLE
How to get pull request checks status?

### ISSUE THREAD

**Issue by Ayub-Khan** [PyGithub/PyGithub#958]
We were using github commit combined status to check the status of pr tests. Those were travis based tests and every thing was working fine. Recently we started using github based tests and that is not working any more. Is there any way we can get the combined status of github checks.

**Comment by sfdye** [comment]
Yes, call `get_combined_status()` on the `Commit` object you wanna check against

**Comment by Ayub-Khan** [comment]
get_combined_status() was working fine regarding travis based checks but its failing in case of github based checks.

**Comment by sfdye** [comment]
By Github checks you mean this? https://developer.github.com/v3/checks/

See #813

**Comment by Ayub-Khan** [comment]
Yes.

**Comment by sfdye** [comment]
Then it's feature request.

Closing in favor of #813
