### ISSUE TITLE
PaginatedList.totalCount is broken when there are 0 results

### ISSUE THREAD

**Issue by isouza-daitan** [PyGithub/PyGithub#960]
Self-contained test:
```
from github import Github

github = Github()
repos = github.search_repositories('shouldreturn0repos')

assert repos.totalCount == 0
```

The `totalCount` method has this code:
```
    def totalCount(self):
        if not self.__totalCount:
            [...]
            if 'link' not in headers:
                self.__totalCount = len(data) if data else 0
            [...]
```
The response has no `link` header but it has this data:
```
{"total_count":0,"incomplete_results":false,"items":[]}
```
and `totalCount` returns 3 because there are 3 items inside the data dict.

I'm not sure why the `total_count` value in the response is not used directly.

**Comment by sfdye** [comment]
Good catch. Probably a bug in the code.

> I'm not sure why the total_count value in the response is not used directly.

It's because for some response (I think for all non-search related API), the response json did not contain the `total_count` key, so we have to get it from the `link` header.

**Comment by s-t-e-v-e-n-k** [comment]
I think @sfdye is right. We should check the returned JSON for a total_count item first, and then fall back if the key doesn't exist. I'll dig into this later today.
