### ISSUE TITLE
Python 3 syntax errors

### ISSUE THREAD

**Issue by cclauss** [PyGithub/PyGithub#965]
https://travis-ci.org/PyGithub/PyGithub/jobs/458702933#L1517

$ flake8 . --count --select=E901,E999,F822,F823 --show-source --statistics
```
./github/GithubObject.py:141:29: E999 SyntaxError: invalid syntax
            except Exception, e:
                            ^
./github/Requester.py:317:30: E999 SyntaxError: invalid syntax
            except ValueError, e:
                             ^
./github/tests/AuthenticatedUser.py:247:87: E999 SyntaxError: invalid token
        self.user.mark_notifications_as_read(datetime.datetime(2018, 10, 18, 18, 20, 01, 0))
                                                                                      ^
./github/tests/ExposeAllAttributes.py:137:31: E999 SyntaxError: invalid syntax
                print className, attrName, "->", repr(value)
                              ^
./github/tests/Framework.py:96:18: E999 SyntaxError: invalid syntax
        print verb, url, input, headers,
                 ^
./scripts/fix_headers.py:158:50: E999 SyntaxError: invalid syntax
                print "Don't know what to do with", filename
                                                 ^
6     E999 SyntaxError: invalid syntax
```

**Comment by cclauss** [comment]
These are syntax errors in Python.  Can we please get some reviews on this PR?

**Comment by KVGarg** [comment]
There are 3 more lines that is still using Python2 syntax
1. https://github.com/PyGithub/PyGithub/blob/master/github/tests/ExposeAllAttributes.py#L137
2. https://github.com/PyGithub/PyGithub/blob/master/github/tests/Framework.py#L96
3. https://github.com/PyGithub/PyGithub/blob/master/github/tests/Framework.py#L119

Do they also need to be changed?

**Comment by KVGarg** [comment]
@cclauss Can I create a PR? that extends the Python 3 compatibility

**Comment by cclauss** [comment]
Both @labrys and I have done so repeatedly:
* https://github.com/PyGithub/PyGithub/pulls?q=is%3Apr+author%3Alabrys+is%3Aclosed
* https://github.com/PyGithub/PyGithub/pulls?q=is%3Apr+author%3Acclauss+is%3Aclosed

but those PRs are never merged because I believe the maintainers like depending on:
* https://github.com/PyGithub/PyGithub/blob/master/setup.py#L100

which is deprecated / no longer recommended but it does still work:
* https://setuptools.readthedocs.io/en/latest/python3.html
