### ISSUE TITLE
There is no way to create a required_status_checks in a branch

### ISSUE THREAD

**Issue by Carles-Figuerola** [PyGithub/PyGithub#973]
On a brand new repo, for most other options, the `edit_something()` calls will enable them but `branch.edit_required_status_checks(strict=True)` is failing with a 404:

```{u'documentation_url': u'https://developer.github.com/enterprise/2.14/v3/repos/branches/#update-required-status-checks-of-protected-branch', u'message': u'Required status checks not enabled'}```

Using github enterprise 2.14, API v3 and pygithub 1.43.3

**Comment by sfdye** [comment]
> Required status checks not enabled

You need to enable this from the repo settings.

**Comment by Carles-Figuerola** [comment]
For anyone finding this in the future, this is how a required status check is enabled:
```master_branch.edit_protection(required_approving_review_count=1, strict=True, contexts=[])```
