### ISSUE TITLE
Timeout on reading file contents from repo.  Retry option?

### ISSUE THREAD

**Issue by peterkline** [PyGithub/PyGithub#984]
I have a context started and sometimes we have a slow network going to our Github Enterprise installation.  So 95% of the time the following code is fine but I will hit an error on occasion:

    The read operation timed out

The code is very simple 

```python     
# Where self.gho is my github object is connected.
contents = self.gho.get_repo(repo).get_file_contents(lookup_file, commit)
```

Is there any way to change the options where there is a retry, a longer timeout?   I know there is the timeout during the initial login but that doesn't help me.

**Comment by allevin** [comment]
@peterkline my project had similar problems.  We had a  very unreliable network and we needed to retry any failed comms to ensure that it was a real failure.   I had developed some nasty wrappers (using lambda functions) around all the PyGithub calls to resolve the issue.  This worked, but I was never happy with the solution.  I always felt that PyGithub should provide some sort of retry feature.

My solution is in PR #860.  It uses the urllib3 retry feature to support low level comms retries.  I believe that @mfonville is using the PR in production code.  I know that the maintainers are interested in this code, but everyone is too busy to move it forward.  The PR is starting to get stale and now looks to have a merge conflict (hopefully, should be easy to fix).  You might try to use the PR and see if it solves your problem.  Any feedback or suggested changes to the PR would be appreciated.

Best of luck.

**Comment by peterkline** [comment]
Thanks, I will take a look at the mentioned PR and see if I can move it forward or adapt.  At worst, I will have to wrap the file lookups in a dumb function that just retries until I get a valid response.
