### ISSUE TITLE
Get issues I created across all visible repositories + owned + member

### ISSUE THREAD

**Issue by pawamoy** [PyGithub/PyGithub#985]
I've been trying for 20 minutes to do a simple thing: get the list of all issues I created. Just like what you get at https://github.com/issues.

So, it should be something like:

```
from github import Github
g = Github('my_token')
user = g.get_user()
issues = list(user.get_issues(state='all', filter='created'))
```
...right?

Except with this I get only the issues for the repositories I own or I am a member of. I don't get the issues I created on visible repositories I don't own or am not a member of.

Am I missing something? I quote the docs from GitHub API:

> List all issues assigned to the authenticated user across all visible repositories including owned repositories, member repositories, and organization repositories.

It seems that what I get is the result of `GET /user/issues`, not `GET /issues`.

**Comment by Diwasdrpm** [comment]
...
