### ISSUE TITLE
get_user() method returns AuthenticatedUser(login=None) although the user is authenticated.

### ISSUE THREAD

**Issue by shibasisp** [PyGithub/PyGithub#992]
Although the user is being authenticated by using access token or (username, password), get_user() method returns `AuthenticatedUser(login=None)`. I think the required behavior should be `AuthenticatedUser(login=<username>)`

Example
```python
from github import Github
>>> client = Github(ACCESS_TOKEN)
>>> client.get_user()
AuthenticatedUser(login=None)

**Comment by shibasisp** [comment]
I would like to solve this issue.

**Comment by sfdye** [comment]
I believe this is due to the lazy retrieving behavior
