### ISSUE TITLE
search_repositories: sporadically missing some repositories during search request

### ISSUE THREAD

**Issue by leadelngalame1611** [PyGithub/PyGithub#997]
I am having some issues while using the github.search_repository API. During a search_repository call, it sometime returns all repositories which is fine, and few minutes later it return a list with some repositories missing.
Here is a log output to be able to visualize where issue lies:

```
10:02:44  Iterate through all github repositories found with query: github.search_repository(query_string)

10:02:45 github repository list  ['si_test2', 'si_test3', 'si_github', 'si_ece', **'si_test1'**, 'si_test5', 'si_circleci-automate', 'si_ece-ami-factory', 'si_aws-sam-skeleton', 'si_training_account_mgmt']

10:04:44 Iterate through all github repositories found with query: github.search_repository(query_string)

10:04:45 github repository list ['si_test3', 'si_test2', 'si_test5', 'si_circleci-automate', 'si_aws-sam-skeleton', 'si_ece-ami-factory', 'si_training_account_mgmt']

10:06:44 Iterate through all github repositories found with query: github.search_repository(query_string)

10:06:44 github repository list ['si_test2', 'si_test3', 'si_github', 'si_ece', **'si_test1'**, 'si_test5', 'si_circleci-automate', 'si_ece-ami-factory', 'si_aws-sam-skeleton', 'si_training_account_mgmt']
```

Notice that at 
10:02:45 si_test1 repository was found in the returned list.
10:04:45 si_test1 repository not found in the list
10:06:44 si_test1 was again found in the list

As i mentioned, this happens sporadically and si_test1 repository was never deleted during the 3 api calls.
Could someone help me understand this? Or is there a better was to search for repositories get a consistent set of result.

**Comment by sfdye** [comment]
Can you reproduce on web search and curl?

**Comment by leadelngalame1611** [comment]
Hallo @sfdye,
yes, this can be reproduced on curl.
``` 
while true; do curl -s "https://api.github.com/search/repositories?q=otto-ec/si_" -u <TOKEN>: | jq -r '.total_count'; echo $(date);  sleep 3; done

Wed Dec 19 15:18:39 CET 2018
9
Wed Dec 19 15:18:43 CET 2018
9
Wed Dec 19 15:18:47 CET 2018
9
Wed Dec 19 15:18:51 CET 2018
5
Wed Dec 19 15:18:55 CET 2018
9
Wed Dec 19 15:18:59 CET 2018
9
Wed Dec 19 15:19:03 CET 2018
9
```

You will realize that at 15:18:51, we had a return count of 5 repositories which does not match the amount to the request prio and after the call.

**Comment by sfdye** [comment]
If this can be reproduced by curl, then it's not a PyGithub issue. You wanna raise an issue with Github support.

**Comment by leadelngalame1611** [comment]
You are right. 
Thanks for your support
